project-oak/oak

.travis.yml, README.md, scripts/build_server_docker, scripts/run_server_docker
=> Add Travis integration

README.md, examples/hello_world/run, examples/running_average/run
There doesn't seem to be a need to be on the bleeding edge.
=> Remove nightly

README.md
=> Update references to scheduling

.travis.yml, Dockerfile, scripts/build_examples_docker
Install protobuf compiler in Docker, and reorganise the Dockerfile.
ref #22
=> Build hello_world example in CI

scripts/build_examples_docker, scripts/build_server_docker, scripts/docker_run, scripts/docker_sh, scripts/run_server_docker
There is now a single `docker_run` script that runs any command passed
to it via Docker.
Build more examples in CI using such script (#22)
=> Refactor Docker scripts

README.md, oak/client/node_client.h, oak/server/enclave_server.h, oak/server/oak_enclave.cc, oak/server/oak_node.cc
Change-Id: I4b175471bec21e82d9102f90b540f994139a2509
=> Reformat files using ./scripts/format

CONTRIBUTING.md, examples/hello_world/client/hello_world.cc, examples/private_set_intersection/client/private_set_intersection.cc, examples/running_average/client/running_average.cc, oak/client/manager_client.h, oak/client/node_client.h, oak/server/BUILD, oak/server/enclave_server.h, oak/server/module_invocation.cc, oak/server/module_invocation.h, oak/server/oak_enclave.cc, oak/server/oak_main.cc, oak/server/oak_manager.cc, oak/server/oak_manager.h, oak/server/oak_node.cc, oak/server/oak_node.h
I'm kind of arbitrarily deciding some of these things but I don't really strongly feel either way, so please let me know if we should do something different. In particular about the `using` statements.
=> Add C++ Style Guide section

oak/client/node_client.h, oak/server/enclave_server.h
This seems to be necessary after #45.
cc @annasapek @keithmoyer
=> Initialize Asylo assertions on server and client

oak/server/BUILD, oak/server/enclave_server.cc, oak/server/enclave_server.h
I have plans to do refactors with this class, as a first step I thought it'd be anyways worth splitting it to header and source.
=> Split up enclave_server.h to a header and a source file

examples/machine_learning/src/lib.rs
Forgot to remove the old macro invocation in #60
=> Fix machine learning example

.gitignore
I'm using vscode and this is the autogenerated stuff, we should ignore this
=> Adding vscode generated files to .gitignore

oak/proto/BUILD, oak/proto/storage.proto, oak/server/BUILD, oak/server/storage/BUILD, oak/server/storage/storage_channel.cc, oak/server/storage/storage_channel.h, oak/server/storage/storage_provider.h, oak/server/storage/storage_service.cc, oak/server/storage/storage_service.h
This will provide module functions access to the persistent StorageService.
=> Implement StorageChannel interface (#77)

oak/server/module_invocation.cc, oak/server/oak_manager.cc, oak/server/oak_manager.h, oak/server/oak_node.cc
Plumb through some error processing, allow logging during initialization, and allow context for logging.
Prob'y best reviewed commit-by-commit.
=> Improve debuggability

examples/hello_world/client/hello_world.cc, examples/hello_world/proto/hello_world.proto, examples/hello_world/src/lib.rs, examples/hello_world/src/proto/hello_world.rs
Best reviewed commit-by-commit.
=> Add streaming methods to service definition and tests

.travis.yml, examples/hello_world/run, examples/machine_learning/run, examples/private_set_intersection/run, examples/running_average/run, oak/server/oak_main.cc, scripts/build_server_docker, scripts/run_example, scripts/run_server_docker
For discussion - not sure we'll want all of these commits.  In particular, 'Run examples in Travis builds' is good because it actually runs all our sample code, but bad because it makes the Travis build slower.
=> Various Travis tweaks

.gitignore, examples/hello_world/src/lib.rs
After #93, this is a small refactor that shows how the code would look
like after we enable generation. Once we agree on how this needs to be,
I will refactor all the examples and then start working on the actual
generation.
Part of solving #11
=> [RFC] Refactor HelloWorld example

scripts/build_server_docker, scripts/check_formatting, scripts/run_example, third_party/run-clang-format/LICENSE, third_party/run-clang-format/run-clang-format.py
Best reviewed commit-by-commit.
=> A smörgåsbord of lint/build tweaks

.devcontainer.json
See https://code.visualstudio.com/docs/remote/containers
=> Add .devcontainer.json file

WORKSPACE, oak/server/BUILD, oak/server/logging_channel.h, oak/server/oak_node.cc, oak/server/wabt_output.cc, oak/server/wabt_output_test.cc
Best reviewed commit-by-commit; also fixes some build warnings along the way.
=> Initial framework to allow testing of C++ code

.travis.yml, oak/server/oak_node.cc, oak/server/oak_node.h, scripts/check_generated, scripts/run_tests
Best reviewed commit-by-commit
=> Build and test tweaks

oak/server/status.h
This compiled as we probably included this via other dependecies.
=> Add include for int32_t type definition for status.h

rust/oak/src/lib.rs
=> Install panic hook

Dockerfile, examples/utils/BUILD, scripts/check_formatting, scripts/format
=> Install buildifier and run it in check_formatting

oak/server/wabt.bzl, scripts/check_formatting, scripts/format, toolchain/cc_toolchain_config.bzl
=> Enable lint warnings for buildifier

examples/hello_world/run, examples/machine_learning/run, examples/private_set_intersection/run, examples/running_average/run, examples/rustfmt/run, scripts/build_examples_docker, scripts/run_example, scripts/run_examples
For #164.
The first commit could actually be dropped as it's not used by later commits (I used it in an earlier version of this PR), but I thought it might be useful to preserve.
=> Make sure C++ module is built and checked

examples/hello_world/module/cpp/hello_world.cc, rust/oak_log/src/tests.rs
(and attempt to fix a flaky rust unit test along the way)
=> Fix up C++ module example

README.md, examples/Cargo.lock, examples/hello_world/module/cpp/hello_world.cc, examples/hello_world/module/rust/src/lib.rs, examples/machine_learning/module/rust/src/lib.rs, examples/private_set_intersection/module/rust/src/lib.rs, examples/running_average/module/rust/src/lib.rs, examples/rustfmt/module/rust/src/lib.rs, oak/client/manager_client.h, oak/proto/oak_api.proto, oak/server/oak_node.cc, oak/server/oak_node.h, oak/server/oak_node_test.cc, oak/server/testdata/minimal.wat, oak/server/testdata/missing.wat, oak/server/testdata/wrong.wat, rust/Cargo.lock, rust/oak/Cargo.toml, rust/oak/src/lib.rs, rust/oak/src/proto/oak_api.rs, rust/oak_derive/Cargo.toml, rust/oak_derive/src/lib.rs, rust/oak_tests/src/lib.rs, rust/oak_tests/src/tests.rs
Not sure how we're going to handle Node termination, but I think most of these changes are likely to be useful whatever we come up with.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/project-oak/oak/183)
=> Tweaks and preparation for Node termination

.bazelrc
This is adding the configs to run asan and friends builds. We also need to use clang for this to work, I will add this later.
=> Adding *san configurations

.gitignore, .travis.yml, README.md, scripts/build_dev_server, scripts/run_server_dev, toolchain/cc_toolchain_config.bzl
Basic scripts to build and run
Updated docs
Treat warnings as errors
Enable Travis build for dev server
=> Create scripts to run devserver and update docs

scripts/build_dev_server, scripts/build_example, scripts/build_examples, scripts/build_server, scripts/check_formatting, scripts/check_generated, scripts/docker_run, scripts/docker_sh, scripts/format, scripts/run_example, scripts/run_server, scripts/run_server_dev, scripts/run_tests
See https://www.tldp.org/LDP/abs/html/options.html for their meaning.
=> Use consistent bash options for all the scripts

oak/server/oak_node.cc
I've ran cppcheck locally and reported these. We should probably run it in Travis, but for now I've added a quick fix.
=> Small fixes reported by cppcheck

toolchain/cc_toolchain_config.bzl
I've rearranged the flags a bit, added Wextra, remove useless ones and
added a few comments and why we have them.
=> Improved clang flags and description

examples/Cargo.lock, examples/Cargo.toml, examples/hello_world/client/hello_world.cc, examples/machine_learning/client/machine_learning.cc, examples/multinode/module/rust/Cargo.toml, examples/multinode/module/rust/src/lib.rs, examples/multinode/module2/rust/Cargo.toml, examples/multinode/module2/rust/src/lib.rs, examples/multinode/multinode_common/Cargo.toml, examples/multinode/multinode_common/src/lib.rs, examples/private_set_intersection/client/private_set_intersection.cc, examples/running_average/client/running_average.cc, examples/rustfmt/client/rustfmt.cc, oak/client/BUILD, oak/client/manager_client.h
For the second commit, I've not yet found a `StatusOr` that wouldn't involve a new dependency or `Status` conversion&hellip;
=> Work on a couple of TODOs

docs/sdk.md, examples/abitest/module/rust/src/lib.rs, examples/abitest/module/rust/src/proto/abitest_grpc.rs, examples/abitest/module2/rust/src/lib.rs, examples/hello_world/module/rust/src/lib.rs, examples/hello_world/module/rust/src/proto/hello_world_grpc.rs, examples/machine_learning/module/rust/src/lib.rs, examples/private_set_intersection/module/rust/src/lib.rs, examples/private_set_intersection/module/rust/src/proto/private_set_intersection_grpc.rs, examples/running_average/module/rust/src/lib.rs, examples/running_average/module/rust/src/proto/running_average_grpc.rs, examples/rustfmt/module/rust/src/lib.rs, examples/rustfmt/module/rust/src/proto/rustfmt_grpc.rs, rust/oak/src/grpc/mod.rs, rust/oak/src/io/mod.rs, rust/oak/src/lib.rs, rust/oak/src/storage/mod.rs, rust/oak/src/tests.rs, rust/oak/src/wasm/mod.rs, rust/oak_derive/src/lib.rs, rust/oak_log/src/lib.rs, rust/oak_log/src/tests.rs, rust/oak_tests/src/lib.rs, rust/oak_tests/src/tests.rs, third_party/grpc-rust/grpc-compiler/src/codegen.rs
The docs/sdk.md file in the final commit may help to give the overall shape of this PR, but changes might be easier to review commit-by-commit.
=> Tidy up and document Rust SDK

oak/server/asylo/BUILD
See
https://github.com/google/asylo/blob/5ab253e2db786a9cccbc397aac2338531d4aa119/asylo/bazel/asylo.bzl#L674
=> Stop using deprecated bazel rule

scripts/check_enclave_reproducibility, scripts/print_enclave_hash
=> Add script to check build reproducibility

examples/Cargo.lock, examples/abitest/module/rust/Cargo.toml, examples/abitest/module/rust/src/lib.rs, oak/proto/oak_api.proto, oak/server/BUILD, oak/server/channel.h, oak/server/oak_node.cc, oak/server/oak_node.h, oak/server/wasm_node.cc, rust/oak/src/io/mod.rs, rust/oak/src/lib.rs, rust/oak/src/proto/oak_api.rs, rust/oak/src/wasm/mod.rs
Probably easiest to review commit-by-commit.
=> Track channel status more precisely

Dockerfile, WORKSPACE, oak/server/BUILD, oak/server/asylo/BUILD, oak/server/asylo/enclave_server.cc
- fix a couple missing dependencies
- add rules to build sigstruct, used for SGX remote attestation
Ref #241
=> Update Asylo and absl version

.bazelrc, examples/abitest/client/BUILD, examples/abitest/client/abitest.cc, examples/abitest/module/rust/src/lib.rs, examples/abitest/module2/rust/src/lib.rs, oak/server/channel.h, oak/server/logging_node.cc, oak/server/node_thread.cc, oak/server/oak_grpc_node.cc, oak/server/oak_node.cc, oak/server/oak_runtime.cc, oak/server/wasm_node.cc
Possibly easier to review commit-by-commit
Makes debugging easier by improving logging from the C++ TCB code, and extends the abitest example to be even more multi-node and multi-channel.
=> Improved tests and diagnostics

.prettierrc.yaml, CONTRIBUTING.md, Dockerfile, INSTALL.md, README.md, docs/abi.md, docs/concepts.md, docs/development.md, docs/programming-oak.md, docs/sdk.md, scripts/check_formatting, scripts/format
=> Autoformat and check Markdown files

.bazelrc, scripts/fuzz
Merge bazel configs where possible.
Ref #261
=> Clean up fuzz config

Dockerfile, scripts/check_formatting, scripts/format
Regenerate with `embedmd -w docs/<file>.md`
=> Check embedded code snippets are up-to-date

docs/programming-oak.md, examples/hello_world/proto/BUILD, oak/common/policy.h, oak/server/module_invocation.cc, oak/server/module_invocation.h, oak/server/oak_grpc_node.cc, oak/server/oak_grpc_node.h, oak/server/oak_node.cc, oak/server/oak_node.h
=> Various small fixes

README.md
=> Add fuzzing badge

docs/programming-oak.md, examples/abitest/module/rust/src/lib.rs, examples/abitest/module/rust/src/proto/abitest_grpc.rs, examples/hello_world/module/rust/src/lib.rs, examples/hello_world/module/rust/src/proto/hello_world_grpc.rs, examples/machine_learning/module/rust/src/lib.rs, examples/private_set_intersection/module/rust/src/lib.rs, examples/private_set_intersection/module/rust/src/proto/private_set_intersection_grpc.rs, examples/private_set_intersection/proto/BUILD, examples/running_average/module/rust/src/lib.rs, examples/running_average/module/rust/src/proto/running_average_grpc.rs, examples/rustfmt/module/rust/src/lib.rs, examples/rustfmt/module/rust/src/proto/rustfmt_grpc.rs, oak/server/BUILD, oak/server/dev/BUILD, oak/server/module_invocation.cc, oak/server/module_invocation.h, oak/server/oak_grpc_node.h, rust/oak/src/grpc/mod.rs, rust/oak_derive/src/lib.rs, rust/oak_tests/src/tests.rs, third_party/grpc-rust/grpc-compiler/src/codegen.rs
For #284, but likely to be modified in future for #285.
Probably easiest to review commit-by-commit.
=> Allow parallel asynchronous gRPC requests

examples/hello_world/module/cpp/BUILD, examples/hello_world/module/cpp/hello_world.cc, oak/common/BUILD, oak/common/handles.cc, oak/server/BUILD, oak/server/base_runtime.h, oak/server/oak_node.cc, oak/server/oak_runtime.cc, oak/server/oak_runtime.h, oak/server/wasm_node.cc, oak/server/wasm_node.h, oak/server/wasm_node_test.cc, sdk/rust/oak_tests/src/lib.rs
Best reviewed commit-by-commit
=> Preparatory changes for allowing dynamic node creation

docs/abi.md, docs/programming-oak.md, examples/abitest/module/rust/src/lib.rs, examples/abitest/module2/rust/src/lib.rs, examples/abitest/tests/src/lib.rs, examples/hello_world/module/cpp/hello_world.cc, oak/server/logging_node.cc, oak/server/logging_node.h, oak/server/node_thread.cc, oak/server/node_thread.h, oak/server/oak_grpc_node.cc, oak/server/oak_grpc_node.h, oak/server/oak_node.h, oak/server/oak_runtime.cc, oak/server/storage/storage_node.cc, oak/server/storage/storage_node.h, oak/server/testdata/minimal.wat, oak/server/testdata/missing.wat, oak/server/testdata/wrong.wat, oak/server/wasm_node.cc, oak/server/wasm_node.h, sdk/rust/oak_derive/src/lib.rs, sdk/rust/oak_tests/src/lib.rs, sdk/rust/oak_tests/src/tests.rs
Not yet used, in preparation for a future commit.
=> Change oak_main signature to take a handle param

oak/client/sgx_application_client.cc, oak/server/BUILD, oak/server/storage/BUILD, scripts/run_tests
Best reviewed commit-by-commit.
@tiziano88 : I've got no idea whether the "Build fuzzer as a library" commit will still work with oss-fuzz &ndash; is there a way to check?
=> Get build //...:all mostly working

.bazelrc, cloudbuild.yaml, scripts/build_server_dev, scripts/run_examples_dev
Under development, just putting as a PR to get a cloudbuild running.
=> Run examples under ASAN and TSAN

INSTALL.md
This is mostly just an excuse to try out a different build trigger, for
which I need a new PR.
=> Clean up Install instructions

android.Dockerfile, cloudbuild.yaml, examples/hello_world/client/android/java/com/google/oak/hello_world/MainActivity.java, examples/hello_world/client/android/java/com/google/oak/hello_world/res/layout/activity_main.xml, examples/hello_world/client/android/java/com/google/oak/hello_world/res/values/strings.xml
This change:
- Adds `docker_pull` for Android SDK in the GCB
- Updates the text field in the hello-world Android application
=> Pull Android Docker in GCB

oak/common/BUILD, oak/common/app_config_test.cc, oak/common/testdata/grpcport.textproto, oak/server/asylo/asylo_oak_manager.cc, oak/server/asylo/asylo_oak_manager.h
This change:
- Adds fixes based on the after the fact drive-by comments in #409
- Adds a gRPC port test in `app_config_test.cc`
=> Add gRPC port test

oak/server/asylo/asylo_oak_app_main.cc, oak/server/asylo/asylo_oak_main.cc
This commit fixes comments in `asylo_oak_main.cc` based on https://github.com/project-oak/oak/pull/409#pullrequestreview-337624322
=> Fix single app comment

scripts/run_examples
=> scripts: reinstate all examples in run_examples

oak/server/time/roughtime_client.cc
Additional servers based on the Cloudflare roughtime ecosystem list.
=> roughtime: add additional servers

oak/server/asylo/asylo_oak_app_main.cc
This change makes single app server use an application config file.
Fixes #413
=> Use application config in single app server

oak/server/wasm_node_fuzzer.cc
This is to fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=20175
=> Add default entry point to fuzzer

docs/programming-oak.md, examples/Cargo.lock, examples/abitest/module_0/rust/src/lib.rs, examples/chat/common/Cargo.toml, examples/chat/common/src/command.rs, examples/chat/module_0/rust/src/lib.rs, examples/chat/module_1/rust/src/lib.rs, examples/machine_learning/module/rust/src/lib.rs, sdk/rust/oak/src/error.rs, sdk/rust/oak/src/grpc/mod.rs, sdk/rust/oak/src/io/decodable.rs, sdk/rust/oak/src/io/encodable.rs, sdk/rust/oak/src/io/mod.rs, sdk/rust/oak/src/io/receiver.rs, sdk/rust/oak/src/io/sender.rs, sdk/rust/oak/src/lib.rs, sdk/rust/oak_log/src/lib.rs, sdk/rust/oak_log/src/tests.rs
More details on individual commit messages.
=> Add `Sender` and `Receiver` traits

sdk/rust/oak/src/grpc/mod.rs, sdk/rust/oak/src/io/receiver.rs, sdk/rust/oak/src/lib.rs, sdk/rust/oak/src/tests.rs, sdk/rust/oak_tests/src/lib.rs
=> Use `result_from_status` after host function calls

PULL_REQUEST_TEMPLATE.md
=> docs: add pull request template

sdk/rust/oak/src/io/mod.rs, sdk/rust/oak/src/io/receiver.rs, sdk/rust/oak/src/io/sender.rs
=> Clarify `Sender` and `Receiver` documentation 

Dockerfile, WORKSPACE, oak/server/asylo/asylo_oak_loader.cc, oak/server/asylo/asylo_oak_loader.h
This change:
- Updates Asylo version to 0.5.1
- Updates Dockerfile
Fixes #345
=> Update Asylo version to 0.5.1

Dockerfile, scripts/docker_run, toolchain/emar.sh, toolchain/emcc.sh
This change fixes TensorFlow example build in non-root Docker containers.
Fixes #476
=> Fix local TensorFlow example build

examples/abitest/module_0/rust/src/lib.rs, sdk/rust/oak/src/error.rs, third_party/expect/src/lib.rs
=> Fix some TODOs

sdk/rust/oak/src/io/receiver.rs, sdk/rust/oak/src/io/sender.rs
=> sdk: add link references

scripts/common
@anghelcovici could you try out these instructions and let me know if they worked for you?
construction.
=> Add instructions for remote cache auth

examples/abitest/module_0/rust/build.rs, examples/abitest/module_0/rust/src/proto/mod.rs, examples/chat/module/rust/build.rs, examples/chat/module/rust/src/command.rs, examples/chat/module/rust/src/proto/mod.rs, examples/hello_world/module/rust/build.rs, examples/hello_world/module/rust/src/proto/mod.rs, examples/private_set_intersection/module/rust/build.rs, examples/private_set_intersection/module/rust/src/proto/mod.rs, examples/running_average/module/rust/build.rs, examples/running_average/module/rust/src/proto/mod.rs, examples/rustfmt/module/rust/build.rs, examples/rustfmt/module/rust/src/proto/mod.rs, examples/translator/common/build.rs, examples/translator/common/src/proto/mod.rs, oak/server/rust/oak_abi/build.rs, oak/server/rust/oak_abi/src/proto/mod.rs, oak/server/rust/oak_runtime/build.rs, oak/server/rust/oak_runtime/src/proto/mod.rs, oak/server/wasm_node_fuzzer.cc, scripts/check_formatting, scripts/check_license, scripts/temp.sh, sdk/rust/oak/build.rs, sdk/rust/oak/src/proto/mod.rs
=> Fix missing license headers and add auto-check

scripts/build_gh_pages, sdk/rust/oak/src/grpc/mod.rs
=> Add doc regeneration script

docs/programming-oak.md, examples/abitest/module_0/rust/src/lib.rs, examples/abitest/module_1/rust/src/lib.rs, sdk/rust/oak_derive/src/lib.rs
@daviddrysdale is this what you had in mind for https://github.com/project-oak/oak/pull/472#discussion_r372325912? 
#542 
construction.
=> Remove separation of catch_panic

README.md
=> Add badge linking to generated Rust docs

docs/programming-oak.md, examples/abitest/module_0/rust/src/lib.rs, examples/abitest/module_0/rust/src/proto/abitest_grpc.rs, examples/chat/module/rust/src/lib.rs, examples/chat/module/rust/src/proto/chat_grpc.rs, examples/hello_world/module/rust/src/lib.rs, examples/hello_world/module/rust/src/proto/hello_world_grpc.rs, examples/private_set_intersection/module/rust/src/lib.rs, examples/private_set_intersection/module/rust/src/proto/private_set_intersection_grpc.rs, examples/running_average/module/rust/src/lib.rs, examples/running_average/module/rust/src/proto/running_average_grpc.rs, examples/rustfmt/module/rust/src/lib.rs, examples/rustfmt/module/rust/src/proto/rustfmt_grpc.rs, examples/translator/common/src/lib.rs, examples/translator/common/src/proto/translator_grpc.rs, examples/translator/module/rust/src/lib.rs, sdk/rust/oak/src/grpc/client.rs, sdk/rust/oak/src/grpc/mod.rs, third_party/grpc-rust/grpc-compiler/src/codegen.rs
=> Autogenerate gRPC client helpers

.markdownlint.yaml, .prettierrc.yaml, Dockerfile, PULL_REQUEST_TEMPLATE.md, cloudbuild.yaml, docs/development.md, examples/chat/README.md, examples/running_average/proto/BUILD, scripts/check_formatting, scripts/format
Also update bazel tools
construction.
=> Add `markdownlint` and fix or ignore warnings

scripts/run_examples_dev
=> scripts: exit on first TSAN error

INSTALL.md, docs/development.md, docs/programming-oak.md, oak/common/app_config.cc, oak/common/app_config.h, oak/common/app_config_test.cc, oak/common/testdata/barenode.textproto, oak/common/testdata/default.textproto, oak/common/testdata/dup_config_name.textproto, oak/common/testdata/dup_wasm.textproto, oak/common/testdata/grpcport.textproto, oak/common/testdata/lognode.textproto, oak/common/testdata/missing_wasm.textproto, oak/common/testdata/no_wasm_main.textproto, oak/common/testdata/storagenode.textproto, oak/common/testdata/two_log.textproto, oak/proto/application.proto, oak/server/oak_runtime.cc, scripts/run_examples, scripts/run_server_asylo, scripts/run_server_dev
=> Doc updates and proto policing commonization

.rustfmt.toml, Cargo.toml, Dockerfile, examples/abitest/module_0/rust/Cargo.toml, examples/chat/module/rust/Cargo.toml, oak/server/rust/oak_runtime/Cargo.toml, scripts/check_formatting, scripts/format
=> Autoformat TOML files

oak/server/rust/oak_runtime/src/channel.rs
@tiziano88 this should address all your [comments](https://github.com/project-oak/oak/pull/609#pullrequestreview-359666082) on #609 
>Should we remove the ones that no longer have references? Can they possibly come back?
The `HashMap` is cleared below and so all references are removed. No `Weak` references that aren't still alive can come back, threads may reinsert when "rewaiting" but locking the mutex prevents that happening at the same time as this routine. 
#631
construction.
=> rust/oak_runtime: Add additional comments to channel.rs

docs/concepts.md
=> Clarify Remote Attestation section

oak/server/rust/oak_runtime/src/channel.rs, oak/server/rust/oak_runtime/src/node/logger.rs, oak/server/rust/oak_runtime/src/node/wasm.rs
=> rust/oak_runtime: Simplify channel operations

runner/src/internal.rs, runner/src/main.rs
The data types are much clearer now, and it's getting closer to being
able to support async steps via Tokio (in a future PR).
Add support for timing individual commands.
construction.
=> Refactor runner script

Cargo.lock, Cargo.toml, experimental/split_grpc/client/Cargo.toml, experimental/split_grpc/client/build.rs, experimental/split_grpc/client/src/main.rs, experimental/split_grpc/client/src/proto/oak.examples.hello_world.rs, experimental/split_grpc/server/Cargo.toml, experimental/split_grpc/server/build.rs, experimental/split_grpc/server/src/main.rs, experimental/split_grpc/server/src/proto/oak.examples.hello_world.rs, scripts/check_license
A basic client and server implementation of the 'hello world' example using Tonic as a gRPC library.
This is the first step towards creating an example of splitting the gRPC server across two proceses as described in #627.
construction.
=> Implement Hello World in Tonic

INSTALL.md, docs/development.md, scripts/build_example, scripts/build_examples, scripts/build_examples_android, scripts/build_server, scripts/build_server_docker, scripts/check_enclave_reproducibility, scripts/common, scripts/deploy_example_gcp, scripts/fuzz, scripts/run_clang_tidy, scripts/run_example, scripts/run_examples, scripts/run_server
=> Improve scripts and docs

Cargo.lock, examples/abitest/client/BUILD, examples/abitest/client/abitest.cc, examples/abitest/client/grpctest.cc, examples/abitest/client/grpctest.h, examples/abitest/config/config.textproto, examples/abitest/module_0/rust/Cargo.toml, examples/abitest/module_0/rust/src/lib.rs, examples/abitest/module_0/rust/src/proto/abitest.rs, examples/abitest/module_0/rust/src/proto/abitest_grpc.rs, examples/abitest/module_1/rust/src/lib.rs, examples/abitest/proto/BUILD, examples/abitest/proto/abitest.proto, examples/abitest/tests/src/tests.rs, examples/hello_world/client/hello_world.cc, examples/hello_world/config/config_translator.textproto, examples/hello_world/module/rust/src/lib.rs, oak/server/logging_node.cc, oak/server/storage/BUILD, oak/server/storage/storage_node.cc, oak/server/storage/storage_processor.cc
=> More extensive platform testing in abitest

oak/server/rust/oak_abi/build.rs, oak/server/rust/oak_abi/src/label.rs
=> Automatically derive Eq and Hash for Label

examples/abitest/module_0/rust/src/lib.rs, oak/server/channel.cc, oak/server/channel.h, oak/server/logging_node.cc, sdk/rust/oak/src/grpc/mod.rs
=> Avoid leaking channels

docs/concepts.md, oak/server/rust/oak_abi/src/label.rs
=> Specify label behaviour in documentation

docs/abi.md, oak/server/rust/oak_abi/src/lib.rs, sdk/rust/oak/src/grpc/client.rs, sdk/rust/oak/src/lib.rs
=> Improve node_create parameter docs

oak/server/oak_runtime.cc, oak/server/rust/oak_abi/build.rs, oak/server/rust/oak_runtime/build.rs
=> Couple of minor tweaks

examples/aggregator/client/android/AndroidManifest.xml, examples/aggregator/client/android/BUILD, examples/aggregator/client/android/cpp/client.cc, examples/aggregator/client/android/java/com/google/oak/aggregator/MainActivity.java, examples/aggregator/client/android/java/com/google/oak/aggregator/res/layout/activity_main.xml, examples/aggregator/client/android/java/com/google/oak/aggregator/res/values/colors.xml, examples/aggregator/client/android/java/com/google/oak/aggregator/res/values/strings.xml, scripts/build_example_android, scripts/build_examples_android
This change:
- Adds an Android for the Aggregator example.
- Updates `build_android*` scripts
Fixes #708
construction.
=> Android client for Aggregator

oak/common/BUILD, oak/server/BUILD, oak/server/storage/BUILD, oak/server/time/BUILD, scripts/run_tests
construction.
To be rebased once #713 is merged.
=> Remove host tag from Bazel tests

WORKSPACE, oak/client/BUILD, oak/common/BUILD, oak/common/logging.h, oak/server/BUILD, oak/server/dev/BUILD, third_party/asylo/BUILD, third_party/asylo/statusor.h
=> Remove Asylo dependency

INSTALL.md, docs/development.md, docs/programming-oak.md
=> docs: update for removal of Asylo dep

.bazelrc, Dockerfile, WORKSPACE, examples/abitest/config/config.textproto, examples/aggregator/README.md, examples/aggregator/scripts/run_server, oak/proto/policy.proto, oak/server/oak_runtime.h, oak/server/wasm_node.h, runner/src/main.rs
=> Remove left-over Asylo references

docs/concepts.md, docs/programming-oak.md
=> docs: updates and tweaks

Dockerfile
=> Tune Dockerfile

INSTALL.md, cloudbuild.yaml, examples/aggregator/README.md, examples/aggregator/scripts/run_server, examples/aggregator/server/BUILD, examples/hello_world/gcp/BUILD, examples/hello_world/gcp/config.json, examples/hello_world/server/BUILD, oak/server/loader/BUILD, oak/server/loader/oak_docker.bzl, oak/server/loader/oak_loader.cc, oak/server/loader/oak_loader.h, oak/server/loader/oak_runner_main.cc, scripts/build_server, scripts/deploy_example_gcp, scripts/run_example, scripts/run_examples, scripts/run_server
=> Rename Oak dev server

examples/chat/client/chat.cc, examples/chat/module/rust/src/backend.rs, examples/chat/module/rust/src/command.rs, examples/hello_world/module/cpp/hello_world.cc, examples/private_set_intersection/module/rust/src/lib.rs, examples/tensorflow/module/cpp/tensorflow.cc, examples/tensorflow/module/cpp/tensorflow_micro.cc, oak/client/application_client.h, oak/common/policy.cc, oak/module/placeholders.h, oak/server/channel.h, oak/server/module_invocation.cc, oak/server/storage/storage_processor.cc, oak/server/storage/storage_processor.h, runner/src/internal.rs, runner/src/main.rs, scripts/check_formatting, scripts/check_todo, sdk/rust/oak/src/storage/mod.rs
=> Ensure all TODOs are associated with an issue

docs/programming-oak.md, examples/abitest/tests/src/tests.rs, examples/aggregator/module/rust/src/tests.rs, examples/hello_world/module/rust/src/tests.rs, examples/private_set_intersection/module/rust/src/tests.rs, examples/running_average/module/rust/src/tests.rs, examples/translator/module/rust/src/tests.rs, oak/server/rust/oak_runtime/src/config.rs, oak/server/rust/oak_runtime/src/lib.rs, oak/server/rust/oak_runtime/src/message.rs, oak/server/rust/oak_runtime/src/node/logger.rs, oak/server/rust/oak_runtime/src/node/mod.rs, oak/server/rust/oak_runtime/src/node/wasm.rs, oak/server/rust/oak_runtime/src/runtime/channel.rs, oak/server/rust/oak_runtime/src/runtime/mod.rs, sdk/rust/oak_tests/src/lib.rs
Move channel ownership (data structure and creation/deletion) into runtime #646
construction.
=> Channel ownership

oak/server/rust/oak_runtime/src/runtime/mod.rs
=> Unpark actual threads waiting on channels

examples/abitest/module_0/rust/src/lib.rs
=> abitest: test handle renumbering

oak/server/rust/oak_runtime/Cargo.toml, oak/server/rust/oak_runtime/src/lib.rs, oak/server/rust/oak_runtime/src/node/logger.rs, oak/server/rust/oak_runtime/src/node/mod.rs, oak/server/rust/oak_runtime/src/node/wasm.rs, oak/server/rust/oak_runtime/src/runtime/mod.rs, sdk/rust/oak_tests/Cargo.toml, sdk/rust/oak_tests/src/lib.rs
This also adds node deallocation mentioned in #776
construction.
=> rust/oak_runtime: Track Handles in Node

oak/server/rust/oak_runtime/src/node/logger.rs, oak/server/rust/oak_runtime/src/runtime/channel.rs, oak/server/rust/oak_runtime/src/runtime/mod.rs
=> Fix channel deallocation

oak/server/rust/oak_runtime/src/runtime/mod.rs
=> Follow up on #768 comments

cloudbuild.yaml
=> Create step to startup bazel in GCP

oak/server/node_thread.cc, oak/server/node_thread.h, oak/server/oak_node.cc, oak/server/oak_node.h
=> Close channels on node termination

oak/proto/application.proto, oak/proto/policy.proto, oak/proto/storage.proto, scripts/check_formatting
=> Add issues to proto TODOs

oak/proto/policy.proto, sdk/rust/oak/src/proto/policy.rs
Covers SAN name only.
Not used in code yet.
Ref #814
construction.
=> Introduce IFC tag for TLS certificate

sdk/rust/oak/src/storage/mod.rs
=> sdk/storage: use generic gRPC client helpers

oak/server/rust/oak_runtime/src/node/grpc_server.rs, oak/server/rust/oak_runtime/src/runtime/channel.rs, oak/server/rust/oak_runtime/src/runtime/mod.rs, sdk/rust/oak/src/grpc/mod.rs
=> Fix paths in documentation comments

README.md
=> Update README.md to change link to slack to the 'join' link, allowing new members to easily join

Dockerfile, examples/machine_learning/proto/machine_learning.proto, examples/tensorflow/proto/tensorflow.proto, oak/proto/application.proto, oak/proto/storage.proto, oak/proto/storage_service.proto, scripts/common, scripts/gcp_common
=> Use later versions of checking tools

cloudbuild.yaml, oak/proto/roughtime_service.proto
=> Fix formatting

.bazelrc, cloudbuild.yaml, examples/abitest/client/BUILD, examples/abitest/client/abitest.cc, examples/abitest/module_0/rust/src/lib.rs, examples/hello_world/client/android/cpp/client.cc, oak/server/loader/oak_runner_main.cc, oak/server/oak_grpc_node.cc, oak/server/oak_runtime.cc, oak/server/rust/oak_glue/oak_glue.h, oak/server/rust/oak_glue/src/lib.rs, oak/server/rust/oak_runtime/src/node/logger.rs, oak/server/rust/oak_runtime/src/node/wasm/mod.rs, oak/server/rust/oak_runtime/src/runtime/mod.rs, scripts/build_server, scripts/run_example, scripts/run_examples, scripts/run_server
=> Various logging improvements

Dockerfile, cloudbuild.yaml, scripts/common, scripts/run_example
=> scripts: add kill_pid helper and on_exit trap

scripts/cargo_raze
=> Improve cargo-raze usage

cloudbuild.yaml, reproducibility_index, scripts/build_reproducibility_index
=> Include Rust `oak_loader` in reproducibilty index

examples/authentication/README.md
=> Add sample Oauth Client ID to auth example

oak/server/storage/BUILD, oak/server/storage/storage_node.cc, oak/server/storage/storage_processor.cc, oak/server/storage/storage_processor.h, third_party/asylo/BUILD, third_party/asylo/cleansing_allocator.h, third_party/asylo/cleansing_types.h
=> Add cleansing types from Asylo and use them in storage

examples/abitest/module_0/rust/src/lib.rs, oak/server/rust/oak_runtime/src/runtime/channel.rs, oak/server/rust/oak_runtime/src/runtime/mod.rs
=> Explore in-flight messages

sdk/rust/oak/src/lib.rs
It is confusing to see error log messages for normal working conditions.
=> Do not log termination as error

Cargo.lock, Dockerfile, WORKSPACE, cloudbuild.yaml, docs/INSTALL-OSX.md, oak/server/rust/oak_runtime/src/node/wasm/mod.rs, oak/server/rust/oak_runtime/src/runtime/mod.rs, scripts/build_gh_pages, scripts/check_docs, scripts/run_tests_tsan
=> Run tests with ThreadSanitizer

cargo/BUILD, cargo/Cargo.toml, cargo/crates.bzl, cargo/remote/futures-0.3.4.BUILD, cargo/remote/futures-executor-0.3.4.BUILD, cargo/remote/futures-io-0.3.4.BUILD, cargo/remote/futures-macro-0.3.4.BUILD, cargo/remote/futures-task-0.3.4.BUILD, cargo/remote/futures-util-0.3.4.BUILD, cargo/remote/proc-macro-hack-0.5.15.BUILD, cargo/remote/proc-macro-nested-0.1.4.BUILD, docs/programming-oak.md, examples/abitest/tests/src/tests.rs, oak/server/rust/oak_glue/src/lib.rs, oak/server/rust/oak_loader/src/main.rs, oak/server/rust/oak_runtime/BUILD, oak/server/rust/oak_runtime/Cargo.toml, oak/server/rust/oak_runtime/src/config.rs, oak/server/rust/oak_runtime/src/lib.rs, oak/server/rust/oak_runtime/src/metrics/server.rs, oak/server/rust/oak_runtime/src/runtime/introspect.rs, oak/server/rust/oak_runtime/src/runtime/mod.rs, oak/server/rust/oak_runtime/tests/integration_test.rs, sdk/rust/oak_tests/src/lib.rs
=> Commonize HTTP servers and shut down gracefully

Dockerfile, cloudbuild.yaml, deny.toml, examples/abitest/abitest_common/Cargo.toml, examples/abitest/module_0/rust/Cargo.toml, examples/abitest/module_1/rust/Cargo.toml, examples/abitest/tests/Cargo.toml, examples/aggregator/backend/Cargo.toml, examples/aggregator/common/Cargo.toml, examples/aggregator/module/rust/Cargo.toml, examples/authentication/server/Cargo.toml, examples/chat/module/rust/Cargo.toml, examples/hello_world/module/rust/Cargo.toml, examples/machine_learning/module/rust/Cargo.toml, examples/private_set_intersection/module/rust/Cargo.toml, examples/running_average/module/rust/Cargo.toml, examples/rustfmt/module/rust/Cargo.toml, examples/translator/common/Cargo.toml, examples/translator/module/rust/Cargo.toml, experimental/split_grpc/client/Cargo.toml, experimental/split_grpc/proxy/Cargo.toml, experimental/split_grpc/server/Cargo.toml, runner/Cargo.toml, scripts/check_cargo_deny, third_party/expect/Cargo.toml
=> Integrate cargo-deny checks into CI

oak/server/rust/oak_loader/BUILD, oak/server/rust/oak_loader/Cargo.toml, oak/server/rust/oak_loader/src/main.rs, scripts/build_server
=> Loader tweaks

examples/chat/README.md
This seems helpful for newcomers. Most other examples also include the build step in their instructions. 
construction.
=> Update the chat example README for clarity & currency

docs/programming-oak.md, examples/abitest/tests/src/tests.rs, examples/aggregator/module/rust/src/tests.rs, examples/hello_world/module/rust/src/tests.rs, examples/private_set_intersection/module/rust/src/tests.rs, examples/running_average/module/rust/src/tests.rs, examples/translator/module/rust/src/tests.rs, oak/server/rust/oak_runtime/src/lib.rs, oak/server/rust/oak_runtime/src/node/external.rs, oak/server/rust/oak_runtime/src/node/grpc/server.rs, oak/server/rust/oak_runtime/src/node/logger.rs, oak/server/rust/oak_runtime/src/node/mod.rs, oak/server/rust/oak_runtime/src/node/wasm/mod.rs, oak/server/rust/oak_runtime/src/runtime/mod.rs, oak/server/rust/oak_runtime/src/runtime/tests.rs
=> Commonize and combine various bits of Node functionality

LICENSE
=> LICENSE: fill in copyright placeholder

oak/server/rust/oak_runtime/src/metrics/server.rs, oak/server/rust/oak_runtime/src/node/external.rs, oak/server/rust/oak_runtime/src/node/grpc/server.rs, oak/server/rust/oak_runtime/src/node/logger.rs, oak/server/rust/oak_runtime/src/node/mod.rs, oak/server/rust/oak_runtime/src/node/wasm/mod.rs, oak/server/rust/oak_runtime/src/runtime/channel.rs, oak/server/rust/oak_runtime/src/runtime/introspect.rs, oak/server/rust/oak_runtime/src/runtime/mod.rs
=> runtime: improve comments

oak/server/rust/oak_runtime/src/metrics/server.rs, oak/server/rust/oak_runtime/src/runtime/introspect.rs
Put the oneshot shutdown future into Hyper's slot for such a thing,
rather than using our own select.
construction.
=> runtime: use hyper's with_graceful_shutdown()

Cargo.lock, oak/server/rust/oak_runtime/Cargo.toml, oak/server/rust/oak_runtime/src/node/wasm/tests.rs, oak/server/rust/oak_runtime/src/runtime/mod.rs, oak/server/rust/oak_runtime/src/runtime/tests.rs, oak/server/rust/oak_runtime/tests/integration_test.rs
=> Fix runtime unit test synchronization

oak/server/rust/oak_loader/src/main.rs
This change updates comments in Oak Loader.
construction.
=> Update comments in Oak Loader

docs/concepts.md, oak/server/rust/oak_runtime/src/runtime/mod.rs, oak/server/rust/oak_runtime/src/runtime/tests.rs
=> Support downgrade of tags

examples/aggregator/client/android/cpp/client.cc, examples/aggregator/client/android/java/com/google/oak/aggregator/MainActivity.java, examples/aggregator/client/android/java/com/google/oak/aggregator/res/layout/activity_main.xml, examples/hello_world/client/android/java/com/google/oak/hello_world/MainActivity.java, examples/hello_world/client/android/java/com/google/oak/hello_world/res/layout/activity_main.xml
construction.
Fixes #991
Fixes #988
=> Move blocking Android code to a background thread

examples/aggregator/scripts/deploy, examples/aggregator/scripts/undeploy
This did not seem to work otherwise
=> Specify zone in gcloud command

README.md
Also update style to make them larger and less likely to be missed
(various people mentioned they did not notice them)
=> Remove Fuzzing badge

examples/tensorflow/client/tensorflow.cc
=> examples: use localhost address in tensorflow client

.github/workflows/reproducibility.yaml
This should make it easier to actually understand what targets were
affected by a PR.
Ref. #861
=> Print reproducibility index diff

cloudbuild.yaml, examples/aggregator/server/BUILD, oak/server/BUILD, oak/server/oak_docker.bzl, scripts/build_example
=> Re-enable more builds

examples/abitest/module_0/rust/src/lib.rs, examples/abitest/tests/src/tests.rs, oak/server/rust/oak_runtime/src/node/grpc/client.rs, oak/server/rust/oak_runtime/src/node/grpc/mod.rs, scripts/run_example, scripts/run_server
=> Fix up gRPC abitest 

oak/server/rust/oak_runtime/src/runtime/mod.rs, oak/server/rust/oak_runtime/src/runtime/tests.rs
Previously downgrade was only allowed when writing to lower labels, but
not when reading from higher labels. This makes both possible, relying
on the same underlying Node privilege.
Credit to @aferr for the explanation and suggestions on how to implement
it, and also link to the relevant Slack discussion, for reference:
https://project-oak.slack.com/messages/CHE9E13C3/p1590712037024800?thread_ts=1590660390.016600
Ref #630
construction.
=> Take into account downgrade privilege when reading

Cargo.lock, examples/abitest/client/grpctest.cc, oak/server/rust/oak_runtime/Cargo.toml, oak/server/rust/oak_runtime/src/io.rs, oak/server/rust/oak_runtime/src/node/grpc/client.rs, oak/server/rust/oak_runtime/src/node/grpc/invocation.rs, oak/server/rust/oak_runtime/src/node/grpc/mod.rs, scripts/run_example
=> Server-streaming method support in gRPC client pseudo-Node

docs/programming-oak.md, docs/sdk.md
=> docs: update for new generated doc location

Cargo.lock, examples/Cargo.lock, oak/common/label.cc, oak/common/label.h, oak/proto/label.proto, oak/server/rust/oak_runtime/Cargo.toml, oak/server/rust/oak_runtime/src/node/mod.rs, oak/server/rust/oak_runtime/src/node/wasm/mod.rs, oak/server/rust/oak_runtime/src/runtime/mod.rs, oak/server/rust/oak_runtime/src/runtime/tests.rs, oak_abi/src/label/mod.rs
Rename protobuf field to clarify that it refers to SHA256 hash.
I also verified that the module hash that gets logged at runtime
corresponds to the one contained in the reproducibility index.
Ref #1069
construction.
=> Grant privilege to WebAssembly nodes

Cargo.lock, examples/Cargo.lock, examples/trusted_information_retrieval/module/rust/Cargo.toml, examples/trusted_information_retrieval/module/rust/src/tests.rs, oak/server/rust/oak_runtime/Cargo.toml, oak/server/rust/oak_runtime/src/runtime/tests.rs, oak/server/rust/oak_runtime/tests/integration_test.rs
=> More simple_logger -> env_logger conversion

WORKSPACE
=> Add sha256 value back to io_grpc_grpc_java

scripts/run_tests, scripts/run_tests_tsan
=> Time the commands in run_tests and run_tests_tsan

scripts/build_example
=> Install node deps when building an example

WORKSPACE, docs/programming-oak.md, examples/translator/client/BUILD, examples/translator/client/translator.go, oak/proto/BUILD
=> Fix up translator example

oak/server/rust/oak_loader/src/main.rs, oak/server/rust/oak_runtime/src/node/grpc/server/mod.rs, scripts/run_example
=> Close channels

oak/server/rust/oak_runtime/src/message.rs, oak/server/rust/oak_runtime/src/node/wasm/mod.rs, oak/server/rust/oak_runtime/src/runtime/mod.rs, oak/server/rust/oak_runtime/src/runtime/proxy.rs
=> Split runtime/mod.rs and shuffle logging around

docs/programming-oak.md, examples/abitest/module_0/rust/src/lib.rs, examples/abitest/tests/Cargo.toml, examples/abitest/tests/src/tests.rs, oak/server/rust/oak_loader/src/main.rs, oak/server/rust/oak_runtime/src/config.rs, oak/server/rust/oak_runtime/src/node/grpc/server/mod.rs, oak/server/rust/oak_runtime/src/runtime/mod.rs, oak/server/rust/oak_runtime/src/runtime/proxy.rs
=> Test gRPC server pseudo-Node startup error cases

examples/hello_world/client/nodejs/index.js
=> Node: Exit with code 1 if an error occured

oak/server/rust/oak_runtime/src/node/grpc/client.rs, oak/server/rust/oak_runtime/src/node/logger.rs, oak/server/rust/oak_runtime/src/runtime/mod.rs
=> Clean up log warnings and errors

scripts/check_formatting, scripts/format
=> Do not format code in node_modules

docs/programming-oak.md, docs/sdk.md
=> Update links to docs on GitHub

docs/abi.md, scripts/format_doc
=> Docs tweak/update

examples/hello_world/client/nodejs/README.MD
Classic Juliette
construction.
=> Replace incorrect command in Node.js Client ReadMe

cloudbuild.yaml
Will follow this up with a PR that integrates examples with multiple clients in a more optimized manner. 
See the issue linked in the Todo: https://github.com/project-oak/oak/issues/1145
construction.
=> Run the hello world nodejs client in our CI

examples/abitest/example.toml
PR submission overlap between #1105 and #1117
construction.
=> abitest: re-enable server streaming tests

docs/abi.md, docs/programming-oak.md
=> docs: describe config map use

Dockerfile, WORKSPACE, docs/INSTALL-OSX.md, scripts/check_docs
=> Upgrade Rust version

examples/hello_world/example.toml, runner/src/main.rs
=> Integrate the Node.js client with the rust runner

.github/workflows/build_rust_docs.yaml, .github/workflows/reproducibility.yaml, docs/CONTRIBUTING.md, docs/programming-oak.md, oak/server/rust/oak_runtime/src/node/wasm/mod.rs, oak/server/rust/oak_runtime/src/runtime/channel.rs, oak/server/rust/oak_runtime/src/runtime/mod.rs, oak_abi/src/label/mod.rs, sdk/rust/oak/src/lib.rs
1. Merge this PR, which renames all internal mentions. (Doing so requires GitHub admin privileges to overwrite the required build check, which is failing due to the currently incorrect links to `https://github.com/project-oak/oak/blob/main/*` in the docs. Worry not, going through this process will make these links exist).
2. Clone this repo via `git clone https://github.com/project-oak/oak.git`
3. Create a local `main` branch via `git branch -m master main`
4. Push it up to the repo with `git push -u origin main`
5. Change the default branch in the GitHub repository settings. You'll see a warning, but it'll be alright.
6. Go through each open PR and change the base branch from `master` to `main`
7. Delete the remote master branch with `git push origin --delete master`
8. Live happily ever …
=> Rename master branch to main

examples/aggregator/README.md, examples/aggregator/gcp/aggregator-dashboard.json
Adds a json file to the Aggregator example, describing the GCP dashboard. The README file is updated with instructions for programatically creating the dashboard from the json file.
=> Add json for Aggregator's monitoring dashboard

docs/programming-oak.md, examples/abitest/tests/src/tests.rs, examples/aggregator/module/rust/tests/integration_test.rs, examples/hello_world/module/rust/tests/integration_test.rs, examples/private_set_intersection/module/rust/tests/integration_test.rs, examples/running_average/module/rust/tests/integration_test.rs, examples/translator/module/rust/tests/integration_test.rs, examples/trusted_information_retrieval/module/rust/src/config.rs, examples/trusted_information_retrieval/module/rust/src/lib.rs, examples/trusted_information_retrieval/module/rust/tests/integration_test.rs, oak/server/rust/oak_loader/src/main.rs, oak/server/rust/oak_runtime/src/config.rs, oak/server/rust/oak_runtime/src/lib.rs, oak/server/rust/oak_runtime/src/node/mod.rs, oak/server/rust/oak_runtime/src/node/wasm/tests.rs, oak/server/rust/oak_runtime/src/runtime/channel.rs, oak/server/rust/oak_runtime/src/runtime/graph.rs, oak/server/rust/oak_runtime/src/runtime/introspect.rs, oak/server/rust/oak_runtime/src/runtime/mod.rs, oak/server/rust/oak_runtime/src/runtime/proxy.rs, oak/server/rust/oak_runtime/src/runtime/tests.rs, oak/server/rust/oak_runtime/tests/integration_test.rs, sdk/rust/oak/src/lib.rs, sdk/rust/oak_tests/src/lib.rs
=> Add helpers and docs for initial config map

examples/aggregator/README.md, examples/aggregator/gcp/aggregator-alert-policy.json, examples/aggregator/scripts/monitoring
=> Add instructions for programatically creating alert policies

BUILD, examples/aggregator/server/BUILD, scripts/build_example, scripts/run_example
Ref [this problem](https://github.com/project-oak/oak/issues/971#issuecomment-646796010) related to #971.
See also [this](https://github.com/project-oak/oak/issues/971#issuecomment-647615479) and [this](https://github.com/project-oak/oak/issues/971#issuecomment-647944747).
=> Specify build target for backend components in examples

examples/aggregator/README.md
Updated the README to match the current state of the code.
=> Update README for aggregator

.tsan_suppress, scripts/run_tests_tsan
=> scripts: suppress ThreadSanitizer report on shutdown

docs/concepts.md
Ref for details: https://project-oak.slack.com/archives/CC03DDX3M/p1593168273206100
construction.
=> Docs: Verbosify IFC example to increase clarity

.github/workflows/upload_coverage.yaml, Dockerfile, scripts/run_tests_coverage
=> Build coverage information from abitest run

scripts/build_example, scripts/run_example
This change adds brackets in bash variables.
=> Use brackets in bash variables

examples/tensorflow/client/tensorflow.cc, examples/tensorflow/module/cpp/BUILD, scripts/run_example
=> Fix tensorflow example

oak/server/rust/oak_runtime/src/node/grpc/server/mod.rs
Ref [comment on 1204](https://github.com/project-oak/oak/pull/1204#discussion_r447100403)
=> Move metrics related logic in grpc server to a separate struct

oak/server/rust/oak_runtime/src/metrics/mod.rs, oak/server/rust/oak_runtime/src/node/grpc/client.rs, oak/server/rust/oak_runtime/src/node/grpc/server/mod.rs
=> Add grpc client metrics

examples/Cargo.lock, examples/trusted_information_retrieval/backend/Cargo.toml, examples/trusted_information_retrieval/backend/src/main.rs
=> Make server shutdown gracefully on signal

docs/programming-oak.md, examples/abitest/config/config.textproto, examples/aggregator/config/config.textproto, examples/chat/config/config.textproto, examples/hello_world/config/config.textproto, examples/machine_learning/config/config.textproto, examples/private_set_intersection/config/config.textproto, examples/running_average/config/config.textproto, examples/tensorflow/config/config.textproto, examples/translator/config/config.textproto, examples/trusted_information_retrieval/config/config.textproto
=> Remove unused textproto files

sdk/Cargo.lock, sdk/rust/oak/Cargo.toml
=> Remove unused dev dependencies from SDK

scripts/build_example, scripts/docker_run, scripts/run_example
=> scripts: restore macOS

.codecov.yml, README.md, WORKSPACE, examples/abitest/client/BUILD, examples/abitest/client/abitest.cc, scripts/run_tests_coverage
=> Test auxiliary servers in abitest

cloudbuild.yaml
=> Fix cloudbuild dependencies

examples/Cargo.lock, sdk/Cargo.lock, sdk/rust/oak/Cargo.toml, sdk/rust/oak/src/io/receiver.rs, sdk/rust/oak/src/io/sender.rs, sdk/rust/oak/src/lib.rs
=> sdk: don't allow serialization of Handles

oak/server/rust/oak_loader/src/main.rs, oak/server/rust/oak_loader/src/options.rs, oak/server/rust/oak_loader/src/tests.rs
A bit of refactoring before starting with #1029
=> Move helper functions in oak_loader to a separate submodule

cloudbuild.yaml, oak/proto/introspection_events.proto, oak/server/rust/oak_runtime/build.rs, oak/server/rust/oak_runtime/src/proto/mod.rs, oak/server/rust/oak_runtime/src/runtime/introspection_events.rs, oak/server/rust/oak_runtime/src/runtime/mod.rs
See #913 for background
construction.
=> Add basic introspection_event method to the Runtime

cloudbuild.yaml, runner/src/main.rs
See the discussion in https://project-oak.slack.com/archives/CHE9E13C3/p1594984760219500 for background. 
construction.
=> Move cloudbuild step of packaging an example into the runner

oak/proto/introspection_events.proto
=> Add missing types to the introspection event schema

oak/server/rust/oak_runtime/src/runtime/mod.rs
Implements events for when messages are written & read. Via #913
construction.
=> Implement MessageEnqueued, MessageDequeued events

docs/CONTRIBUTING.md
=> Clarify code formatting in our contributing docs

oak/server/rust/oak_runtime/src/metrics/server.rs, oak/server/rust/oak_runtime/src/runtime/introspect.rs, oak/server/rust/oak_runtime/src/runtime/mod.rs
For introspection we'll add another channel to aux servers, so this naming clarifies the scope/purpose of the existing one-shot channel.
See #913 & https://github.com/project-oak/oak/issues/913#issuecomment-657698910 for context
construction.
=> Aux servers: rename notify_sender to termination_notificiation_sender for clarity

docs/CONTRIBUTING.md
Tiziano [requesteth](https://project-oak.slack.com/archives/CHE9E13C3/p1596117170374000?thread_ts=1596111762.363100&cid=CHE9E13C3), Juliette delivereth
construction.
=> Prefix format command with docker_run

docs/Docker.md, runner/src/main.rs
=> Tiny doc fixes

runner/src/main.rs
Tried to disable liche with minimum change to the code... Is there a better way to do this?
=> Disable liche

examples/aggregator/client/aggregator.cc
=> Assign label to aggregator example

runner/src/internal.rs
=> Print failing command if there is any error

oak/server/Cargo.lock, oak/server/rust/oak_loader/Cargo.toml, oak/server/rust/oak_runtime/src/lib.rs, oak/server/rust/oak_runtime/src/permissions.rs
=> Add a new module and struct for configuring permitted features

examples/Cargo.lock, examples/aggregator/client/aggregator.cc, examples/aggregator/config.toml, examples/aggregator/example.toml, examples/aggregator/module/rust/Cargo.toml, examples/aggregator/module/rust/src/lib.rs, examples/aggregator/module/rust/tests/integration_test.rs, examples/aggregator/oak_app_manifest.toml, sdk/rust/oak_tests/src/lib.rs
=> Configure gRPC port for aggregator example

examples/Cargo.lock, examples/Cargo.toml, examples/hello_world/client/rust/Cargo.toml, examples/hello_world/client/rust/src/main.rs, examples/hello_world/example.toml
Basic hello world example client in Rust. 
construction.
=> Hello World client in Rust

docs/programming-oak.md, examples/authentication/README.md, examples/chat/README.md
=> Fixes in docs

oak/server/rust/oak_runtime/src/channel.rs, oak/server/rust/oak_runtime/src/lib.rs, oak/server/rust/oak_runtime/src/proxy.rs
~Ready for review once #1342 is merged.~ Ready for review. :) 
See the related issue #913
construction.
=> Implement ChannelDestroyed event

examples/hello_world/client/rust/src/main.rs
=> Improve Future usage in hello world example

docs/concepts.md
Proposing these changes in small PRs so they can be reviewed carefully. 
This aligns the description of the confidentiality- & integrity checks with the mental model I mentioned earlier: https://project-oak.slack.com/archives/CC03DDX3M/p1593173725212500
More specifically it aims to answer the questions of "What's the specific purpose of each check?" and "Why do we need both?" which were top-of-mind for me when first learning about our IFC system.
construction.
=> IFC docs: Clarify confidentiality- & integrity check definitions

experimental/ni_coq/README.md, experimental/ni_coq/vfiles/EvAugSemantics.v, experimental/ni_coq/vfiles/Events.v, experimental/ni_coq/vfiles/LowEquivalences.v, experimental/ni_coq/vfiles/Parameters.v, experimental/ni_coq/vfiles/RuntimeModel.v
- [ x ] Pull request includes prototype/experimental work that is under
construction.
=> Use ssreflect.finmap; options for channels, nodes

experimental/ni_coq/vfiles/EvAugSemantics.v, experimental/ni_coq/vfiles/PossibilisticNI.v
The EvAug semantics is refactored so that it no longer is a state ->
trace -> state -> trace -> Prop relation but instead just a trace ->
trace -> Prop relation. This removes the need to have various
propositions about the states and traces involved in the step relation
agreeing. This also updates the statement of possibilistic NI and the
single step theorem. In the process, some problems with both of those
theorems are fixed. There is also some progress on the proof
for possibilistic NI. It is mostly done aside from some smaller lemmas
that I think are true but are admitted (the proof of the single-step
theorem is also still admitted).
construction.
=> EvAug cuts out states; progress on PossibilisticNI

oak_io/src/lib.rs, oak_loader/Cargo.lock, oak_loader/Cargo.toml, oak_loader/src/options.rs, oak_loader/src/tests.rs, oak_runtime/Cargo.lock, oak_runtime/Cargo.toml, oak_runtime/deny.toml, oak_runtime/src/config.rs, oak_runtime/src/io.rs, oak_runtime/src/node/grpc/client.rs, oak_runtime/src/node/grpc/invocation.rs, oak_runtime/src/node/http/mod.rs, oak_runtime/src/node/http/tests.rs, oak_runtime/src/node/roughtime.rs, oak_runtime/src/node/wasm/mod.rs, oak_runtime/src/node/wasm/tests.rs, oak_runtime/tests/integration_test.rs
=> Fix oak_runtime tests and formatting

oak_runtime/src/node/http/tests.rs
Add a test to check that HTTP server node rejects unsecure requests
=> Negative test for HTTP server pseudo-node

oak_runtime/src/node/http/tests.rs
Addresses [this comment](https://github.com/project-oak/oak/pull/1397/files#r478521829) and [this comment](https://github.com/project-oak/oak/pull/1397/files#r478519569).
=> Make HTTP tests more idiomatic

experimental/ni_coq/README.md, experimental/ni_coq/vfiles/EvAugSemantics.v, experimental/ni_coq/vfiles/Events.v, experimental/ni_coq/vfiles/Parameters.v, experimental/ni_coq/vfiles/RuntimeModel.v, experimental/ni_coq/vfiles/TraceTheorems.v
=> Fix channel_write channel_read calls

examples/hello_world/client/nodejs/index.js, runner/src/main.rs
=> Format JavaScript & TypeScript with prettier

experimental/ni_coq/vfiles/TraceTheorems.v
=> Proofs of Lemmas in TraceTheorems.v

docs/development.md
=> Put --logs in the right place

oak_runtime/introspection_browser_client/components/ApplicationStateOverview/index.tsx, oak_runtime/introspection_browser_client/components/Root/index.tsx, oak_runtime/src/lib.rs, proto/introspection_events.proto
=> Add Node name & ChannelHalf direction support to the introspection client

oak_runtime/introspection_browser_client/build, oak_runtime/introspection_browser_client/components/ApplicationStateOverview/index.tsx, oak_runtime/introspection_browser_client/components/EventList/index.tsx, oak_runtime/introspection_browser_client/components/Root/index.tsx, oak_runtime/src/lib.rs, oak_runtime/src/proto/mod.rs, oak_utils/src/lib.rs, proto/introspection_events.proto
=> Add labels to introspection events

oak_runtime/src/node/http/mod.rs, oak_runtime/src/node/http/tests.rs
=> Fix early termination of HTTP server node

oak_runtime/introspection_browser_client/components/MainTabs/index.tsx, oak_runtime/introspection_browser_client/components/Root/index.tsx, oak_runtime/introspection_browser_client/components/StateGraph/index.tsx, oak_runtime/introspection_browser_client/package-lock.json, oak_runtime/introspection_browser_client/package.json, oak_runtime/introspection_browser_client/static/index.html
=> Introspection: Add basic styles & navigation

examples/Cargo.lock, examples/http_server/README.md, examples/http_server/module/Cargo.toml, examples/http_server/module/src/lib.rs, examples/http_server/module/static/index.html, oak_runtime/src/node/http/mod.rs, oak_runtime/src/node/http/tests.rs, oak_services/proto/http_encap.proto
Rename path to uri in proto message.
Add instructions on how to run and test the example via a browser.
construction.
=> Implement more comprehensive HTTP example

oak_runtime/src/node/http/mod.rs
=> Respond with bad request if oak-label is not set in HTTP request

experimental/ni_coq/vfiles/TraceTheorems.v
Following up on a conversation with @aferr, this PR creates some tactic scripts from the proofs in `TraceTheorems.v` and uses them instead of manual manipulations. This should make the proofs less sensitive to code changes, and take some pain out of proving future theorems.
Some of the tactics (e.g. `destruct_match`) are pretty general-purpose and could be factored out so other files can import them.
construction.
=> Proof automation in TraceTheorems.v

docs/programming-oak.md, examples/abitest/module_0/rust/tests/integration_test.rs, examples/aggregator/module/rust/tests/integration_test.rs, examples/chat/module/rust/tests/integration_test.rs, examples/hello_world/module/rust/tests/integration_test.rs, examples/private_set_intersection/module/rust/tests/integration_test.rs, examples/running_average/module/rust/tests/integration_test.rs, examples/translator/module/rust/tests/integration_test.rs, examples/trusted_information_retrieval/module_0/rust/tests/integration_test.rs, examples/trusted_information_retrieval/module_1/rust/tests/integration_test.rs, oak_runtime/src/tests.rs, oak_runtime/tests/integration_test.rs
=> Mark env_logger test instances as is_test(true)

experimental/ni_coq/vfiles/PossibilisticNI.v, experimental/ni_coq/vfiles/RuntimeModel.v
=> Proof of unwinding for havoc call.

oak_runtime/introspection_browser_client/components/EventList/index.tsx, oak_runtime/introspection_browser_client/components/Root/index.tsx, oak_runtime/introspection_browser_client/components/StateGraph/index.tsx, oak_runtime/introspection_browser_client/components/TimeTravelControls/index.tsx, oak_runtime/introspection_browser_client/package-lock.json, oak_runtime/introspection_browser_client/package.json
Implements the basic functionality, will work with a designer to improve the UI
construction.
=> Introspection: Add functionality to view past application states

oak_runtime/Cargo.toml, runner/src/internal.rs, runner/src/main.rs, sdk/rust/oak_tests/Cargo.toml
Possibly best viewed commit-by-commit, if only for the rationales in the commit descriptions.
=> Various fixes to improve interactive development

examples/Cargo.lock, oak_loader/Cargo.lock, oak_runtime/Cargo.lock, oak_runtime/Cargo.toml, oak_runtime/src/node/logger.rs, sdk/Cargo.lock
=> Logging pseudo-Node improvements

oak_runtime/introspection_browser_client/package-lock.json, oak_runtime/introspection_browser_client/package.json, oak_runtime/introspection_browser_client/webpack.config.js
=> Cache TypeScript compilation

oak_runtime/src/lib.rs, oak_runtime/src/metrics/mod.rs, oak_runtime/src/node/grpc/client.rs, oak_runtime/src/node/grpc/server/mod.rs, oak_runtime/src/node/http/mod.rs, oak_runtime/src/node/logger.rs, oak_runtime/src/node/mod.rs, oak_runtime/src/node/roughtime.rs, oak_runtime/src/node/storage.rs, oak_runtime/src/node/wasm/mod.rs, oak_runtime/src/proxy.rs, oak_runtime/src/tests.rs, oak_runtime/tests/integration_test.rs
=> runtime: break down node count metric by type

examples/abitest/client/abitest.cc, examples/aggregator/client/aggregator.cc, examples/chat/client/chat.cc, examples/chat/module/rust/src/backend.rs, examples/hello_world/client/hello_world.cc, examples/injection/client/injection.cc, examples/machine_learning/client/machine_learning.cc, examples/private_set_intersection/client/private_set_intersection.cc, examples/running_average/client/running_average.cc, examples/tensorflow/client/tensorflow.cc, examples/trusted_information_retrieval/client/trusted_information_retrieval.cc, oak/client/application_client.h, oak_runtime/src/node/grpc/server/mod.rs
=> Improve examples esp. chat

runner/src/internal.rs, runner/src/main.rs, scripts/run_tests_coverage
=> Runner tweaks

oak_runtime/src/node/http/tests.rs
=> Retry sending requests in HTTP tests to make the tests stable

oak_runtime/src/node/http/tests.rs
Ref [comment on 1469](https://github.com/project-oak/oak/pull/1469#discussion_r489710316)
=> Use the runtime to start the test HTTP server node

scripts/run_tests_coverage
=> Drop branch info from coverage data

oak_runtime/introspection_browser_client/components/Root/index.tsx
=> Introspection: Add support for message events

oak_runtime/introspection_browser_client/components/StateGraph/index.tsx
=> Introspection: Add basic support for messages to the state graph

oak_runtime/introspection_browser_client/build, oak_runtime/introspection_browser_client/package.json, oak_runtime/introspection_browser_client/webpack.config.js
=> Introspection: Merge the dev setup with the build script

oak_runtime/introspection_browser_client/components/MainTabs/index.tsx
https://reactjs.org/docs/lists-and-keys.html#keys
construction.
=> Introspection Tabs: Add missing React keys

oak_runtime/introspection_browser_client/components/ChannelDetails/index.tsx, oak_runtime/introspection_browser_client/components/HandleDetails/index.tsx, oak_runtime/introspection_browser_client/components/NodeDetails/index.tsx, oak_runtime/introspection_browser_client/components/NotFound/index.tsx, oak_runtime/introspection_browser_client/components/Root/index.tsx, oak_runtime/introspection_browser_client/components/StateGraph/index.tsx, oak_runtime/introspection_browser_client/package-lock.json, oak_runtime/introspection_browser_client/package.json, oak_runtime/introspection_browser_client/static/index.html, oak_runtime/introspection_browser_client/webpack.config.js, oak_runtime/src/introspect.rs
Adds client side routing, and placeholder details pages for nodes, handles, channels
construction.
=> Introspection: Add client-side routing

oak_runtime/introspection_browser_client/components/Event/index.tsx, oak_runtime/introspection_browser_client/components/EventList/index.tsx
=> Semantically format Events

examples/http_server/module/src/lib.rs, oak_runtime/src/node/http/mod.rs, oak_services/proto/http_encap.proto
=> Allow headers with multiple values

experimental/ni_coq/_CoqProject, experimental/ni_coq/vfiles/EvAugSemantics.v, experimental/ni_coq/vfiles/Events.v, experimental/ni_coq/vfiles/LowEquivalences.v, experimental/ni_coq/vfiles/NIUtilTheorems.v, experimental/ni_coq/vfiles/PossibilisticNI.v, experimental/ni_coq/vfiles/RuntimeModel.v, experimental/ni_coq/vfiles/TraceTheorems.v, experimental/ni_coq/vfiles/Unwind.v
=> Restructure NI defs to use low projections. NI Proofs using low proj steps.

experimental/ni_coq/vfiles/GenericMap.v, experimental/ni_coq/vfiles/NIUtilTheorems.v, experimental/ni_coq/vfiles/PossibilisticNI.v
=> Nflows case for low_proj_steps_implies_leq_step

oak_runtime/introspection_browser_client/components/ApplicationStateOverview/index.tsx, oak_runtime/introspection_browser_client/components/ChannelDetails/index.tsx, oak_runtime/introspection_browser_client/components/Event/index.tsx, oak_runtime/introspection_browser_client/components/Node/index.tsx, oak_runtime/introspection_browser_client/components/ObjectAsDescriptionList/index.tsx, oak_runtime/introspection_browser_client/components/Root/index.tsx
Best to review commit by commit as some refactoring precedes this change to make it easier to implement. 
construction.
=> Display NodeDetails in a description list

docs/concepts.md, docs/development.md, docs/programming-oak.md
This change updates docs regarding Wasm signature labels.
=> Update docs for signature labels

experimental/Cargo.lock, oak_runtime/src/node/http/mod.rs, oak_services/src/http/mod.rs
Ref [comment on 1528](https://github.com/project-oak/oak/pull/1528#discussion_r497370582).
=> Implement IntoIterator for HeaderMap in oak_services

experimental/ni_coq/vfiles/EvAugSemantics.v, experimental/ni_coq/vfiles/GenericMap.v, experimental/ni_coq/vfiles/NIUtilTheorems.v, experimental/ni_coq/vfiles/PossibilisticNI.v, experimental/ni_coq/vfiles/Unwind.v
=> Lowproj step WriteChannel FlowsTo case

experimental/ni_coq/_CoqProject, experimental/ni_coq/vfiles/NIUtilTheorems.v, experimental/ni_coq/vfiles/PossibilisticNI.v, experimental/ni_coq/vfiles/Unwind.v
=> WriteChannel step_implies_lowproj_steps proof

examples/trusted_information_retrieval/module_1/rust/src/lib.rs
This change removes commented code in TIR
=> Remove commented code in TIR

oak_runtime/src/lib.rs
Previously there was bug in which the channel was dropped before the `HandleDestroyed` event fired. This led to an oddly ordered list of events, in which handles referenced channels that no longer existed. 
construction.
=> Ensure HandleDestroyed event fires before ChannelDestroyed

examples/aggregator/client/cpp/aggregator.cc, examples/aggregator/module/rust/src/data.rs, examples/aggregator/module/rust/src/lib.rs, examples/aggregator/module/rust/tests/integration_test.rs, examples/aggregator/oak_app_manifest.toml, examples/aggregator/proto/aggregator_init.proto
This change makes Aggregator create gRPC client Node before receiving invocations.
Fixes https://github.com/project-oak/oak/issues/1246
=> Change aggregator creation

experimental/ni_coq/vfiles/NIUtilTheorems.v, experimental/ni_coq/vfiles/PossibilisticNI.v
=> Finish proof of step_implies_lowproj_steps_leq

experimental/ni_coq/vfiles/PossibilisticNI.v
=> Finish low_proj_steps_implies... + ..._unwind_t; tactics

examples/trusted_database/module/rust/src/database.rs, examples/trusted_database/module/rust/src/handler.rs, examples/trusted_database/module/rust/src/lib.rs, examples/trusted_database/module/rust/src/tests.rs, examples/trusted_database/proto/trusted_database.proto, experimental/Cargo.lock, experimental/Cargo.toml, experimental/benchmark/Cargo.toml, experimental/benchmark/build.rs, experimental/benchmark/src/application/mod.rs, experimental/benchmark/src/application/native.rs, experimental/benchmark/src/application/oak.rs, experimental/benchmark/src/application/raw.rs, experimental/benchmark/src/database.rs, experimental/benchmark/src/main.rs, experimental/deny.toml
This change adds an experimental Trusted Database benchmark.
Ref https://github.com/project-oak/oak/issues/1522
construction.
=> Add Trusted Database benchmark

examples/Cargo.lock, examples/chat/module/rust/Cargo.toml, examples/chat/module/rust/src/backend.rs, examples/http_server/module/Cargo.toml, examples/http_server/module/src/lib.rs, examples/injection/module/rust/Cargo.toml, examples/injection/module/rust/src/lib.rs, examples/trusted_database/module/rust/src/lib.rs, experimental/Cargo.lock, sdk/Cargo.lock, sdk/rust/oak/Cargo.toml, sdk/rust/oak/src/grpc/mod.rs, sdk/rust/oak/src/lib.rs
=> Use anyhow for error handling in CommandHandler

oak_runtime/introspection_browser_client/components/Event/index.tsx, oak_runtime/introspection_browser_client/components/EventList/index.tsx, oak_runtime/introspection_browser_client/components/Root/index.tsx, oak_runtime/introspection_browser_client/package-lock.json, oak_runtime/introspection_browser_client/package.json, oak_runtime/src/lib.rs, proto/introspection_events.proto
- Use the node name consistenly
- Highlight most relevant information
- Clip details at one line for brevity
- Add a dialog to see the full change details
construction.
=> Introspection: Improve change list

experimental/ni_coq/vfiles/LowEquivalences.v, experimental/ni_coq/vfiles/NIUtilTheorems.v, experimental/ni_coq/vfiles/PossibilisticNI.v, experimental/ni_coq/vfiles/RuntimeModel.v
=> Fix state projection defs; finish unobs_step lemma

oak_runtime/src/lib.rs, oak_runtime/src/node/http/tests.rs, oak_runtime/src/proxy.rs, oak_runtime/src/tests.rs
=> Allow creating Oak nodes for testing

examples/deny.toml, experimental/deny.toml, oak_loader/deny.toml, oak_runtime/deny.toml, oak_sign/deny.toml, runner/deny.toml, sdk/deny.toml
Fixes #1268 
Resolves part of #1270 
construction.
=> Resolve additional cargo-deny warnings

scripts/git_clean
=> Add git clean script that preserves auth files

oak_runtime/introspection_browser_client/components/StateGraph/index.tsx
=> Show channel name in the dynamic introspection graph

examples/chat/module/rust/src/lib.rs
Caused by a race condition between submission of #1653 and #1648
construction.
=> Add node name to `node_create` call

experimental/ni_coq/vfiles/EvAugSemantics.v, experimental/ni_coq/vfiles/Events.v, experimental/ni_coq/vfiles/GenericMap.v, experimental/ni_coq/vfiles/LowEquivalences.v, experimental/ni_coq/vfiles/NIUtilTheorems.v, experimental/ni_coq/vfiles/PossibilisticNI.v, experimental/ni_coq/vfiles/RuntimeModel.v, experimental/ni_coq/vfiles/Unwind.v
=> Amend definitions of labeled things.

oak_runtime/src/io.rs, oak_runtime/src/lib.rs, oak_runtime/src/proxy.rs
=> Add label to ReceiverExt and SenderExt in the runtime

experimental/oak_async/src/grpc.rs, experimental/oak_async/src/io.rs, experimental/oak_async/src/lib.rs, oak_utils/src/lib.rs
construction.
Example of using the new Async service code can be found at: https://github.com/wildarch/oak/blob/async_service_with_chat/examples/chat/module/rust/src/lib.rs.
=> Async service generator

oak_io/src/lib.rs
=> Define InitWrapper message

oak_utils/src/lib.rs, sdk/rust/oak/src/stubs.rs
=> Streamline stubs

docs/abi.md
See https://github.com/project-oak/oak/pull/1648#pullrequestreview-522261737
construction.
=> Add explanation of node name

runner/src/main.rs
This brings the prettier step down from 55s to 3s on my machine.
The error message still mentions the correct file in case of failure:
```
[23:24:26; E:0,O:0,R:10]: ci ❯ format ❯ prettier (coalesced) ⊢ ERROR [3s]
ci ❯ format ❯ prettier (coalesced) ╔════════════════════════
ci ❯ format ❯ prettier (coalesced) ║ ════╡ stdout ╞════
ci ❯ format ❯ prettier (coalesced) ║ Checking formatting...
ci ❯ format ❯ prettier (coalesced) ║ ════╡ stderr ╞════
ci ❯ format ❯ prettier (coalesced) ║ [warn] README.md
ci ❯ format ❯ prettier (coalesced) ║ [warn] Code style issues found in the above file(s). Forgot to run Prettier?
ci ❯ format ❯ prettier (coalesced) ╚════════════════════════
```
Fix #1680
=> Make runner format step faster

docs/programming-oak.md, examples/Cargo.lock, examples/private_set_intersection/README.md, examples/private_set_intersection/module/rust/Cargo.toml, examples/private_set_intersection/module/rust/src/lib.rs, examples/private_set_intersection/oak_app_manifest.toml, examples/private_set_intersection/private_set_intersection.sign, examples/running_average/module/rust/Cargo.toml, examples/running_average/module/rust/src/lib.rs
=> Implement main / handler pattern for more examples

examples/Cargo.lock, examples/abitest/client/cpp/BUILD, examples/abitest/module_0/rust/src/lib.rs, examples/abitest/module_0/rust/tests/integration_test.rs, experimental/Cargo.lock, oak_derive/Cargo.lock, oak_io/Cargo.lock, oak_io/Cargo.toml, oak_io/src/lib.rs, oak_loader/Cargo.lock, oak_runtime/Cargo.lock, oak_runtime/src/channel.rs, oak_runtime/src/node/http/mod.rs, oak_services/Cargo.lock, sdk/Cargo.lock, sdk/rust/oak/src/grpc/server.rs, sdk/rust/oak/src/http/mod.rs, sdk/rust/oak/src/io/mod.rs
=> Test and fix leaks, improve things along the way

oak_runtime/introspection_browser_client/components/EventListWrapper/index.tsx, oak_runtime/introspection_browser_client/components/Root/index.tsx
=> Allow users to resize the event list

experimental/ni_coq/vfiles/LowEquivalences.v, experimental/ni_coq/vfiles/NIUtilTheorems.v, experimental/ni_coq/vfiles/PossibilisticNI.v
=> Implement new defintions suggested by @jadephilipoom

examples/abitest/module_0/rust/src/lib.rs
=> More abitest tweaks

examples/abitest/client/cpp/BUILD, oak/common/BUILD, oak_abi/proto/label.proto
=> Remove unnecessary bazel target

docs/programming-oak.md, examples/Cargo.lock, examples/machine_learning/module/rust/Cargo.toml, examples/machine_learning/module/rust/build.rs, examples/machine_learning/module/rust/src/lib.rs
I think we just implemented this manually in the early days before we
had protobuf support.
=> Use protobuf for machine_learning example

examples/Cargo.lock, experimental/Cargo.lock, oak_derive/Cargo.lock, oak_derive/src/lib.rs, oak_derive/tests/visit.rs, oak_io/Cargo.lock, oak_io/Cargo.toml, oak_io/src/handle.rs, oak_io/src/receiver.rs, oak_io/src/sender.rs, oak_loader/Cargo.lock, oak_runtime/Cargo.lock, oak_services/Cargo.lock, sdk/Cargo.lock
=> Change signature of `HandleVisit` impl function to a fold.

oak_runtime/src/graph.rs
=> runtime: de-dup channels in introspection graph

experimental/ni_coq/vfiles/NIUtilTheorems.v
This is a continuation of #1710 (because I made some git mistakes).
=> Prove set_call_unobs

oak_runtime/src/tests.rs
=> Fix runtime tests

examples/Cargo.lock, examples/deny.toml, experimental/Cargo.lock, experimental/deny.toml, oak_loader/Cargo.lock, oak_loader/deny.toml, oak_runtime/Cargo.lock, oak_runtime/Cargo.toml, oak_runtime/deny.toml, sdk/Cargo.lock, sdk/deny.toml
=> Update prometheus version

examples/abitest/module_0/rust/src/lib.rs, oak_runtime/src/node/logger.rs, sdk/rust/oak/src/logger/mod.rs
=> Give top privilege to logger in debug builds

scripts/run_cargo_crev
Linked to #1201 
construction.
=> Add root ID to cargo crev verification script

experimental/ni_coq/_CoqProject, experimental/ni_coq/vfiles/LowEqPS.v, experimental/ni_coq/vfiles/LowProjPS_Thms.v, experimental/ni_coq/vfiles/NIUtilTheorems.v, experimental/ni_coq/vfiles/PossibilisticNI.v, experimental/ni_coq/vfiles/RuntimeModelPS.v
The two different definitions of low projection and two different models
discussed in (issue #1722)[https://github.com/project-oak/oak/issues/1722]
are both alive in the code up to some smaller theorems.
The code redundancy is not ideal at the moment, so if these are really
meant to stay alive forever, then that should be improved at some point.
construction.
=> Split low projection definitions + model

oak_runtime/src/lib.rs
Ignores errors in case the NodeInfo entry for a node cannot be found,
but log a warning in that case as it is not something that we would
expect to happen often (ever?) in production.
This may probably be fixed in a better way by a more general refactoring partially
undoing part of
https://github.com/project-oak/oak/commit/76d0ff37cf0edf6f23dffdd5e53dcc4b4695b65f
, but for now this seems a good compromise.
Fixes #1762
construction.
=> Fix race condition in add_node_stopper

examples/Cargo.lock, examples/aggregator/backend/Cargo.toml, examples/authentication/client/Cargo.toml, examples/hello_world/client/rust/Cargo.toml, examples/http_server/client/rust/Cargo.toml, examples/private_set_intersection/client/rust/Cargo.toml, examples/trusted_database/client/rust/Cargo.toml, experimental/Cargo.lock, experimental/oak_async/Cargo.toml, experimental/split_grpc/proxy/src/main.rs, experimental/split_grpc/server/Cargo.toml, oak_abi/Cargo.lock, oak_client/Cargo.lock, oak_derive/Cargo.lock, oak_io/Cargo.lock, oak_loader/Cargo.lock, oak_runtime/Cargo.lock, oak_runtime/Cargo.toml, oak_runtime/src/node/grpc/codec.rs, oak_services/Cargo.lock, oak_sign/Cargo.lock, oak_utils/Cargo.lock, runner/Cargo.lock, runner/Cargo.toml, runner/src/internal.rs, sdk/Cargo.lock, sdk/rust/oak_app_build/Cargo.toml
=> Update Rust deps across the workspaces

.github/workflows/coq.yaml, experimental/ni_coq/vfiles/NIUtilTheorems.v, experimental/ni_coq/vfiles/PossibilisticNI.v
=> Finish Proofs in PossibilisticNI.v

docs/abi.md, docs/concepts.md
=> docs: consistency fixes

experimental/ni_coq/vfiles/Unwind.v
The proof of the last theorem is clearly a mess, though.
construction.
=> Finish set_call_unwind (And NI proof!)

chrome_extension/background.js
=> Prevent false positives for pages whose CSP cannot be checked

experimental/Cargo.lock, experimental/Cargo.toml, experimental/treehouse/application/client/rust/Cargo.toml, experimental/treehouse/application/client/rust/build.rs, experimental/treehouse/application/client/rust/src/lib.rs, experimental/treehouse/application/client/rust/src/main.rs, experimental/treehouse/application/example.toml, experimental/treehouse/application/module/Cargo.toml, experimental/treehouse/application/module/build.rs, experimental/treehouse/application/module/src/handler.rs, experimental/treehouse/application/module/src/lib.rs, experimental/treehouse/application/module/src/router.rs, experimental/treehouse/application/proto/treehouse.proto, experimental/treehouse/application/proto/treehouse_init.proto
Ref https://github.com/project-oak/oak/issues/1795
=> Add empty Treehouse Oak Application

experimental/web/.eslintrc.js, experimental/web/build, experimental/web/index.ts, experimental/web/package-lock.json, experimental/web/package.json
=> Start migration to protoc generated code away protobufjs

experimental/Cargo.lock, experimental/treehouse/application/client/src/main.rs, experimental/treehouse/application/module/Cargo.toml, experimental/treehouse/application/module/src/handler.rs, experimental/treehouse/application/proto/treehouse.proto, experimental/treehouse/fetch/src/lib.rs
=> Get calendar events in a date

experimental/web/index.ts, experimental/web/static/index.html
=> Retrieve wasm module from url

experimental/Cargo.lock, experimental/treehouse/application/module/Cargo.toml, experimental/treehouse/application/module/src/handler.rs, experimental/treehouse/application/module/src/lib.rs, experimental/treehouse/application/proto/treehouse.proto
=> More meaningful response from handler

experimental/treehouse/application/module/src/handler.rs, runner/src/main.rs
=> Use valid certificate

experimental/treehouse/application/example.toml, experimental/treehouse/application/module/src/handler.rs
=> Fix ConfigMap

experimental/treehouse/application/client/src/main.rs, experimental/treehouse/application/module/src/handler.rs
=> More fixes

experimental/treehouse/application/module/src/handler.rs, experimental/treehouse/application/proto/treehouse.proto
=> Allow origin for loading photos

experimental/treehouse/application/client/src/main.rs, experimental/treehouse/application/example.toml, experimental/treehouse/application/module/src/handler.rs, experimental/treehouse/application/proto/treehouse.proto, experimental/web/static/index.html, oak_loader/src/options.rs, oak_runtime/src/node/http/client.rs
=> Improved card response

chrome_extension/README.md, chrome_extension/background.js, chrome_extension/getInnerHtml.js, chrome_extension/index.html, chrome_extension/manifest.json
=> Update chrome extension to prevent top level navigation

chrome_extension/background.js, chrome_extension/index.html, chrome_extension/manifest.json
=> Chrome extension: Fail a bit more gracefully

chrome_extension/README.md
=> Improve chrome extension readme

examples/Cargo.lock, examples/trusted_database/client/rust/Cargo.toml, examples/trusted_database/client/rust/src/main.rs, experimental/Cargo.lock, experimental/Cargo.toml, oak_client/src/interceptors/auth.rs, oak_runtime/Cargo.lock, oak_runtime/src/node/grpc/server/mod.rs
=> Add challenge response support to the gRPC server node

oak_runtime/src/node/http/server.rs, oak_runtime/src/node/http/tests.rs, oak_runtime/src/node/http/util.rs
=> Use anyhow in HttpServerNode

oak_runtime/src/lib.rs, scripts/run_tests_coverage, third_party/prost/prost-build/src/ast.rs, third_party/prost/prost-build/src/code_generator.rs, third_party/prost/prost-derive/src/field/scalar.rs, third_party/prost/prost-derive/src/lib.rs
=> Small fixes

oak_loader/Cargo.toml, oak_runtime/src/channel.rs, oak_runtime/src/graph.rs, oak_runtime/src/introspection_events.rs, oak_runtime/src/lib.rs, oak_runtime/src/proxy.rs
=> Fix non-oak_debug builds

examples/deny.toml, experimental/deny.toml, oak_client/deny.toml, oak_loader/deny.toml, oak_runtime/deny.toml, oak_runtime/src/node/http/server.rs, sdk/deny.toml
=> Ignore RUSTSEC-2021-0020

examples/private_set_intersection/oak_app_manifest.toml, examples/private_set_intersection/private_set_intersection_handler.sign
This change adds a new signature file for the Private Set Intersection example and updates a corresponding Google Storage link.
=> Fix Private Set Intersection signature

oak_loader/Cargo.lock, oak_loader/Cargo.toml, oak_runtime/Cargo.lock, oak_runtime/Cargo.toml, runner/src/main.rs
=> runtime: add gcpkms feature

examples/aggregator/client/android/cpp/client.cc, examples/aggregator/client/cpp/aggregator.cc, examples/aggregator/config.toml, examples/private_set_intersection/private_set_intersection_handler.sign, oak_io/Cargo.toml, oak_io/src/handle.rs, sdk/rust/oak/Cargo.toml, sdk/rust/oak/src/io/mod.rs, sdk/rust/oak/src/io/sender.rs
construction.
This flag is not necessary after #1900.
=> No more no-linear-handles

oak_functions/.dockerignore, oak_functions/Dockerfile, scripts/deploy_oak_functions_loader
For now it is a combined image with both the loader and the actual
application, but in the future those will be unbundled.
Ref #1934
construction.
=> Add Dockerfile and deployment script for Functions

oak_functions/.dockerignore, oak_functions/Dockerfile, oak_functions/loader/testdata/.dockerignore, oak_functions/loader/testdata/Dockerfile, scripts/deploy_oak_functions_loader
=> Split base and example images for Oak Functions

.github/workflows/ci.yaml, .github/workflows/reproducibility.yaml, Dockerfile, oak_functions/loader/src/server.rs, runner/src/internal.rs, runner/src/main.rs, scripts/build_reproducibility_index
=> Add runner command for building oak-functions loader

oak_functions/loader/testdata/Dockerfile, scripts/deploy_oak_functions_loader
=> Perform multiple requests deploying on Cloud Run

oak_functions/loader/src/server.rs, oak_functions/loader/testdata/Dockerfile, scripts/deploy_oak_functions_loader
=> Define /invoke endpoint for Functions loader

oak_functions/loader/Cargo.lock, oak_functions/loader/Cargo.toml, oak_functions/loader/build.rs, oak_functions/loader/src/main.rs, oak_functions/loader/src/tests.rs, oak_functions/proto/lookup_data.proto
Not actually used in the server implementation yet.
Ref #1930
construction.
=> Allow loading lookup data in Oak Functions loader

.github/workflows/ci.yaml
=> Disable cargo udeps step in CI

oak_functions/examples/hello_world/.dockerignore, oak_functions/examples/hello_world/Dockerfile, oak_functions/loader/testdata/.dockerignore, scripts/deploy_oak_functions_loader
At least it will do something interesting :)
Ref #1934
construction.
=> Deploy hello world to Cloud Run

oak_functions/examples/hello_world/module/src/lib.rs, oak_functions/examples/hello_world/module/src/tests.rs, oak_functions/loader/Cargo.lock, oak_functions/loader/Cargo.toml, oak_functions/loader/src/tests.rs, oak_functions/sdk/oak_functions/src/lib.rs
=> Use hello_world as benchmark

oak_functions/loader/src/main.rs
=> Use new logger consistently

oak_functions/loader/src/main.rs
=> Unify logs for lookup data

oak_functions/examples/Cargo.lock, oak_functions/examples/hello_world/config.toml, oak_functions/examples/hello_world/module/Cargo.toml, oak_functions/examples/hello_world/module/src/lib.rs, oak_functions/examples/hello_world/module/src/tests.rs, oak_functions/loader/Cargo.lock, oak_functions/loader/Cargo.toml, oak_functions/loader/src/tests.rs, oak_functions/lookup_data_generator/Cargo.lock, oak_functions/lookup_data_generator/Cargo.toml, oak_functions/lookup_data_generator/src/main.rs, scripts/deploy_oak_functions_loader, scripts/generate_and_upload_lookup_data_random, scripts/generate_and_upload_lookup_data_weather
Replacing the Hello World example content
construction.
=> Implement Weather Lookup functionality

oak_functions/examples/Cargo.lock, oak_functions/examples/hello_world/module/src/tests.rs, oak_functions/loader/Cargo.lock, oak_functions/loader/src/main.rs, oak_functions/loader/src/server.rs, oak_functions/loader/src/tests.rs, oak_functions/sdk/Cargo.lock, oak_functions/sdk/test_utils/Cargo.toml, oak_functions/sdk/test_utils/src/lib.rs
=> Introduce utility to spawn background tasks

examples/abitest/module_0/rust/tests/integration_test.rs
Race conditions in `test_leaks` sometime cause false positives. This happens if a back-end node is a bit slower than expected to close its orphaned channels. It a potential leak is detected, the code will now wait for 5 seconds and then retry the count to make sure it is a genuine leak.
See #2008 
construction.
=> Add logic to retry counts in case of possible leak

examples/Cargo.lock, experimental/Cargo.lock, oak_loader/Cargo.lock, oak_runtime/Cargo.lock, oak_runtime/Cargo.toml, sdk/Cargo.lock
=> Update prometheus to latest published version

oak_functions/examples/Cargo.lock, oak_functions/examples/weather_lookup/README.md, oak_functions/examples/weather_lookup/client/client, oak_functions/examples/weather_lookup/module/Cargo.toml, oak_functions/examples/weather_lookup/module/src/tests.rs, oak_functions/loader/Cargo.lock, oak_functions/loader/Cargo.toml, oak_functions/loader/src/server.rs, oak_functions/loader/src/tests.rs, scripts/deploy_oak_functions_loader
This may be necessary for streaming HTTP requests
construction.
=> Support HTTP2 serving

.github/workflows/ci.yaml, oak_functions/loader/src/tests.rs, runner/src/internal.rs, runner/src/main.rs
=> Update run-cargo-tests to run benchmarks too

oak_functions/examples/Cargo.lock, oak_functions/examples/deny.toml, oak_functions/examples/weather_lookup/config.toml, oak_functions/loader/Cargo.lock, oak_functions/loader/Cargo.toml, oak_functions/loader/deny.toml, oak_functions/loader/src/lookup.rs
=> Enable HTTPS fetching of lookup data

.github/workflows/ci.yaml, docs/development.md, runner/src/internal.rs, runner/src/main.rs
=> Add new runner command for running fuzz targets

oak_functions/loader/Cargo.lock
=> Update Oak Functions deps

scripts/git_check_diff
=> Update git_check_diff to check the presence of any newly generated files

examples/Cargo.lock, examples/aggregator/README.md, examples/aggregator/client/android/cpp/client.cc, examples/aggregator/client/cpp/aggregator.cc, examples/aggregator/config.toml, examples/private_set_intersection/private_set_intersection_handler.sign, oak_loader/Cargo.lock, oak_runtime/Cargo.lock, runner/Cargo.lock
=> Update various Rust deps

oak_functions/loader/fuzz/fuzz_targets/apply_policy.rs, oak_functions/loader/fuzz/fuzz_targets/wasm_invoke.rs
* Loads Wasm module from `/out/bin` when running the OSS-Fuzz project, to fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=34645. This fix requires updating oss-fuzz too: https://github.com/google/oss-fuzz/pull/5830.
* Uses a lazily instantiated static `tokio::Runtime` instance instead of creating an instance for each testcase. This will hopefully improve performance. According to the performance reports (e.g., [apply_policy: 2021-05-24](https://oss-fuzz.com/performance-report/libFuzzer_oak_apply_policy/libfuzzer_asan_oak/2021-05-24)), the current speed is less than 100 testcases per second. It is advised to **optimize the target function so that the execution speed is at least 1,000 testcases per second**. Hopefully, this change will improve performance.
=> Fix fuzz targets

examples/grpc_attestation/client/java/src/Main.java, oak_functions/client/java/src/AttestationClient.java
Fixes https://github.com/project-oak/oak/issues/2136
=> Fix Java logging in gRPC Attestation

experimental/attestation_common/src/crypto.rs, oak_functions/client/java/BUILD, oak_functions/client/java/src/AeadEncryptor.java, oak_functions/client/java/src/AttestationClient.java, oak_functions/client/java/src/KeyNegotiator.java, oak_functions/client/java/src/Util.java
Fixes https://github.com/project-oak/oak/issues/2120
=> Use javax.crypto in Java gRPC Attestation

oak_functions/client/java/src/AttestationClient.java
Set templates in order to remove raw Java types.
=> Set Java template in gRPC Attestation

oak_functions/client/java/src/com/google/oak/functions/client/AttestationClient.java
More formatting and linting to make g3 happy.
=> Format AttestationCleint.java

oak_functions/loader/fuzz/fuzz_targets/wasm_invoke.rs, oak_utils/src/lib.rs
Fixing timeout error: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=34972
=> Optimize fuzz input of wasm_invoke to avoid timeouts

oak_functions/client/rust/Cargo.lock, oak_functions/client/rust/Cargo.toml, oak_functions/client/rust/README.md, oak_functions/examples/Cargo.lock, oak_functions/examples/key_value_lookup/config.toml, oak_functions/examples/weather_lookup/.dockerignore, oak_functions/examples/weather_lookup/Dockerfile, oak_functions/examples/weather_lookup/README.md, oak_functions/examples/weather_lookup/client/java/src/Main.java, oak_functions/examples/weather_lookup/config.toml, oak_functions/examples/weather_lookup/scripts/cloud_run_deploy, oak_functions/gcp/README.md, oak_functions/gcp/endpoint_api_config.yaml.template, oak_functions/load_test/Cargo.lock, oak_functions/loader/Cargo.lock, oak_functions/loader/src/main.rs, oak_functions/sdk/Cargo.lock, runner/src/examples.rs, runner/src/files.rs, runner/src/internal.rs, runner/src/main.rs, scripts/deploy_oak_functions_api, scripts/deploy_oak_functions_endpoints, scripts/deploy_oak_functions_loader, scripts/gcloud_build_image, scripts/gcp_common
=> Update deploy scripts

oak_functions/client/android/com/google/oak/functions/android/client/MainActivity.java, oak_functions/client/java/src/com/google/oak/functions/client/AttestationClient.java, oak_functions/examples/weather_lookup/client/java/src/Main.java
Ref https://github.com/project-oak/oak/issues/2172
=> Add TLS/gRPC connections to Java Oak Functions

oak_functions/loader/fuzz/Cargo.lock, oak_functions/loader/fuzz/Cargo.toml, oak_functions/loader/fuzz/fuzz_targets/wasm_invoke.rs, oak_functions/loader/src/lookup.rs
Ref https://github.com/project-oak/oak/pull/2114#issuecomment-846882117
=> Use non-empty lookup data for wasm_invoke fuzz target

oak_functions/examples/weather_lookup/README.md, oak_functions/examples/weather_lookup/client/java/src/Main.java, oak_functions/examples/weather_lookup/config.toml, oak_functions/examples/weather_lookup/example.toml, oak_functions/examples/weather_lookup/module/src/lib.rs, oak_functions/examples/weather_lookup/module/src/tests.rs, oak_functions/loader/src/main.rs, oak_functions/loader/src/server.rs, oak_functions/loader/src/tests.rs, oak_functions/lookup_data_generator/README.md, oak_functions/lookup_data_generator/src/main.rs, scripts/generate_and_upload_lookup_data_weather
=> Weather lookup example with sparse data

oak_functions/examples/weather_lookup/module/src/lib.rs, oak_functions/sdk/oak_functions/src/lib.rs
=> Ignore result from Oak Functions SDK log macro

runner/src/files.rs
It should be close enough to what we want.
=> Use clang formatting for .java files

oak_functions/client/rust/src/main.rs, oak_functions/examples/weather_lookup/client/java/src/Main.java, oak_functions/examples/weather_lookup/example.toml, oak_functions/examples/weather_lookup/scripts/cloud_run_deploy, scripts/deploy_oak_functions_endpoints, scripts/deploy_oak_functions_loader
* Changes Oak Functions Cloud Run service to require authentication 
* Copies the correct `.wasm` file to the example docker image
* Fixes the example
=> Make Oak Functions cloud run service private

oak_functions/examples/Cargo.lock, oak_functions/examples/fuzzable/module/src/tests.rs, oak_functions/examples/key_value_lookup/module/src/tests.rs, oak_functions/examples/weather_lookup/module/src/tests.rs, oak_functions/loader/Cargo.lock, oak_functions/loader/Cargo.toml, oak_functions/loader/fuzz/Cargo.lock, oak_functions/loader/src/lookup.rs, oak_functions/loader/src/main.rs, oak_functions/loader/src/tests.rs, runner/Cargo.lock
=> Add support for authenticated downloads of lookup data

oak_functions/examples/Cargo.lock, oak_functions/examples/fuzzable/module/src/tests.rs, oak_functions/examples/key_value_lookup/module/src/tests.rs, oak_functions/examples/weather_lookup/module/Cargo.toml, oak_functions/examples/weather_lookup/module/src/lib.rs, oak_functions/examples/weather_lookup/module/src/tests.rs, oak_functions/loader/src/tests.rs, oak_functions/lookup_data_generator/src/data.rs, oak_functions/lookup_data_generator/src/lib.rs, oak_functions/lookup_data_generator/src/main.rs, oak_functions/sdk/test_utils/src/lib.rs
Fixes #2264
Fixes #2266
construction.
=> Add benchmark test to weather lookup example

oak_functions/loader/src/server.rs, oak_functions/loader/src/tf.rs
Ref https://github.com/project-oak/oak/pull/2278#discussion_r703384995
=> Make Extension::invoke API better resemble existing APIs

oak_functions/client/java/src/com/google/oak/functions/client/AttestationClient.java, oak_functions/client/rust/src/attestation.rs, oak_functions/client/rust/src/lib.rs, oak_functions/loader/src/attestation.rs, oak_functions/loader/src/grpc.rs, oak_functions/loader/src/lib.rs, oak_functions/proto/server.proto
This commit changes Oak Functions gRPC service definition.
Fixes https://github.com/project-oak/oak/issues/2307
=> Rename Oak Functions proto

docs/Docker.md, docs/development.md
=> Add descriptions for Linux

docs/oak_functions_abi.md
=> Update Oak Functions ABI docu

oak_functions/README.md
=> Add introduction to Oak Functions readme

runner/src/main.rs
=> Remove --all flage

.devcontainer.json, examples/chat/module/rust/src/lib.rs, runner/src/internal.rs, runner/src/main.rs, scripts/common
=> Re-enable cargo clippy warnings 1598

docs/oak_functions_abi.md
=> Remove duplicate param list

oak_functions/examples/weather_lookup/module/src/tests.rs
=> Change to seeded rng

oak_functions/loader/fuzz/fuzz_targets/wasm_invoke.rs
=> Fix typo in error message

oak_functions/Cargo.lock, oak_functions/Cargo.toml, oak_functions/loader/fuzz/Cargo.lock, oak_functions/loader/fuzz/Cargo.toml
=> Make fuzz a workspace

.devcontainer.json, .runner_bash_completion, Dockerfile, runner/src/internal.rs, runner/src/main.rs, scripts/common, scripts/generate_bash_completion_for_runner, scripts/runner
=> Bash completion for runner 2392

.github/workflows/ci.yaml, .runner_bash_completion, runner/src/internal.rs, runner/src/main.rs
=> Remove --benches from `./scripts/runner run-cargo-tests`

scripts/git_clean
Otherwise the last stash will be applied.
=> Only apply stash if files were stashed previously

oak_functions/loader/src/server.rs
This will allow us to add a function `f(mut self: Box<Self>)` to the `UwabiExtension` trait.
=> Replace BoxedUwabiExtension using trait bounds

oak_functions/client/java/src/com/google/oak/functions/client/AttestationClient.java, oak_functions/examples/weather_lookup/README.md
This change adds an exact weather file format description to the `weather_lookup` README file.
=> Add weather file format description

experimental/attestation_common/src/certificate.rs, experimental/attestation_common/src/keying_material.rs, experimental/attestation_common/src/report.rs, experimental/proxy_attestation/src/lib.rs, experimental/proxy_attestation/src/main.rs, experimental/tf_proxy/client/src/data.rs, experimental/tf_proxy/client/src/main.rs, oak_functions/client/rust/src/rekor.rs, oak_functions/examples/mobilenet/module/src/lib.rs, oak_functions/loader/src/metrics.rs, oak_functions/loader/src/server.rs, oak_functions/location_utils/src/lib.rs, remote_attestation/rust/src/crypto.rs, remote_attestation/rust/src/handshaker.rs, remote_attestation/rust/src/message.rs, runner/src/internal.rs, scripts/check_docs
=> Fix docs and re-enable docs check

.devcontainer.json, Dockerfile, scripts/common
We will figure out separately what needs to be changed in order to
re-upgrade it.
Fixes #2553
=> Downgrade Bazel

oak_functions/loader/src/server.rs
Remove option, because we rely on the endpoint being there always.
Generally we have to re-think how the endpoints are given to the extensions (and to their connected Wasm module, simultanously). 
Something to be determined in #2551 .
=> Make endpoint not optional

docs/development.md, oak_functions/client/rust/src/main.rs
A first pass at making the instructions work again after the Oak Classic code was removed.
=> Fix development instructions

Cargo.lock, Cargo.toml, oak_functions/location_utils/src/lib.rs, oak_functions/lookup_data_checker/Cargo.toml, oak_functions/lookup_data_checker/README.md, oak_functions/lookup_data_checker/src/main.rs
This PR adds an utility that checks the correctness of the weather lookup data file.
=> Add a lookup data checker

oak_functions/examples/echo/config.toml, oak_functions/examples/echo/example.toml
=> Add toml files for echo example

oak_functions/loader/src/lib.rs
This wasn't clear to me when first reading the code. Without a comment it likely wouldn't be for other newcomers and/or external reviewers. [Ref the related discussions in #2569 and #2551].
=> Add comment explaining config behevaior and rationale

.github/workflows/scorecards.yml
=> Scorecards

xtask/src/diffs.rs
This change makes the default functionality of `xtask` with `--scope=diff_to_main` more robust. If the `git diff ...` command fails, `xtask` runs the command for the entire code base, and basically falls back to `--scope=all`.
=> Run xtask for the entire repo if finding the diff fails

grpc_unary_attestation/src/client.rs, grpc_unary_attestation/src/lib.rs, grpc_unary_attestation/src/server.rs, oak_functions/proto/unary_server.proto
Addressees https://github.com/project-oak/oak/pull/2607#discussion_r826410844
=> Use byte array as session_id

kokoro/presubmit.sh
The idea is to have a simple script for Kokoro jobs here, so that we don't have to change the scripts in Google3 whenever the scripts or the commands changes here.
=> Add a script for Kokoro

oak_functions/client/android/com/google/oak/functions/android/client/MainActivity.java, oak_functions/client/java/src/com/google/oak/functions/client/AttestationClient.java, oak_functions/examples/weather_lookup/client/java/src/Main.java, oak_functions/examples/weather_lookup/config.toml, oak_functions/examples/weather_lookup/example.toml, oak_functions/proto/BUILD
First time writing Java! Was fun, shoutout to @ipetr0v for teaching me how to log objects the Java Way [TM] in debugging
```
byte[] bytes = streamingResponse.getBody().toByteArray();
byte[] HEX_ARRAY = "0123456789ABCDEF".getBytes(StandardCharsets.US_ASCII);
byte[] hexChars = new byte[bytes.length * 2];
for (int j = 0; j < bytes.length; j++) {
int v = bytes[j] & 0xFF;
hexChars[j * 2] = HEX_ARRAY[v >>> 4];
hexChars[j * 2 + 1] = HEX_ARRAY[v & 0x0F];
}
String s = new String(hexChars, StandardCharsets.UTF_8);
logger.log(s);
```
=> Update Java client to use unary requests

Cargo.lock, Cargo.toml, oak_functions/loader/src/metrics.rs, oak_functions/sdk/oak_functions/Cargo.toml, oak_functions/sdk/oak_functions/tests/integration_test.rs, oak_functions/sdk/oak_functions/tests/metrics_module/Cargo.toml, oak_functions/sdk/oak_functions/tests/metrics_module/src/lib.rs
Fixes https://github.com/project-oak/oak/issues/2415 .
=> Add integration test for `report_metric`

oak_functions/abi/src/lib.rs, oak_functions/loader/src/tests.rs
=> Fix flakiness in test long response time

oak_functions/loader/src/lookup.rs, oak_functions/loader/src/metrics.rs, oak_functions/loader/src/server.rs, oak_functions/loader/src/testing.rs, oak_functions/loader/src/tf.rs
=> Give request as argument to OakAbiNativeExtension

docs/oak_functions_abi.md, oak_functions/abi/src/lib.rs, oak_functions/loader/src/lookup.rs, oak_functions/loader/src/metrics.rs, oak_functions/loader/src/server.rs, oak_functions/loader/src/testing.rs, oak_functions/loader/src/tf.rs, oak_functions/sdk/oak_functions/tests/integration_test.rs, oak_functions/sdk/oak_functions/tests/testing_module/src/lib.rs
=> Return Option<Vec<u8>> in invoke in OakApiNativeExtension

docs/oak_functions_abi.md, oak_functions/abi/src/lib.rs, oak_functions/sdk/oak_functions/src/lib.rs, oak_functions/sdk/oak_functions/tests/testing_module/src/lib.rs
=> Call `invoke` instead of `tf_infer`

Cargo.lock, Cargo.toml, experimental/offline_attestation/README.md, experimental/offline_attestation/client/Cargo.toml, experimental/offline_attestation/client/src/main.rs, experimental/offline_attestation/server/Cargo.toml, experimental/offline_attestation/server/src/main.rs, experimental/offline_attestation/shared/Cargo.toml, experimental/offline_attestation/shared/src/lib.rs
This is a simple example that uses an offline attestation approach for encryption and decryption.
=> Add experimental offline attestation echo example

Cargo.lock, experimental/trusted_shuffler/scripts/run, experimental/trusted_shuffler/server/Cargo.toml, experimental/trusted_shuffler/server/src/http.rs, experimental/trusted_shuffler/server/src/main.rs, experimental/trusted_shuffler/trusted_shuffler/src/lib.rs, experimental/trusted_shuffler/trusted_shuffler/src/tests.rs
This PR adds Trusted Shuffler to the corresponding server binary.
Ref #2614
=> Add Trusted Shuffler server

experimental/uefi/loader/src/main.rs
By replacing our while loop with the appropiate method call
=> Reading the comms serial port: Improve readability a bit

remote_attestation/rust/src/report.rs
=> Update lingering TODO

experimental/uefi/runtime/src/lib.rs
Increases its size. Changes it from denoting just the length of body to the length of the whole frame (including the length prefix itself and any other future header values).
=> Change frame length prefix to match planned framing

oak_functions/wasm/src/lib.rs, oak_functions/wasm/src/tests.rs
=> Remove superflous `read_extension_args`

oak_functions/examples/weather_lookup/README.md
The command for incoking the client was incorrect.
=> Fix Weather Lookup example readme

oak_functions/examples/echo/config.toml, oak_functions/examples/key_value_lookup/config.toml, oak_functions/examples/metrics/config.toml, oak_functions/examples/mobilenet/config.toml, oak_functions/examples/weather_lookup/config.toml, oak_functions/loader/src/lib.rs, oak_functions/oak_functions_loader_base/src/main.rs, oak_functions/oak_functions_loader_unsafe/src/main.rs
=> Remove `worker_threads` from `Config`

experimental/trusted_shuffler/server/src/http.rs, experimental/trusted_shuffler/server/src/main.rs, experimental/trusted_shuffler/trusted_shuffler/src/lib.rs, experimental/trusted_shuffler/trusted_shuffler/src/tests.rs
=> Add timeout as argument to Trusted Shuffler

experimental/trusted_shuffler/trusted_shuffler/src/lib.rs, experimental/trusted_shuffler/trusted_shuffler/src/tests.rs
=> Add timeout for responses

docs/remote-attestation.md
=> Fix remote attestation doc

Cargo.lock, Cargo.toml, experimental/vsock/echo/Cargo.toml, experimental/vsock/echo/README.md, experimental/vsock/echo/src/main.rs
This PR adds a simple runtime for running inside a sandbox which uses VSock for communications.
=> Add simple VSock echo runtime

Cargo.lock, experimental/virtio/Cargo.toml, experimental/virtio/src/vsock/socket/tests.rs
=> Fix "Bump wasm-bindgen-test from 0.3.30 to 0.3.31"

experimental/oak_baremetal_client/README.MD
Made a typo here when creating this file in #2956.
=> Fix incorrect command in docs

experimental/oak_baremetal_channel/src/frame.rs
=> Fix frame-length wrapping

experimental/oak_baremetal_loader/src/main.rs, experimental/oak_baremetal_loader/src/server.rs
Makes it so that the requests and responses sent over this channel consistently represent flatbuffer encoded messages. Previously this was the case only for requests but not responses. 
Improves comments/naming for clarity. 
This will make the upcoming code change (sending lookup data updates over the same channel) easier to review.
=> Refactor bmrng channel in the untrusted loader to increase clarity

experimental/oak_baremetal_loader/src/main.rs
Thanks to the previous refactors (#3068, #3069, #3070, #3074) this is now pretty straightforward.
=> Untrusted Loader: Periodically refresh lookup data

Cargo.lock, experimental/oak_baremetal_launcher/Cargo.toml, experimental/oak_baremetal_launcher/src/server.rs
Will allow us to test the web client with the launcher. 
Tracking issue: #3081
=> Launcher: Support grpc-web with feature flags

experimental/oak_baremetal_launcher/src/server.rs
Fleeting mistake introduced in #3123
=> Fix incorrectly named feature check

.devcontainer.json, Dockerfile, experimental/web_client/README.md, oak_functions/examples/echo/example.toml, scripts/common, xtask/src/examples.rs
=> Run web-client integration test in CI

.github/workflows/provenance.yaml
=> Give provenance pull-request permission

.xtask_bash_completion, xtask/src/internal.rs, xtask/src/launcher.rs, xtask/src/main.rs
This reverts commit 1e6471b9ed5cd4b61df8b67bf6edb5ea377dba9d.
The previously removed code is needed for #3152
=> Revert "Remove unused xtask options (#3099)"

.github/actions/reproducibility_index/action.yml, .github/workflows/provenance.yaml, buildconfigs/oak_baremetal_app_crosvm.toml
Follow up on #3152 now that #3099 is reverted (in #3164).
=> Uncomment provenance generation for crosvm

testing/sev_snp_hello_world_kernel/src/main.rs
Experimentally this seems to be a better way to ensure the machine is actually reset properly.
=> Use int3 instead of i8042 to shut down the test kernel

experimental/sev_guest/src/ghcb.rs
See section 4.1.2 for https://developer.amd.com/wp-content/resources/56421.pdf for more details.
=> Add implementation of the GHCB protocol that supports IOIO_PROT

experimental/sev_guest/src/ghcb.rs, experimental/sev_guest/src/msr.rs
See section 15.34.10 of [AMD64 Architecture Programmer’s Manual, Volume 2: System Programming](https://www.amd.com/system/files/TechDocs/24593.pdf)
=> Add support for reading the SEV status MSR

testing/sev_snp_hello_world_kernel/src/ghcb.rs
This PR adds the additional GHCB-related steps to support running the Hello World test kernel on AMD SEV-SNP.
=> Add AMD SEV-SNP support for GHCB protocol

trusted_shuffler/server/src/http.rs, trusted_shuffler/trusted_shuffler/src/lib.rs, trusted_shuffler/trusted_shuffler/src/tests.rs
=> Add selected headers to TrustedShufflerResponse

experimental/sev_guest/src/msr.rs, stage0/Cargo.lock, stage0/Cargo.toml, stage0/src/main.rs
This looks to be the bare minimum we need to do to jump to the actual kernel at `0x200000`.
=> SEV-SNP enlightenment: call `PVALIDATE` on pages we touch.

xtask/src/examples.rs
This is not needed any more, and if needed in the future should probably be redesigned anyways.
=> Remove logic for running backends in examples

scripts/xtask
Currently it is quite noisy when running things in the terminal
=> Only print sccache stats in CI

.github/workflows/provenance.yaml
Modifies the provenance generation workflow to generate signed provenances for every merged PR.
=> Run signed provenance generation for every merged PR

testing/sev_snp_hello_world_kernel/src/main.rs
We read the `SEV_STATUS` MSR (`0xC001_0131`) to determine whether we should use the GHCB-based I/O protocol and whether SEV is enabled at all.
If you try to read it on a machine that supports SEV, but SEV is not necessarily enabled, the read works just fine. However, if you try to read it on a machine that _doesn't_ support SEV at all, then it triggers a `#GP` exception as the MSR is unsupported.
Thus: let's implement a really basic `#GP` handler that, when triggered, figures out whether it fired because the next instruction was `rdmsr` and if yes, then just skip the instruction altogether by moving the instruction pointer forward.
=> Add a crude #GP handler to sev_snp_hello_world.

experimental/oak_baremetal_simple_io/src/lib.rs
The purpose of this PR is the same as #3290: be explicit whether we're dealing with virtual or physical addresses.
Thankfully there's not much going on in this crate, so the code is trivial.
=> Distinguish between `VirtAddr` and `PhysAddr` in the simple_io crate.

trusted_shuffler/server/src/http.rs
=> Refactor stripping and building hyper requests

.github/actions/reproducibility_index/action.yml, .github/workflows/build_rust_docs.yaml, .github/workflows/ci.yaml, .github/workflows/provenance.yaml
=> Update checkout and cache action to latest version

testing/sev_snp_hello_world_kernel/src/main.rs
This trashes the RAX register, as we use it for our own purposes, but (a) if the instruction that triggered the #GP was indeed `rdmsr`, we want to overwrite RAX anyway and (b) if the instruction wasn't `rdmsr`, we'll crash as that shouldn't happen, so overwriting RAX doesn't matter.
=> Replace the #GP handler in hello world test with one that emulates `rdmsr` properly.

Cargo.lock, cc/tflite_micro/BUILD, cc/tflite_micro/tflite_micro.cc, cc/tflite_micro/tflite_micro.h, oak_tensorflow_freestanding_bin/Cargo.lock, oak_tensorflow_service/Cargo.toml, oak_tensorflow_service/build.rs, oak_tensorflow_service/src/lib.rs, oak_tensorflow_service/src/tflite.rs
This PR links together the TFLite C++ code and Rust TensorFlow Runtime.
Ref https://github.com/project-oak/oak/issues/3297
=> Link TFLite C++ code to Rust Runtime

Cargo.lock, oak_functions_linux_vsock_bin/src/channel.rs
Unfortunately dependabot doesn't know how to refactor code :(
=> Update `ringbuf` and change code to match API changes

oak_restricted_kernel/src/mm/bitmap_frame_allocator.rs, oak_restricted_kernel/src/mm/frame_allocator.rs
I left the tests as-is in the previous PR to prove to myself that the behaviour of the code is the same; now we can fix the tests properly.
=> Change tests to use exclusive ranges as #3352 has been merged.

scripts/build_gh_pages
=> Fix cargo doc generation

.github/workflows/provenance.yaml
=> Upload DSSE document to Ent and print its hash

oak_restricted_kernel/src/mm/page_tables.rs
I'm not entirely sure _why_, but Intel CPUs seem fine with the `GLOBAL` flag set but the AMD CPU we're trying things on refused to load page tables with the `GLOBAL` bit set for the parent entries.
Note that the _leaves_ of the page table still have `GLOBAL` set, and the AMD CPU seems fine with that.
Semantically, we do want `GLOBAL`: we're mapping memory in kernel space, which means it should be the same no matter the process. (Even though we don't have processes right now).
Stripping the bit off got the code to boot on the AMD CPU; now I'm off to read the specs as to _why_ exactly this was rejected...
=> SEV: don't set `GLOBAL` in parent page table entries

.github/actions/reproducibility_index/action.yml, .github/workflows/provenance.yaml
Follow-up fix for #3382.
Fix scripts following upgrading the version to v6. See https://github.com/actions/github-script#breaking-changes-in-v5.
=> Fix github-script

.github/workflows/provenance.yaml
=> Fix passing GITHUB_TOKEN

.github/workflows/provenance.yaml
Follow up on #3390.
I hope this time it works.
=> Update  generator_generic_slsa3 version

oak_protobuf_idl_build/src/lib.rs, oak_protobuf_idl_tests/build.rs, oak_protobuf_idl_tests/oak.protobuf_idl.tests.rs.txt
Make generated server struct cloneable (as long as its fields are).
Ref #3385
=> Allow compiling multiple proto files at once

.github/workflows/build_rust_docs.yaml, .github/workflows/ci.yaml, .github/workflows/cifuzz.yml, .github/workflows/provenance.yaml
Attempt at fixing #2056. Not sure if it works.
=> Fix cancelling of workflows on merge

oak_restricted_kernel/src/ghcb.rs
When we build our proper page tables, the kernel region will be mapped using 4KiB pages, not 2MiB pages. Therefore, this `reshare_ghcb` never succeeded and failed... but we never saw the error message because to see the error message, we need a functioning GHCB page.
=> SEV-ES: reshare GHCB using 4K page size, not 2M

experimental/sev_guest/src/guest.rs
The PR builds on #3424 to provide the specific messages needed to request and process remote attestation reports.
=> Add data structures to request attestation reports

Cargo.lock, experimental/sev_guest/Cargo.toml, experimental/sev_guest/src/crypto.rs, experimental/sev_guest/src/guest.rs, experimental/sev_guest/src/lib.rs, oak_functions_freestanding_bin/Cargo.lock, oak_tensorflow_freestanding_bin/Cargo.lock, oak_tensorflow_freestanding_bin/deny.toml, stage0/Cargo.lock, stage0/deny.toml, testing/oak_echo_bin/Cargo.lock, testing/oak_echo_bin/deny.toml, testing/oak_echo_raw_bin/Cargo.lock, testing/oak_echo_raw_bin/deny.toml, testing/sev_snp_hello_world_kernel/Cargo.lock, testing/sev_snp_hello_world_kernel/Cargo.toml, testing/sev_snp_hello_world_kernel/deny.toml
Communications with the AMD platform secure processor via the guest message protocol must be encrypted to ensure that the messages aren't leaked or tampered with by the hypervisor. This PR provides an implementation of the required crypto based on the RustCrypto crates.
=> Add support for encrypting and decrypting messages

oak_remote_attestation_noninteractive/proto/oak_session_noninteractive_v1.proto
=> Add proto definition for offline attestation

experimental/sev_guest/src/cpuid.rs, oak_restricted_kernel/src/interrupts.rs
If we are running with SEV-SNP enabled we can just lookup CPUID values from the CPUID page rather than use the more restricted CPUID MSR protocol.
=> Use CPUID page in #VC handler if it is available

Cargo.lock, oak_functions_freestanding/Cargo.toml, oak_functions_freestanding/tests/integration_test.rs, oak_functions_freestanding_bin/Cargo.lock, oak_functions_freestanding_bin/Cargo.toml, oak_functions_linux_fd_bin/Cargo.toml, oak_functions_linux_vsock_bin/Cargo.toml
=> Remove unused attestation sessions code

docs/release.md
=> Update build & release documentation

Cargo.lock, oak_core/src/sync.rs, oak_functions_freestanding_bin/Cargo.lock, oak_restricted_kernel/Cargo.toml, oak_restricted_kernel/src/attestation.rs, oak_restricted_kernel/src/descriptors.rs, oak_restricted_kernel/src/ghcb.rs, oak_restricted_kernel/src/interface.rs, oak_restricted_kernel/src/interrupts.rs, oak_restricted_kernel/src/lib.rs, oak_restricted_kernel/src/logging.rs, oak_tensorflow_freestanding_bin/Cargo.lock, testing/oak_echo_bin/Cargo.lock, testing/oak_echo_raw_bin/Cargo.lock
=> Stop using `lazy_static` in the restricted kernel

deny.toml, fuzz/deny.toml
=> Clean up cargo deny warnings

.github/workflows/provenance.yaml, buildconfigs/oak_echo_bin.toml, buildconfigs/oak_echo_raw_bin.toml, buildconfigs/oak_functions_freestanding_bin.toml, buildconfigs/oak_tensorflow_freestanding_bin.toml
For all the enclave binaries that we care about.
Also add them to the appropriate CI step.
Fix #3507
=> Create or fix buildconfig files

Dockerfile, oak_functions_freestanding_bin/.cargo/config.toml, oak_tensorflow_freestanding_bin/.cargo/config.toml, scripts/common, stage0/.cargo/config.toml, testing/oak_echo_bin/.cargo/config.toml, testing/oak_echo_raw_bin/.cargo/config.toml, testing/sev_snp_hello_world_kernel/.cargo/config.toml
Use the appropriate preinstalled rust target instead.
=> Avoid rebuilding stdlib

stage0/src/acpi.rs
This makes us a bit more resilient toward (a) VMMs having weird names for the ACPI table files, and (b) them containing proprietary commands that we don't (yet?) know how to handle.
=> Ignore unknown ACPI linker commands

snp_measurement/src/main.rs
This change updates the order of measurement to match the expected behaviour on production instances where the ELF enclave binary is actually loaded into memory before the Stage 0 firmware ROM image.
=> Measure the ELF binary before Stage 0

.devcontainer.json, .xtask_bash_completion, oak_functions_launcher/README.md, oak_functions_launcher/src/main.rs, xtask/src/internal.rs, xtask/src/launcher.rs, xtask/src/main.rs
=> Fix Oak Functions Loader README

oak_restricted_kernel/src/payload.rs
Another step closer to Ring 3: this moves the actual userspace stack into the lower half of the memory, away from the kernel space.
=> Set up a userspace stack before jumping to the payload.

oak_functions_launcher/src/main.rs
=> Fully load lookup data on start up

oak_simple_io/src/lib.rs
Sometimes when writing large enough buffers fast enough the host side won't be able to keep up with our write rate.
This does deviate from what's specified in the design doc for the device, but matches its implementation.
=> Don't blindly assume the host processed all of our data.

Cargo.lock, Cargo.toml, quirk_echo_service/Cargo.toml, quirk_echo_service/README.md, quirk_echo_service/build.rs, quirk_echo_service/proto/quirk_echo.proto, quirk_echo_service/src/lib.rs, quirk_echo_service/tests/integration_test.rs
Echo service will allow us to experiment with the end to end developer flow on Oak platform.
=> Creating an Echo rpc service for the Quirk experiments

Cargo.lock
=> Fix Cargo.lock file

.envrc, .github/workflows/nix.yml, .gitignore, flake.lock, flake.nix
Use Nix for local development.
This is an experimental alternative to the way we install tools directly in the Docker image, so we can try it out separately.
Ref #3707
=> Add experimental Nix dev environment

.devcontainer.json, Dockerfile, flake.nix, scripts/common
=> Remove Android NDK from Docker image and Nix config

oak_functions_launcher/src/lookup.rs
=> Chunk Lookup Data

oak_functions/lookup/src/lib.rs, oak_functions_service/src/lib.rs
=> Implement Update Actions To Start And Finish

oak_functions/lookup/src/lib.rs, oak_functions_service/src/lib.rs
=> Abort the update of lookup data

oak_functions_launcher/src/lib.rs, oak_functions_launcher/src/lookup.rs, oak_functions_launcher/tests/integration_test.rs, oak_functions_test_utils/src/lib.rs
=> Send two chunks of lookup data

oak_tensorflow_service/build.rs
Show what went wrong with Bazel.
=> Diagnostics

docs/development.md, flake.nix
=> Add instructions on how to install Nix

oak_restricted_kernel/src/payload.rs
This causes a GPF - even if corrected to -16.
=> Don't align the stack

oak_functions/lookup/src/lib.rs, oak_functions_launcher/src/lookup.rs, oak_functions_service/proto/oak_functions.proto, oak_functions_service/src/lib.rs, oak_functions_service/tests/integration_test.rs
=> Simplify states when updating lookup data

oak_functions_launcher/src/lookup.rs
=> Add aborting from launcher

.github/workflows/build_toolchain.yaml, .gitignore, Cargo.lock, oak_functions_enclave_app/Cargo.lock, toolchain/build.sh
Note that I'm heavily into the "I have no idea what I'm doing" territory here; the workflow has been cobbled together from our existing workflows.
The goal is to build `workflow.tar.bz2` and upload it to Ent. Ideally, I'd want to run it as a post-merge if something touches the `workflow/` directory, but for now let's keep it manual.
I'm not even sure you can test workflows before actually submitting them, which is less than ideal.
=> Create a workflow to build the toolchain

oak_functions/wasm/src/lib.rs
=> Use func_wrap in wasmi::Linker

oak_functions/lookup/src/lib.rs, oak_functions_launcher/src/lookup.rs, oak_functions_service/proto/oak_functions.proto, oak_functions_service/src/lib.rs, oak_functions_service/tests/integration_test.rs
=> Remove Update Actions

stage0/src/fw_cfg.rs, stage0/src/main.rs
When we initiate DMA with the host, the host will need to read the `FwCfgDmaAccess` structure to know where to write data, and later we need to read the `FwCfgDmaAccess` structure to find out whether the DMA transfer was successful or not.
We already mark the actual buffer we use for data transfer as shared, but the `FwCfgDmaAccess` structure itself is in encrypted memory. Let's ensure that said data structure is also properly shared with the host.
=> Ensure `FwCfgDmaAccess` lands in shared memory as well

oak_channel/src/lib.rs
This just moves the conditionals to the front and avoids several layers of nesting, which I think is more readable.
(I'm planning to refactor the code a bit more in the future, hence why I am looking at this bit.)
=> Reorganize code in frame decoding method a bit

kokoro/presubmit.sh
=> Remove KVM and Docker-related things that Kokoro no longer needs.

oak_functions/wasm/src/lib.rs
=> Add logging to Wasm interpreter

oak_channel/src/frame.rs
This is the last of my small-scale optimizations -- instead of copying data into a vector use a mutable reference when writing frames to a channel.
=> Elide one copy in the frame write path.

.config/nextest.toml, kokoro/presubmit.sh
For now only those in the root workspace
Rename junit output to be parseable by Kokoro
=> Run all tests in Kokoro

stage0/README.md
Significant overhaul of the README, going into more detail about why stage0 exists, how to use it, and references to other projects of interest.
This also includes the table that @conradgrobler proposed in #3878.
=> Major rewrite of the stage0 README

Cargo.lock, deny.toml, oak_functions_launcher/Cargo.toml, oak_functions_launcher/tests/integration_test.rs, oak_remote_attestation_noninteractive/tests/integration_test.rs, xtask/src/launcher.rs
echo and weather_lookup
Ref #2591
=> turn more examples into tests

.xtask_bash_completion
Accidentally left this out of ebafd31c38199e84ebd90b296e660131909055d7
=> Fix xtask completion

.github/workflows/reusable_provenance.yaml
Follow up on #3910, which prints empty digests!
=> Fix empty digest in provenance comment

.devcontainer.json
Follow up to #3922. Disables an annoying setting that inserts git information within the code
=> Devcontainer: Minor config change to an extension

oak_docker_linux_init/docker_to_rootfs.sh
There is no change in functionality.
=> Add more descriptive help to docker_to_rootfs.sh

Cargo.lock, enclave_apps/Cargo.lock, oak_channel/Cargo.toml, oak_channel/src/frame.rs, oak_channel/src/lib.rs, oak_channel/src/message.rs, oak_restricted_kernel_bin/Cargo.lock
=> Using put on a single bytes::BytesMut instance to read frames.

oak_grpc_utils/src/lib.rs
=> Use more conservative rerun logic for protos

java/src/main/java/com/google/oak/client/android/MainActivity.java, java/src/main/java/com/google/oak/client/weather_lookup_client/Main.java, java/src/main/java/com/google/oak/crypto/ClientEncryptor.java, java/src/main/java/com/google/oak/util/Result.java, java/src/test/java/com/google/oak/transport/GrpcStreamingTransportTest.java, java/src/test/java/com/google/oak/util/ResultTest.java
=> Add an unwrap method to type Result

Cargo.lock, oak_core/Cargo.toml, oak_core/src/lib.rs, oak_core/src/samplestore.rs, oak_core/src/timer.rs, oak_restricted_kernel_bin/Cargo.lock, stage0/Cargo.lock
Although we can't measure actual seconds, counting clock cycles via `RDTSC` should be good enough to get an idea where time is spent.
=> Create a basic histogram and timer structs for collecting statistics

java/src/main/java/com/google/oak/client/OakClient.java, java/src/main/java/com/google/oak/client/weather_lookup_client/BUILD, java/src/main/java/com/google/oak/client/weather_lookup_client/Main.java, java/src/main/java/com/google/oak/crypto/BUILD, java/src/main/java/com/google/oak/crypto/ClientEncryptor.java, java/src/main/java/com/google/oak/crypto/ServerEncryptor.java, java/src/main/java/com/google/oak/crypto/hpke/BUILD, java/src/main/java/com/google/oak/crypto/hpke/Context.java, java/src/main/java/com/google/oak/crypto/hpke/Hpke.java, java/src/main/java/com/google/oak/transport/BUILD, java/src/main/java/com/google/oak/transport/GrpcStreamingTransport.java, java/src/main/java/com/google/oak/util/Result.java
Refactor Java code to comply with internal formatting style
=> Refactor Java Oak Client code style

.github/workflows/reusable_provenance.yaml
=> Update builder_docker-based_slsa3 tag

stage0_bin/supply-chain/audits.toml
https://sourcegraph.com/crates/unicode-ident@v1.0.4
https://sourcegraph.com/crates/cfg-if@v1.0.0
Fixes #3970
Fixes #3951
=> Vet `unicode-ident` and `cfg-if`

stage0_bin/supply-chain/audits.toml, stage0_bin/supply-chain/imports.lock
Source code is at https://sourcegraph.com/crates/byteorder@v1.4.3/
Fixes #3950
=> Vet byteorder 1.4.3

Cargo.lock, Cargo.toml, oak_containers_launcher/Cargo.toml, oak_containers_launcher/build.rs, oak_containers_launcher/src/main.rs, oak_containers_launcher/src/server.rs
=> Add skeleton Oak Containers Launcher for testing

Cargo.lock, oak_containers_stage1/Cargo.toml, oak_containers_stage1/src/client.rs, oak_containers_stage1/src/main.rs
I've unashamedly stolen most of the code from #4022 as the functionality is pretty much identical at this stage.
Next up: adding QEMU to the launcher to see if we can actually boot this thing...
=> Change stage1 to use virtio-vsock

Cargo.lock, oak_containers_launcher/Cargo.toml, oak_containers_launcher/src/main.rs, oak_containers_launcher/src/server.rs
=> Serve actual files in the launcher

oak_containers_stage1/src/main.rs
It's going to be annoying to pass command line flags to stage1 in the VM, so these sound like reasonable defaults to have.
=> Default to CID 2 and port 8080 in stage1.

oak_containers_stage1/src/image.rs, oak_containers_stage1/src/main.rs
This is a little less than ideal as it leaves the old rootfs around and just mounts a ramdisk over it, but you can't use `pivot_root` to replace the rootfs and thus clearly something more clever is needed here. What exactly is a task for the future; for now, creating an empty ramfs and unpacking the system image onto it works.
=> Unpack the system image and run its init in stage1

oak_containers_container_example/Dockerfile, oak_containers_container_example/build_container_bundle, oak_containers_container_example/config.json
Illustrates how a container bundle should look like, useful for manual testing during development. See the discussion on the container format on http://b/287236707
=> Script to build example container bundle

oak_containers_stage1/Makefile
Yes, a proper oldschool `Makefile`. It works.
=> Add a script to build the initrd containing the stage1 binary

.bazelrc, WORKSPACE
This PR:
- Updates Protobuf to v23.3
- Updates Abseil to LTS 20230125.3
=> Update Protobuf and Abseil

cc/client/BUILD, cc/client/client.cc, cc/client/client.h, cc/transport/BUILD, cc/transport/grpc_streaming_transport.cc, cc/transport/grpc_streaming_transport.h, cc/transport/transport.cc, cc/transport/transport.h, oak_remote_attestation/proto/v1/BUILD
This PR:
- Adds an empty implementation of the C++ Oak Client
- Adds C++ gRPC to the WORKSPACE
=> Add C++ client template

oak_containers_system_image/Dockerfile, oak_containers_system_image/build.sh, oak_containers_system_image/oak-orchestrator.service
and launch it at boot
-------
Merge after https://github.com/project-oak/oak/pull/4066
=> Include the orchestrator in the system image

cc/client/client.h, cc/client/crypto_provider.h, cc/client/evidence_provider.h, cc/client/verifier.h, cc/transport/grpc_streaming_transport.h, cc/transport/transport.h, oak_remote_attestation/proto/v1/BUILD
Fixing header guards in PR #4067
=> C++ Client Template Class Header Guard Fix

oak_containers_stage1/src/main.rs
systemd will overwrite this file with an identifier later in the boot process, but if the file doesn't exist at all, `systemd-machine-id-setup` will fail. Interestingly it will fail even though an ID is written (at some point) to that file!
However, if we just create an empty file before starting `systemd`, that's enough to satisfy `systemd-machine-id-setup` and now we have the guest starting up with zero errors!
```
● localhost
State: running
Units: 153 loaded (incl. loaded aliases)
Jobs: 0 queued
Failed: 0 units
```
=> Create a placeholder `/etc/machine-id` file in stage1

kokoro/build_binaries.sh
=> Add bash script for building and importing binaries with Kokoro

.github/workflows/build_rust_docs.yaml, .github/workflows/ci.yaml, scripts/build_gh_pages
=> Fix doc generation

docs/development.md, flake.nix
Add instructions for remote SSH setup for VS Code.
Remove most instructions related to Docker.
=> Fix development instructions for Nix

Cargo.lock, Cargo.toml, oak_restricted_kernel/src/virtio_console.rs, oak_restricted_kernel_bin/Cargo.lock, oak_restricted_kernel_bin/Cargo.toml
=> Update the virtio-drivers crate

.github/workflows/ci.yaml, Cargo.lock, kokoro/oak_containers_presubmit.sh, oak_containers_stage1/Cargo.toml, oak_containers_stage1/src/image.rs, oak_containers_system_image/build.sh
This reduces the system image size from ~1.1 GB to ~300 MB. Of course, it doesn't change size once it's been uncompressed, so the ramdrive still needs to be sized accordingly.
=> Compress the system image with `xz` (and make stage1 uncompress it)

justfile
=> Build the hello world container bundle in kokoro

java/src/main/java/com/google/oak/client/OakClient.java, java/src/main/java/com/google/oak/crypto/ClientEncryptor.java, java/src/main/java/com/google/oak/crypto/ServerEncryptor.java, java/src/test/java/com/google/oak/client/BUILD, java/src/test/java/com/google/oak/client/OakClientTest.java
This PR adds the ability to invoke the client multiple times within the same session.
Ref https://github.com/project-oak/oak/issues/3644
=> Support sessions in Java client

oak_containers_stage1/src/main.rs
This file may linger around in the system image as we're building it off a Docker container, and it makes systemd think it's running inside a container, which it is not.
=> Remove `/.dockerenv`, if it exists, as we're not running under Docker

cc/client/BUILD, cc/client/grpc_client_cli.cc
Ref https://github.com/project-oak/oak/issues/4069
=> Implement C++ gRPC client CLI

oak_containers_hello_world_container/build_container_bundle, oak_containers_hello_world_trusted_app/src/app_service.rs, oak_containers_system_image/build.sh
This fixes a previous race condition, that led the hello world app to occasionally fail.
=> Fix Hello World App: Prevent prevent premature shutdown.

Cargo.lock, deny.toml
=> Update colored crate to remove dependecy on atty

Cargo.lock, justfile, kokoro/build_binaries_oak_containers.sh, oak_containers_hello_world_trusted_app/Cargo.toml, oak_containers_hello_world_trusted_app/src/app_service.rs, oak_containers_hello_world_trusted_app/src/main.rs, oak_containers_hello_world_trusted_app/src/orchestrator_client.rs, oak_containers_hello_world_untrusted_app/Cargo.toml, oak_containers_hello_world_untrusted_app/src/app_client.rs, oak_containers_hello_world_untrusted_app/src/lib.rs, oak_containers_hello_world_untrusted_app/src/main.rs, oak_containers_hello_world_untrusted_app/tests/integration_test.rs, oak_containers_kernel/Makefile, oak_containers_launcher/Cargo.toml, oak_containers_launcher/src/lib.rs, oak_containers_launcher/src/main.rs, oak_containers_launcher/src/qemu.rs, oak_containers_launcher_server/src/lib.rs, oak_containers_orchestrator/src/container_runtime.rs, oak_containers_system_image/10-enp0s1.network
=> Add Oak Containers integration test

java/src/main/java/com/google/oak/util/Result.java, java/src/test/java/com/google/oak/util/ResultTest.java
I realized that these methods could be handy when implementing server-side gRPC methods.
=> Add orElse, ifSuccess, and ifError methods to Result

stage0/src/acpi.rs
Move some of the validation code to `DescriptionHeader` itself, as we'll need it for not just the XSDT, but the MADT as well.
=> Refactor how we validate ACPI tables a bit

stage0/src/acpi.rs, stage0/src/lib.rs
This should finish the little adventure of having to parse ACPI data structures, as we can find out what CPUs exist from the MADT.
Obviously we're not trying to bootstrap the APs yet; for now, I just dump the MADT contents we're interested in to the log. For example, if I give QEMU 16 CPUs, here's the output:
```
tage0 DEBUG: Found ACPI MADT table: Madt { header: DescriptionHeader { signature: [65, 80, 73, 67], length: 202, revision: 1, checksum: 148, oem_id: [66, 79, 67, 72, 83, 32], oem_table_id: [66, 88, 80, 67, 32, 32, 32, 32], oem_revision: 1, creator_id: 1129338946, creator_revision: 1 }, local_apic_address: 4276092928, flags: MadtFlags(PCAT_COMPAT) }
stage0 DEBUG: Local APIC: ProcessorLocalApic { header: ControllerHeader { structure_type: 0, len: 8 }, processor_uid: 0, apic_id: 0, …
```
=> Parse the APIC and X2APIC structures out of the ACPI MADT table

Cargo.lock, stage0/Cargo.toml, stage0/src/kernel.rs, stage0/src/lib.rs, stage0_bin/Cargo.lock, stage0_bin/build.rs
I have decided to move away from the approach in #4208, and to rather add measurment logic in smaller increments.
Ref #4074
=> Measure the kernel image in Stage 0

stage0/src/acpi_tables.rs, stage0/src/smp.rs
RSDT is the older relative of the XSDT, with the key difference that the pointers in RSDT are 32 bit. Unfortunately this means we can't just transmogrify the table into Rust references with some `unsafe` casting as the pointers still need to be 64 bit, and thus have to do some extra legwork.
=> Add support for parsing ACPI RSDT table as well

stage0/src/acpi.rs, stage0/src/kernel.rs, stage0/src/lib.rs, stage0/src/zero_page.rs
These are the final missing measurements we needed for attestation evidence.
This change also includes some refactoring to make some of the other measurement code more consistent.
Ref #4074
=> Measure the ACPI table generation commands and the physical memory map (E820 table)

micro_rpc_build/src/lib.rs, micro_rpc_tests/out/micro_rpc.tests.rs.txt, micro_rpc_tests/tests/test_schema.rs, oak_functions_service/src/lib.rs, oak_functions_service/src/wasm/api.rs, oak_iree_service/src/lib.rs, oak_tensorflow_service/src/lib.rs, quirk_echo_service/src/lib.rs, testing/oak_echo_service/src/lib.rs
=> optimize micro_rpc by removing surplus copies

stage0_bin/supply-chain/audits.toml, stage0_bin/supply-chain/imports.lock
=> vet spinning_top:0.2.4

stage0_bin/supply-chain/audits.toml, stage0_bin/supply-chain/imports.lock
=> vet lock_api:0.4.9

stage0_bin/supply-chain/audits.toml, stage0_bin/supply-chain/imports.lock
closes https://github.com/project-oak/oak/issues/3960
=> vet scopeguard 1.1.0

oak_remote_attestation_verification/src/tests.rs, oak_remote_attestation_verification/src/verifier.rs
Small fix in the verification of `BinaryAttestation`.
=> Fix binary attestation verification

oak_containers_orchestrator/src/container_runtime.rs
So far we have ignored environment variables in the container config, but we might need it for some containers.
This also changes some of the orchestrator's logging to make the output more readable and relevant.
=> Add Oak Containers environment variable support

stage0/src/apic.rs, stage0/src/smp.rs
Unfortunately it looks like supporting x2APIC is not enough. We need to support the older xAPIC as well.
The API is similar enough; the key difference between x2APIC and xAPIC (for us) is that (a) the APIC identifiers are shorter (8 bit vs 32 bit), so we can only support up to 256 CPUs and (b) instead of using MSRs we need to do MMIO to interact with the APIC.
This shuffles some deck chairs around and creates an enum that tries to encapsulate the difference (MSR vs MMIO) while providing an uniform API.
Feel free to bikeshed about the design, though.
=> Refactor APIC register code into an enum

.github/workflows/build_toolchain.yaml, .github/workflows/reusable_provenance.yaml
Update URL to use `sha2-256` instead of `sha256`
=> Use new version of ent client

stage0/src/apic.rs, stage0/src/smp.rs
I'd like to split this into smaller pieces, but with Github not supporting dependencies between PRs, it's going to be all in one...
Unfortunately we've found out that in some circumstances (cough, AMD Milan + a certain VMM) we need to use xAPIC instead of the more modern x2APIC.
The APIs xAPIC and x2APIC use are tantalizingly close, but yet there are enough incompatibilities that I couldn't figure out a really nice generic interface.
However, it works -- I was able to bootstrap the APs, at least on QEMU, via xAPIC.
Ref #4235
=> Add support for bootstrapping APs using xAPIC

stage0/src/apic.rs
Minor change which makes it more readable, I think, and less error-prone as the offsets are in only one location.
=> Change the ICR field enum values to properly shifted u32's

stage0/src/allocator.rs, stage0/src/kernel.rs, stage0/src/lib.rs, stage0/src/paging.rs
As we've given up and included an allocator in stage0, we might as well use the standard Rust idioms with `BOOT_ALLOC` as well.
This doesn't actually change _how_ we're using that memory, we're still leaking it left and right, but now we can use the standard API to do that.
There's more memory clean-ups that can be done here as well; I might squeeze a few in.
=> Use the standard Allocator API for `BOOT_ALLOC`

stage0/src/fw_cfg.rs, stage0/src/lib.rs, stage0/src/sev.rs
Instead of explicitly managing the shared state, this creates a RAII-like wrapper around shared data structures.
While it's useful in the current form, there's *a ton* of improvements that can be done here. To start with, don't leak the memory and ensure the value is properly destructed, and don't assume static lifetimes. GHCB requires some special handling, as well. Third, handle data structures that may be bigger than one page -- or at the very least, panic if they exceed the one page.
This should hopefully in the future give one centralized place where to manage sharedness, with e.g. TDX requiring us to flip the bit the other way.
=> Create a RAII wrapper for shared data structures

.github/workflows/reusable_provenance.yaml
Let me know if we need the logging part, then I can bring it back.
=> Remove computation, logging, and comment posting of digests.

linux_boot_params/src/lib.rs, stage0/src/lib.rs, stage0/src/zero_page.rs
Three minor improvements that I stashed in one PR out of sheer laziness:
1) move the `SEV_STATUS` static into the `sev_status()` function; now we can be _really_ sure nobody will mutate it
2) don't leak zero page immediately, but only when we really need to (in jump_to_kernel)
3) reserve memory for ACPI tables and the reserved region properly, even if we get a memory map via the QEMU API.
There's obviously more spit and polish to be done in stage0, but for now, I think I'm done.
=> Minor improvements in stage0

java/src/main/java/com/google/oak/transparency/LogEntryVerifier.java, java/src/main/java/com/google/oak/transparency/RekorLogEntry.java, java/src/main/java/com/google/oak/transparency/RekorSignatureBundle.java, java/src/main/java/com/google/oak/transparency/SignatureVerifier.java, java/src/test/java/com/google/oak/transparency/BUILD, java/src/test/java/com/google/oak/transparency/LogEntryVerifierTest.java, java/src/test/java/com/google/oak/transparency/SignatureVerifierTest.java, oak_remote_attestation_verification/testdata/BUILD
- Add implementation of signature verification
- Add more tests
- Add automatic raw/PEM format detection for command line tools
- Fix essential typo: logID not logId - variable names are taken literally as JSON keys
- Fix capitalization in javadocs per style guide
Ref #2854
=> Add Java signature verification.

Cargo.lock, Cargo.toml, oak_functions_containers_app/Cargo.toml, oak_functions_containers_app/README.md, oak_functions_containers_app/build.rs, oak_functions_containers_app/src/lib.rs, oak_functions_containers_app/src/main.rs
Create simple Oak Functions interface using Oak Containers.
Each handler only prints that it received a request. This is not yet functional. Sending this request to get initial feedback on my work.
#4182
=> Create simple Oak Functions interface for Oak Containers

oak_containers_orchestrator/src/container_runtime.rs
As far as sandboxing goes, it's not much, but it's a start -- at least with these changes we know `runc` can only write to (a) its own `RuntimeDirectory` and (b) wherever the orchestrator placed the container image.
=> Enable `ProtectSystem=strict` (with an exception) for `runc`

oak_containers_orchestrator/src/container_runtime.rs, oak_containers_orchestrator/src/main.rs
A couple of small things that should really been part of my other PRs, but weren't.
=> Minor clean-ups in the orchestrator

oak_containers_syslogd/src/main.rs
I made the change, and pushed the PR, thinking that I addressed your review comment... only to discover after I merged that PR that no, I actually didn't add the commit to the PR.
Oops.
=> Fix formatting issue in #4398

.xtask_bash_completion, cc/tflite_micro/BUILD, chrome_extension/background.js, enclave_apps/Cargo.lock, flake.lock, flake.nix, justfile, kokoro/build_binaries_rust.sh, oak_containers_launcher/src/server.rs, oak_containers_orchestrator/src/lib.rs, oak_containers_syslogd/src/main.rs, oak_crypto/proto/v1/BUILD, oak_crypto/src/encryptor.rs, oak_functions_service/src/lookup.rs, oak_functions_service/src/wasm/mod.rs, oak_remote_attestation/proto/v1/BUILD, oak_remote_attestation_verification/src/rekor.rs, oak_restricted_kernel/src/interrupts.rs, oak_virtio/src/console/mod.rs, oak_virtio/src/test.rs, oak_virtio/src/vsock/socket/mod.rs, proto/BUILD, proto/attestation/BUILD, stage0/src/acpi_tables.rs, stage0/src/fw_cfg.rs, stage0/src/lib.rs, xtask/src/diffs.rs, xtask/src/main.rs
Fix things that the Rust compiler now complains about
=> Update nix deps

Cargo.lock, oak_containers_stage1/Cargo.toml, oak_containers_stage1/src/dice.rs, oak_containers_stage1/src/main.rs
For now we just read the DICE data from the memory addres that Stage 0 sent. We don't yet do anything useful with it apart from logging the magic number.
Converting the DICE data to a proto and adding a measurement for the next stage will be done as follow-up PRs..
=> Read Stage 0 DICE data in Stage 1

oak_restricted_kernel/src/interrupts.rs
=> Stop using deprecated _MM_GET_EXCEPTION_STATE

proto/attestation/evidence.proto
See http://go/protodosdonts#unspecified-enum for rationale
=> Rename default enum value

oak_functions_containers_launcher/src/main.rs
Step 1 at launching the enclave properly: load the wasm code.
Ref #4409
=> Load the wasm code at startup

justfile, kokoro/build_binaries_oak_containers.sh, oak_functions_containers_container/build_container_bundle
First step toward importing it for internal use cases.
Ref #4409
=> Build the Oak Functions Containers bundle as part of Kokoro presubmit

Cargo.lock, oak_functions_containers_launcher/Cargo.toml, oak_functions_containers_launcher/src/lib.rs, oak_functions_containers_launcher/src/lookup.rs, oak_functions_containers_launcher/src/main.rs
This is pretty much a copy-paste of the code in `oak_functions_launcher`.
Yes, this needs to be refactored so that there's only one implementation. But my goal right now is to first get it to work, and then make it nice. :)
Ref #4409
=> Load lookup data in `oak_functions_containers_launcher`

oak_functions_service/src/lib.rs
First: a micro_optimization: don't call `clone()` on `result.encrypted_response`. There is no need to create a copy; a reference will do.
Second: fold `ok_or` and `map_err` into one, it's (a) more readable and (b) avoids the useless `anyhow!`.
Third: `Message::encode()` encodes the message via `BufMut`, potentially returning an error if the buffer is not big enough. Vectors can be resized to pretty large (`isize::MAX`), so it's unlikely that'll ever fail. And... `Message::encode_to_vec()` does all of that for us, returning a straight `Vec` for us, which is much simpler.
(Also, should `result.encrypted_response` be cleared out now that it's serialized into `result.body`?)
=> Elide a copy in user request handler

cc/transport/grpc_streaming_transport.cc, java/src/main/java/com/google/oak/server/EncryptedStreamObserver.java, java/src/main/java/com/google/oak/transport/GrpcStreamingTransport.java, java/src/test/java/com/google/oak/transport/GrpcStreamingTransportTest.java, oak_client/src/transport.rs
=> Use explicit crypto responses in Oak Clients

oak_restricted_kernel/src/lib.rs
Please carefully review. I arrived at this code after some experimentation. It contains unsafe code. I do not claim fully understand the nuances of memory management here, though I am keen to learn. 
Left some questions as comments.
=> Read stage0 dice data in restricted kernel

oak_containers_stage1/src/dice.rs
Reading directly from `/dev/mem/` doesn't work when AMD SEV is enabled, as it reads encrypted garbage. By using `mmap` the page tables for the memory is set up correctly so that the memory pages are decrypted when reading.
=> Use `mmap` to read Stage 0 DICE data in Stage 1

oak_functions_launcher/benches/integration_benches.rs, oak_functions_service/src/lib.rs, oak_functions_service/tests/integration_test.rs
=> Use explicit crypto requests in Oak Enclaves

cc/transport/grpc_streaming_transport.cc, java/src/main/java/com/google/oak/transport/BUILD, java/src/main/java/com/google/oak/transport/GrpcStreamingTransport.java, oak_client/src/transport.rs, oak_functions_containers_launcher/src/server.rs, oak_functions_launcher/benches/integration_benches.rs, oak_functions_launcher/src/server.rs, oak_functions_service/src/lib.rs, oak_functions_service/tests/integration_test.rs
=> Use explicit crypto protos in client requests

oak_client/src/transport.rs, oak_functions_containers_launcher/src/server.rs, oak_functions_launcher/benches/integration_benches.rs, oak_functions_launcher/src/server.rs, oak_functions_service/src/lib.rs, oak_functions_service/tests/integration_test.rs, oak_remote_attestation/proto/v1/messages.proto, proto/oak_functions/service/oak_functions.proto
Fixes https://github.com/project-oak/oak/issues/4037
Fixes https://github.com/project-oak/oak/issues/4267
=> Remove serialized crypto protos

Cargo.lock, enclave_apps/Cargo.lock, oak_containers_orchestrator/Cargo.toml, oak_containers_orchestrator/src/main.rs, oak_crypto/src/encryptor.rs, oak_crypto/src/hpke/mod.rs, oak_crypto/src/tests.rs, oak_dice/src/evidence.rs, oak_functions_service/src/lib.rs, oak_remote_attestation/src/dice.rs, oak_restricted_kernel_api/Cargo.toml, oak_restricted_kernel_api/src/dice.rs, oak_restricted_kernel_api/src/lib.rs, oak_restricted_kernel_bin/Cargo.lock
=> Add enclave app API for retrieving DICE data

oak_functions_containers_app/src/lib.rs
This doesn't change anything about the keys themselves, but does one of the steps @tiziano88 laid out: instead of wrapping `OakFunctionsService`, use `OakFunctionsInstance` directly.
The code itself is largely copy-pasted from `OakFunctionsService`, unsurprisingly. The functionality should thus be exactly the same.
=> Refactor `OakFunctionsContainersService` to use `OakFunctionsInstance`

justfile
This should help with identifying and debugging test failures
=> Print debug messages for failing tests on kokoro

stage0/src/kernel.rs, stage0/src/lib.rs
The systems that use the ELF kernels do not currently recognise the `--oak-dice` kernel command-line parameter, so for now we don't want to append it when we load an ELF kernel.
=> Don't add the DICE data parameter for ELF kernels

micro_rpc_workspace_test/Cargo.lock, micro_rpc_workspace_test/Cargo.toml, micro_rpc_workspace_test/build.rs, micro_rpc_workspace_test/deny.toml, micro_rpc_workspace_test/proto/stubs.proto, micro_rpc_workspace_test/proto/test.proto, micro_rpc_workspace_test/src/lib.rs, oak_grpc_utils/src/lib.rs
=> Allow compiling protos from other workspaces

oak_containers_system_image/Dockerfile, oak_containers_system_image/build.sh
=> Fix Oak Containers system image rebuilding

stage0/src/acpi_tables.rs
Entry addresses of XSDT are placed from offset 0x24, and an entry address has 8 bytes. If the XSDT table header is 4-byte aligned, there is only 50% chance that the entry addresses are 8-byte aligned.
In debug mode, it is observed that `Xsdt::entries()` function causes the following panic:
```
stage0 ERROR: panicked at /path/to/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:155:5 :
unsafe precondition(s) violated: slice::from_raw_parts requires the pointer to be aligned and non-null, and the total size of the slice not to exceed `isize::MAX`
```
This patch adds a pointer wrapper to handle the alignment issue. This wrapper itself is 8 bytes but only 1-byte aligned. Trait `Deref` is implemented for this wrapper.
=> stage0: add a wrapper for unaligned 64bit address

Cargo.lock, deny.toml, enclave_apps/Cargo.lock, stage0_bin/Cargo.lock
=> Update elliptic-curve dep

cc/crypto/client_encryptor.cc, cc/crypto/hpke/BUILD, cc/crypto/hpke/jni/BUILD, cc/crypto/hpke/jni/com_google_oak_crypto_hpke_Hpke.h, cc/crypto/hpke/jni/com_google_oak_crypto_hpke_RecipientContext.h, cc/crypto/hpke/jni/com_google_oak_crypto_hpke_SenderContext.h, cc/crypto/hpke/jni/context_jni.cc, cc/crypto/hpke/jni/hpke_jni.cc, cc/crypto/hpke/recipient_context.cc, cc/crypto/hpke/recipient_context.h, cc/crypto/hpke/recipient_context_test.cc, cc/crypto/hpke/sender_context.cc, cc/crypto/hpke/sender_context.h, cc/crypto/hpke/sender_context_test.cc, cc/crypto/hpke/utils.cc, cc/crypto/hpke/utils.h, cc/crypto/hpke/utils_test.cc, cc/crypto/server_encryptor.cc, java/src/main/java/com/google/oak/crypto/ClientEncryptor.java, java/src/main/java/com/google/oak/crypto/ServerEncryptor.java, java/src/main/java/com/google/oak/crypto/hpke/Hpke.java, java/src/main/java/com/google/oak/crypto/hpke/RecipientContext.java, java/src/main/java/com/google/oak/crypto/hpke/SenderContext.java
This PR makes Oak C++ and Java Hybrid Encryption use random nonces.
=> Add random nonces to Oak C++ and Java Crypto

.devcontainer.json, Dockerfile, scripts/common
=> Use debian as base image in CI

cc/client/client_test.cc, cc/crypto/BUILD, cc/crypto/client_encryptor.cc, cc/crypto/hpke/BUILD, cc/crypto/hpke/recipient_context.h, cc/crypto/hpke/recipient_context_test.cc, cc/crypto/hpke/sender_context.h, cc/crypto/hpke/sender_context_test.cc, cc/crypto/hpke/utils_test.cc, cc/crypto/server_encryptor.cc
Missing from 3a28b30f9479579232ee100a1a1f096257e80e87
=> Add missing BUILD deps

oak_containers/proto/interfaces.proto, oak_containers_orchestrator/src/ipc_server.rs, oak_containers_stage1/src/client.rs
It's replaced by OrchestratorCryptoClient
=> Remove the old OrchestratorClient crypto methods

Cargo.lock, oak_attestation_verification/Cargo.toml, oak_attestation_verification/src/lib.rs, oak_attestation_verification/src/verifier.rs, oak_ml_transparency/runner/Cargo.lock, oak_sev_guest/src/guest.rs
This is only the first step of several, adds some functions for scaffolding but does add any signature/cert verification.
=> Parse attestation report and verify debug mode.

Cargo.lock, oak_attestation_verification/Cargo.toml, oak_attestation_verification/src/rekor.rs, oak_ml_transparency/runner/Cargo.lock
Minimal changes to replace this dependency and unblock importing.
Closes #4616
=> Replace serde_jcs dependency with serde_canonical_json

Cargo.lock, oak_containers_launcher/src/qemu.rs, oak_containers_orchestrator/Cargo.toml, oak_containers_orchestrator/src/metrics.rs, oak_containers_syslogd/Cargo.toml, oak_containers_syslogd/src/log_relay.rs, oak_containers_syslogd/src/main.rs, oak_functions_containers_app/Cargo.toml, oak_functions_containers_app/src/lib.rs, oak_functions_containers_app/src/main.rs, oak_functions_containers_app/tests/integration_test.rs, oak_launcher_utils/src/launcher.rs
=> Update Rust dependencies

oak_containers_orchestrator/src/crypto.rs, oak_containers_orchestrator/src/main.rs
Implements basic signing functionality in the orchestrator, using the instance key.
=> Implement signing functionality in the orchestrator

stage0/src/lib.rs, stage0_dice/src/lib.rs
=> Log Stage 0 measurement digests in hex

oak_functions_containers_app/src/lib.rs
=> Set the max incoming packet size to 1 GiB for Oak Functions gRPC

oak_functions_sdk/tests/integration_test.rs, oak_functions_service/src/instance.rs, oak_functions_service/src/logger.rs, oak_functions_service/src/lookup.rs, oak_functions_service/src/wasm/api.rs, oak_functions_service/src/wasm/mod.rs, oak_functions_service/src/wasm/tests.rs
=> Remove OakLogger generics

Cargo.lock, oak_functions_service/Cargo.toml, oak_functions_service/benches/wasm_benchmark.rs, oak_functions_service/src/wasm/tests.rs
=> Create more solid Wasm benchmarks

java/src/main/java/com/google/oak/client/BUILD, java/src/main/java/com/google/oak/client/OakClient.java, java/src/main/java/com/google/oak/client/weather_lookup_client/BUILD, java/src/main/java/com/google/oak/remote_attestation/BUILD, java/src/main/java/com/google/oak/remote_attestation/InsecureAttestationVerifier.java, java/src/test/java/com/google/oak/client/OakClientTest.java, java/src/test/java/com/google/oak/transport/BUILD
Convert some java_library targets to android_library to be able to use cose-lib dependency in google3. Also some import and dependency cleanup
=> Convert some java_library targets to android_library

Cargo.lock, Cargo.toml, enclave_apps/Cargo.lock, enclave_apps/Cargo.toml, enclave_apps/oak_orchestrator/Cargo.toml, enclave_apps/oak_orchestrator/src/main.rs, justfile, oak_restricted_kernel_bin/Cargo.toml, oak_restricted_kernel_launcher/README.md, oak_restricted_kernel_orchestrator/Cargo.toml, oak_restricted_kernel_orchestrator/src/lib.rs
Wait to merge until https://github.com/project-oak/oak/pull/4759 is merged
=> Basic orchestrator enclave app

enclave_apps/oak_orchestrator/src/main.rs, oak_restricted_kernel/src/syscall/dice_data.rs, oak_restricted_kernel/src/syscall/key.rs, oak_restricted_kernel/src/syscall/mod.rs, oak_restricted_kernel_orchestrator/src/lib.rs
Code copied from #4767, with minor modifications.
=> Permit the orchestrator to write the derived key

oak_attestation_verification/testdata/BUILD
I forgot to update the BUILD file in #4774
=> Add fake evidence test data to the build file

oak_restricted_kernel/src/lib.rs, oak_restricted_kernel/src/mm/encrypted_mapper.rs, oak_restricted_kernel/src/mm/mod.rs, oak_restricted_kernel/src/mm/page_tables.rs, oak_restricted_kernel/src/payload.rs, oak_restricted_kernel/src/syscall/switch_process.rs
No concurrency yet, but introduces a process struct separate from applications. PR depends on  #4811. 
To view just the changes related to the process struct, click on the last commit: https://github.com/project-oak/oak/pull/4812/commits/ae448386eaffda7c7e06b2098ebe66d200c8e865
=> Implement processes in the restricted kernel

.github/workflows/ci.yaml
=> Remove run-cargo-tests from GitHub Actions

kokoro/run_clippy.sh
=> Add Kokoro script for running clippy

stage0/src/acpi.rs
QEMU itself doesn't need this, but to support some other VMMs will have broken ACPI tables if we don't patch them with this custom command.
=> Add support for `ADD_PCI_HOLES` to stage0

kokoro/check_format.sh, kokoro/completion.sh, kokoro/format.sh, kokoro/run_bazel_tests.sh, kokoro/run_cargo_deny.sh, kokoro/run_cargo_fuzz.sh, kokoro/run_cargo_udeps.sh
I was originally planning to do one PR per item, but doing them all at
once seems reasonable. (Clippy was done already in #4837)
These aren't wired to Kokoro yet, so the testing for this PR has been to
manually run each script.
=> Add Kokoro build scripts for the remaining xtask items

oak_functions_containers_app/src/lib.rs, oak_functions_containers_app/src/main.rs, oak_functions_containers_app/tests/integration_test.rs
Tentative step towards possibly having multiple kinds of streams, e.g. virtio-vsock streams.
The amount of generic arguments `serve` has is starting to get rather silly, though.
=> Move listener stream construction out of `serve`

flake.nix, oak_containers_kernel/Makefile
First step towards attempting to build and cache it via nix too, but this is also useful in itself to make sure that the archive does not change.
b/328294742
=> Download and pin upstream linux kernel via nix

oak_containers_launcher/src/qemu.rs
Does what it says on the tin. Not used right now, but will be soon to test the vsock functionality in Oak Functions.
=> Add a parameter to `Qemu` to add a virtio-vsock device

oak_containers_launcher/src/lib.rs
In itself a seemingly unnecessary change but this paves the road to having different kind of trusted application addresses -- namely, vsock ones.
=> Create a wrapper to store trusted app address instead of a SocketAddr

xtask/src/check_todo.rs
=> Fix todo matching logic

oak_containers_launcher/src/lib.rs, oak_containers_launcher/src/qemu.rs, oak_functions_containers_launcher/src/lib.rs
This will not change existing behaviour but shuffles the code around enough to allow us to introduce a VirtioVsock channel in a cleaner way.
=> Make the choice of a trusted application channel more explicit

WORKSPACE, proto/attestation/BUILD, proto/containers/BUILD, proto/crypto/BUILD, proto/micro_rpc/BUILD, proto/session/BUILD, xtask/src/main.rs
Also remove java_lite_proto_library rule: it was failing and it was not used.
#4540 
b/327614806
=> Build proto directory as part of CI.

oak_functions_service/src/lookup.rs
Based on the suggestion in the previous PR.
=> Replace the multiple conditionals with just two mod-s

oak_attestation_verification/tests/verifier_tests.rs
So far we have not been testing the intial measurement with reference value. This just makes sure that the reference values is actually checked.
=> Add tests for verifying initial measurement

flake.nix, oak_containers_kernel/Makefile
=> Remove vmlinux target

kokoro/build_binaries_oak_containers.sh
=> Track oak containers binaries in kokoro

WORKSPACE, java/src/main/java/com/google/oak/crypto/BUILD, java/src/main/java/com/google/oak/crypto/DecryptionResult.kt, java/src/main/java/com/google/oak/verification/BUILD, java/src/main/java/com/google/oak/verification/Failure.kt
=> Add kotlin_rules and convert some simple classes as examples 

flake.nix
=> Fix username and host when building kernel

cc/containers/sdk/encryption_key_handle.cc, cc/containers/sdk/encryption_key_handle.h
=> Add GroupEncryptionKeyHandle to C++ Containers SDK

stage0/src/sev.rs
This should help us give more evidence whether hugepages are in use or not.
We first try to `PVALIDATE` using 2 MiB pages, and if that fails (with a `FAIL_SIZEMISMATCH` error), we validate the same region using 4 KiB pages.
Hence, if hugepages are not in use, I'd expect to see zero successful 2 MiB validations, `n` errors, and `512*n` successful 4K validations.
Ref b/330345538
=> Collect, and print out, some `PVALIDATE` stats in stage0

oak_sev_guest/src/ghcb.rs
Minor readability PR: our existing methods in `GhcbProtocol` use different ways to access the GHCB. For clarity make sure all the functions are implemented the same way.
Entirely optional PR, feel free to push back if you don't like this particular style I've chosen.
=> Clean up different ways we use the GHCB in `oak_sev_guest`.

xtask/src/main.rs
Change-Id: Ic9817fa4ffa21ee57ba150f7c1200b1df8622a25
=> Bazel test all as part of CI

.github/workflows/reusable_provenance.yaml
Change-Id: Ie3df48c899c4b90e39af4f599f8c7a9b05cfda17
https://github.com/project-oak/oak/pull/4995 broke this step
=> fix bug in provenance generation script

oak_functions_service/src/wasm/mod.rs, oak_functions_service/src/wasm/wasmtime.rs
a) If we're built with `deny_sensitive_logging`, elide the `log_sensitive` calls altogether.
As the logger is hidden behind a `Box<dyn OakLogger>`, the compiler can make no assumptions about which logger is in use and even when we build with `deny_sensitive_logging`, we format the debug strings only then to immediately throw them away.
This is the reason why the `log` crate has `info!` and friends macros: with a macro, you can check if logging is enabled, and only format the string if it is. We should consider implementing similar macros; but for now, let's see if using the same crate feature gets rid of all the CPU we're burning on string formatting.
b) When constructing the response, move the contents of the vector, don't clone it. Doing a move removes an unnecessary allocation and a …
=> Micro-optimizations for Oak Functions

oak_attestation_verification/src/verifier.rs, proto/attestation/expected_value.proto
=> Split verify_text_value into get_expected/compare calls

oak_restricted_kernel_dice/BUILD
Change-Id: Ie703559f1d1764563be44982af80d47805da0534
=> Build oak_restricted_kernel_dice with Bazel

oak_functions_service/src/wasm/wasmtime.rs
=> Set Cranelift opt level to `Speed`.

oak_restricted_kernel_interface/BUILD
Change-Id: Ie276d222782cdd0d79b6224092b1738e2ce8e61a
=> Build oak_restricted_kernel_interface with Bazel
