examples/hello_world/client/BUILD, examples/hello_world/client/hello_world.cc, examples/running_average/client/BUILD, examples/running_average/client/running_average.cc, oak/client/BUILD, oak/client/manager_client.h
Some of the classes were renamed in #14, but the examples were missed.
ref #7
=> Fix references to Oak Scheduler client in examples

.dockerignore, Dockerfile, scripts/build_server_docker, scripts/docker_sh
This should help with #22.
Also exclude bazel-cache folder from docker context, as it is already
mounted in the docker command used to build and run the targets.
=> Install Rust in Dockerfile

.clang-format
The default derives alignment from the file, allowing inconsistency
between files.
=> Add explicit PointerAlignment for clang-format

oak/client/manager_client.h, oak/server/enclave_server.h, oak/server/oak_enclave.cc, oak/server/oak_main.cc, oak/server/oak_manager.cc, oak/server/oak_manager.h, oak/server/oak_node.h, scripts/format
It turns out that the glob expression was incorrect, so that is now
fixed, and all the files are now correctly formatted.
In particular #29 affects pointer types, which are now consistent.
=> Format all code with clang-format

examples/private_set_intersection/client/private_set_intersection.cc, oak/client/node_client.h, oak/proto/node.proto, oak/server/BUILD, oak/server/oak_node.cc, oak/server/oak_node.h
Add support for the Oak Node reporting the SHA256 hash of the Oak Module
with which it was initialized.
Modify one of the examples to print out the remote attestation received
from the Oak Node.
ref. #6
=> Support hash-based remote attestation in Oak Nodes

scripts/docker_run
Accidentally missed the flag to expose the port on which Oak Nodes are
listening.
=> Fix docker_run script

oak/server/BUILD, oak/server/grpc_stream.cc, oak/server/oak_node.cc, oak/server/oak_node.h
Avoids copying and managing an external cursor by using a Span
for the request data and pushing ::grpc::ByteBuffer conversion
up to the caller.
ref #4
=> Improve memory management for Oak Module

CONTRIBUTING.md, INSTALL.md, examples/hello_world/client/hello_world.cc, examples/private_set_intersection/client/private_set_intersection.cc, examples/private_set_intersection/src/lib.rs, examples/running_average/client/running_average.cc, examples/utils/utils.h, scripts/format
For some reason just using shell globs was not working for Rust files,
so I switched to using `find` instead to enumerate the various
categories of files.
=> Fix and run format script

.bazelrc, Dockerfile, WORKSPACE
Changes done
- Updated to asylo-v0.3.4 from v0.3.3
- Replaced http_archive loads with git_repository loads
Remarks:
- Dependency version numbers should really be loaded from a common place, at the moment it's somewhat inconsistent. For example in the [Dockerfile](https://github.com/project-oak/oak/blob/c3a262477df8d843f005ddf9c9e7c000b74de09e/Dockerfile#L6) Protobuf version is explicitly set to v3.7.1 while in the [WORKSPACE](https://github.com/project-oak/oak/blob/c3a262477df8d843f005ddf9c9e7c000b74de09e/WORKSPACE#L30) file it's v3.6.1.2. I'm not sure what would be the right way of doing that, probably injecting a Step 0 that'd generate the Dockerfile and the WORKSPACE file from a version config.
-  Interesting thing is that the project doesn't build with protobuf v3.7+, the problem is …
=> Updated asylo to v0.3.4

WORKSPACE, oak/client/node_client.h, oak/server/BUILD, oak/server/enclave_server.h, oak/server/oak_manager.cc
This further fixes #58 by moving the authority configuration out of the EnclaveServer and into the OakManager.
=> Add assertion authority configuration to OakManager

scripts/build_examples_docker, scripts/build_server_docker, scripts/docker_run, scripts/docker_sh, scripts/format, scripts/run_server_docker
The new shebang is preferable both because of portability, and because bash is more rich in features than sh.
=> Made all scripts have proper shebang

examples/hello_world/Cargo.toml, examples/hello_world/src/lib.rs, examples/machine_learning/Cargo.toml, examples/machine_learning/src/lib.rs, examples/private_set_intersection/Cargo.toml, examples/private_set_intersection/src/lib.rs, examples/running_average/Cargo.toml, examples/running_average/src/lib.rs, rust/oak/Cargo.toml, rust/oak/src/lib.rs, rust/oak_derive/Cargo.toml, rust/oak_derive/src/lib.rs
Rely on procedural macros to support the `#[derive]` annotations instead
of the previous approach.
=> Implement code generation for Oak nodes

WORKSPACE, examples/Cargo.lock, oak/server/enclave_server.cc, oak/server/enclave_server.h
In #61 the assertions were correctly configured, so here we are removing
the unnecessary setup that was added previously (which does not belong
to the enclave configuration).
Also update Asylo to hotfix release v0.3.4.2
=> Fix Asylo assertion configuration

scripts/build_examples_docker, scripts/build_server_docker, scripts/docker_run, scripts/docker_sh, scripts/format, scripts/run_server_docker
I used [ShellCheck](https://github.com/koalaman/shellcheck) to identify the places where this needed to be done. For portability, they also recommend using `find .` explicitly since it is not implicit in all versions of `find`.
=> Add quotes to scripts where appropriate.

WORKSPACE, examples/hello_world/client/BUILD, examples/hello_world/proto/BUILD, examples/machine_learning/client/BUILD, examples/machine_learning/proto/BUILD, examples/private_set_intersection/client/BUILD, examples/private_set_intersection/proto/BUILD, examples/running_average/client/BUILD, examples/running_average/proto/BUILD, oak/client/BUILD, oak/proto/BUILD, oak/server/BUILD
Updates gRPC rules to allow dependencies on cc_proto_library, which
will facilitate reusing proto rules for services such as Cloud Spanner.
Updates the proto rules to follow Bazel best practices:
https://docs.bazel.build/versions/master/be/protocol-buffer.html#proto_library
=> Convert Bazel rules to use cc_grpc_library

examples/hello_world/src/lib.rs, examples/machine_learning/src/lib.rs, examples/private_set_intersection/src/lib.rs, examples/running_average/src/lib.rs, rust/oak/src/lib.rs
This fixes most of the issues raised by running clippy. A following diff
will enable clippy as a default check, but this prevents CI from
failing.
There still are issues with automatic generated protobuf code, which is
being fixed here: https://github.com/stepancheg/rust-protobuf/pull/332
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/project-oak/oak/87)
=> Fix rust clippy errors and warnings

.dockerignore, .gitignore, Dockerfile, scripts/build_examples_docker, scripts/check_formatting, scripts/docker_run
Clippy compiles code and this took a long time since we were not reusing
artefacts. In order to do that, we are running everything in the
container as current user instead of root. This requires mounting both
the bazel cache and the cargo one.
Fixes: #70, #79
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/project-oak/oak/86)
=> Add rust-clippy to CI and set docker UID

oak/server/BUILD, oak/server/enclave_server.cc, oak/server/oak_node.cc, oak/server/oak_node.h, oak/server/wabt_output.cc, oak/server/wabt_output.h
Check that an Oak module exports the required entrypoints, and that they have the correct signature.
Move Oak Node creation to a factory method to allow early detection of an invalid Node.
Best reviewed commit-by-commit.
=> Police Oak module exported function requirements

oak/server/oak_node.cc
If the channel handle is not in the channel map, don't
attempt to use it.
=> Don't use an invalid channel handle

rust/oak/src/lib.rs
Somewhat speculative, not sure that this is an ideal approach.
=> Police multiple attempts to set the one true Node instance

Dockerfile, scripts/docker_run, scripts/run_examples
- Use short `id` options that work on OSX too
- Cope with an already-existing group
=> Make build scripts more robust

Dockerfile
Bazel has updated to 0.27 and is breaking a bunch of stuff in asylo bzl
files. This is the fastest fix to unblock CI - it will cause remote
cache to stop working. We will add a proper fix in the next days.
=> Fix continuous integration builds

WORKSPACE
The version we have in the WORKSPACE was different from the one we have
in the Dockerfile. This aligns them
=> Update protobuf version to match the compiler

Dockerfile, scripts/docker_run, scripts/run_examples
Only set user at runtime, but build Docker image with the default user
(root). This simplifies things because we don't need to switch user
halfway through the build process.
Following @remyabel's suggestion in
https://github.com/project-oak/oak/issues/70#issuecomment-502232945
ref #70
=> Improve Docker user management

scripts/check_formatting
Now that we have two workspaces (one for the main lib and one for the
examples) we can invoke `cargo clippy` in a more idiomatic way.
=> Run cargo clippy by workspace

scripts/docker_run, scripts/run_examples
Avoiding duplicate docker run commands in `scripts/docker_run` and
`scripts/run_examples`.
=> Refactoring: Pass `detach` flag to scripts/docker_run

scripts/build_example, scripts/run_example
This is a small script that allows to build only one of the examples,
either by entering it as an arg or selecting it from a list.
Additionally, it allows us to build the C++ code in debug mode, if
needed.
=> Add script to build a single example

examples/hello_world/src/lib.rs, examples/hello_world/src/proto/hello_world_grpc.rs, examples/private_set_intersection/src/lib.rs, examples/private_set_intersection/src/proto/private_set_intersection_grpc.rs, examples/running_average/src/lib.rs, examples/running_average/src/proto/running_average_grpc.rs, rust/oak/src/lib.rs, rust/oak/src/proto/mod.rs, third_party/grpc-rust/grpc-compiler/src/codegen.rs
This is a better match to normal gRPC behaviour; however, note that
the status does not (yet) go anywhere, it just gets dropped in the
generated dispatcher code.
=> Always emit a status along with a proto response

Dockerfile
The current dockerfile install the latest version of Rust at the time
the Docker image is built, which is obviously not reproducible.
In particular, there has just been a [new Rust
release](https://blog.rust-lang.org/2019/07/04/Rust-1.36.0.html) and our
tests are now suddenly failing because of some incompatible changes,
even though we have not modified anything in our code to trigger the
failure.
=> Define rust version to install in Dockerfile

README.md, examples/Cargo.lock, examples/hello_world/src/proto/hello_world_grpc.rs, examples/private_set_intersection/src/proto/private_set_intersection_grpc.rs, examples/running_average/src/proto/running_average_grpc.rs, oak/server/BUILD, oak/server/buffer_channel.h, oak/server/channel.h, oak/server/oak_node.cc, oak/server/status.h, rust/Cargo.lock, rust/oak/Cargo.toml, rust/oak/src/lib.rs, third_party/grpc-rust/grpc-compiler/src/codegen.rs
To guarantee that a read only ever produces a complete message, we need
to cope with the case where the provided buffer for channel_read is not
large enough.  In this case, no data is returned but the required size
needs to be, so the caller can re-allocate and call again.
Wasm only currently allows a single return value in function signatures,
so hackily overload the returned size i32 so that negative values
indicate that nothing was returned, and what the required size is.
In turn, this means that the Rust code for a ReadChannelHalf cannot
implement the Read trait any more, because that trait is fundamentally
stream-oriented not message-oriented (i.e. it assumes partial reads are
just fine, and just repeats until EOF).
=> Make channels message-oriented

scripts/build_example, scripts/build_server_docker
build_example was not logging enough and build_server_docker was logging
too much. I will change the key for the remote cache, as we leaked the
previous one.
=> Change scripts to properly log things

.travis.yml, scripts/build_example
Looks like the Travis cache works better now than for #88 / #53, but there's still a "could not download cache" error for the [largest build](https://travis-ci.org/daviddrysdale/oak/jobs/561113337)
=> Speed up Travis builds

.gitignore, scripts/build_example, scripts/run_example
Also use distinct names for the symlinks to built code, and avoid
using `bazel run` (as that requires us to be careful that the build
and run steps use exactly the same options).
=> Use different --output_base when building examples

.travis.yml
The cargo-cache/ directory holds source code rather than built
objects, and so downloading this from Travis cache rather than
crates.io probably won't make much difference.
Instead, cache the two main target/ subdirectories, which hold
built objects and so should prevent some unneeded rebuilding.
=> Fix caching of Rust objects

.bazelrc, WORKSPACE, examples/hello_world/module/cpp/BUILD, examples/hello_world/module/cpp/hello_world.cc, oak/common/BUILD, oak/common/handles.h, oak/module/BUILD, oak/module/defines.h, oak/server/BUILD, oak/server/oak_node.h, scripts/build_example, scripts/run_example, toolchain/BUILD, toolchain/cc_toolchain_config.bzl, toolchain/clang.sh, toolchain/clang_llvm.BUILD
Please see commits separately.
The compilation becomes difficult due to 3 toolchains now and bazel is not great at handling this. We've already had problems when compiling server - client combinations, as it invalidated the cache. This, hopefully, fixes most of this, even if it goes in circles for it.
First step towards building #10
=> Add support for writing wasm modules in C++

rust/oak/src/lib.rs, rust/oak/src/tests.rs, rust/oak_tests/src/lib.rs
If tests happen to get run one after another (e.g. with
`cargo test -- --test-threads=1` then the global state changes from
an earlier test can affect later tests.
Add a couple of test-only entrypoint to reset globals to their
pristine state, and use these at the start of relevant tests.
=> Explicitly clear global state before each test

Dockerfile
There were a couple of missing dependencies in Docker that clang (strangely) needs.
Fixes #164
=> Fix docker cpp wasm build

Dockerfile, WORKSPACE, oak/proto/BUILD, oak/proto/application.proto
Temporarily depend on a version of Asylo that includes https://github.com/google/asylo/commit/efcc507e6c028412a0e612256e493341628b1fdb .
Also remove unnecessary proto import.
Fixes #111 .
=> Upgrade protobuf

oak/server/oak_node.cc, oak/server/oak_node.h, oak/server/oak_runtime.cc, oak/server/oak_runtime.h
This is a step towards #176 , as we need OakRuntime to manage Channels,
as opposed to the OakNode creating them directly.
=> Move logging channel from OakNode to OakRuntime

oak/server/BUILD, oak/server/channel.h, oak/server/module_invocation.cc, oak/server/module_invocation.h, oak/server/oak_node.cc, oak/server/oak_node.h, oak/server/oak_runtime.cc, oak/server/oak_runtime.h, scripts/docker_run, scripts/run_examples
Move most of the gRPC logic from OakChannel to OakRuntime, passing
channel halves around as necessary. After this commit, the gRPC channels
are owned by OakRuntime, and only the appropriate halves are passed to
OakNode.
Ref #176
=> Move gRPC channels to runtime

oak/server/channel.cc
The move is preventing a compiler optimisation. Recommendation is to return by value here.
=> Fix clang warning on copy elison

.travis.yml, README.md, scripts/build_examples, scripts/build_server, scripts/run_examples, scripts/run_server
Currently some scripts assume they need to run commands in Docker, while
some others assume they will be run in Docker already. This commit
separates the two things so that most scripts run commands without
knowledge about Docker, but they can easily be run via `docker_run` if
necessary.
Note the new command for starting a server in docker is now longer.
=> Decouple scripts from Docker

oak/server/BUILD, oak/server/asylo/enclave_server.cc, oak/server/asylo/enclave_server.h, oak/server/dev/dev_oak_manager.cc, oak/server/dev/dev_oak_manager.h, oak/server/oak_grpc_node.cc, oak/server/oak_grpc_node.h, oak/server/oak_node.cc, oak/server/oak_node.h, oak/server/oak_runtime.cc, oak/server/oak_runtime.h
This is another step towards having a fully configurable set of channels
and nodes. It introduces a special (for now) new node that is the GRPC
one. It also decouples the manager-server ownership and moves it to the
runtime
This allows the wasm nodes to stop being gRPC servers.
Next, we need to create a base class for all nodes and start migrating
towards a model where all channels and nodes are configurable and owned
by the runtime
=> Refactor server code outside of the manager

examples/hello_world/client/hello_world.cc, examples/hello_world/module/cpp/hello_world.cc, oak/client/manager_client.h, oak/common/app_config.cc, oak/common/app_config.h, oak/proto/manager.proto, oak/server/BUILD, oak/server/asylo/asylo_oak_manager.cc, oak/server/asylo/asylo_oak_manager.h, oak/server/asylo/enclave_server.cc, oak/server/asylo/enclave_server.h, oak/server/channel.h, oak/server/dev/dev_oak_manager.cc, oak/server/dev/dev_oak_manager.h, oak/server/logging_node.cc, oak/server/logging_node.h, oak/server/module_invocation.h, oak/server/node_thread.h, oak/server/oak_grpc_node.cc, oak/server/oak_grpc_node.h, oak/server/oak_node.cc, oak/server/oak_node.h, oak/server/oak_runtime.cc, oak/server/oak_runtime.h, oak/server/storage/BUILD, oak/server/storage/storage_node.cc, oak/server/storage/storage_node.h, oak/server/wasm_node.cc, oak/server/wasm_node.h, oak/server/wasm_node_test.cc
Evolving node processing to a common base `OakNode` class, with all node types deriving from it, some via `NodeThread`.
Along the way, add an initial chunk of code for termination processing.
Probably easiest to review commit-by-commit, particularly given the rename of `OakNode` to `WasmNode` and subsequent re-use of the `OakNode` name.
=> Nodes, channels and termination

examples/hello_world/client/BUILD, examples/hello_world/module/cpp/BUILD, examples/hello_world/proto/BUILD, examples/machine_learning/client/BUILD, examples/machine_learning/proto/BUILD, examples/private_set_intersection/client/BUILD, examples/private_set_intersection/proto/BUILD, examples/running_average/client/BUILD, examples/running_average/proto/BUILD, examples/rustfmt/client/BUILD, examples/rustfmt/proto/BUILD, examples/utils/BUILD, oak/client/BUILD, oak/common/BUILD, oak/module/BUILD, oak/proto/BUILD, oak/server/BUILD, oak/server/asylo/BUILD, oak/server/dev/BUILD, oak/server/storage/BUILD, scripts/check_formatting, toolchain/BUILD
This is needed in order to import the code in //google3/third_party, see
http://go/thirdpartylicenses (internal link).
Add presubmit to ensure we don't forget in the future.
=> Add license information to BUILD files

.travis.yml, scripts/build_example, scripts/build_server, scripts/docker_run
I made our cloud storage bucket publicly readable so that we can rely on
bazel remote cache from any branch. Then in the future we should add the
secret key so that it gets passed only to master.
Remove travis cache for bazel (which is often timing out recently).
=> Improve caching for CI

oak/server/wasm_node.cc, oak/server/wasm_node.h
=> Fix TODO on Wasm object ownership

oak/server/wasm_node.cc
For any offset+size parameters passed to Oak host functions, check
that the corresponding linear memory range is actually available
before using it.  Fixes #219.
=> Check bounds of all linear memory references

.gitignore, oak/server/asylo/BUILD, scripts/check_enclave_reproducibility
Disable stamping in order to attempt to get reproducibility.
Note that after this change, builds are still not reproducible, so there
must be some other source of discrepancy.
Ref. #241
=> Improve script for testing reproducibility

scripts/check_formatting, scripts/run_tests
It needs to build the code anyways, and it gets already built in the
testing phase anyways, so running clippy after tests is essentially
instantaneous.
This way the format script does purely syntactic checks and it is much
faster to return errors if there are any.
=> Move Rust clippy from formatting to test script

.travis.yml, scripts/docker_pull, scripts/docker_push, scripts/docker_run
For now, we still rely on logged-in users to manually push a new version
of the image when dependencies change, in the future we should automate
that too. CI and other users can already rely on those images to avoid
rebuilding the images locally every time, since the Registry is set to
allow public access.
=> Cache docker images to Google Container Registry

cloudbuild.yaml, scripts/build_dev_server, scripts/build_server, scripts/run_tests
Add an additional pipeline running on Google Cloud Build, which builds
the enclave binary and pushes it to Google Cloud Storage. The intention
is for this to be used to build reference binary artifacts to be
deployed on Borg in Google if necessary, once we get full reproducible
builds (#241).
Example run:
https://pantheon.corp.google.com/cloud-build/builds/700d7aea-6799-4822-afa1-ec3758e88faf?project=oak-ci
=> Use Google Cloud Build to upload artifacts

.travis.yml, cloudbuild.yaml, scripts/build_example, scripts/run_examples
Mirror more of the build steps on Google Cloud Build, so that for a
while we can run them in parallel and see whether one is faster / less
flaky than the other.
Change `run_examples` script so that it runs entirely in Docker (both
server and clients), which should make things more stable in CI.
=> Execute more steps on Google Cloud Build

.bazelrc, oak/server/BUILD, oak/server/wasm_node_fuzzer.cc, scripts/build_dev_server, scripts/build_example, scripts/build_server, scripts/fuzz
Add fuzz configuration to `.bazelrc`.
Create fuzz target for `wasm_node`.
Add `./scripts/fuzz` to get things up and running quickly.
Ref #261
=> Create skeleton for fuzz target

rust/Cargo.lock, rust/oak_log/Cargo.toml, rust/oak_log/src/lib.rs, rust/oak_log/src/tests.rs
For some reason, occasionally the log::max_level() is set to Off
and so the oak_log test fails.  Force the level to Info (and check
it).
Fixes #267 (hopefully).
=> Ensure max log level is set in tests

docs/programming-oak.md, examples/abitest/client/abitest.cc, examples/hello_world/client/hello_world.cc, examples/machine_learning/client/machine_learning.cc, examples/private_set_intersection/client/private_set_intersection.cc, examples/running_average/client/running_average.cc, examples/rustfmt/client/rustfmt.cc, oak/client/BUILD, oak/client/application_client.h, oak/client/manager_client.h, oak/client/policy_metadata.cc, oak/client/policy_metadata.h
Create PolicyMetadata client class to be used by clients to attach
policies to gRPC requests.
Refactor gRPC channel creation so it is encapsulated by
ApplicationClient.
Ref #212
=> Introduce policy as gRPC metadata

examples/abitest/client/abitest.cc, oak/common/app_config.cc, oak/common/app_config_test.cc, oak/common/testdata/barenode.textproto, oak/common/testdata/channel_dest_missing.textproto, oak/common/testdata/channel_inverted.textproto, oak/common/testdata/channel_source_missing.textproto, oak/common/testdata/default.textproto, oak/common/testdata/dup_node_name.textproto, oak/common/testdata/dup_port.textproto, oak/common/testdata/dup_wasm.textproto, oak/common/testdata/in_port_empty.textproto, oak/common/testdata/lognode.textproto, oak/common/testdata/missing_wasm.textproto, oak/common/testdata/multinode.textproto, oak/common/testdata/out_port_empty.textproto, oak/common/testdata/storagenode.textproto, oak/common/testdata/two_grpc.textproto, oak/common/testdata/two_log.textproto, oak/proto/manager.proto, oak/server/oak_runtime.cc
This allows the Wasm code for a Node to be shared between multiple
instances without duplication.
=> Add indirection between Wasm Node and its code

.bazelrc, toolchain/BUILD
Latest version of Bazel require explicit attribute for ar files to be included in the sandbox -https://github.com/bazelbuild/bazel/issues/8531
These were introduced before 28.1, which we are using in our Docker file, so it should work - https://docs.bazel.build/versions/0.28.0/be/c-cpp.html
=> Update toolchain config to work with Bazel 1.0.0

oak/client/BUILD, oak/client/policy_metadata.cc, oak/client/policy_metadata.h, oak/common/BUILD, oak/common/policy.cc, oak/common/policy.h, oak/server/BUILD, oak/server/channel.h, oak/server/module_invocation.cc, scripts/build_example, scripts/build_server_dev
Currently those labels are not used for anything, but in the future they
will be used for information flow.
Convert constant from absl::string_view back to char*, it does not seem
to work with std::multimap otherwise.
Rename _policy_ to _label_. This may still not be the final terminology,
but seems more appropriate.
Reintroduce `--output_base` flag to `build_example` to avoid losing
incremental state.
Ref #212
=> Attach policy labels to Messages

WORKSPACE, scripts/check_enclave_reproducibility
This finally allows building enclave code reproducibly (#241).
For the record, I got the following output from
`scripts/check_enclave_reproducibility`:
```
5d3b12032df2c95728f2ecf0f646abdc67c46f2f  ./diff/oak_enclave_unsigned_e66a750eaafcaec35b50ba1df0298f342a8aa8f1_2019-10-14T20:05:25+00:00.so
5d3b12032df2c95728f2ecf0f646abdc67c46f2f  ./diff/oak_enclave_unsigned_e66a750eaafcaec35b50ba1df0298f342a8aa8f1_2019-10-14T20:10:46+00:00.so
```
=> Update Asylo dependency to current HEAD

oak/common/fuzzer.bzl, oak/server/BUILD
This will be replaced in actual fuzzing with something like
https://github.com/google/oss-fuzz/blob/7f8013db108e62727fba1c3cbcccac07d543682b/projects/grpc/build.sh#L33
so that it can depend on a provided fuzzer library.
Ref #261
=> Add shim bazel rule for fuzzer

oak/proto/storage_channel.proto, oak/server/storage/BUILD, oak/server/storage/storage_node.cc, rust/oak/src/proto/storage_channel.rs, rust/oak/src/storage/mod.rs
This is using gRPC to encapsulate request and response messages to and
from the storage node, but not actually using any transport from gRPC
itself.
Essentially it is a DSL that describes how to interact with the storage
node from other nodes, and as such it can rely on code generation to
create type-safe clients from other nodes, and also ensure that the node
implementation conforms to the same interface, rather than using
distinct and unrelated sets of request and response messages.
=> Convert storage API to gRPC

docs/abi.md, docs/sdk.md, examples/abitest/module/rust/src/lib.rs, oak/server/wasm_node.cc, rust/oak/src/grpc/mod.rs, rust/oak/src/lib.rs, rust/oak/src/tests.rs, rust/oak/src/wasm/mod.rs, rust/oak_tests/src/lib.rs
Use u32/u64/usize everywhere (all ABI values are treated as unsigned),
with usize specifically indicating a linear memory address or size
(so any future Wasm64 port would map usize->u64 instead of u32).
=> Clarify sign/size of ABI types

rust/oak/src/storage/mod.rs
The rust-protobuf implementation does not automatically set
Any::type_url.
=> Fix gRPC encapsulated storage operations

oak/client/BUILD, oak/client/application_client.h, oak/client/authorization_bearer_token_metadata.cc, oak/client/authorization_bearer_token_metadata.h, oak/client/policy_metadata.cc, oak/client/policy_metadata.h, oak/common/BUILD, oak/common/nonce_generator.h, oak/common/policy.cc, oak/common/policy.h, oak/proto/BUILD, oak/proto/policy.proto, oak/server/BUILD, oak/server/channel.h, oak/server/module_invocation.cc
This will probably be removed completely in favour of public key
assertions, but for now it lets us try out policies until Asylo supports
cert assertions.
=> Implement authorization bearer token credentials

Dockerfile, WORKSPACE, examples/abitest/client/BUILD, examples/abitest/proto/BUILD, examples/chat/client/BUILD, examples/chat/proto/BUILD, examples/hello_world/client/BUILD, examples/hello_world/module/cpp/BUILD, examples/hello_world/proto/BUILD, examples/machine_learning/client/BUILD, examples/machine_learning/proto/BUILD, examples/private_set_intersection/client/BUILD, examples/private_set_intersection/proto/BUILD, examples/running_average/client/BUILD, examples/running_average/proto/BUILD, examples/rustfmt/client/BUILD, examples/rustfmt/proto/BUILD, examples/utils/BUILD, oak/client/BUILD, oak/common/BUILD, oak/common/fuzzer.bzl, oak/module/BUILD, oak/proto/BUILD, oak/server/BUILD, oak/server/asylo/BUILD, oak/server/dev/BUILD, oak/server/storage/BUILD, scripts/check_formatting, scripts/format, toolchain/BUILD
Fix newly introduced warnings, mostly to do with
https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#native-proto
or similar.
Include WORKSPACE in format checks.
Move `load` lines to the beginning of file, and keep them to one line
each (since there are so many of them now).
=> Use latest version of buildifier

oak/server/rust/BUILD, oak/server/rust/src/asylo_alloc.rs, oak/server/rust/src/lib.rs
This is a thin wrapper around `malloc` / `free` provided by newlib as
part of Asylo.
Fixes #322
=> Implement Rust allocator

.bazelrc, WORKSPACE, cloudbuild.yaml
Also turn off forced errors for sign comparison warnings so Clang
builds still work.
=> Update Asylo dependency to current version

WORKSPACE, oak/server/asylo/BUILD, scripts/print_mrenclave
This change:
- adds a new Bazel build rule, that generates oak_mrenclave.txt file (with a hex string)
- updates Asylo
- adds print_mrenclave script
=> Add MRENCLAVE generation

README.md
Replace with generic badge from https://img.shields.io linking to the
GCB dashboard page (which BTW is currently only accessible to members of
the project Oak team).
Ref #325
=> Remove Travis build badge link

docs/abi.md, oak/common/app_config.cc, oak/common/testdata/channel_dest_missing.textproto, oak/common/testdata/channel_inverted.textproto, oak/common/testdata/channel_source_missing.textproto, oak/common/testdata/default.textproto, oak/common/testdata/dup_node_name.textproto, oak/common/testdata/dup_port.textproto, oak/common/testdata/in_port_empty.textproto, oak/common/testdata/out_port_empty.textproto, oak/common/testdata/storagenode.textproto, oak/common/testdata/two_grpc.textproto, oak/common/testdata/two_log.textproto, oak/proto/manager.proto, oak/server/storage/storage_node.cc, sdk/rust/oak/src/storage/mod.rs
Rather than using a global response channel for the storage
pseudo-Node, instead expect that each request should be accompanied
by a response channel handle.  This is more consistent with how the
gRPC channels currently work, allows for easier parallelizing /
multiplexing, and will ease future changes for dynamic Node creation.
=> storage: pass a response channel with each request

oak/server/wasm_node_fuzzer.cc
Commit edb3a73a8930 ("Add owning-runtime link to Wasm node") changed
the signature of WasmNode::Create, but the fuzzer driver wasn't updated
at the time (and wasn't noticed because CI doesn't build this target).
=> Update fuzzer for new WasmNode::Create signature

third_party/google/rpc/BUILD
This change adds an explicit load of `proto_library` and `cc_proto_library` in `third_party/google/rpc`.
=> Load proto_library in google/rpc

oak/server/node_thread.cc, oak/server/node_thread.h
=> runtime: don't call virtual fn in destructor

third_party/google/rpc/BUILD, third_party/google/rpc/LICENSE
This change adds a `licenses` parameter to `package` in `third_party/google/rpc/BUILD`.
=> Add licence in google/rpc

oak/common/BUILD
This change adds `@com_google_absl//absl/base` in `policy` library, since `policy.h` includes `absl/base/attributes.h`.
=> Add absl/base dependency in policy

oak/client/BUILD, oak/client/sgx_application_client.cc
This change adds an explicit dependency on `asylo/identity/sgx:sgx_identity_cc_proto` to the `sgx_application_client` build target.
=> Add Asylo proto dependency in client

scripts/generate_compilation_database, scripts/run_clang_tidy
This commit changes GCC specific flags in the compilation database to Clang specific ones.
Fixes #362
=> Remove clang-tidy flag warnings

examples/chat/module/rust/src/lib.rs
This avoids having to convert the inner type.
=> Make error functions generic

cloudbuild.yaml, scripts/env_test
This change adds `BAZEL_GOOGLE_CREDENTIALS` environment variable in `cloudbuild` to update Bazel cache after merges.
Fixes #357
=> Update Bazel cache in GCB

docs/programming-oak.md, examples/abitest/module/rust/src/lib.rs, examples/abitest/tests/src/tests.rs, sdk/rust/oak_tests/src/lib.rs
[Lots of little commits for ease of rebasing; not sure whether it's easier to review in one go or commit-by-commit though.]
General aim here is to make the test runtime more suitable for non-test use, by making it more robust.  Many of the changes are of the form:
- Convert `unwrap` to `expect` to make diagnostics better.
- Re-write code that checks an `Option` / `Result` for an early `return` then `unwrap`s to use an inline `match` instead.
(But there's a few other things too.)
=> Minimize use of `unwrap()` in oak_tests

oak/client/authorization_bearer_token_metadata.cc, oak/client/policy_metadata.cc, oak/server/dev/dev_oak_main.cc, oak/server/dev/dev_oak_manager.cc, oak/server/oak_grpc_node.cc, oak/server/storage/memory_provider.cc, oak/server/storage/storage_processor.cc, oak/server/storage/storage_service.cc, oak/server/wasm_node.cc
Comment out unused parameter names where they look like placeholders
that will be used in future, and remove altogether if they don't
look like they will be needed.
For #374.
=> Remove unused function parameter names

oak/server/module_invocation.cc, oak/server/oak_runtime.cc, scripts/run_clang_tidy
This change promotes `clang-tidy` warnings to errors.
Fixes #363
=> Promote clang-tidy warnings to errors

BUILD
This change exports the `LICENSE` file in the root `BUILD`.
=> Export license in BUILD

BUILD, examples/hello_world/client/android/java/com/google/oak/hello_world/MainActivity.java
Reference types that declare an `equals()` method, should not be compared for reference equality with `==` or `!=`.
=> Fix Java equals

oak/server/BUILD, oak/server/base_runtime.h, oak/server/logging_node.h, oak/server/node_thread.cc, oak/server/node_thread.h, oak/server/oak_grpc_node.cc, oak/server/oak_grpc_node.h, oak/server/oak_node.cc, oak/server/oak_node.h, oak/server/oak_runtime.cc, oak/server/oak_runtime.h, oak/server/storage/storage_node.cc, oak/server/storage/storage_node.h, oak/server/wasm_node.cc, oak/server/wasm_node.h
Following up on #417, I realized that having per-Node and per-Runtime termination-pending flags is probably unnecessary.
=> Commonize termination-pending flags

scripts/run_example
Original script mistakenly assumed that `find` emits results in
alphabetical order.
=> scripts: list modules in consistent alpha order

docs/programming-oak.md
Escape the parentheses so the marker stays invisible in the browser.
=> docs: fix visible embedmd markers

examples/abitest/client/abitest.cc
Commit c72de5c58bd6 ("Rename abitest example modules") re-ordered
the modules to be frontend,backend but didn't change the order for
the client's command-line option.
=> examples: fix abitest module ordering

examples/abitest/module_0/rust/src/lib.rs, examples/abitest/module_1/rust/src/lib.rs, examples/chat/module_1/rust/src/lib.rs, sdk/rust/oak/src/grpc/mod.rs, sdk/rust/oak/src/lib.rs, sdk/rust/oak/src/tests.rs, sdk/rust/oak_derive/src/lib.rs, sdk/rust/oak_log/src/tests.rs, sdk/rust/oak_runtime/src/lib.rs, sdk/rust/oak_tests/src/lib.rs, sdk/rust/oak_tests/src/tests.rs
Makes sdk `Handle` an opaque non-serializable type.
- `oak_runtime` keeps the Handle type alias to u64 as specified by the ABI. (This is used for example in `_raw` tests in `oak/examples/abitest/module/...` which are tests directly against the wasm which don't use the sdk)
- Tests updated to use opaque Handle where appropriate.  
#427
=> Make sdk `Handle` an opaque non-serializable type

docs/abi.md, examples/abitest/module_0/rust/src/lib.rs, examples/abitest/module_1/rust/src/lib.rs, oak/proto/oak_api.proto, oak/server/rust/oak_abi/src/proto/oak_api.rs, oak/server/rust/oak_runtime/src/lib.rs, oak/server/wasm_node.cc, sdk/rust/oak/src/io/mod.rs, sdk/rust/oak/src/lib.rs, sdk/rust/oak/src/wasm/mod.rs, sdk/rust/oak_log/src/tests.rs, sdk/rust/oak_tests/src/lib.rs
Previously a Node could not distinguish between a channel_read operation
on an empty channel from one that returned an empty message.
=> runtime: emit CHANNEL_EMPTY for empty channel read

sdk/rust/oak/src/lib.rs
- ~~Also adds missing resize for HANDLE_SPACE_TOO_SMALL~~
#451
=> sdk/oak: Add Handle (un)pack for safe serialization to Wasm host ABI

WORKSPACE, oak/server/time/BUILD, oak/server/time/roughtime_client.cc, oak/server/time/roughtime_client.h, oak/server/time/roughtime_client_test.cc, third_party/roughtime/BUILD, third_party/roughtime/roughtime.BUILD
This is the initial implementation of a roughtime client to provide
trusted time to server components inside an enclave.
=> oak_runtime: add simple roughtime client

oak/common/BUILD, oak/common/app_config.cc, oak/common/app_config.h, oak/common/app_config_serializer.cc, oak/common/app_config_test.cc, oak/common/utils.cc, oak/common/utils.h
This change adds an Oak application configuration serializer
Fixes #412
=> Add application config serializer

examples/tensorflow/module/cpp/BUILD, examples/tensorflow/module/cpp/tensorflow.cc, oak/module/BUILD, oak/module/placeholders.h
This change adds placeholder functions to reduce the amount of Wasm imports from the TensorFlow example, that was built with Emscripten.
Fixes #439
=> Add placeholders for Wasm imports

.rustfmt.toml, sdk/rust/oak_derive/src/lib.rs
Mostly with comment-related settings.
I have re-run `cargo fmt` with these settings, but it does not reflow
comments that are already shorter than the limit, so we may have to do a
separate pass to fix them if we care about it.
=> Add `.rustfmt.toml` configuration file

docs/programming-oak.md, examples/abitest/module_0/rust/src/lib.rs, examples/abitest/module_1/rust/src/lib.rs, examples/abitest/tests/src/tests.rs, examples/chat/common/src/lib.rs, examples/chat/module_0/rust/src/lib.rs, examples/chat/module_1/rust/src/lib.rs, examples/hello_world/module/rust/src/tests.rs, examples/machine_learning/module/rust/src/lib.rs, oak/server/rust/oak_runtime/src/lib.rs, sdk/rust/oak/src/grpc/mod.rs, sdk/rust/oak/src/io/mod.rs, sdk/rust/oak/src/lib.rs, sdk/rust/oak/src/rand/mod.rs, sdk/rust/oak/src/storage/mod.rs, sdk/rust/oak/src/tests.rs, sdk/rust/oak_derive/src/lib.rs, sdk/rust/oak_log/src/lib.rs, sdk/rust/oak_log/src/tests.rs, sdk/rust/oak_tests/src/lib.rs, sdk/rust/oak_tests/src/tests.rs
- Make most SDK functions return a `Result` type so that callers can use
idiomatic error handling
- Fix tests and code to explicitly handle such results; when possible, propagate them up using the `?` operator, otherwise `unwrap` or `expect` them, at least for the time being
- Modify the signature of the `main` function from `pub fn main(in_handle: u64) -> i32` to `pub fn main(in_handle: u64) -> Result<(), oak::OakStatus>`, so that error propagation would work more naturally. Of course this is still converted to `i32` in order to cross the FFI boundary, and this is now performed by a slightly different piece of code in `oak_main` (which is still generated by `OakExports`).
- `oak_tests` was modified slightly, and now it is slightly more complicated, because it expects to be able to find …
=> Improve error handling in Oak SDK crate

sdk/rust/oak/src/lib.rs
Code is inspired by the default panic hook.
https://github.com/rust-lang/rust/blob/7d761fe0462ba0f671a237d0bb35e3579b8ba0e8/src/libstd/panicking.rs#L171-L177
=> Support additional panic hook payload types

examples/chat/common/src/command.rs, sdk/rust/oak/src/io/decodable.rs, sdk/rust/oak/src/io/encodable.rs, sdk/rust/oak/src/io/mod.rs, sdk/rust/oak/src/io/receiver.rs, sdk/rust/oak/src/io/sender.rs
This will be needed as part of #488 when implementing a node routing
messages based on policies.
construction.
=> Replace tuple with named struct for `oak::io`

examples/abitest/module_0/rust/Cargo.toml, examples/abitest/module_1/rust/Cargo.toml, examples/abitest/tests/Cargo.toml, examples/chat/common/Cargo.toml, examples/chat/module_0/rust/Cargo.toml, examples/chat/module_1/rust/Cargo.toml, examples/hello_world/module/rust/Cargo.toml, examples/machine_learning/module/rust/Cargo.toml, examples/private_set_intersection/module/rust/Cargo.toml, examples/running_average/module/rust/Cargo.toml, examples/rustfmt/module/rust/Cargo.toml, oak/server/rust/oak_runtime/Cargo.toml, sdk/rust/oak_derive/Cargo.toml, sdk/rust/oak_log/Cargo.toml, sdk/rust/oak_tests/Cargo.toml
This change adds `=0.1.0` oak version to `Cargo.toml` files to remove intersection with existing `oak` crate on `crates.io`.
Fixes #477
=> Cargo update ambiguous version fix

oak/server/rust/oak_runtime/src/lib.rs, runner/src/main.rs, scripts/check_formatting, scripts/format, scripts/run_tests
For some reason doc tests are excluded by `--all-targets`, so we need a
separate `cargo test` run for them.
construction.
=> Run cargo doc tests

Dockerfile, WORKSPACE
This change:
- Updates Asylo to v0.5.2
- Updates Dockerfile
- Adds an explicit dependency on `rules_cc`
- Updated `Protobuf version to v3.11.2
Fixes https://github.com/google/asylo/issues/58
=> Update Asylo to 0.5.2

examples/chat/module_0/rust/src/lib.rs, examples/private_set_intersection/module/rust/src/lib.rs, examples/running_average/module/rust/src/lib.rs, examples/rustfmt/module/rust/src/lib.rs, sdk/rust/oak_derive/src/lib.rs
In order to avoid ambiguities. Also, `warn` was not fully qualified
previously, which means that it had to be manually imported in the
parent scope.
Also reformat the expanded code.
construction.
=> Use absolute paths in `oak_derive` expansion

third_party/expect/src/lib.rs
=> expect: use fully-qualified names in macro

docs/abi.md, docs/concepts.md, examples/hello_world/module/cpp/hello_world.cc, oak/server/module_invocation.cc, oak/server/module_invocation.h, oak/server/rust/oak_runtime/src/lib.rs, sdk/rust/oak/src/grpc/mod.rs, sdk/rust/oak_tests/src/lib.rs
=> Encapsulate gRPC requests in a separate per-method invocation channel

docs/abi.md, docs/sdk.md
I believe this is the current runtime behaviour, specifically `wait_on_channels` won't return failure if one of the handles is invalid, it will instead set the corresponding status byte to a bad handle status. 
construction.
=> Minor doc clarifications

third_party/grpc-rust/protoc-rust-grpc/Cargo.toml, third_party/grpc-rust/protoc-rust-grpc/src/lib.rs
construction.
Updates protoc-rust-grpc from upstream. The relaxed bounds prevent building examples generating protoc v2.8 code. Related #520
=> protoc-rust-grpc: update from upstream

examples/chat/module/rust/src/backend.rs, oak/server/rust/oak_runtime/src/lib.rs, sdk/rust/oak/src/grpc/invocation.rs, sdk/rust/oak/src/grpc/mod.rs, sdk/rust/oak_tests/src/lib.rs
- Encapsulate a request receiver and a response sender into a single
object which implements `Encodable` and `Decodable`.
- Add `#[must_use]` to a couple places where return status codes were
not checked. We should probably consider using `Result` types
everywhere.
Fixes #528
construction.
=> Define gRPC Invocation in Rust SDK

examples/tensorflow/client/tensorflow.cc, examples/tensorflow/module/cpp/tensorflow.cc, examples/tensorflow/module/cpp/tensorflow_micro.cc, oak/server/wasm_node.cc, oak/server/wasm_node.h
This change:
- Adds a WASI placeholder in order to run TensorFlow Lite example in Oak
- Update TensorFlow Lite example `main` functions
construction.
=> Add a WASI placeholder

examples/abitest/module_0/rust/src/proto/abitest_grpc.rs, examples/chat/module/rust/src/proto/chat_grpc.rs, examples/hello_world/module/rust/src/proto/hello_world_grpc.rs, examples/private_set_intersection/module/rust/src/proto/private_set_intersection_grpc.rs, examples/running_average/module/rust/src/proto/running_average_grpc.rs, examples/rustfmt/module/rust/src/proto/rustfmt_grpc.rs, third_party/grpc-rust/grpc-compiler/src/codegen.rs
=> Rely on static dispatch for gRPC nodes

oak/client/BUILD, oak/client/application_client.h, oak/common/BUILD, oak/common/hmac.cc, oak/common/hmac.h, oak/common/hmac_test.cc, oak/common/policy.cc, oak/proto/policy.proto, sdk/rust/oak/src/proto/policy.rs
The previous implementation used the actual (secret) token as both the
policy and the authentication mechanism.
This commit makes it so that the policy only uses a (public) HMAC
derived from the token, so that the actual (secret) token is only used
for actual authentication.
Ref #488
construction.
=> Implement bearer token authentication using HMAC

sdk/rust/oak/src/grpc/mod.rs, sdk/rust/oak/src/io/decodable.rs, sdk/rust/oak/src/io/encodable.rs
Allow any protobuf message to be encoded and decoded as bytes + handles,
where handles are always empty.
Also validate that incoming handles are indeed empty when decoding, and
return an error if that's not the case.
construction.
=> Provide blanket implementation for protobuf

examples/Cargo.lock, examples/chat/module/rust/Cargo.toml, examples/chat/module/rust/build.rs, examples/translator/common/Cargo.toml, examples/translator/common/build.rs, examples/translator/module/rust/Cargo.toml
We should find a way of enforcing that we always use `oak_utils`
wrappers instead of the underlying `grpc` functions.
See #510
construction.
=> Use `oak_utils` wrapper for protobuf generation

scripts/check_formatting, scripts/format
This change excludes `.git` directory from formatting checks.
construction.
=> Fix format scripts

oak/server/dev/dev_oak_main.cc
This change:
- Deletes an unnecessary signal handler from `server_dev`
- Updates includes
Done after the following comment: https://github.com/project-oak/oak/pull/553#discussion_r375389045
construction.
=> Delete signal handler from `server_dev`

oak/common/app_config.bzl, oak/common/app_config.cc, oak/common/app_config_serializer.cc
This change adds a Bazel rule for creating a serialized config binary.
Necessary for #462
construction.
=> Add a `serialized_config` Bazel rule

third_party/rust/BUILD, third_party/rust/src/libstd/BUILD
This change adds a `default_visibility` argument to `third_party/rust/*/BUILD` files. 
This argument was added because the `rust_library` rule doesn't have a `visibility` argument:
https://github.com/bazelbuild/rules_rust/blob/master/docs/index.md#rust_library
construction.
=> Add `default_visibility` to `third_party/rust`

third_party/wabt/BUILD, third_party/wabt/LICENSE, third_party/wabt/wabt.BUILD
This change adds a `LICENSE` file to a `third_party/wabt/` directory.
The `LICENSE` was taken from https://github.com/WebAssembly/wabt/blob/master/LICENSE
construction.
=> Add WABT license

docs/programming-oak.md, examples/abitest/module_0/rust/src/lib.rs, examples/chat/module/rust/src/backend.rs, examples/translator/module/rust/src/lib.rs, sdk/rust/oak/src/grpc/mod.rs, sdk/rust/oak/src/lib.rs, sdk/rust/oak_derive/src/lib.rs
Provide blanket implementation of it for gRPC server nodes.
Change code generated by `oak_derive` crate to depend only on the `Node`
trait, instead of being tied to gRPC.
construction.
=> Introduce generic Node trait

oak/server/rust/oak_runtime/src/node/mod.rs, oak/server/rust/oak_runtime/src/runtime.rs
=> oak_runtime: Return a `Result` from load_wasm

docs/programming-oak.md, examples/Cargo.lock, examples/abitest/tests/src/tests.rs, examples/hello_world/module/rust/src/tests.rs, scripts/run_tests, sdk/rust/Cargo.lock, sdk/rust/oak_tests/Cargo.toml, sdk/rust/oak_tests/src/lib.rs
Removes hard coded Wasm paths in abitest & hello_world, and builds the Wasm modules during test invocation. 
The Wasm files are outputted to a temporary directory and cargo doesn't seem to use artefacts from the host target dir so this does currently cause the tests to do a full rebuild of their Wasm files. 
construction.
#541
=> Remove hard coded Wasm paths in abitest & hello_world

oak/common/app_config.bzl
Use different `name` for `genrule` in `app_config.bzl`.
construction.
=> Fix name duplication in `app_config` Bazel rule

Dockerfile, scripts/build_gh_pages
Remove diff logic so that it can be run at any commit and just push the
latest version, even if it causes extra diffs because of the
non-determinism. Incidentally, it seems to be deterministic on my
machine (but maybe it's just because generated docs are cached).
Add generation of index.html file.
Use a temporary directory to stage the output of the generation process.
construction.
=> Tweak build_gh_pages script

Dockerfile, WORKSPACE, examples/Cargo.lock, examples/rustfmt/module/rust/src/lib.rs, oak/server/rust/oak_runtime/src/channel.rs, oak/server/rust/oak_runtime/src/lib.rs, scripts/run_examples, scripts/run_examples_dev, third_party/grpc-rust/grpc-compiler/src/codegen.rs
- Updates rust in Dockerfile
- updates packages as necessary
- fixes new clippy errors
Similar to #443 but slightly newer nightly (with full component set) and fixes to pass tests
edit: due to [this rustc ICE](https://github.com/rust-lang/rust/issues/64450) rustfmt example has to be disabled temporarily (`grep -v rustfmt` in run_examples) 
construction.
=> Update Rust version

oak/common/app_config_serializer.cc, oak/common/policy.h
This change:
- Deletes a redundant `get()` call from `app_config_serializer.cc`
- Use same argument names in `policy.h` and `policy.cc`
construction.
=> Use same argument names in `policy.h` and `policy.cc`

examples/Cargo.lock, examples/Cargo.toml
Commit d362ebd84172 ("Update Rust version (#588)") upgraded the
'dirs' (2.0.1->2.0.2) and 'term' (0.5.2->0.6.1) dependencies so
the pins to particular commits are no longer needed.
=> examples: drop specific-commit deps for dirs/term

examples/chat/client/chat.cc, scripts/run_examples, scripts/run_examples_dev
This change:
- Adds a non-interactive version of Chat application with `--test` flag
- Enables Chat application in `run_examples`
construction.
=> Add a `--test` flag to chat

examples/Cargo.lock, sdk/rust/Cargo.lock, sdk/rust/oak_tests/Cargo.toml, sdk/rust/oak_tests/src/lib.rs
Instead parse the json output of `cargo metadata` for the workspace target directory. 
#601
construction.
=> Don't use temp dir when rebuilding Wasm files

oak/server/rust/oak_runtime/src/channel.rs, oak/server/rust/oak_runtime/src/lib.rs, oak/server/rust/oak_runtime/src/node/logger.rs, oak/server/rust/oak_runtime/src/runtime.rs
This uses thread park/unpark instead of other options. 
Related #288 #593 
construction.
=> rust/oak_runtime: Perform blocking channel waits instead of spinning

scripts/build_gh_pages
After #613 there is now a single Cargo workspace, so the script needs to
be changed to deal with that.
Note that this now also generates docs for example crates.
Ref. #534
construction.
=> Fix build_gh_pages script

docs/programming-oak.md, docs/sdk.md
=> Fix links to Rust documentation

runner/src/internal.rs, runner/src/main.rs
The downside is that it now requires all the steps to have finished
before printing anything at all, which makes it hard to figure out at
what point of the overall execution it is.
On the other hand this will make it easier to support future-based
return value in the future, at which point we will reimplement the
streaming-line output functionality.
construction.
=> Support structured output in runner script

runner/src/internal.rs, runner/src/main.rs
Return a set of statuses from each combined step (including top-level)
so that it is possible to have an overview of the various steps.
Sample output:
```
➡ root ➡ prettier ➡ ./docs/development.md ⊢ OK
➡ root ➡ prettier ➡ ./INSTALL.md ⊢ OK
➡ root ➡ prettier ➡ ./README.md ⊢ OK
➡ root ➡ prettier } ⊢ [OK]
➡ root ➡ embedmd {
➡ root ➡ embedmd ➡ ./examples/chat/README.md ⊢ OK
➡ root ➡ embedmd ➡ ./PULL_REQUEST_TEMPLATE.md ⊢ OK
➡ root ➡ embedmd ➡ ./CONTRIBUTING.md ⊢ OK
➡ root ➡ embedmd ➡ ./docs/abi.md ⊢ OK
➡ root ➡ embedmd ➡ ./docs/concepts.md ⊢ OK
➡ root ➡ embedmd ➡ ./docs/programming-oak.md ⊢ ERROR
➡ root ➡ embedmd ➡ ./docs/programming-oak.md ╔════════════════════════
➡ root ➡ embedmd ➡ ./docs/programming-oak.md ║
➡ root ➡ embedmd ➡ ./docs/programming-oak.md ║ @@ -405,7 +405,7 @@
➡ root ➡ …
```
=> Return exit code from runner

Dockerfile, cloudbuild.yaml, runner/src/main.rs, scripts/build_example, scripts/check_formatting, scripts/common, scripts/format
Reduces CI build time from ~35 minutes to ~21 minutes (see
https://pantheon.corp.google.com/cloud-build/builds?project=oak-ci).
Some of the build steps may be run in parallel; the main rule of thumb
is that they can if they don't share the same Bazel `output_base`,
because otherwise they would contend for the same lock.
Ensure that Bazel caching for wasm32 and emscripten works properly.
Ensure that Bazel is properly initialized in the Dockerfile.
Reorder steps in Dockerfile so that less frequently changed steps appear
first (namely, Emscripten, which is also quite large).
Fix various other minor things in the Dockerfile (env variables).
construction.
=> Parallelize build steps

examples/hello_world/client/hello_world.cc, examples/hello_world/module/rust/src/lib.rs, oak/server/module_invocation.cc
Fix error propagation and add a check to catch future regression.
construction.
=> Fix gRPC error propagation

oak/server/rust/oak_abi/Cargo.toml, oak/server/rust/oak_abi/src/lib.rs, oak/server/rust/oak_runtime/Cargo.toml
This is a temporary fix to allow oak_abi `no_std` compilation. See #638, a follow up PR will be done to resolve this long term. I would like to add this as a temporary fix as it blocks work on making the oak_runtime `no_std` compatible. 
construction.
=> rust/oak_abi: Make oak_abi

examples/aggregator/module/rust/src/lib.rs, examples/aggregator/module/rust/src/proto/aggregator_grpc.rs
This change fixes build Aggregator failure with the new gRPC dispatcher architecture.
construction.
=> Aggregator grpc dispatcher fix

scripts/build_examples
Example `rustfmt` was disabled in `run_examples` and `run_tests` in #588. It seems `build_examples` has been broken since then (e.g. CI uses `run_examples` which doesn't use `build_examples`).
construction.
=> Disable rustfmt example in scripts/build_examples

Cargo.lock, Cargo.toml, experimental/split_grpc/client/Cargo.toml, experimental/split_grpc/proxy/Cargo.toml, experimental/split_grpc/proxy/src/main.rs, experimental/split_grpc/server/Cargo.toml, experimental/split_grpc/server/src/main.rs
This initial version of the proxy makes a new TCP connection to the server for each incoming request from the client and copies the bytes directly. 
This is just a test to ensure that the TLS still works when the connections are being proxied before implementing a UDS-based proxy as described in #627.
construction.
=> Implement naive proxy using new TCP connections

examples/abitest/tests/src/tests.rs, oak/server/rust/oak_runtime/src/config.rs, oak/server/rust/oak_runtime/src/lib.rs, oak/server/rust/oak_runtime/src/node/mod.rs, oak/server/rust/oak_runtime/src/runtime.rs, sdk/rust/oak_tests/src/lib.rs
Feature gate protobuf configuration behind `std` feature flag. This will allow configurations to be passed to a `no_std` variant directly without requiring protobuf. (Presumably the configuration will still be loaded from a protobuf definition and passed into the no_std variant.) 
construction.
=> oak_runtime: Gate protobuf configuration with `std` feature

experimental/split_grpc/client/build.rs, experimental/split_grpc/server/build.rs
=> Rerun build.rs only if proto file changed

.bazelrc, oak/server/asylo/BUILD, oak/server/asylo/asylo_oak_runner_main.cc
For the Asylo runner, attempt to show a backtrace on signals
that indicate a crash (if --debug=true is set, which is the
default).
Shift the Asylo build to always include debug symbols.
construction.
=> runtime: show backtrace on crash

Cargo.lock, oak/server/rust/oak_abi/Cargo.toml, oak/server/rust/oak_abi/build.rs, oak/server/rust/oak_abi/src/label.rs, oak/server/rust/oak_abi/src/lib.rs, oak/server/rust/oak_abi/src/proto.rs
Not used yet, but as a starting point for future functionality.
It is in the ABI because it will be used by both the runtime and the
SDK.
Ref #630
construction.
=> Introduce label lattice definition in Oak ABI

scripts/run_example, scripts/run_examples
This change returns `TSAN_OPTIONS` to `run_example` script.
Adding to `run_example` instead of `run_examples`, so this variable will be set while running a single example (e.g. `abitest`).
Fixes #681
construction.
=> Return TSAN_OPTIONS

docs/programming-oak.md, examples/abitest/tests/src/tests.rs, examples/aggregator/module/rust/src/tests.rs, examples/hello_world/module/rust/src/tests.rs, examples/private_set_intersection/module/rust/src/tests.rs, examples/running_average/module/rust/src/tests.rs, examples/translator/module/rust/src/tests.rs, oak/server/rust/oak_runtime/src/config.rs, oak/server/rust/oak_runtime/src/lib.rs, oak/server/rust/oak_runtime/src/message.rs, oak/server/rust/oak_runtime/src/node/logger.rs, oak/server/rust/oak_runtime/src/node/mod.rs, oak/server/rust/oak_runtime/src/node/wasm.rs, oak/server/rust/oak_runtime/src/runtime.rs, oak/server/rust/oak_runtime/src/runtime/channel.rs, sdk/rust/oak_tests/src/lib.rs
Channel reading/writing/status methods are moved to the runtime, and so all channel calls go through the runtime.
A more incremental approach to #648. This still allows flexibility to move to a different ownership model. 
construction.
=> oak_runtime: Move channel ownership to runtime

oak/server/BUILD, oak/server/channel.cc, oak/server/channel.h, oak/server/notification.cc, oak/server/notification.h, oak/server/notification_test.cc, oak/server/oak_node.cc
=> Avoid polling in C++ runtime

oak/server/rust/oak_runtime/Cargo.toml, oak/server/rust/oak_runtime/src/lib.rs, oak/server/rust/oak_runtime/src/node/mod.rs, oak/server/rust/oak_runtime/src/runtime/mod.rs
=> oak_runtime: Track Nodes with u64 NodeRefs

scripts/run_example
This change allows `run_example` script to stop server even if client returned an error (adds an `exit-trap`).
Fixes #677
construction.
=> Fix runner hanging

examples/abitest/module_0/rust/src/lib.rs, oak/server/rust/oak_runtime/build.rs, oak/server/rust/oak_runtime/src/node/logger.rs, oak/server/rust/oak_runtime/src/proto.rs
* Uses LogMessage protobuf for logging in `rust/oak_runtime`
construction.
=> Use LogMessage in logger in `rust/oak_runtime`

oak/server/rust/oak_abi/src/label.rs, oak/server/rust/oak_abi/src/lib.rs, oak/server/rust/oak_runtime/src/node/wasm.rs, oak/server/rust/oak_runtime/src/runtime/mod.rs
This is not part of the Wasm ABI yet, just part of the implementation of
the Rust oak_runtime, but not used for information flow yet.
Unify Label trait and struct in oak_abi (there is no strong reason for
the separation at this point, though we may want to reintroduce it in
the future).
Rename `Label::can_flow_to` to `Label::flows_to` in accordance with
literature.
Add various missing doc links.
Ref #603
construction.
=> Introduce label parameter to `Runtime::node_create` 

WORKSPACE, oak/server/storage/BUILD, oak/server/storage/storage_node.cc, oak/server/storage/storage_processor.cc
Drop dependency on the Asylo wrappers for BoringSSL's AEAD
functionality.
construction.
=> runtime/storage: use BoringSSL directly

oak/server/rust/oak_runtime/src/node/wasm.rs, oak/server/rust/oak_runtime/src/runtime/channel.rs, oak/server/rust/oak_runtime/src/runtime/mod.rs, sdk/rust/oak_tests/src/lib.rs
Will be used for enforcing Information Flow between Nodes and Channels
as part of #630.
Ref #603
construction.
=> Add label field to Channel struct

oak/server/rust/oak_runtime/src/config.rs, oak/server/rust/oak_runtime/src/node/logger.rs, oak/server/rust/oak_runtime/src/node/mod.rs, oak/server/rust/oak_runtime/src/node/wasm.rs, oak/server/rust/oak_runtime/src/runtime/channel.rs, oak/server/rust/oak_runtime/src/runtime/mod.rs
Have Log and Wasm nodes implement it.
Add a simple test for the Wasm node.
=> Define base `Node` trait

oak/server/BUILD, oak/server/channel.cc, oak/server/channel.h, oak/server/channel_test.cc, oak/server/grpc_client_node.cc, oak/server/grpc_client_node.h, oak/server/handle_closer.h, oak/server/invocation.cc, oak/server/invocation.h, oak/server/logging_node.cc, oak/server/module_invocation.cc, oak/server/module_invocation.h, oak/server/node_thread.cc, oak/server/node_thread.h, oak/server/oak_grpc_node.cc, oak/server/oak_grpc_node.h, oak/server/oak_node.cc, oak/server/oak_node.h, oak/server/oak_runtime.cc, oak/server/oak_runtime.h, oak/server/storage/BUILD, oak/server/storage/storage_node.cc, oak/server/wasm_node.cc
=> Make pseudo-Nodes use Handles not raw channel references

sdk/rust/oak_tests/src/lib.rs
=> oak_tests: Don't pass RUSTFLAGS to `compile_rust_wasm`

oak/server/rust/oak_runtime/src/runtime/channel.rs, oak/server/rust/oak_runtime/src/runtime/mod.rs
See #780. Note this can be checked with 
- `RUSTFLAGS="-Z sanitizer=thread" cargo -Zbuild-std test --manifest-path=./examples/abitest/tests/Cargo.toml --target x86_64-unknown-linux-gnu -- --nocapture` 
(Note I believe`-Zbuild-std`, to instrument the standard library, is required).
- With a nightly compiler newer than 2020.03.19
construction.
=> rust oak_runtime: Fix any possible lock inversion issues

examples/abitest/module_0/rust/src/proto/abitest_grpc.rs, examples/aggregator/module/rust/src/proto/aggregator_grpc.rs, examples/chat/module/rust/src/proto/chat_grpc.rs, examples/hello_world/module/rust/src/proto/hello_world_grpc.rs, examples/private_set_intersection/module/rust/src/proto/private_set_intersection_grpc.rs, examples/running_average/module/rust/src/proto/running_average_grpc.rs, examples/rustfmt/module/rust/src/proto/rustfmt_grpc.rs, examples/translator/common/src/proto/translator_grpc.rs, third_party/grpc-rust/grpc-compiler/src/codegen.rs
Updates grpc codegen to log an error instead of panicking when trying to invoke an unknown method.
Fixes #726 
construction.
=> Replace panic! with error! in grpc-codegen (#762)

Cargo.lock, oak/server/rust/oak_runtime/Cargo.toml, oak/server/rust/oak_runtime/src/node/wasm.rs, oak/server/rust/oak_runtime/src/runtime/mod.rs
Adds unit-tests for the Rust wasm node, similar to those for the cpp wasm node.
- Since the Rust WasmNode takes a wasmi::Module as input (instead of a string as in cpp WasmNode), some scenarios in https://github.com/project-oak/oak/blob/master/oak/server/wasm_node_test.cc are not relevant here. In particular:
- Empty string
- Module with wrong version
- wat is used instead of wabt, since it is implemented completely in Rust.
Fixes #726
construction.
=> Add unit tests for Rust wasm node (#726)

examples/aggregator/module/rust/src/tests.rs, examples/running_average/module/rust/src/tests.rs, oak/server/rust/oak_runtime/src/config.rs, oak/server/rust/oak_runtime/src/lib.rs, oak/server/rust/oak_runtime/src/node/logger.rs, oak/server/rust/oak_runtime/src/node/mod.rs, oak/server/rust/oak_runtime/src/node/wasm.rs, oak/server/rust/oak_runtime/src/runtime/mod.rs, sdk/rust/oak_tests/src/lib.rs
Instead define methods on `Arc<Self>` receiver when necessary.
Ref #630
construction.
=> Remove `RuntimeRef` object

oak/server/rust/oak_runtime/src/node/mod.rs, oak/server/rust/oak_runtime/src/runtime/mod.rs
This also allows to write tests for the newly created
`node_start_instance` function, extracted from `node_create`.
Fixes #788
construction.
=> Split node initialization and start

oak/server/rust/oak_runtime/src/node/logger.rs, oak/server/rust/oak_runtime/src/node/mod.rs, oak/server/rust/oak_runtime/src/node/wasm.rs, oak/server/rust/oak_runtime/src/runtime/mod.rs
This allows to define a clear ABI that node and pseudo-node
implementations in Rust have access to.
Ref #630
construction.
=> Introduce `RuntimeProxy` type

oak/server/rust/oak_runtime/src/lib.rs, oak/server/rust/oak_runtime/src/node/logger.rs, oak/server/rust/oak_runtime/src/node/wasm.rs, oak/server/rust/oak_runtime/src/runtime/mod.rs
Using named threads should help identifying threads during debugging.
https://doc.rust-lang.org/std/thread/struct.Builder.html#method.name
Example log:
2020-03-31 13:49:42,080 DEBUG [oak_runtime::runtime] wait_on_channels: \
thread Thread { id: ThreadId(4), name: Some("node_logger=log") } re-woken
2020-03-31 13:49:42,080 DEBUG [oak_runtime::runtime] wait_on_channels: \
thread Thread { id: ThreadId(3), name: Some("node=translator") } re-woken
Before it would show: Thread { id: ThreadId(4), name: None }
Fixes #770
construction.
=> Use named threads for nodes and loggers

oak/server/rust/oak_runtime/src/runtime/channel.rs, oak/server/rust/oak_runtime/src/runtime/mod.rs
=> Reduce scope and number of locks in Rust runtime

docs/abi.md, oak/proto/oak_api.proto, oak/server/rust/oak_abi/src/label.rs, oak/server/rust/oak_runtime/src/runtime/channel.rs, oak/server/rust/oak_runtime/src/runtime/mod.rs, sdk/rust/oak/src/io/mod.rs
Introduce a new `ERR_PERMISSION_DENIED` value for `OakStatus` to
indicate information flow violations.
Add test infrastructure and various tests to confirm this is working.
Ref. #630
=> Check labels when operating on channels

oak/server/rust/oak_runtime/src/config.rs, oak/server/rust/oak_runtime/src/runtime/mod.rs
This was removed in 99b7d31c
construction.
=> Cleanup remaining references to `RuntimeRef`

oak/server/storage/storage_node.cc
The prost protobuf library does not support message descriptors, so
encapsulated Any messages from Nodes cannot fill in the type_url
field.  However, the C++ protobuf library code that unpacks an Any
message into a specific protobuf message type requires this field
to be present and match.
Work around this by assuming that storage requests are of the correct
type, and modify the Any message to set its type_url field
appropriately.
construction.
=> runtime: set type_url for storage Any requests

Cargo.lock, docs/abi.md, examples/abitest/module_0/rust/src/lib.rs, oak/proto/BUILD, oak/proto/grpc_encap.proto, oak/proto/storage_service.proto, oak/server/grpc_client_node.cc, oak/server/module_invocation.cc, oak/server/rust/oak_abi/Cargo.toml, oak/server/rust/oak_abi/build.rs, oak/server/rust/oak_abi/src/grpc/mod.rs, oak/server/rust/oak_abi/src/label/mod.rs, oak/server/rust/oak_abi/src/lib.rs, oak/server/rust/oak_abi/src/proto.rs, oak/server/rust/oak_runtime/Cargo.toml, oak/server/rust/oak_runtime/build.rs, oak/server/rust/oak_runtime/src/node/grpc_server.rs, oak/server/rust/oak_runtime/src/node/logger.rs, oak/server/rust/oak_runtime/src/proto.rs, oak/server/storage/BUILD, oak/server/storage/storage_node.cc, oak/server/storage/storage_node.h, sdk/rust/oak/build.rs, sdk/rust/oak/src/grpc/invocation.rs, sdk/rust/oak/src/grpc/mod.rs, sdk/rust/oak/src/lib.rs, sdk/rust/oak/src/logger/mod.rs, sdk/rust/oak/src/storage/mod.rs, sdk/rust/oak_tests/src/lib.rs
Protocol buffer messages that are exchanged in serialized form between
Wasm Nodes and Oak-provided pseudo-Nodes are effectively part of the
Oak ABI, so move the generated code for them into the oak_abi crate.
This allows us to remove the oak_runtime->oak dependency that was
introduced by #772.
Along the way, put the gRPC encapsulation protobuf messages into an
`encap` submodule/namespace.
Fixes #764.
construction.
=> Move generated protos into oak_abi

examples/abitest/module_0/rust/src/lib.rs, oak/proto/BUILD, oak/proto/grpc_encap.proto, oak/server/grpc_client_node.cc, oak/server/module_invocation.cc, oak/server/rust/oak_abi/src/grpc/mod.rs, oak/server/rust/oak_runtime/src/node/grpc_server.rs, oak/server/storage/storage_node.cc, sdk/rust/oak/src/grpc/mod.rs, sdk/rust/oak_tests/src/lib.rs, sdk/rust/oak_utils/src/lib.rs
This will also be useful for #819
=> Use bytes to represent gRPC message body

docs/programming-oak.md
The documentation was still mentioning the old rust-protobuf based code
generation.
construction.
=> update grpc code generation documentation (#829)

oak/server/grpc_client_node.cc, oak/server/grpc_client_node.h, oak/server/loader/oak_runner_main.cc, oak/server/logging_node.h, oak/server/node_thread.h, oak/server/oak_grpc_node.cc, oak/server/oak_grpc_node.h, oak/server/oak_node.h, oak/server/oak_runtime.cc, oak/server/oak_runtime.h, oak/server/rust/oak_runtime/Cargo.toml, oak/server/rust/oak_runtime/src/node/wasm/mod.rs, oak/server/storage/storage_node.cc, oak/server/storage/storage_node.h, oak/server/wasm_node.cc, oak/server/wasm_node.h, oak/server/wasm_node_test.cc
This PR has the preparatory commits of #801 to reduce the (large) amount of merging that's going to be needed for that PR.
construction.
=> Preparatory commits from #801

cloudbuild.yaml, scripts/build_gh_pages, scripts/check_docs
* Added generate_docs to cloudbuild to check generation of doc
* Moved check_formatting towards the end of cloudbuild
Fixes #810 
construction.
=> Add CI step for documentations

oak/server/rust/oak_runtime/src/runtime/mod.rs
This just forwards to `Runtime::stop`, but it ensures that the
appropriate cleanup is performed when `Runtime` gets out of scope, which
should make it more likely that we would catch any issues in tests.
=> Implement `Drop` for `Runtime`

Cargo.lock, docs/abi.md, docs/concepts.md, docs/sdk.md, examples/abitest/config/config.textproto, examples/abitest/module_0/rust/Cargo.toml, examples/abitest/module_0/rust/src/lib.rs, examples/abitest/tests/src/tests.rs, oak/proto/BUILD, oak/proto/application.proto, oak/proto/roughtime_service.proto, oak/server/BUILD, oak/server/oak_runtime.cc, oak/server/oak_runtime.h, oak/server/roughtime_client_node.cc, oak/server/roughtime_client_node.h, oak/server/rust/oak_runtime/src/proto/oak.rs, oak/server/time/roughtime_client.cc, oak/server/time/roughtime_client.h, oak/server/time/roughtime_client_test.cc, oak/server/time/roughtime_util.cc, oak/server/time/roughtime_util.h, sdk/rust/oak/build.rs, sdk/rust/oak/src/lib.rs, sdk/rust/oak/src/roughtime/mod.rs
=> Add Roughtime client pseudo-Node

docs/abi.md, examples/abitest/module_0/rust/src/lib.rs, oak/server/rust/oak_abi/src/lib.rs, oak/server/rust/oak_runtime/src/node/wasm/mod.rs, oak/server/rust/oak_runtime/src/node/wasm/tests.rs, sdk/rust/oak/src/lib.rs
=> Allow passing label to `node_create`

scripts/check_docs
=> Add printing of warnings from `cargo doc`

oak/server/rust/oak_runtime/src/node/external.rs, oak/server/rust/oak_runtime/src/node/grpc_server.rs, oak/server/rust/oak_runtime/src/node/logger.rs, oak/server/rust/oak_runtime/src/node/mod.rs, oak/server/rust/oak_runtime/src/node/wasm/mod.rs, oak/server/rust/oak_runtime/src/node/wasm/tests.rs, oak/server/rust/oak_runtime/src/runtime/mod.rs, oak/server/rust/oak_runtime/src/runtime/tests.rs, scripts/check_docs
Each node now just returns a JoinHandle to a main thread, and the main
thread is encapsulated in a separate method, in which the node itself is
moved, instead of having to clone all the fields from the parent node.
=> Simplify node thread creation and management

cloudbuild.yaml, reproducibility_index, scripts/build_reproducibility_index
Also add a cloud build step to build the Rust oak_loader binary.
Unfortunately, the artifacts are not actually reproducibly buildable
right now, so we cannot enforce this yet, but I'm checking in the
generated file that I get on my machine, which seems to differ between
my machine and GCP.
When we figure out the source of the discrepancy, then we can enforce
that the hashes are actually checked in when changes are made to the
source.
Ref #861
=> Add script to generate reproducibility index file

.cargo/config
Partly addresses #862 (it looks like there are some other
non-deterministic diffs unrelated to this)
construction.
=> Disable build-id link-time generation

.github/workflows/build_rust_docs.yaml, scripts/build_gh_pages, scripts/docker_run
This is not feasible on GCP because we don't have a way of
authenticating only post-merge workflows.
GitHub actions instead get provisioned with a read-only token for pull
requests, and with a read + write token for merge.
=> Use GitHub actions to build and publish Rust docs 

Dockerfile, docs/INSTALL-OSX.md, scripts/build_server, scripts/run_server
Relies on the `x86_64-unknown-linux-musl` build target to produce a
fully static binary.
construction.
=> Produce statically linked `oak_loader` binary

Dockerfile
This change adds `musl-tools` package to the `Dockerfile`.
`musl-tools` contains `musl-gcc` that is necessary to compile `ring` (that is a `rustls` dependency) with a `--target=x86_64-unknown-linux-musl` flag.
construction.
=> Add `musl-tools`

examples/abitest/module_0/rust/src/lib.rs, examples/chat/module/rust/src/lib.rs, examples/hello_world/module/rust/src/lib.rs, examples/machine_learning/module/rust/src/lib.rs, sdk/rust/oak/src/grpc/mod.rs
=> sdk: grpc::ChannelResponseWriter doesn't need mut

oak/server/rust/oak_glue/src/lib.rs, oak/server/rust/oak_runtime/src/node/grpc_server.rs, oak/server/rust/oak_runtime/src/node/logger.rs, oak/server/rust/oak_runtime/src/node/wasm/mod.rs, oak/server/rust/oak_runtime/src/runtime/mod.rs
As independent commits so things can be easily dropped if needed.
construction.
=> Rust runtime tidy-ups

.hadolint.yaml, Dockerfile, android.Dockerfile, docs/INSTALL-OSX.md, scripts/check_formatting
See https://github.com/hadolint/hadolint
Fix various issues brought up by hadolint, plus extra ones.
- update base image to a more recent one
- use consistent naming for `ARG` (lowercase)
- use `curl` instead of `wget`
- move `&&` continuations to new line
- clear apt cache after install commands
- set PIPEFAIL option
=> Lint Dockerfile using Hadolint

reproducibility_index
Currently out of sync with the actual one due to a race condition in
submitting #880.
construction.
=> Fix hash of `oak_loader` binary

.github/workflows/reproducibility.yaml, .gitignore, cloudbuild.yaml, reproducibility_index, scripts/build_reproducibility_index
Revert af85a1c since it is too annoying
to keep the index in sync at each commit.
Supersedes #895
Ref #861
=> Rebuild reproducibility index on GitHub Actions

.github/workflows/reproducibility.yaml
The current version does not work because when running on merge events
the PR number is not present, so we need to look it up based on commit
SHA.
Ref #861
=> Fix posting reproducibility index to PR

Cargo.lock, Cargo.toml, examples/authentication/README.md, examples/authentication/client/Cargo.toml, examples/authentication/client/src/main.rs
This is the first part of the authentication client example. It opens the browser to allow the user to authenticate, and then receives the resulting authentication code. The example will be extended to exhange the auth code for an identity token once the authentication service is availble to support it and then pass the token to the runtime as proof of identity (#855).
construction.
=> Add initial OpenID Connect auth client example

oak/server/grpc_client_node.cc, oak/server/roughtime_client_node.cc, oak/server/rust/oak_runtime/src/node/logger.rs, oak/server/rust/oak_runtime/src/node/wasm/mod.rs
Broke out the more straightforward parts of #894:
- tweak `wasm/mod.rs` to reduce things than would need to be manually kept in sync
- reorganize `wasm/mod.rs` to have distinct layers:
- first get the Wasm arguments and forward on
- next convert chunks of linear memory into Rust strings and vectors and forward on
- innermost layer either performs the function (e.g. `random_get`) or forwards on to the `RuntimeProxy`
- close channels on the way out of pseudo-Nodes.
construction.
=> Rust runtime smaller tweaks

Cargo.lock, Cargo.toml, examples/authentication/README.md, examples/authentication/client/Cargo.toml, examples/authentication/client/build.rs, examples/authentication/client/src/auth_client.rs, examples/authentication/client/src/main.rs, examples/authentication/client/src/redirect_handler.rs, examples/authentication/proto/authentication.proto, examples/authentication/server/Cargo.toml, examples/authentication/server/build.rs, examples/authentication/server/src/main.rs
This initial version of the auth server only provides the client ID and OAuth endpoint to the client. Subsequent versions will expand the parameters provided and implement the logic the exchange the authentication code for an identity token.
construction.
=> Add initial authentication server implementation

.cargo/config
This was done in #863 for the gnu (libc) target
Ref #862
=> Disable BUILD_ID generation for musl target

INSTALL.md
Super duper minor, but we one needs to to configure the shell before running `rustup`. Else you'd get "rustup: command not found".
Should make things ever so slightly easier to setup for beginners.
=> Configure shell to use rustup command before using it

cloudbuild.yaml, scripts/build_example
This change adds parameters for choosing server type in Docker images.
Change is necessary, since an Oak server for Docker images was not compiled using `clang`.
=> Compile Docker server with clang

.github/workflows/build_rust_docs.yaml, .github/workflows/reproducibility.yaml
Use a separate branch, and a similar workflow to that used for Rust
documentation, using GitHub Actions to push changes.
Ref #861
=> Track reproducibility index history

cargo/Cargo.toml, cargo/remote/ring-0.16.12.BUILD, oak/server/rust/oak_abi/Cargo.toml, oak/server/rust/oak_glue/Cargo.toml, oak/server/rust/oak_runtime/Cargo.toml, scripts/cargo_raze, scripts/run_clang_tidy, scripts/run_tests
This change fixes `ring` compilation errors in Bazel.
Note: this contains a change in ` cargo/remote/ring-0.16.12.BUILD` that might be rewritten by running `cargo raze` (will require `git checkout cargo/remote/ring-0.16.12.BUILD` afterwards).
Fixes https://github.com/project-oak/oak/issues/890
construction.
=> Fix `ring` compilation errors in Bazel

examples/chat/README.md, examples/chat/client/chat.cc
It appears that https://github.com/project-oak/oak/commit/a2c09489934f2ab22b010beb834980f2267804fa#diff-05fd908aa4ea56a3aef0a53b3fedae3c renamed the `--app-address` flag to `--address`. 
The logs and part of the README still mention the now defunct `--app-address` flag. This updates that. 
construction.
=> Chat example: Update outdated app_address flag

INSTALL.md
This change adds `musl-tools` to `INSTALL.md`
=> Add musl-tools to INSTALL.md

.github/workflows/reproducibility.yaml
This was already done in the Rust doc generation GitHub action, and
seems necessary here too now.
Ref #861
=> Free up space in reproducibility GitHub action

cloudbuild.yaml
This change temporary disables `asan` and `tsan` builds in CI.
Bug is tracked by https://github.com/project-oak/oak/issues/942
=> Disable asan and tsan

cargo/remote/ring-0.16.12.BUILD, cloudbuild.yaml, oak/proto/application.proto, oak/server/rust/oak_loader/src/main.rs, oak/server/rust/oak_runtime/Cargo.toml, oak/server/rust/oak_runtime/src/config.rs, oak/server/rust/oak_runtime/src/node/grpc_server.rs, oak/server/rust/oak_runtime/src/node/mod.rs, oak/server/rust/oak_runtime/src/proto/oak.application.rs, scripts/run_server, sdk/rust/oak/src/grpc/mod.rs, sdk/rust/oak/src/grpc/server.rs
This change:
- Adds TLS handling logic to the gRPC pseudo-Node
- Reimplements gRPC processing using Tonic library
Fixes #806
Fixes #813
~~Blocked by https://github.com/project-oak/oak/pull/891~~
construction.
=> Add TLS handling to the gRPC pseudo-node

oak/server/rust/oak_runtime/src/node/grpc/mod.rs, oak/server/rust/oak_runtime/src/node/grpc/server.rs, oak/server/rust/oak_runtime/src/node/mod.rs
This change moves gRPC server to a separate directory.
construction.
=> Move gRPC server to a separate directory

oak/server/rust/oak_runtime/src/runtime/introspect.rs
Removes the invisible chart edges, by making it cover the whole browser window.
Before:
After:
construction.
Ref #913
=> Remove invisible chart edges

oak/server/rust/oak_loader/src/main.rs
This change makes `simple_logger` use `RUST_LOG` environment variable to set up log level.
construction.
=> Use `RUST_LOG` in `simple_logger`

oak/server/rust/oak_runtime/src/runtime/mod.rs
This change fixes a bug where `channel_read` was tracking the channel on which it read a message instead of tracking the received handles.
=> Track handles in `channel_read`

oak/server/rust/oak_runtime/src/node/grpc/codec.rs, oak/server/rust/oak_runtime/src/node/grpc/mod.rs, oak/server/rust/oak_runtime/src/node/grpc/server.rs
This change moves a gRPC encoder/decoder to a separate directory.
construction.
=> Move codec to a separate directory

oak/server/rust/oak_runtime/src/node/grpc/server.rs
This change fixes gRPC request handling (double decoding) in gRPC server pseudo-Node.
construction.
=> Fix gRPC request handling

scripts/run_examples
This change deletes an unused Bash variable `client_args`.
=> Delete an unused variable

oak/server/rust/oak_runtime/src/runtime/introspect.rs
Kind of a minor thing, but using a 405, instead of 404 code seems more accurate here.
405 is specific for responding to requests of unsupported methods.
Before:
After:
Images brought to you by https://http.cat/
construction.
=> Introspection Server: Use 405 http status code for disallowed methods

oak/server/rust/oak_runtime/src/node/grpc/server.rs, sdk/rust/oak/src/grpc/mod.rs, sdk/rust/oak/src/grpc/server.rs
This change fixes gRPC response handling in the gRPC pseudo-Node.
construction.
=> Fix GrpsResponse handling

docs/abi.md, oak/proto/oak_abi.proto, oak/server/rust/oak_abi/src/proto/oak_abi.rs, oak/server/rust/oak_runtime/src/node/wasm/mod.rs, oak/server/rust/oak_runtime/src/runtime/mod.rs, oak/server/rust/oak_runtime/src/runtime/tests.rs, sdk/rust/oak/src/lib.rs
* `wait_on_channel` in `oak_runtime` returns early if any of the channels is invalid or orphaned
* `wait_on_channel` in `oak_runtime` returns a vector containing all statuses if any is inaccessible
* Added the a new status `PERMISSION_DENIED` to `ChannelReadStatus` 
* Updated documentation
Fixes #803 
construction.
=> Return immediately from wait if at least one invalid channel

docs/abi.md, examples/abitest/module_0/rust/src/lib.rs, examples/aggregator/README.md, examples/aggregator/module/rust/Cargo.toml, examples/aggregator/module/rust/src/lib.rs, oak/server/rust/oak_abi/src/lib.rs, oak/server/rust/oak_glue/src/lib.rs, oak/server/rust/oak_runtime/src/node/grpc/server.rs, oak/server/rust/oak_runtime/src/node/wasm/mod.rs, oak/server/rust/oak_runtime/src/node/wasm/tests.rs, oak/server/rust/oak_runtime/src/runtime/mod.rs, oak/server/rust/oak_runtime/src/runtime/tests.rs, sdk/rust/oak/src/grpc/client.rs, sdk/rust/oak/src/io/mod.rs, sdk/rust/oak/src/lib.rs, sdk/rust/oak_tests/src/lib.rs
Expand `channel_create` host function call to accept a Label parameter,
similar to `node_create`.
Add `Client::new_with_label` method to allow creating a gRPC client
pseudo-node at a specific IFC label. This will act as a
declassification, once more IFC rules are implemented in the Runtime.
Update ABI documentation.
Fix aggregator example documentation.
Ref #972 #630
construction.
=> Assign labels on channel creation

docs/abi.md, oak/server/rust/oak_runtime/src/node/wasm/mod.rs
I was tired of trying to keep the parameter numbers in sync :)
Fix ABI documentation to not repeat types, and use terminology more in
line with standard WebAssembly (see
https://hacks.mozilla.org/2019/11/multi-value-all-the-wasm/ for the
choice of `param` and `result` in particular).
Ref #877
construction.
=> Redirect ABI method comments to documentation

docs/concepts.md, examples/abitest/module_0/rust/src/lib.rs
Notwithstanding the discussion in #763, this PR tests and documents current semantics.
construction.
=> Be clearer about current orphaned channel semantics

oak/server/rust/oak_runtime/src/metrics/mod.rs, oak/server/rust/oak_runtime/src/metrics/server.rs, oak/server/rust/oak_runtime/src/node/grpc/server.rs, oak/server/rust/oak_runtime/src/runtime/mod.rs, oak/server/rust/oak_runtime/tests/integration_test.rs
- Instantiates and manages prometheus registry in the Runtime,
instead of using a static instance
- Uses labels for finer grained collection of metrics
- Better instrumentation for gRPC server pseudo-node
- Exposes metrics on `/metrics` endpoint
Fixes #899 
construction.
=> Manage prometheus registry in Oak Runtime

cloudbuild.yaml, examples/abitest/module_0/rust/src/lib.rs, oak/server/rust/oak_runtime/src/config.rs, oak/server/rust/oak_runtime/src/node/external.rs, oak/server/rust/oak_runtime/src/node/grpc/client.rs, oak/server/rust/oak_runtime/src/node/grpc/server.rs, oak/server/rust/oak_runtime/src/node/logger.rs, oak/server/rust/oak_runtime/src/node/mod.rs, oak/server/rust/oak_runtime/src/node/wasm/mod.rs, oak/server/rust/oak_runtime/src/runtime/mod.rs, oak/server/rust/oak_runtime/src/runtime/tests.rs
This change:
- Adds futures select for Tokio Runtime
- Temporary disables gRPC client tests in `abitest` since they now require TLS certificates (will be re-enabled after examples start using Rust Loader)
Fixes https://github.com/project-oak/oak/issues/982
construction.
=> Use futures select for stopping gRPC nodes

oak/server/rust/oak_runtime/src/metrics/mod.rs, oak/server/rust/oak_runtime/src/runtime/mod.rs, oak/server/rust/oak_runtime/tests/integration_test.rs
- Adds a metric, with a fixed value of 1, to indicate that the Runtime is up.
construction.
=> Add runtime health-check metric

scripts/build_reproducibility_index, scripts/common
Currently only the return value of the last command in a pipeline is
taken into account, any other failures are silently ignored.
In the reproducibility script this was actually causing the `sha256sum`
command failure to be ignored.
See
https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html
construction.
=> Make scripts fail if any part of a pipeline fails

examples/aggregator/README.md, examples/aggregator/gcp/pod.yaml
Added a new container from [prometheus-to-sd](https://github.com/GoogleCloudPlatform/k8s-stackdriver/tree/master/prometheus-to-sd)  to the aggregator pod. This container scrapes metrics from the aggregator oak-application.
Fixes #976 
construction.
=> Add prometheus-to-sd to scrape metrics

Cargo.lock, cargo/BUILD, cargo/Cargo.lock, cargo/Cargo.toml, oak/proto/application.proto, oak/server/rust/oak_loader/BUILD, oak/server/rust/oak_loader/Cargo.toml, oak/server/rust/oak_loader/src/main.rs, oak/server/rust/oak_loader/src/tests.rs, oak/server/rust/oak_runtime/src/proto/oak.application.rs
This will be used to pass configuration files and secrets to Oak
Applications, by specifying them via command line flags to the
`oak_loader` binary.
Also switch the top-level `oak_loader` error handling to the `anyhow`
crate.
Ref #689
=> Introduce config map format and parsing logic

oak/server/rust/oak_runtime/src/runtime/mod.rs
=> runtime: cope with aux servers quitting first

examples/private_set_intersection/client/private_set_intersection.cc, examples/running_average/client/running_average.cc
This change adds `assert` to the `running_average` and `private_set_intersection` examples.
=> Add asserts to examples

runner/src/internal.rs, runner/src/main.rs, scripts/runner
It's not quite on par with the other scripts there, but getting there
Add `./scripts/runner` to make it easier to invoke.
construction.
=> Add build examples and build server to runner

scripts/run_tests
It is much faster to complete, so it makes sense to return any issues
from it as soon as possible.
=> Run `cargo clippy` before actual tests

docs/concepts.md, docs/development.md, examples/aggregator/module/rust/src/lib.rs, examples/chat/proto/chat.proto, oak/common/label.cc, oak/proto/label.proto, oak/server/rust/oak_abi/src/label/mod.rs, oak/server/rust/oak_abi/src/label/tests.rs, oak/server/rust/oak_abi/src/proto/oak.label.rs, oak/server/rust/oak_runtime/src/runtime/mod.rs, oak/server/rust/oak_runtime/src/runtime/tests.rs
Seems a more accurate representation of the fact that data is kept
confidential to a set of subjects, as opposed to just secret, which
feels more like all-or-nothing.
construction.
=> Rename secrecy to confidentiality

BUILD, examples/aggregator/README.md, examples/aggregator/gcp/pod.yaml, examples/tensorflow/config/BUILD, oak/server/loader/BUILD, oak/server/loader/oak_docker.bzl, scripts/build_example
This change:
- Makes Docker images to use Rust Oak Loader
- Adds support for `tensorflow` example Docker image
Fixes #448
=> Use Rust Oak Loader in Docker images

Cargo.lock, docs/programming-oak.md, examples/abitest/config/config.textproto, examples/abitest/tests/src/tests.rs, examples/aggregator/config/config.textproto, examples/chat/config/config.textproto, examples/hello_world/config/config.textproto, examples/machine_learning/config/config.textproto, examples/private_set_intersection/config/config.textproto, examples/running_average/config/config.textproto, examples/rustfmt/config/config.textproto, examples/tensorflow/config/config.textproto, examples/translator/config/config.textproto, oak/proto/application.proto, oak/server/rust/oak_glue/src/lib.rs, oak/server/rust/oak_loader/BUILD, oak/server/rust/oak_loader/Cargo.toml, oak/server/rust/oak_loader/src/main.rs, oak/server/rust/oak_runtime/src/config.rs, oak/server/rust/oak_runtime/src/lib.rs, oak/server/rust/oak_runtime/src/node/mod.rs, oak/server/rust/oak_runtime/src/node/wasm/tests.rs, oak/server/rust/oak_runtime/src/proto/oak.application.rs, oak/server/rust/oak_runtime/src/runtime/mod.rs, oak/server/rust/oak_runtime/src/runtime/tests.rs, oak/server/rust/oak_runtime/tests/integration_test.rs, sdk/rust/oak_tests/src/lib.rs
=> Move TLS parameters out of application config

oak/server/rust/oak_runtime/src/runtime/mod.rs, oak/server/rust/oak_runtime/src/runtime/tests.rs
=> runtime: use 'confidential' rather than 'secret'

oak/server/rust/oak_runtime/src/runtime/channel.rs, oak/server/rust/oak_runtime/src/runtime/graph.rs, oak/server/rust/oak_runtime/src/runtime/introspect.rs, oak/server/rust/oak_runtime/src/runtime/mod.rs
=> Move the creation of Runtime dot graph to a separate submodule

docs/development.md, examples/aggregator/README.md, examples/chat/README.md
This change updates docs to use localhost instead of `127.0.0.1`.
=> Use localhost instead of 127.0.0.1 in docs

examples/abitest/module_0/rust/src/lib.rs, examples/aggregator/module/rust/src/lib.rs, oak/server/rust/oak_glue/src/lib.rs, oak/server/rust/oak_runtime/src/node/grpc/server/mod.rs, oak/server/rust/oak_runtime/src/node/wasm/tests.rs, oak/server/rust/oak_runtime/src/runtime/mod.rs, oak_abi/src/label/mod.rs, oak_abi/src/label/tests.rs, sdk/rust/oak/src/grpc/client.rs, sdk/rust/oak/src/lib.rs, sdk/rust/oak_tests/src/lib.rs
This was incorrectly referred to as `public_trusted`, while in fact it
is not trusted by anyone, as it has an empty integrity label.
Fix #980
=> Fix name of `public_untrusted` label

BUILD, Cargo.lock, examples/abitest/config/BUILD, examples/aggregator/config/BUILD, examples/chat/config/BUILD, examples/hello_world/config/BUILD, examples/machine_learning/config/BUILD, examples/private_set_intersection/config/BUILD, examples/running_average/config/BUILD, examples/rustfmt/config/BUILD, examples/translator/config/BUILD, scripts/build_example, scripts/build_reproducibility_index, scripts/check_formatting, scripts/format, sdk/rust/oak_tests/Cargo.toml, sdk/rust/oak_tests/src/lib.rs
It should help with #971, until a more proper solution is in place.
=> Use separate target dir when compiling Wasm code

docs/concepts.md
The Oak runner docs have been removed (https://github.com/project-oak/oak/commit/25b36c05511841aa269471b3c68829a6946867ad) but the now orphaned item in the table of contents remains. 
Given that we're looking to migrate away from bash scripts to the runner (https://github.com/project-oak/oak/issues/396), it seems it would actually be nice to have docs on it though? 
construction.
=> Docs: Remove orphaned bullet point from the table of contents

scripts/build_gh_pages, scripts/check_docs
Updates `check_docs` and `build_gh_docs` scripts to also check and generate docs
for `oak_abi`, now that it is a separate crate.
Creates the following hierarchy under the given `TARGET_DIR`:
```
├── oak
│   ├── index.html
│   └── doc
├── oak_abi
│   ├── index.html
│   └── doc
├── oak_utils
│    ├── index.html
│    └── doc
└─── index.html
```
Ref #1037 
construction.
=> Generate docs for the `oak_abi` crate

Cargo.lock, docs/programming-oak.md, examples/abitest/tests/Cargo.toml, examples/abitest/tests/src/tests.rs, examples/aggregator/module/rust/Cargo.toml, examples/aggregator/module/rust/src/tests.rs, examples/hello_world/module/rust/Cargo.toml, examples/hello_world/module/rust/src/tests.rs, examples/private_set_intersection/module/rust/Cargo.toml, examples/private_set_intersection/module/rust/src/tests.rs, examples/running_average/module/rust/Cargo.toml, examples/running_average/module/rust/src/tests.rs, examples/translator/module/rust/Cargo.toml, examples/translator/module/rust/src/tests.rs, oak/server/rust/oak_loader/Cargo.toml, oak/server/rust/oak_loader/src/main.rs
The env_logger crate allows better control over the details of
what gets logged.
construction.
=> Replace simple_logger with env_logger

examples/Cargo.lock
Github misled me to believe that merging #1045 would be conflict free! Here is the fix. 
construction.
=> Update cargo lock

docs/programming-oak.md, examples/abitest/client/abitest.cc, examples/aggregator/client/aggregator.cc, examples/aggregator/client/android/cpp/client.cc, examples/chat/client/chat.cc, examples/hello_world/client/hello_world.cc, examples/hello_world/client/nodejs/index.js, examples/machine_learning/client/machine_learning.cc, examples/private_set_intersection/client/private_set_intersection.cc, examples/running_average/client/running_average.cc, examples/tensorflow/client/tensorflow.cc, examples/translator/client/translator.go, oak/client/application_client.h, oak/common/label.cc, oak/common/label.h, oak/server/rust/oak_runtime/src/node/grpc/server/mod.rs, oak/server/rust/oak_runtime/src/runtime/mod.rs, sdk/rust/oak/src/lib.rs
- Enforce that **exactly** one label is specified per gRPC request. From
now on, the gRPC server will reject requests with no label attached, or
with multiple labels. It is possible to attach a "public" label, but it
needs to be specified explicitly.
- Change the examples to attach such "public" label, until we figure out
the rest of the downgrading functionality in the Oak Runtime.
- Change return type of `handle_grpc_request` and `handle_grpc_response`
from `Result<GrpcResponse, OakStatus>` to `Result<GrpcResponse, ()>`, to
make it clear that all errors are actually logged within the body of the
functions. Previously there was a comment somewhere else that was
explaining why those errors were being ignored, and also a statement
that confirmed that they were all logged (which turned out …
=> Propagate gRPC request label

examples/trusted_information_retrieval/client/trusted_information_retrieval.cc
Add labels to the Trusted Information Retrieval example.
=> Use labels in TIR

examples/Cargo.lock, examples/trusted_information_retrieval/module/rust/src/database.rs, examples/trusted_information_retrieval/module/rust/src/lib.rs, examples/trusted_information_retrieval/module/rust/src/tests.rs, scripts/check_cargo_deny, scripts/check_formatting, scripts/common, scripts/format, scripts/run_tests, third_party/expect/Cargo.toml
Ref #971, #1045 
construction.
=> Update scripts after reorganization of the code

examples/aggregator/client/aggregator.cc, sdk/rust/oak/src/grpc/mod.rs, sdk/rust/oak/src/lib.rs
If there is an error when reading a gRPC request from an invocation,
then attempt to send an error response to the caller rather than leave
it hanging forever (this happens in case of misplaced labels).
=> More accurate logging of gRPC requests lifecycle

Dockerfile, docs/PULL_REQUEST_TEMPLATE.md, docs/abi.md, docs/concepts.md, docs/sdk.md, examples/aggregator/README.md, scripts/check_formatting
I tried a few tools out there, but `liche` was the only one that
actually checks links between docs in the same repository.
construction.
=> Check markdown links

examples/abitest/module_0/rust/src/lib.rs, oak/server/rust/oak_runtime/src/node/grpc/client.rs
=> Re-use connection in gRPC client

oak/server/rust/oak_runtime/src/node/grpc/server/mod.rs
The main change is that we log one info entry for each gRPC request,
including details of its label, so that it's possible to debug label
mismatch issues.
Also do not log the contents of the request, only its size, and the
client IP address (though this does not seem to work reliably yet).
=> Improve logging of gRPC request handling 

scripts/build_example
Reverts project-oak/oak#1096
Running this in our docker images leads to build_example failing with 
```
+ npm ci --prefix ./examples/hello_world/client/nodejs
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /.npm
npm ERR! errno -13
npm ERR! 
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR! 
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1001:0 "/.npm"
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /.npm
npm ERR! errno -13
npm ERR! 
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR! 
npm ERR! To permanently fix this problem, please run:
npm ERR! …
```
=> Revert "Install node deps when building an example"

examples/abitest/module_0/rust/src/lib.rs, oak/proto/BUILD, oak/proto/application.proto, oak/proto/roughtime_service.proto, oak/server/rust/oak_runtime/src/node/grpc/mod.rs, oak/server/rust/oak_runtime/src/node/mod.rs, oak/server/rust/oak_runtime/src/node/roughtime.rs, oak/server/rust/oak_runtime/src/time/mod.rs, oak_abi/build.rs, oak_abi/src/proto/mod.rs, oak_utils/src/lib.rs, runner/src/main.rs, scripts/run_example, sdk/rust/oak/src/roughtime/mod.rs
=> Implement Roughtime client pseudo-node

examples/abitest/module_0/rust/src/lib.rs, oak/server/rust/oak_runtime/src/node/wasm/mod.rs
=> Improve handling of aborts in Wasm code (e.g from panic)

oak/server/rust/oak_loader/src/main.rs, oak_abi/src/lib.rs
Example new error message:
```
Error: could not read gRPC TLS private key
Caused by:
No such file or directory (os error 2)
```
Old error message:
```
Error: No such file or directory (os error 2)
```
=> Use `anyhow` for error handling in oak_loader

examples/abitest/module_0/rust/src/lib.rs, oak/server/rust/oak_runtime/src/node/wasm/mod.rs
Removes the extra check in `WasmInterface::wait_on_channels` that returns
`Err(OakStatus::ErrBadHandle)` when all handles are invalid. This is done to
make the behaviour more consistent with that of `Runtime::wait_on_channels`.
Ref [this comment](https://github.com/project-oak/oak/pull/1114#discussion_r437606434).
construction.
=> Make wait_on_channels errors more consistent

docs/development.md
Most packages induce fairly obvious error messages when they're
missing, but musl-tools gives an obscure error that's not obviously
related.
construction.
=> docs: explicitly mention need for musl

examples/hello_world/module/cpp/hello_world.cc, oak/server/rust/oak_runtime/src/node/grpc/server/mod.rs, runner/src/main.rs, scripts/run_example
=> Server-streaming support in gRPC server pseudo-Node

oak/server/rust/oak_runtime/src/node/wasm/mod.rs, oak/server/rust/oak_runtime/src/runtime/mod.rs, sdk/rust/oak/src/io/receiver.rs, sdk/rust/oak/src/lib.rs
=> Return ChannelReadStatus from Receiver::wait

sdk/rust/oak/src/io/receiver.rs, sdk/rust/oak/src/lib.rs
Ref [discussion on Slack](https://project-oak.slack.com/archives/CHE9E13C3/p1591781120186400), I've replaced panics added in #1114  with error. Does this look better?
=> Use error instead of panic

examples/hello_world/client/nodejs/README.MD, scripts/build_example, scripts/run_example
Thanks to the work done by @ipetr0v in #1110 this was super simple. :) 
construction.
=> Add support for Node.js clients to the run_example script

examples/hello_world/client/nodejs/index.js, examples/hello_world/client/nodejs/package-lock.json, examples/hello_world/client/nodejs/package.json
This was lot less complex than I feared. :) It should bring the node client up to par with #1068. 
Sets me up for my next PR, which should be running this client as part of the CI.
construction.
=> Add label support to the nodejs client

cloudbuild.yaml, scripts/run_example, scripts/run_examples
Adresses https://github.com/project-oak/oak/issues/1145
construction.
=> Allow specifying multiple clients for run_examples

examples/Cargo.lock, oak/server/Cargo.lock, oak/server/rust/oak_runtime/src/node/wasm/mod.rs, sdk/Cargo.lock
The main difference in terms of API is the `sha2` crate, which has
different names for some of the methods.
=> Update Rust dependencies for Oak runtime

oak/server/rust/oak_runtime/Cargo.toml, runner/src/internal.rs, runner/src/main.rs
Remove unused server variants.
Disable `rustfmt` build feature of `tonic-build`, to allow for
simpler compatibility with custom toolchains.
=> Support rust toolchain override in `runner`

scripts/run_example
Fixes the issue of incorrectly skipping clients, as caught by David: https://github.com/project-oak/oak/pull/1148#discussion_r442065904
Looking back the forgiving nature of this logic probably isn't ideal. Instead it seems that a type of "manifest" that specifies all clients that should be available for an example (and fails if they are not) is preferable.
=> Fix incorrect example client checks

examples/aggregator/README.md, oak/server/rust/oak_runtime/src/metrics/mod.rs, oak/server/rust/oak_runtime/src/node/grpc/server/mod.rs
Adds a new metric `grpc_server_msg_sent_total` to measure the total number of RPC response messages sent by the server..
Ref #736
=> Add grpc streaming metrics

cloudbuild.yaml, examples/hello_world/client/nodejs/README.MD, scripts/build_example, scripts/run_example, scripts/run_examples
TL;DR
`cpp` -> `bazel`
`rust` -> `cargo`
`nodejs` -> `npm`
----
Addresses @daviddrysdale's earlier comment: https://github.com/project-oak/oak/pull/1169#discussion_r442165207
This renames the issue of the somewhat confusing `cpp` variant. 
This makes sense, since bazel is the build system the scripts will use for this variant. And other non cpp clients (Go) that use bazel shouldn't use the `cpp` flag.
Similarly this renames `rust` to `cargo`, and `nodejs` to `npm`, so we always refer to the build system. 
This is quite similar to the naming used in the rust runner. 
https://github.com/project-oak/oak/blob/19ff6bb2c676f501816d8a57c3f430f5bed45463/runner/src/main.rs#L295
Imho it might be worth to think about doing the same for the server/application variants. …
=> Build scripts: Name client variants by their build system for clarity

examples/trusted_information_retrieval/client/trusted_information_retrieval.cc
Similar to 2ec130ad9feba547b5061d8277b711056f392955 , but for the
Trusted Information Retrieval example.
=> Make client actually fail on errors

docs/concepts.md
Super minor, but I think it makes it a bit clearer that a given entity is only ever described by a single label. 
My understanding is that while a label consists of a collection of multiple tags, Channels and Nodes each only ever have one Label. 
construction.
=> Docs: Clarify that Channels and Nodes each only have one Label

cloudbuild.yaml, scripts/run_example, scripts/run_examples
Replaces the current way of deducting available clients from the folder structure (#1148) with instead explicitly specifying them in the conditionals of the `run_examples` script. 
This is nice, because it allows us to explicitly fail if a client is not avaible.
construction.
=> Always run all clients in run_examples

scripts/build_example, scripts/run_example
=> Move NPM build step inside of client variant logic inside of build_example

Dockerfile, cloudbuild.yaml, scripts/run_cargo_crev
This just adds a step to the cloud build process that outputs the
results of the cargo crev verification process. Given it does not have a
web of trust configured, none of the crates appear as reviewed by trusted reviewers yet.
Ref #1195
construction.
=> Add simple integration with cargo-crev

.cargo/config
When building for aarch64, cross or native,
linking with musl will fail due to missing symbols.
This change only affects Rust code targetting:
- aarch64-unknown-linux-musl
Workaround for:
https://github.com/rust-lang/compiler-builtins/issues/201
construction.
=> Add workaround for aarch64 Rust missing symbols

oak/server/rust/oak_runtime/src/io.rs, oak/server/rust/oak_runtime/src/node/grpc/client.rs
=> Downgrade error on gRPC client node invocation channel closure

scripts/build_example, scripts/common, scripts/run_example
Possible fix for the [problem discussed on Slack](https://project-oak.slack.com/archives/CHE9E13C3/p1593003638448300).
=> Use the default target for backend components

docs/abi.md, docs/concepts.md, oak/server/rust/oak_runtime/src/message.rs, oak/server/rust/oak_runtime/src/runtime/mod.rs, oak/server/rust/oak_runtime/src/runtime/tests.rs
Implement `Clone` and `PartialEq` for `NodeMessage` to facilitate
testing.
Add termination check to `channel_create` host function.
Add more logging around labels in various host functions.
The tests are not as comprehensive as I would like them to be, since it
is hard to simulate the case in which a public node creates a non-public
channel and passes that to a non-public node.
Fixes #1143
=> Only allow public Nodes to create entities

README.md
We've received feedback that the mailing list and slack links are easy to miss, so it's been suggested we add them as links in the text body as well. I've added a 'getting involved' section at the bottom of the readme for this.
construction.
=> Add mailing list and slack links to text body

examples/Cargo.lock, examples/abitest/grpc/Cargo.toml, examples/abitest/grpc/build.rs, examples/aggregator/backend/Cargo.toml, examples/aggregator/backend/build.rs, examples/aggregator/grpc/Cargo.toml, examples/aggregator/grpc/build.rs, examples/authentication/client/Cargo.toml, examples/authentication/client/build.rs, examples/hello_world/grpc/Cargo.toml, examples/hello_world/grpc/build.rs, examples/private_set_intersection/grpc/Cargo.toml, examples/private_set_intersection/grpc/build.rs, examples/running_average/grpc/Cargo.toml, examples/running_average/grpc/build.rs, examples/translator/grpc/Cargo.toml, examples/translator/grpc/build.rs, examples/trusted_information_retrieval/backend/Cargo.toml, examples/trusted_information_retrieval/backend/build.rs, examples/trusted_information_retrieval/client/rust/Cargo.toml, examples/trusted_information_retrieval/client/rust/build.rs, oak/server/Cargo.lock, oak/server/rust/oak_runtime/Cargo.toml, oak/server/rust/oak_runtime/build.rs, oak_abi/Cargo.lock, oak_utils/Cargo.lock, oak_utils/Cargo.toml, oak_utils/src/lib.rs, sdk/Cargo.lock
This change moves Protobuf generation function to `oak_utils`.
Fixes https://github.com/project-oak/oak/issues/1120
Ref https://github.com/project-oak/oak/issues/1093
=> Move client proto generation to oak_utils

examples/private_set_intersection/module/rust/src/lib.rs, examples/private_set_intersection/module/rust/tests/integration_test.rs, examples/private_set_intersection/proto/private_set_intersection.proto
This change enhances Private Set Intersection example:
- Limits number of clients
- Freezes set after first query
Fixes https://github.com/project-oak/oak/issues/747
=> Enhance Private Set Intersection

Dockerfile, scripts/check_cargo_deny
=> Use existing binaries for Rust tools, where possible

scripts/build_gh_pages
Fix paths in `scripts/build_gh_pages` for generating GitHub pages.
=> Fix GitHub pages

runner/src/internal.rs, runner/src/main.rs
This allows removing a layer of nesting in various places where we used
to use `flatten` instead.
A common case is for lists of flags, which sometimes contain other lists
of flags, which need to be expanded in line.
The implementation is not very efficient and has some corner cases (e.g.
still requires calls to `to_string` to make things work sometimes).
construction.
=> Support "spread" operator via macro

Dockerfile, cloudbuild.yaml, docs/INSTALL-OSX.md, oak/module/placeholders.h, toolchain/emcc.sh
I've tried to remove unused stuff and reuse existing binaries where possible.
This shaves about 1 GB from the image size, according to my local docker image ls and hopefully makes building the whole image faster.
I've also changed the order for GCB, to run the spellchecking first.
construction.
=> Small clean-up of Dockerfile

examples/aggregator/scripts/docker_push, examples/aggregator/scripts/run_backend, examples/aggregator/scripts/run_client, examples/aggregator/scripts/run_server, examples/aggregator/scripts/undeploy
These scripts were not under `./scripts` and therefore missed by
`shellcheck`.
As part of #1190, `runner` actually runs `shellcheck` on them, and
pointed out a few existing errors.
construction.
=> Fix issues found by shellcheck

deny.toml, examples/Cargo.lock, examples/Cargo.toml, oak/server/Cargo.lock, oak/server/Cargo.toml, oak_abi/Cargo.lock, oak_abi/Cargo.toml, oak_abi/build.rs, oak_utils/Cargo.lock, oak_utils/Cargo.toml, oak_utils/src/lib.rs, sdk/Cargo.lock, sdk/Cargo.toml
This also introduces a `ProtoOptions` struct to `oak_utils` much like `CodegenOptions`,
so adding new options in the future is easier.
This should make it easier to subsequently land #1108.
construction.
=> Use the vendored prost everywhere.

examples/aggregator/scripts/run_backend, scripts/build_example, scripts/run_example
The same way the host triple is explicitly specified as the target when
building the backend components, it should be specified using the
`--target` flag when building the clients, to avoid cache invalidation.
The CI-build takes 6-7 minutes less after this change. 
Ref #971
=> Specify the host triple as the target

scripts/push_example
This change adds a script for saving example modules in Google Storage.
Ref https://github.com/project-oak/oak/issues/1183
construction.
=> Add push_example script

docs/development.md, runner/Cargo.lock, runner/Cargo.toml, runner/src/internal.rs, runner/src/main.rs
Can be installed with the following commands:
```bash
alias runner=./scripts/runner
source <(runner completion)
```
=> Generate bash completions in runner

.codecov.yml
At the moment they're not helpful.  If we sort out the oddly-low
reported numbers from codecov (cf. #1187) we can always re-enable
later.
construction.
=> Turn off PR comments from codecov

runner/src/main.rs
This change:
- Removes `cargo run` from `runner`
- Copies `oak_loader` into `bin` and use it to run Oak server
Fixes https://github.com/project-oak/oak/issues/1252
=> Remove cargo run from runner

oak/proto/introspection_events.proto
See [David's comment](https://github.com/project-oak/oak/issues/913#issuecomment-655652315) for background on this change in #913. These events will allow dynamic introspect, they're based on his [stringly typed](https://wiki.c2.com/?StringlyTyped) version of'em. 
construction.
=> Add protobuf schema for introspection events

examples/deny.toml, experimental/deny.toml, oak/server/deny.toml, oak_abi/deny.toml, oak_utils/deny.toml, runner/deny.toml, sdk/deny.toml
All workspaces shared a single global deny.toml which led to many unnecessary warnings. This change also removes the global deny.toml file to ensure cargo deny does not automatically fall back to it when new workspaces are added.
Warnings raised by cargo-deny during CI was also being ignored. This change converts warnings realted to advisories and duplicate crate versions to errors to ensure these would block CI in future.
It also contains explicit exclusions to allow CI to still pass for the current state with TODOs to remove these in future when these exceptions are no longer required.
Fixes #933, as individual issues have been created to remove explicit exclusions when feasible.
=> Clean up cargo-deny warnings

runner/src/main.rs
Link check often fails when checking `https://codecov.io/gh/project-oak/oak`. To make the CI-builds more stable it is excluded from `liche`.
=> Exclude `https://codecov.io/gh/project-oak/oak` from link check

oak/proto/application.proto, oak/proto/http_encap.proto, oak/server/rust/oak_runtime/src/node/http/mod.rs, oak/server/rust/oak_runtime/src/node/http/tests.rs, oak/server/rust/oak_runtime/src/node/mod.rs, oak_abi/build.rs, oak_abi/src/lib.rs
First step towards an HTTP server pseudo-node: #1186 
* Adds HttpServerNode similar to GrpcServerNode
* Updates config protos
* Adds a low level test of HttpServerNode functionality
construction.
=> Add HTTP pseudo-node

docs/development.md, examples/hello_world/client/nodejs/README.MD
- Add `--logs` commandline argument to the quickstart section to include logs
- Update the sample output to match the current state of the runner
- Update node.js README to use `--logs` in the right position
construction.
=> Update development doc to match runner output

examples/trusted_information_retrieval/example.toml
This change adds a Rust TIR client in the `example.toml`.
Fixes https://github.com/project-oak/oak/issues/1285
=> Run Rust TIR client with runner

runner/src/internal.rs, runner/src/main.rs
This change adds a short failure summary in `runner`.
Fixes https://github.com/project-oak/oak/issues/1234
=> Show error summary in runner

oak/server/rust/oak_runtime/src/runtime/channel.rs, oak/server/rust/oak_runtime/src/runtime/introspection_events.rs, oak/server/rust/oak_runtime/src/runtime/mod.rs
Implements `ChannelCreated`, `HandleCreated`, `HandleDestroyed`, `NodeCreated`, `NodeDestroyed`
Omits the `ChannelDestroyed` event for now, for reasons explained here: https://github.com/project-oak/oak/issues/913#issuecomment-661794936
construction.
=> Implement introspection events 

Dockerfile
NPM uses the `~/.config` folder to check for its intended version and to suggest updates. 
Given it access to it patches the warning highlighted by @benlaurie on slack: https://project-oak.slack.com/archives/CHE9E13C3/p1595603416335400
`chmod a+rwx` is what we used so far to patch permission issues in our docker setup, but if there's concerns regarding this specific folder (the entirety of `/.config` after all) I'm happy to suggest less aggressive solutions. 
construction.
=> Docker: chmod a+rwx "/.config" to remove npm warning

.github/workflows/reproducibility.yaml, docs/INSTALL-OSX.md, docs/development.md, examples/aggregator/README.md, examples/chat/README.md, runner/src/internal.rs, runner/src/main.rs
This change adds a `client_variant` parameter to `runner` (replaces `run_clients`).
Fixes https://github.com/project-oak/oak/issues/1294
=> Choose client variants in runner

runner/Cargo.lock, runner/Cargo.toml, runner/src/internal.rs, runner/src/main.rs
* Adds time-of-day (UTC) in the `%H:%M:%S` format to each log line
* Adds run status in the `E:<error-count>,O:<ok-count>,R:<remaining-count>`
format to each log line
Example log line:
```
[11:43:59; E:0,O:6,R:3]:  ❯ ci ❯ examples ❯ aggregator ❯ run ❯ background server ❯ run clients ❯ cpp } ⊢ [OK] [3s]
```
This change can hopefully address some of the issues raised in #1283 and #1291.
=> Add time-of-day, and fail/pass status to each log line of `runner`

oak/server/rust/oak_runtime/src/runtime/introspection_events.rs
This change moves Introspection event output into `debug`.
=> Move introspection output to debug

docs/programming-oak.md, examples/aggregator/config.toml
This change:
- Makes `aggregator` example download Wasm module form cloud
- Updates docs
=> Update docs on Wasm cache

.devcontainer.json, Dockerfile, cloudbuild.yaml, docs/development.md, scripts/docker_build, scripts/docker_run
Split Docker image build and run steps
Create script for docker build, and use it in cloud build too
Create user as part of the docker build step, so that it is a real user
with a proper $HOME and most tools work as expected
Add instructions on how to get things up and running on VS Code using
the remote container extension
=> Improve dev container support in VS code 

examples/abitest/module_0/rust/src/lib.rs, examples/aggregator/module/rust/src/lib.rs, examples/chat/module/rust/src/lib.rs, examples/injection/module/rust/src/lib.rs, sdk/rust/oak/src/grpc/client.rs, sdk/rust/oak/src/grpc/mod.rs, sdk/rust/oak/src/grpc/server.rs, sdk/rust/oak/src/io/mod.rs, sdk/rust/oak/src/io/receiver.rs, sdk/rust/oak/src/io/sender.rs, sdk/rust/oak/src/lib.rs, sdk/rust/oak/src/logger/mod.rs
Move the context-dependent implementations from the SDK's `Sender` and `Receiver` structs into extension traits.
This is a first step towards implementing #1224, #1249, #1324, and generally making it possible to serialise handles in protos in the runtime pseudo nodes as well. This requires harmonising the `Sender` and `Receiver` structs between the SDK and runtime. Some of the functions are incompatible between the runtime and SDK, so have to be moved out of the implementation of the struct itself. The next step is to do something similar for the runtime versions of these structs.
- `SenderExt`
- `send`
- `close`
- `ReceiverExt`
- `receive`
- `wait`
- `try_receive`
- `close`
construction.
=> Move implementations from SDK Sender and Receiver

oak/server/rust/oak_runtime/src/config.rs, oak/server/rust/oak_runtime/src/io.rs, oak/server/rust/oak_runtime/src/node/grpc/client.rs, oak/server/rust/oak_runtime/src/node/grpc/invocation.rs, oak/server/rust/oak_runtime/src/node/http/mod.rs, oak/server/rust/oak_runtime/src/node/roughtime.rs
Move the runtime-specific implementations from the Sender and Receiver structs into extension traits.
This is a step towards implementing #1224, #1249, and #1324. It is the `oak_runtime` counterpart to #1330.
construction.
=> Move Sender and Receiver runtime functionality

examples/abitest/module_0/rust/src/lib.rs, examples/abitest/module_1/rust/src/lib.rs, sdk/rust/oak/src/handle.rs, sdk/rust/oak/src/io/decodable.rs, sdk/rust/oak/src/io/encodable.rs, sdk/rust/oak/src/io/receiver.rs, sdk/rust/oak/src/io/sender.rs, sdk/rust/oak/src/lib.rs, sdk/rust/oak/tests/handle_extract_inject.rs, sdk/rust/oak_derive/src/lib.rs, sdk/rust/oak_derive/tests/visit.rs
This PR removes the `Handle` struct from the SDK and uses the ABI `Handle` type alias directly. It is another step towards harmonising similar data structures between the Runtime and SDK with the end-goal of enabling automatic serialisation of handles in protobufs in the Oak runtime.
This is a follow-up to #1330 and #1331, and an additional step towards resolving #1224, #1249, and #1324.
An associated PR (to follow) will add `ReadHandle` and `WriteHandle` support to the Runtime.
construction.
=> Remove SDK `Handle` struct

oak/proto/introspection_events.proto, oak/server/rust/oak_runtime/src/lib.rs
As suggested by @daviddrysdale: https://project-oak.slack.com/archives/CHE9E13C3/p1595049790239800?thread_ts=1594995744.232500&cid=CHE9E13C3
Imho this makes sense conceptually, since channels aren't tied to Nodes, but connected to them via handles. 
See the related issue #913
construction.
=> Drop node_id from channel introspection events

oak/server/rust/oak_runtime/src/introspect.rs, oak/server/rust/oak_runtime/src/metrics/server.rs
This change updates IP addresses used by `oak_loader` and makes them IPv6.
Fixes https://github.com/project-oak/oak/issues/1314
=> Use IPv6 in oak_loader

docs/concepts.md
Proposing these changes in small PRs so they can be reviewed carefully.
Reorders the paragraphs a bit, so they go from "high level" to "concrete examples" 
construction.
=> IFC docs: Reorder sections a bit

oak/server/rust/oak_runtime/src/lib.rs
`NodeCreated` should always be logged prior to any events related to the node, such as `HandleCreated`.
`ChannelCreated` should always be logged prior to any events related to the channel, such as `HandleCreated`.
I'd like to write an integration test to ensure this is always the case, but not sure how testing currently works in our codebase.
Ideally the test would involve starting an Oak application (hello_world works), and then running a small script that iterates over the built up `introspection_event_queue` and ensures the events are in the valid order.
Ref: is #913
construction.
=> Ensure introspection events are logged in the right order

runner/src/check_license.rs, runner/src/main.rs
=> Make runner ignore (some) generated files

cloudbuild.yaml
=> cloudbuild: allow for longer runner stage

sdk/rust/oak/src/grpc/server.rs, sdk/rust/oak/src/io/sender.rs
This would be better as something integrated with the `ServerInvocationChannel`
and `Sender` types, but works for now.
Fixes #1358
construction.
=> sdk: don't leak gRPC channel handle

examples/chat/module/rust/src/lib.rs, oak_runtime/src/node/grpc/server/mod.rs
=> Spawn a thread per-invocation in gRPC server processing

docs/programming-oak.md
construction.
This adds a short section on handles in Protocol Buffers to the documentation. 
It feels a bit short to me, so feel free to suggest more things to touch upon here 😄. I would put an example where a message is received and then the handle is used immediately afterwards, but I don't think we have such a snippet in our codebase currently 😅.
=> Add documentation on passing handles in Protobuf.

examples/Cargo.lock, examples/Cargo.toml, examples/deny.toml, examples/http_server/client/Cargo.toml, examples/http_server/client/client, examples/http_server/client/src/main.rs, examples/http_server/example.toml, oak_loader/Cargo.lock, oak_loader/src/options.rs, oak_runtime/Cargo.lock, oak_runtime/Cargo.toml, oak_runtime/deny.toml, oak_runtime/src/config.rs, oak_runtime/src/lib.rs, oak_runtime/src/node/http/mod.rs, oak_runtime/src/node/http/tests.rs, oak_runtime/src/node/mod.rs, oak_runtime/src/node/wasm/tests.rs, oak_runtime/src/proxy.rs, oak_runtime/src/tests.rs, oak_runtime/src/tls.rs, oak_runtime/tests/integration_test.rs, sdk/Cargo.lock, sdk/rust/oak_tests/src/lib.rs
- Adds TLS support for HTTP server pseudo-node
- Adds new flags optional to `oak_loader` for HTTP tls configuration
- Adds a Rust client for the `http_server` example
Fixes #1345 
construction.
=> Adds TLS support for HTTP server pseudo-node

runner/src/internal.rs, runner/src/main.rs
This adds the option '--client-rust-target' to the runner,
following the pattern from the '--server-rust-target'.
In addition in the case of heterogeneous builds, the framework
is in place to add '--client-rust-toolchain' at a later date.
Issues: 1349
construction.
=> Provide example client rust target override on runner command line

oak_runtime/src/lib.rs
Moves the `NodeCreated` introspection event from being fired in the `Runtime.node_create` method to the `Runtime.node_configure_instance` method. This is done since the first node (`implicit.initial`) is created directly in `RuntimeProxy.create_runtime` and does not go through `Runtime.node_create`.
construction.
=> Ensure NodeCreated is fired for the initial node

examples/Cargo.lock, examples/http_server/client/Cargo.toml, examples/http_server/client/client, examples/http_server/client/src/main.rs, examples/http_server/example.toml, oak_abi/Cargo.lock, oak_abi/Cargo.toml, oak_io/Cargo.lock, oak_loader/Cargo.lock, oak_runtime/Cargo.lock, oak_runtime/src/node/http/mod.rs, oak_runtime/src/node/http/tests.rs, oak_services/Cargo.lock, oak_utils/src/lib.rs, sdk/Cargo.lock
* Allows serializing and deserializing IFC labels to and from json
* Updates HTTP server examples and tests accordingly
Fixes #1279 
construction.
=> Add support for IFC labels as json

runner/src/main.rs
`./scripts/runner --logs run-examples --client-variant=none --server-variant=logless --example-name=hello_world` fails with:
This seems to be the `--no-default-features` cargo flag, which is already passed during compilation: 
https://github.com/project-oak/oak/blob/e174def0a34f1e975d1c0d9cd905cf05c856b4f4/runner/src/main.rs#L351
construction.
=> Runner: Remove invalid CLI flag

arm64v8.Dockerfile
This PR introduces a Dockerfile for arm64v8, for later integration
with aarch64 CI systems on Packet.io
This Dockerfile is currently unused in the normal build process,
but can be used at will with the apropriate 'docker build'
commands.
(It is intended that this forms the basis of images to be cached
as part of a multi-arch image manifest for Oak Docker builds)
it is intended that this may eventually be merged with the main
Dockerfile once BuildKit is functional, however, that remains
a chicken and egg situation.
The arm64-v8 build proces under docker now includes a full
gcc-aarch64-linux-musl build as part of the multi-stage build.
Both this and the Basel build stage need careful treatment with
'--cache-from' to preven excessive build times for Docker. …
=> Add arm64v8 Dockerfile

experimental/ni_coq/vfiles/EvAugSemantics.v, experimental/ni_coq/vfiles/Parameters.v, experimental/ni_coq/vfiles/PossibilisticNI.v, experimental/ni_coq/vfiles/RuntimeModel.v, experimental/ni_coq/vfiles/TraceTheorems.v
This commit includes a proof of possibilistic_ni_1step in
PossibilisticNI.v, which is the unwinding condition. However, it still
depends on several theorems are still admitted, but should be true. The
definition for havocking calls for nodes that have just executed has
also been fixed in the system-wide state transition relation.
Previously, the call havocking part of the definition assumed that the
contents of the node have not changed as a result of the node's
execution, but clearly that is wrong. Now it properly updates the
(possibly changed) node that is pointed to by the node id that was
executed.
construction.
=> Possibilistic single-step for system transition

examples/http_server/client/src/main.rs, oak_abi/src/lib.rs, oak_runtime/src/node/http/mod.rs, oak_runtime/src/node/http/tests.rs
Ref [this comment](https://github.com/project-oak/oak/pull/1398#discussion_r478527779).
=> Allow both JSON and protobuf labels in HTTP requests

oak_runtime/introspection_browser_client/index.tsx, oak_runtime/introspection_browser_client/tsconfig.json
Implements the logic to deduct the state of an Oak application from a list of events describing state mutations. "Time traveling" to view a past state then becomes as easy as calculating the state from a subset of the present event list.
The UI currently isn't very pretty and shows only the current state. I'll be working with a designer to create a more beautiful and useful version.
construction.
=> Introspection client: Get state from events

Dockerfile, docs/programming-oak.md, examples/hello_world/client/nodejs/index.js, oak_runtime/introspection_browser_client/components/ApplicationStateOverview/index.tsx, oak_runtime/introspection_browser_client/components/Root/index.tsx, oak_runtime/introspection_browser_client/webpack.config.js
See: https://prettier.io/blog/2020/03/21/2.0.0.html
Matches the major version of the Prettier VSCode plugin, thereby avoiding formatting inconsistencies between that & our format script.
construction.
=> Update prettier to version 2

experimental/ni_coq/vfiles/EvAugSemantics.v, experimental/ni_coq/vfiles/PossibilisticNI.v, experimental/ni_coq/vfiles/TraceTheorems.v
This PR, instead of proving the admitted lemma `step_system_multi_backwards`, removes the need for it by:
- flipping the order of transitivity in multi-step semantics so that forward steps are more natural
- replacing the use of `step_system_multi_backwards` with simpler reasoning based on the new semantics
Essentially, the change to the multi-step semantics made it so that, when constructing an inductive that proves there exists a sequence of valid steps starting with trace `t1` and ending with trace `t2`, we increase the sequence length by *adding events to `t2`*, rather than *removing them from `t1`*.
Most of the line-by-line changes are slight adjustments to the `TraceTheorems.v` proofs to match them with the new transitivity order.
cover any TODOs …
=> Remove need for step_system_multi_backwards admit

oak_runtime/introspection_browser_client/package-lock.json, oak_runtime/introspection_browser_client/package.json, oak_runtime/introspection_browser_client/webpack.config.js, oak_runtime/src/introspect.rs
Cuts the size of the generated JS bundle in half, so this seems sensible. 
construction.
=> Compress introspection client files with gzip

oak_runtime/introspection_browser_client/components/Root/index.tsx, oak_runtime/introspection_browser_client/components/StateGraph/index.tsx, oak_runtime/introspection_browser_client/package-lock.json, oak_runtime/introspection_browser_client/package.json, oak_runtime/introspection_browser_client/tsconfig.json, oak_runtime/introspection_browser_client/webpack.config.js, oak_runtime/src/introspect.rs
Replicates the behavior of Rust introspection by rendering the application state as a graph
construction.
=> Render oakApplicationState with graphviz

oak_runtime/introspection_browser_client/components/ApplicationStateOverview/index.tsx, oak_runtime/introspection_browser_client/components/Root/index.tsx, oak_runtime/introspection_browser_client/components/StateGraph/index.tsx, proto/introspection_events.proto
Good times. :) 
In the generated JavaScript code, the Google protobuf compiler converts `uint64` to the JavaScript `number`  type though that one only supports integers up to 2^53 - 1 .
This remedies this by appending `[jstype = JS_STRING]` to these fields and converting them to `BigInt`s on the client. 
construction.
=> Fix protobuf silently losing precision for 64 bit integers in JS

examples/Cargo.lock, examples/http_server/client/Cargo.toml, examples/http_server/client/src/main.rs
It should help debugging the issue described in https://github.com/project-oak/oak/pull/1461#discussion_r486658233
construction.
=> Make http_server example client actually log

rfcs/01391_async_sdk.md
Provide first class support for async Rust in the Oak SDK.
construction.
=> [RFC] Async SDK

oak_runtime/introspection_browser_client/package-lock.json
Updates `node-forge` (a subdependency required by the `webpack-dev-server`) to a newer version that removes methods vulnerable to prototype pollution. See details: https://github.com/project-oak/oak/network/alert/oak_runtime/introspection_browser_client/package-lock.json/node-forge/closed 
The vulnerability wasn't particularly urgent for our use-case, the affected package was only used in the dev-environment, but this patches it. :) 
construction.
=> Update vulnerable subdependency

oak_runtime/introspection_browser_client/.gitignore, oak_runtime/introspection_browser_client/build
Doing this allows for caching of webpack build steps down the line. (Ref: #1456)
construction.
=> Preserve last modified date for generated proto code

oak_runtime/introspection_browser_client/.gitignore, oak_runtime/introspection_browser_client/build, oak_runtime/introspection_browser_client/webpack.config.js
Implements the same behavior as #1476, with the same bash logic as applied to generated proto code in #1485. 
Issue ref: #1456
construction.
=> Preserve last modified date for webpack output

experimental/ni_coq/Makefile.conf, experimental/ni_coq/_CoqProject, experimental/ni_coq/vfiles/LowEquivalences.v, experimental/ni_coq/vfiles/NIUtilTheorems.v, experimental/ni_coq/vfiles/PossibilisticNI.v, experimental/ni_coq/vfiles/Unwind.v
This commit finishes a proof of the single-step, single-threaded
unwinding condition for just the write call and just in the case where
the label of the node making the call does flow to the label of the
observer. Several new smaller theorems are introduced but admitted for
now. They should be relatively simple. The files are reorganized a bit.
construction.
=> Write call single-step, single-thread unwind

chrome_extension/README.md, chrome_extension/background.js, chrome_extension/content.js, chrome_extension/manifest.json
This is a very experimental placeholder, which exposes an API for tabs
to switch to "Oak private mode", allowing the extension to then
intercept and block requests.
Ref #1492
construction.
=> Create Oak Chrome extension skeleton

experimental/ni_coq/vfiles/EvAugSemantics.v, experimental/ni_coq/vfiles/GenericMap.v, experimental/ni_coq/vfiles/LowEquivalences.v, experimental/ni_coq/vfiles/NIUtilTheorems.v, experimental/ni_coq/vfiles/Parameters.v, experimental/ni_coq/vfiles/PossibilisticNI.v, experimental/ni_coq/vfiles/RuntimeModel.v, experimental/ni_coq/vfiles/Unwind.v
Following discussion with @jadephilipoom,  this commit removes the ssreflect
finmap in favor of using the old simpler GenericMap.v implementation of
finite maps. SSReflect is a fairly complicated library that turns out to
be closer to a whole new dialect of coq. Given that the only use for it
was finite maps and we are not doing computation on maps, it seems
best to just use simpler maps.
construction.
=> Move back to GenericMap

oak_runtime/src/introspect.rs, oak_runtime/src/lib.rs, oak_runtime/src/node/mod.rs, oak_runtime/src/proxy.rs
This decouples the Runtime object from the details of how specific nodes
are created, which may vary based on platform or purpose in which the
Runtime is instantiated.
Ref #1497
construction.
=> Split node creation logic into separate trait

experimental/ni_coq/README.md, experimental/ni_coq/vfiles/Events.v, experimental/ni_coq/vfiles/Unwind.v
Follow-up to  af58235b7a8bd441c639b2b9ae093c0f563f99d7
Since I've swapped out my laptop, I was building without `mathcomp-finmap` installed, and found one lingering import that apparently affected the behavior of one proof. This PR:
- removes the lingering import
- fixes the single affected proof
- removes the line on the README saying mathcomp-finmap is a dependency
construction.
=> Build without mathcomp-finmap installed

oak_runtime/introspection_browser_client/components/EventList/index.tsx
In #1472 I added the `reversed` tag to the HTML list, but neglected to reverse the array of events to match it.
Before:
After:
construction.
=> Introspection: Patch incorrect event order in the Event List tab

experimental/ni_coq/_CoqProject, experimental/ni_coq/vfiles/Tactics.v, experimental/ni_coq/vfiles/TraceTheorems.v
In preparation for doing more proof automation, I moved the more general-purpose tactics from `TraceTheorems.v` into their own file and, since they'll now be exported for use in other files, I added some tests for them. The tests aren't strictly necessary, but they can be a nice warning system if you change the expected behavior of a tactic that's used in multiple files, so I think they might come in handy.
construction.
=> Move tactics into their own file and test them

LICENSE
This reverts commit 1f67e3b602f5ad2f72aa2be1c88412fcccedef33.
See updated (2020-07-08) advice at:
https://opensource.google/docs/releasing/preparing/#Apache-header
=> Revert "LICENSE: fill in copyright placeholder (#967)"

oak_runtime/introspection_browser_client/components/ApplicationStateOverview/index.tsx, oak_runtime/introspection_browser_client/components/ChannelDetails/index.tsx, oak_runtime/introspection_browser_client/components/HandleDetails/index.tsx, oak_runtime/introspection_browser_client/components/NodeDetails/index.tsx, oak_runtime/introspection_browser_client/components/Root/index.tsx, oak_runtime/introspection_browser_client/components/StateGraph/index.tsx
These will be rendered as strings either way, there's little value in converting handles/channels/nodes from protobuf strings to BigInts and then back to strings for rendering. 
I used BigInts for accuracy (and since it would be correct for `google-protobuf` to return them for 64 bit integers) but it seems best to be pragmatic. ^^ 
construction.
=> Move from BigInts to strings for simplicity

docs/abi.md, examples/abitest/module_0/rust/src/lib.rs, oak/module/oak_abi.h, oak_abi/src/lib.rs, oak_runtime/src/lib.rs, oak_runtime/src/node/wasm/mod.rs, oak_runtime/src/proxy.rs, oak_services/proto/http_encap.proto, sdk/rust/oak/src/lib.rs, sdk/rust/oak/src/stubs.rs
This PR adds functionality to allow WASM nodes to view their labels and downgrading privilege, and the labels associated with channel handles.
The ABI documentation changes were copied from #1137
Fixes #1406
construction.
=> Add ABI support for node and channel labels

oak_runtime/src/lib.rs
An introspection event already existed for `channel_read`, but was missing when reading messages via this message.
construction.
=> Add missing introspection event for channel_try_read_message

examples/Cargo.lock, examples/http_server/module/Cargo.toml, examples/http_server/module/src/lib.rs, oak_loader/Cargo.lock, oak_runtime/Cargo.lock, oak_runtime/src/node/http/mod.rs, oak_runtime/src/node/http/tests.rs, oak_services/Cargo.lock, oak_services/Cargo.toml, oak_services/proto/http_encap.proto, oak_services/src/http/mod.rs, oak_services/src/lib.rs, sdk/Cargo.lock, sdk/rust/oak/Cargo.toml, sdk/rust/oak/src/http/mod.rs
=> Use idiomatic HTTP types in the SDK

examples/Cargo.lock, examples/Cargo.toml, examples/private_set_intersection/client/rust/Cargo.toml, examples/private_set_intersection/client/rust/build.rs, examples/private_set_intersection/client/rust/src/lib.rs, examples/private_set_intersection/client/rust/src/main.rs, examples/private_set_intersection/example.toml
This change adds a Rust Private Set Intersection client.
=> Add PSI Rust client

experimental/ni_coq/vfiles/EvAugSemantics.v, experimental/ni_coq/vfiles/Events.v, experimental/ni_coq/vfiles/TraceTheorems.v, experimental/ni_coq/vfiles/Unwind.v
In EvAugSemantics, an event for node creation is added. I think this is
more accurate because presumably an attacker can tell whether or not a
node gets created.
I think it still does not make sense to add an event for node creation
because node creation can only be observed indirectly (i.e., an attacker
writes code that tries to read or write from a channel to see if the channel
exists). The events for read/write will capture these potential indirect
leaks.
Things to do with changing the call in the last node to execute when
constructing traces are removed. These are no longer needed now that
there is a single step semantics on just states and traces are built
separately.
A note about connecting system_step and system_step_ev are added.
cover any TODOs …
=> Event for node creation. Prune old things. A TODO

oak_runtime/introspection_browser_client/components/StateGraph/index.tsx
Got some help from a designer, she suggest this styling to make the graph more legible. 
Now:
Before:
construction.
=> Improve graph styles

examples/Cargo.lock, examples/aggregator/backend/Cargo.toml, examples/aggregator/backend/src/main.rs, examples/aggregator/example.toml, examples/trusted_information_retrieval/backend/src/main.rs, experimental/Cargo.lock
This change:
- Adds aggregator backend to CI
- Updates aggregator and PIR backends (adds `anyhow`)
=> Fix aggregator backend

experimental/ni_coq/vfiles/PossibilisticNI.v
Follow-up to discussion here: https://github.com/project-oak/oak/pull/1535#discussion_r499647876
The reason the plain `Hint Resolve`s weren't working was that `state_upd_node_unwind` produces a `node_low_eq` subgoal, and there's no declared `Reflexive` instance for that definition. Using an explicit `Hint Extern` tells `eauto` to unfold the definition until it finds an equality underneath. So I was wrong to suspect in the previous discussion that it was an `eapply` unfolding things more aggressively than `eauto` does; it was actually `reflexivity`!
construction.
=> Create 'unwind' hint db for eauto

oak_runtime/src/introspect.rs
Fixes a bug introduced in #1560 that led to serving the string file path instead of the actual file. 😬
construction.
=> Introspection: (Re)add missing include_bytes! call

experimental/ni_coq/vfiles/PossibilisticNI.v, experimental/ni_coq/vfiles/TraceTheorems.v
I put together some tactics and used them to automate the `possibilistic_ni` proof. Also proves a small admit in `TraceTheorems.v`. The proof structure here is actually pretty similar to before; it's just that the tactics are handling manipulations like plugging one hypothesis into the other.
construction.
=> Automate possibilistic_ni proof and prove no_steps_from_empty

examples/Cargo.lock, examples/abitest/client/cpp/BUILD, examples/abitest/client/cpp/abitest.cc, examples/abitest/client/cpp/httplib_config.h, examples/abitest/client/cpp/httptest.cc, examples/abitest/client/cpp/httptest.h, examples/abitest/module_0/rust/Cargo.toml, examples/abitest/module_0/rust/src/lib.rs, examples/http_server/example.toml, examples/http_server/module/src/lib.rs, oak_runtime/src/node/http/mod.rs, oak_runtime/src/tls.rs, runner/src/main.rs, sdk/rust/oak_tests/src/lib.rs
Fixes #1334.
The uncovered code is error checking logic that would be very difficult to simulate in the tests.
=> Add abitests for HTTP server pseudo-node

oak_runtime/introspection_browser_client/components/Event/index.tsx, oak_runtime/introspection_browser_client/components/Root/index.tsx, oak_runtime/introspection_browser_client/package-lock.json, oak_runtime/introspection_browser_client/package.json
Uses [session storage](https://developer.mozilla.org/en/docs/Web/API/Window/sessionStorage) to persist application state across page refreshes & links. 
Prevents state from resetting when navigating via native links etc
construction.
=> Introspection: Persist state across links & page refreshes

experimental/web/README.md, experimental/web/index.html
Very barebones, only stubs all Oak ABI calls instead of doing anything
useful with them.
Demo:
https://screencast.googleplex.com/cast/NTc0OTA3NTU3ODE5MTg3Mnw1NmE2ZGUyNi1lMw
Ref: #1067
construction.
=> Initial web emulator

docs/programming-oak.md, examples/abitest/module_0/rust/src/lib.rs, examples/aggregator/module/rust/src/lib.rs, examples/chat/module/rust/src/backend.rs, examples/chat/module/rust/src/lib.rs, examples/hello_world/module/rust/src/lib.rs, examples/http_server/module/src/lib.rs, examples/injection/module/rust/src/lib.rs, examples/machine_learning/module/rust/src/lib.rs, examples/private_set_intersection/module/rust/src/lib.rs, examples/running_average/module/rust/src/lib.rs, examples/translator/module/rust/src/lib.rs, examples/trusted_database/module/rust/src/handler.rs, examples/trusted_database/module/rust/src/lib.rs, examples/trusted_information_retrieval/module_0/rust/src/lib.rs, examples/trusted_information_retrieval/module_1/rust/src/lib.rs, oak_io/src/handle.rs, oak_io/src/receiver.rs, sdk/rust/oak/src/grpc/mod.rs, sdk/rust/oak/src/lib.rs
This makes more sense as the command handling logic is only potentially
part of a Node, but not a Node per se.
construction.
=> Rename `Node` to `CommandHandler`.

examples/abitest/module_0/rust/tests/integration_test.rs, examples/trusted_database/module/rust/tests/integration_test.rs, sdk/rust/oak_tests/src/lib.rs
This change adds an option to compile release Wasm in tests (necessary for benchmarking).
=> Add an option to compile release Wasm in tests

sdk/rust/oak_tests/src/lib.rs
This change renames `cargo_path` to `manifest_path` in `oak_tests`.
=> Rename cargo_path to manifest_path

experimental/web/index.html
This uses the https://github.com/protobufjs/protobuf.js library and
loads the proto descriptors from GitHub.
Ref #1067
construction.
=> Parse protobuf messages in web emulator

experimental/Cargo.lock, experimental/oak_async/src/io.rs, experimental/oak_async/src/lib.rs, experimental/oak_async/tests/tests.rs
construction.
Adds a `ChannelReadStream` type implementing [`Stream`](https://docs.rs/futures/0.3.5/futures/stream/trait.Stream.html) to the async sdk.
This PR builds on top of #1466.
For more background, please see the [RFC#01391](
https://github.com/project-oak/oak/blob/main/rfcs/01391_async_sdk.md).
=> Add async channel stream

sdk/rust/oak_tests/src/lib.rs
This change fixes `module_path` in `compile_rust_wasm`
=> Fix module_path in compile_rust_wasm

experimental/ni_coq/vfiles/PossibilisticNI.v
Based on conversation with @aferr, this change implements a tactic that applies all the system/node constructors before any of the generated subgoals are solved. That way, we can use `eexists` instead of manually repeating the new state based on the constructor, which should help the proof keep pace with future changes. ~Also, it seems to help out `eauto with unwind`, which now solves the subgoal it was struggling with before!~ ~(Edit: never mind, CI says no so fixing)~ (Edit again: I accidentally deleted a `Hint Extern`, now it works again!)
construction.
=> Apply all constructors first to automatically construct new state

oak_loader/Cargo.lock, oak_runtime/src/node/grpc/client.rs, oak_runtime/src/time/mod.rs
This change updates `futures_util` from 0.3.5 to 0.3.6 in `oak_loader`
=> Update futures_util from 0.3.5 to 0.3.6

runner/Cargo.lock, runner/Cargo.toml, runner/deny.toml, runner/src/internal.rs, runner/src/main.rs
It was not working correctly after introducing the async model anyways,
and it depends on a number of outdated crates. It may be reintroduced
properly in the future based on this commit, if necessary.
Fix #1269
Fix #1270
Fix #1595
=> Remove file watching functionality from Runner

sdk/rust/oak/src/io/receiver.rs, sdk/rust/oak/src/io/sender.rs
Deduplicate and canonicalize method documentation.
construction.
=> Expose label methods from sender and receiver

examples/aggregator/backend/src/main.rs, examples/authentication/client/src/auth_client.rs, examples/hello_world/client/rust/src/main.rs, examples/private_set_intersection/client/rust/src/main.rs, examples/trusted_database/client/rust/src/main.rs, examples/trusted_information_retrieval/backend/src/main.rs, examples/trusted_information_retrieval/client/rust/src/main.rs, experimental/split_grpc/client/src/main.rs, experimental/split_grpc/server/src/main.rs
This change replaces `tokio::fs::read` with `std::fs::read`, because `tokio::fs::read` is an unnecessary complication in these particular examples.
=> Replace tokio::fs::read with std::fs::read

examples/aggregator/module/rust/src/lib.rs
Replacing `Client::new_with_label` with `Client::new` because Aggregator uses a `public_untrusted` label for gRPC client.
=> Use default gRPC client label in Aggregator

sdk/rust/oak/src/grpc/client.rs
This change fixes channel label in gRPC client.
Previously, when gRPC client node was created with a specific label, the corresponding channel didn't have one (only had a public label).
=> Create labeled channel in gRPC client

docs/programming-oak.md, examples/abitest/module_0/rust/src/lib.rs, examples/abitest/module_1/rust/src/lib.rs, examples/aggregator/module/rust/src/lib.rs, examples/chat/module/rust/src/lib.rs, examples/injection/module/rust/src/lib.rs, examples/trusted_database/module/rust/src/lib.rs, sdk/rust/oak/src/grpc/client.rs, sdk/rust/oak/src/grpc/mod.rs, sdk/rust/oak/src/grpc/server.rs, sdk/rust/oak/src/http/mod.rs, sdk/rust/oak/src/io/mod.rs, sdk/rust/oak/src/lib.rs, sdk/rust/oak/src/logger/mod.rs
This is a preparatory change for #1615.
construction.
=> Make label compulsory for `oak::channel_create`

docs/programming-oak.md, examples/abitest/module_0/rust/src/lib.rs, examples/aggregator/module/rust/src/lib.rs, examples/chat/module/rust/src/lib.rs, examples/injection/module/rust/src/lib.rs, examples/trusted_database/module/rust/src/lib.rs, sdk/rust/oak/src/grpc/client.rs, sdk/rust/oak/src/grpc/server.rs, sdk/rust/oak/src/http/mod.rs, sdk/rust/oak/src/lib.rs, sdk/rust/oak/src/logger/mod.rs
This is a preparatory change for #1615.
construction.
=> Make label mandatory on `oak::node_create`

examples/deny.toml, experimental/deny.toml, oak_abi/deny.toml, oak_client/deny.toml, oak_derive/deny.toml, oak_io/deny.toml, oak_loader/deny.toml, oak_runtime/deny.toml, oak_services/deny.toml, oak_sign/deny.toml, oak_utils/deny.toml, runner/deny.toml, sdk/deny.toml
An updated version of cargo-deny has started warning about wildcard versions for rust crates. This update explicitly allows wildcards to remove these warnings.
construction.
=> Remove cargo-deny warnings for wildcard versions

docs/programming-oak.md, examples/abitest/module_0/rust/src/lib.rs, examples/aggregator/module/rust/src/lib.rs, examples/chat/module/rust/src/lib.rs, examples/hello_world/module/rust/src/lib.rs, examples/http_server/module/src/lib.rs, examples/injection/module/rust/src/lib.rs, examples/machine_learning/module/rust/src/lib.rs, examples/private_set_intersection/module/rust/src/lib.rs, examples/running_average/module/rust/src/lib.rs, examples/translator/module/rust/src/lib.rs, examples/trusted_database/module/rust/src/handler.rs, examples/trusted_database/module/rust/src/lib.rs, sdk/rust/oak/src/io/receiver.rs, sdk/rust/oak/src/lib.rs
The logic is mostly refactored from the `run_command_loop` function,
which is now much simpler and allows passing in arbitrary iterator over
messages. This in turn will allow processing the incoming stream of
messages in a functional way, e.g. when combined with #1637.
Fixes #1593
construction.
=> Implement Iterator for Receiver

examples/Cargo.lock, experimental/Cargo.lock, oak_derive/Cargo.lock, oak_io/Cargo.lock, oak_io/Cargo.toml, oak_io/src/lib.rs, oak_loader/Cargo.lock, oak_runtime/Cargo.lock, oak_services/Cargo.lock, sdk/Cargo.lock
The `Either` type comes from the https://docs.rs/either/1.6.1/either/
crate instead of being re-implemented from scratch, as that has useful
methods already defined on it, and it is pretty lightweight.
This may be used as foundation for more interesting patterns related to
multiplexing several message types on the same channel, e.g. init and
command messages.
construction.
=> Implement Decodable and Encodable for Either type

.devcontainer.json, Dockerfile
Also configure VSCode dev container to use it, so that it is guaranteed
to work with the Rust version we use, and also fix settings so that it
works well with protobuf imports.
construction.
=> Install `rust-analyzer` in docker image

examples/Cargo.lock, examples/chat/module/rust/tests/integration_test.rs, experimental/Cargo.lock, oak_loader/Cargo.lock, oak_runtime/Cargo.lock, oak_sign/Cargo.lock, oak_sign/Cargo.toml, oak_sign/src/lib.rs, oak_sign/src/main.rs, oak_sign/src/tests.rs, sdk/Cargo.lock
This change:
- Refactors `oak_sign::KeyBundle` to `oak_sign::KeyPair`
- Adds more comments
- Implements `Clone` for `oak_sign::KeyPair` (necessary for tests)
Fixes https://github.com/project-oak/oak/issues/1620
=> Refactor oak sign key pair

oak_abi/proto/label.proto, oak_abi/src/label/mod.rs, oak_runtime/src/lib.rs, oak_runtime/src/node/grpc/server/mod.rs, oak_runtime/src/node/http/mod.rs, oak_runtime/src/tests.rs
=> Add top privilege tag

examples/Cargo.lock, examples/aggregator/module/rust/Cargo.toml, examples/aggregator/module/rust/src/lib.rs, examples/aggregator/proto/aggregator_init.proto
=> Use Either pattern to initialize aggregator node

examples/chat/module/rust/src/lib.rs, examples/chat/module/rust/tests/integration_test.rs, examples/chat/oak_app_manifest.toml, sdk/rust/oak/src/lib.rs
Introduce macro for setting up a Node with a CommandHandler instance.
Ref #1639
construction.
=> Implement planner + router + worker pattern

examples/abitest/client/cpp/httptest.cc, oak_runtime/src/node/http/mod.rs, oak_runtime/src/node/http/tests.rs
* Adds a new test for HttpServerNode
* Uses a router node in the http tests to allow serving requests with
non-empty request labels
* Fixes HttpServerNode to use base64 protobuf headers for request labels
=> Add an HTTP test with non-empty label

examples/chat/module/rust/src/lib.rs, examples/http_server/module/src/lib.rs, examples/injection/module/rust/src/lib.rs, examples/trusted_database/module/rust/src/lib.rs, sdk/rust/oak/src/grpc/mod.rs, sdk/rust/oak/src/lib.rs
This makes sense because there is only at most one implementation of
`CommandHandler` for each underlying type. Also allows cleaning up some
type bounds on a few methods.
construction.
=> Make command an associated type of CommandHandler

examples/chat/module/rust/src/lib.rs, sdk/rust/oak/src/grpc/server.rs, sdk/rust/oak/src/http/mod.rs
This allows creating a gRPC server node passing an existing channel to a
node that will receive invocations.
I expect that as we move towards a model in which the main node sets up
other nodes, but does not directly process requests, this new method
will be preferred instead of the existing one that also creates a local
channel from which to read invocations, since the main node would not
have any use for it.
Ref #1639
=> Add `init_with_sender` method for HTTP and gRPC 

docs/programming-oak.md, examples/chat/module/rust/src/lib.rs, oak_utils/src/lib.rs, sdk/rust/oak/src/io/mod.rs, sdk/rust/oak/src/lib.rs
This allows creating Wasm nodes in a type safe way, returning a channel
of the correct type for the particular node instance, as long as that
instance implements the corresponding traits.
Ref #1639
construction.
=> Implement type safe wasm entrypoint

examples/deny.toml, experimental/deny.toml, oak_client/deny.toml, oak_loader/deny.toml, oak_runtime/deny.toml, sdk/deny.toml
Ignoring the older version rather than the newer version should mean that cargo-deny should start warning when the old version is no longer used so that we can then clean it up.
construction.
=> Ignore older duplicate versions in deny.toml

examples/Cargo.lock, examples/abitest/module_0/rust/src/lib.rs, examples/hello_world/module/rust/Cargo.toml, examples/http_server/README.md, examples/http_server/module/src/lib.rs
=> Use type safe methods in http_server example

experimental/ni_coq/vfiles/NIUtilTheorems.v, experimental/ni_coq/vfiles/PossibilisticNI.v, experimental/ni_coq/vfiles/RuntimeModel.v, experimental/ni_coq/vfiles/Unwind.v
Notably, the way channel append works when writing to a channel needed
to be changed in order to make this provable. Because it is possible for
a public node to send a message to a secret channel, and because a
public observer cannot distinguish between a handle that points to a
secret channel and a handle that points to nothing (becuase the channel
was deleted for example), the write call cannot check whether or not the
handle is allocated because this would cause a leak. This potential leak made
step_implies_lowproj unprovable without changing the semantics.
The change is in chan_append_labeled and the semantics of the write call.
If the write call is to a handle that points to nothing, the write has no
effect and no error is thrown. See chan_append_labeled.
For similar reasons, the …
=> Prove step_implies_lowproj_steps_leq

examples/Cargo.lock, examples/hello_world/module/rust/Cargo.toml, examples/hello_world/module/rust/src/lib.rs, oak_io/src/lib.rs, oak_utils/src/lib.rs, sdk/rust/oak/src/io/mod.rs, sdk/rust/oak/src/lib.rs
Introduce a `WithInit` trait implemented by structs that correspond to
nodes that require receiving initialization data over their inbound
channel, before accepting command from the wrapped channel.
Currently there are two entrypoint-related macros, one for structs that
impl `Default` and do not require init data, and the new one for structs
that impl `WithInit`, which expect an `InitWrapper` message. It may be
possible to unify them in the future with some more macro magic, or we
may just decide to make everything impl `WithInit`, using `()` as init
in case the node does not require init data, but for now I think the
separation makes sense.
Ref #1639
construction.
=> Allow creating node entrypoint with init data

sdk/rust/oak_app_build/src/main.rs
This change adds a status check for downloading Wasm modules from URL, because `reqwest::get()` doesn't fail on 404
Fixes https://github.com/project-oak/oak/issues/1677
=> Fix Wasm module download from URL

examples/abitest/module_0/rust/src/lib.rs, examples/aggregator/module/rust/src/lib.rs, examples/hello_world/module/rust/src/lib.rs, oak_utils/src/lib.rs, sdk/rust/oak/src/grpc/client.rs, sdk/rust/oak/src/roughtime/mod.rs, sdk/rust/oak/src/storage/mod.rs
Most of them are not particularly useful now that we use `Sender` and
`Receiver` more extensively elsewhere in the SDK API.
construction.
=> Remove unnecessary types for gRPC client

experimental/ni_coq/vfiles/PossibilisticNI.v, experimental/ni_coq/vfiles/Unwind.v
A cleanup of work from a pair-programming session with @aferr. I changed the format of `state_upd_{node,chan}_unwind` because it was helpful for `eauto with unwind` to know what to plug in, but it would also work with the original version to do `eapply state_upd_node_unwind with (n1:=Labeled _ _ _); [ reflexivity .. | ]`.
I tried proving the new versions to make sure they were provable, but I don't think they are -- and I don't think the old ones are either, actually, without functional extensionality. The issue is that `low_eq` expects Leibniz equality (`eq`), but `nodes` and `chans` are both functions, so unless the two are constructed in exactly the same way they will not be Leibniz-equal. Was this addressed somehow in the previous version of the code, before labels were introduced? If …
=> Fix WriteChannel case for low_proj_steps_implies_leq_step

examples/Cargo.lock, examples/abitest/client/cpp/BUILD, examples/abitest/client/cpp/httptest.cc, examples/abitest/client/cpp/httptest.h, examples/http_server/client/rust/Cargo.toml, examples/http_server/client/rust/src/main.rs, oak/common/BUILD, oak_abi/build.rs, oak_abi/proto/BUILD, oak_abi/proto/identity.proto, oak_abi/proto/label.proto, oak_abi/src/label/mod.rs, oak_abi/src/lib.rs, oak_runtime/src/node/http/mod.rs, oak_runtime/src/node/http/tests.rs, oak_utils/src/lib.rs
Similar to #1586, but instead of using an intermediate `UserNode` it relies on the `top` privilege of the `HttpServerNode` to set the user's identity in the response channel. Moreover, it omits setting the user's identity in the integrity component of the request label. 
Ref #1357, #1428
=> Use challenge response for authentication

sdk/deny.toml
=> Remove unused `bans.skip` entries from the SDK's `deny.toml`

oak_utils/src/lib.rs, sdk/rust/oak/src/grpc/mod.rs
Instead of going back and forth between the generated code and the code
in `oak::grpc`, this change simplifies the logic of the dispatcher by
returning pointers to the appropriate methods based on method name. This
also allows accessing and manipulating those methods from other code,
enabling also reflection-like operations based on method names.
Ref #1691.
construction.
=> Generate simpler gRPC methods

docs/programming-oak.md, examples/abitest/module_0/rust/tests/integration_test.rs, examples/aggregator/module/rust/tests/integration_test.rs, examples/chat/module/rust/tests/integration_test.rs, examples/hello_world/module/rust/tests/integration_test.rs, examples/private_set_intersection/module/rust/tests/integration_test.rs, examples/running_average/module/rust/tests/integration_test.rs, examples/translator/module/rust/tests/integration_test.rs, examples/trusted_database/module/rust/tests/integration_test.rs, experimental/benchmark/src/application/oak.rs, oak_abi/proto/label.proto, sdk/rust/oak_tests/src/lib.rs
This change adds `Label` to `channel_and_interceptor` since currently we start to check incoming client labels in examples.
=> Add label to channels in oak_tests

experimental/ni_coq/vfiles/LowEquivalences.v, experimental/ni_coq/vfiles/NIUtilTheorems.v, experimental/ni_coq/vfiles/PossibilisticNI.v, experimental/ni_coq/vfiles/RuntimeModel.v, experimental/ni_coq/vfiles/Unwind.v
The commit messages are worth reading as a guide for the most significant changes,
particularly the commit message for "[WIP]Working on unobs; need significant def change"
The proof state is roughly where it was before despite the low-level definitional change.
I fixed and then unfixed the spacing in NIUtils to make the PR readable temporarily :) 
construction.
=> Low projection makes labels themselves partially secret

experimental/ni_coq/vfiles/NIUtilTheorems.v
These proofs all follow the general pattern from state_upd_chan_unobs.
Either the node_state_ or channel_state_low_proj Prop is irrelevant and
can be quickly addressed. The other is a universal Prop across map IDs,
so we split the cases for the node's ID (or channel's handle) vs other
IDs/handles. The equality case is the bulk of the rest of the proof;
the inequality case is simple.
=> Complete unobservable proofs

experimental/ni_coq/_CoqProject, experimental/ni_coq/vfiles/EvAugSemantics.v, experimental/ni_coq/vfiles/Events.v, experimental/ni_coq/vfiles/LowEquivalences.v, experimental/ni_coq/vfiles/ModelSemUtils.v, experimental/ni_coq/vfiles/ModelTypes.v, experimental/ni_coq/vfiles/NIUtilTheorems.v, experimental/ni_coq/vfiles/PossibilisticNI.v, experimental/ni_coq/vfiles/PossibilisticNI_def.v, experimental/ni_coq/vfiles/RuntimeModel.v, experimental/ni_coq/vfiles/State.v, experimental/ni_coq/vfiles/Tactics.v, experimental/ni_coq/vfiles/TraceLowEq.v, experimental/ni_coq/vfiles/Unfold.v, experimental/ni_coq/vfiles/Unwind.v
The goal of this refactor is to support:
- keeping around more than one definition of low-equivalence / low-projection and some of the lower-level theorems about those
(though they might not really be hot-swappable in the top-level proofs since some properties will be available with one 
set of definitions but not in the other)
- having multiple runtime models that can benefit from some common definitions
- having multiple security properties and disconnecting the property definitions from the models that have them.
construction.
=> Refactoring

examples/aggregator/client/android/cpp/client.cc, examples/aggregator/client/cpp/aggregator.cc, examples/aggregator/config.toml, examples/aggregator/module/rust/src/router.rs, examples/aggregator/oak_app_manifest.toml, examples/private_set_intersection/module/rust/src/lib.rs, examples/private_set_intersection/oak_app_manifest.toml, examples/private_set_intersection/private_set_intersection.sign, sdk/rust/oak/src/io/mod.rs
This change adds `forward_invocation` function that checks invocation receiver label before forwarding it and is used in `Router` Nodes.
=> Add forward_invocation function

examples/deny.toml, experimental/deny.toml, oak_abi/deny.toml, oak_client/deny.toml, oak_derive/deny.toml, oak_io/deny.toml, oak_loader/deny.toml, oak_runtime/deny.toml, oak_services/deny.toml, oak_sign/deny.toml, oak_utils/deny.toml, runner/deny.toml, sdk/deny.toml
We currently allow multiple versions anyway by just adding exceptions and then removing it later when no longer needed. This change means that we don't have to keep doing this maintenance for now while the versions are not very stable. We can add the checks in later for specific crates if exact versions become important.
Closes #1270 
construction.
=> Allow multiple versions of the same crate in cargo-deny

docs/programming-oak.md, examples/trusted_database/module/rust/Cargo.toml, examples/trusted_database/module/rust/build.rs, examples/trusted_database/module/rust/src/handler.rs, examples/trusted_database/module/rust/src/lib.rs, examples/trusted_database/module/rust/src/router.rs, examples/trusted_database/proto/trusted_database_init.proto
This change updates Trusted Database example to use Router pattern.
Ref https://github.com/project-oak/oak/issues/1066
=> Use Router in Trusted Database

docs/concepts.md, oak_abi/proto/application.proto
* Adds json schema files for IFC labels, generated using [protoc-gen-jsonschema](https://github.com/chrusty/protoc-gen-jsonschema)
* Updates documentation about the use of IFC labels with HTTP requests
=> Update docs about the use of labels with HTTP requests

examples/aggregator/common/src/lib.rs, examples/aggregator/common/src/tests.rs, examples/aggregator/module/rust/src/handler.rs
Remove an unnecessary layer of wrapping to keep track of exhaustion.
Make the API of ThresholdAggregator revolve around a single method.
construction.
=> Simplify aggregator API

.github/workflows/build_rust_docs.yaml, .github/workflows/ci.yaml, runner/src/internal.rs, runner/src/main.rs
This is in addition to the GCP run for the time being, and not blocking
for any submission, but it should give a faster feedback for some of the
steps since they are run in parallel.
=> Use GitHub Actions for CI

examples/Cargo.lock, experimental/Cargo.lock, oak_loader/src/options.rs, oak_runtime/src/config.rs, oak_runtime/src/lib.rs, oak_runtime/src/node/grpc/client.rs, oak_runtime/src/node/http/client.rs, oak_runtime/src/node/http/tests.rs, oak_runtime/src/node/mod.rs, oak_runtime/src/tests.rs, oak_runtime/src/tls.rs, sdk/Cargo.lock, sdk/rust/oak_tests/Cargo.toml, sdk/rust/oak_tests/src/lib.rs
=> Consistently pass the certificate as byte vector in the configurations

docs/concepts.md, docs/programming-oak.md, docs/sdk.md, examples/Cargo.lock, examples/abitest/module_0/rust/src/lib.rs, examples/http_server/client/rust/Cargo.toml, examples/http_server/client/rust/src/main.rs, examples/http_server/module/src/lib.rs, oak_services/src/http/mod.rs, sdk/rust/oak/src/http/client.rs, sdk/rust/oak/src/http/mod.rs, sdk/rust/oak/src/http/server.rs, sdk/rust/oak/src/http/util.rs, sdk/rust/oak/src/node_config.rs
=> Add SDK support for HTTP client pseudo-node

experimental/ni_coq/README.md, experimental/ni_coq/vfiles/LowProjPS_Thms.v, experimental/ni_coq/vfiles/ModelSemUtils.v, experimental/ni_coq/vfiles/NIUtilTheorems.v, experimental/ni_coq/vfiles/PossibilisticNI.v, experimental/ni_coq/vfiles/RuntimeModelPS.v
The definition of fresh_han and fresh_chan needed to be changed so
that the labels of unused objects is public. For the other definition
where labels are partially secret, I think this would need to stay
"top". Either way, fresh_han and fresh_chan are not really parts of the
implementation; in the implementation I think these objects are just
genuinely newly created objects.
There's also some fixup leftover from the last PR :) 
construction.
=> Finish NIUtils.v proofs

docs/programming-oak.md, examples/translator/module/rust/src/lib.rs
This change adds Router pattern and client labels to Translator example.
Translator creates individual Handler Nodes for each client request and assigns client labels to them.
Ref https://github.com/project-oak/oak/pull/1745
=> Use Router and labels in Translator

examples/hello_world/module/rust/src/handler.rs, examples/hello_world/module/rust/src/lib.rs
This change adds Router pattern and client labels to Hello World example.
Hello World creates individual Handler Nodes for each client request and assigns client labels to them.
Ref #1745
=> Use Router and labels in Hello World

experimental/ni_coq/vfiles/Unwind.v
I think set_call_unwind needs to be weakened.
construction.
=> Finish Unwind.v except set_call_unwind

scripts/docker_run
The current logic is not quite right; the thing that is missing from
GitHub action is the interactive STDIN, not the TTY itself. Fixing this
makes most commands detect the TTY correctly, which produces colored
outputs in logs etc.
=> Enable colorized output in GitHub actions logs

.gitignore
As part of the Treehouse project we may end up with files that we do not
intend to check in on different branches. This pattern allows calling
them with the same suffix in order to be ignored.
construction.
=> Add gitignore pattern for secrets

Dockerfile, arm64v8.Dockerfile
This change pins `cargo deadlinks` version to `0.5.0` in the Dockerfile.
Fixes https://github.com/project-oak/oak/issues/1776
=> Pin deadlinks version

oak_runtime/src/io.rs, oak_runtime/src/node/grpc/server/mod.rs, oak_runtime/src/node/http/server.rs, oak_runtime/src/node/http/tests.rs, oak_runtime/src/node/http/util.rs
This change:
- Adds typed `channel_create` and `channel_create_with_downgrade` to `oak_runtime`
- Updates gRPC server and HTTP tests with new functions
Fixes https://github.com/project-oak/oak/issues/1496
=> Add typed channel_create in Oak Runtime

examples/http_server/module/src/lib.rs, sdk/rust/oak/src/http/client.rs, sdk/rust/oak/src/http/mod.rs
This change:
- Adds `create_http_invocation` function
- Refactors `http_server` example
Ref https://github.com/project-oak/oak/issues/1832
=> Add create_http_invocation function

examples/Cargo.lock, experimental/Cargo.lock, oak_loader/Cargo.lock, oak_runtime/Cargo.lock, sdk/Cargo.lock, sdk/rust/oak/src/io/receiver.rs
This change adds a status check after `receiver.wait`.
Fixes https://github.com/project-oak/oak/issues/1796
=> Add NotReady check in receive function

docs/abi.md, examples/abitest/module_0/rust/src/lib.rs, oak/module/oak_abi.h, oak_abi/src/lib.rs, oak_runtime/src/lib.rs, oak_runtime/src/node/wasm/mod.rs, oak_runtime/src/proxy.rs, oak_runtime/src/tests.rs, sdk/rust/oak/src/stubs.rs
construction.
This adds a new ABI call `handle_clone` and implements it in the Oak runtime. This function can be used to create distinct read handles. Following PRs will change the SDK implementations of handles to correctly implement `Clone` and `Drop` based on `handle_clone` and `channel_close`, so that the runtime can keep track of the number of live channel handles.
Background: https://github.com/project-oak/oak/issues/1686#issuecomment-731309914
=> Add handle_clone to ABI and runtime.

examples/trusted_database/client/rust/src/main.rs
Leftover from #1707! I had not realized the request label was meant to be set to the user's identity!
=> Use user's identity as the request label in the Trusted Database example

.github/workflows/ci.yaml
Currently it seems our CI workflow is running out of space. 
Some PRs where this is happening:
https://github.com/project-oak/oak/pull/1843
https://github.com/project-oak/oak/pull/1846
https://github.com/project-oak/oak/pull/1857
This tries to patch it by removing some prebuilt tools included by GitHub to free up more space. 
An approach recommend here: https://github.com/actions/virtual-environments/issues/709#issuecomment-612569242
And used by big repos such as https://github.com/facebook/proxygen
construction.
=> Remove unused tools to free up CI disk space

BUILD, WORKSPACE, toolchain/BUILD, toolchain/cc_toolchain_config.bzl, toolchain/clang_arm.sh
This change makes Bazel select between ARM and x86 versions of `clang`.
=> Add Clang for ARM

examples/hello_world/client/nodejs/index.js, examples/hello_world/client/nodejs/oakSign.js, examples/hello_world/client/nodejs/package-lock.json, examples/hello_world/client/nodejs/package.json
Uses https://github.com/paulmillr/noble-ed25519, a dependency free ed25519 JS implementation. 
The [WebCrypto API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API) doesn't yet support ed25519, but `noble-ed25519` uses it under the hood when possible. 
One noteworthy thing is that the Node.js built in crypto lib technically does support `ed25519`, however for a reason I haven't yet understood, it appears to work with 44byte public keys, and doesn't work with the runtime. 
Thinking about building an example that works in the browser and via http after.  
construction.
=> Implement challenge reponse signing in JS

examples/abitest/module_0/rust/src/lib.rs, examples/aggregator/README.md, examples/aggregator/client/android/cpp/client.cc, examples/aggregator/client/cpp/aggregator.cc, examples/aggregator/config.toml, examples/aggregator/oak_app_manifest.toml, examples/private_set_intersection/oak_app_manifest.toml, examples/private_set_intersection/private_set_intersection_handler.sign, experimental/oak_async/tests/fake_runtime.rs, oak/module/oak_abi.h, oak_abi/src/lib.rs, oak_runtime/src/lib.rs, oak_runtime/src/node/wasm/mod.rs, oak_runtime/src/proxy.rs, sdk/rust/oak/src/io/receiver.rs, sdk/rust/oak/src/lib.rs, sdk/rust/oak/src/stubs.rs
This change adds:
- `channel_read_with_downgrade` to ABI and SDK
- `channel_try_read_message_with_downgrade` to Runtime
Ref https://github.com/project-oak/oak/issues/1736
=> Add channel_read_with_downgrade to SDK

oak_runtime/src/channel.rs
This makes the label information for channels visible in the
introspection graph.
construction.
=> runtime: include label in channel half info

.github/workflows/ci.yaml, examples/Cargo.lock, examples/Cargo.toml, examples/proxy_attestation/client/rust/Cargo.toml, examples/proxy_attestation/client/rust/build.rs, examples/proxy_attestation/client/rust/src/lib.rs, examples/proxy_attestation/client/rust/src/main.rs, examples/proxy_attestation/example.toml, examples/proxy_attestation/module/rust/Cargo.toml, examples/proxy_attestation/module/rust/build.rs, examples/proxy_attestation/module/rust/src/lib.rs, examples/proxy_attestation/oak_app_manifest.toml, examples/proxy_attestation/proto/proxy_attestation_example.proto, experimental/Cargo.lock, experimental/Cargo.toml, experimental/proxy_attestation/Cargo.toml, experimental/proxy_attestation/build.rs, experimental/proxy_attestation/proto/proxy_attestation.proto, experimental/proxy_attestation/src/certificate.rs, experimental/proxy_attestation/src/lib.rs, experimental/proxy_attestation/src/main.rs, oak_loader/Cargo.lock, oak_loader/Cargo.toml, oak_loader/src/attestation.rs, oak_loader/src/main.rs, oak_loader/src/options.rs, runner/src/internal.rs, runner/src/main.rs
This change adds Proxy Attestation example.
It consists of:
- `experimental/proxy_attestation`: CA that can create signed certificates based on certificate signing requests
- `examples/proxy_attestation/client`: Client that can request the CA root certificate and use it to connect to an Oak application
- `examples/proxy_attestation/module`: Simple example Oak application
Certificate signing requests are created by `oak_loader`.
Fixes https://github.com/project-oak/oak/issues/1860
Ref https://github.com/project-oak/oak/issues/1374
=> Add Proxy Attestation example

examples/Cargo.lock, examples/Cargo.toml, examples/abitest/example.toml, examples/abitest/module_0/rust/src/lib.rs, examples/abitest/module_0/rust/tests/integration_test.rs, examples/abitest/module_linear_handles/rust/Cargo.toml, examples/abitest/module_linear_handles/rust/src/lib.rs, examples/abitest/oak_app_manifest.toml, oak_io/Cargo.toml, oak_io/src/handle.rs, oak_io/src/receiver.rs, oak_io/src/sender.rs, oak_loader/Cargo.lock, sdk/rust/oak/Cargo.toml
construction.
The feature enables what I hope will eventually be the default behaviour for handles. Roughly speaking, this does 3 things:
- Make handles non-`Copy`
- Add a `Clone` impl that calls `oak_abi::handle_clone`
- Add a `Drop` impl that calls `oak_abi::channel_close`
This builds on #1782.
Related issue: #1686. It is step (3) in https://github.com/project-oak/oak/issues/1686#issuecomment-765351586.
=> Add linear-handles feature to oak_io

oak_loader/Cargo.lock, sdk/rust/oak/src/io/mod.rs, sdk/rust/oak/src/io/receiver.rs, sdk/rust/oak/src/io/sender.rs, sdk/rust/oak/src/lib.rs
This is currently not needed because handles implement `Copy`, but once
they are made linear, using borrowed handles will be the only way to use
these functions without giving up ownership of the handle.
construction.
Related issue: #1686
=> Allow passing borrowed handles to SDK functions.

oak_client/Cargo.lock, scripts/build_gh_pages, scripts/common
This change adds `oak_client` to Bash scripts that generate and check Rust docs.
=> Generate docs for oak_client

oak_runtime/src/lib.rs, oak_runtime/src/node/crypto/mod.rs, oak_runtime/src/node/grpc/client.rs, oak_runtime/src/node/grpc/server/mod.rs, oak_runtime/src/node/http/client.rs, oak_runtime/src/node/http/server.rs, oak_runtime/src/node/http/tests.rs, oak_runtime/src/node/logger.rs, oak_runtime/src/node/mod.rs, oak_runtime/src/node/wasm/mod.rs, oak_runtime/src/proxy.rs, oak_runtime/src/tests.rs
Note to reviewers: please double check I am not mixing up privileges for
the various node types, thanks!
construction.
=> Centralize node privilege assignment

examples/Cargo.lock, examples/abitest/module_0/rust/src/lib.rs, examples/abitest/module_linear_handles/rust/Cargo.toml, examples/abitest/module_linear_handles/rust/src/lib.rs, oak_io/src/receiver.rs, sdk/rust/oak/Cargo.toml, sdk/rust/oak/src/io/mod.rs, sdk/rust/oak/src/io/receiver.rs
=> Add linear-handles feature to SDK.

examples/abitest/module_0/rust/src/lib.rs, examples/aggregator/client/android/cpp/client.cc, examples/aggregator/client/cpp/aggregator.cc, examples/aggregator/config.toml, examples/aggregator/oak_app_manifest.toml, examples/private_set_intersection/oak_app_manifest.toml, examples/private_set_intersection/private_set_intersection_handler.sign, experimental/oak_async/tests/fake_runtime.rs, oak/module/oak_abi.h, oak_abi/src/lib.rs, oak_runtime/src/node/wasm/mod.rs, oak_runtime/src/proxy.rs, sdk/rust/oak/src/io/receiver.rs, sdk/rust/oak/src/lib.rs, sdk/rust/oak/src/stubs.rs
This change adds:
- `wait_on_channels_with_downgrade` to ABI, SDK andRuntime
Fixes https://github.com/project-oak/oak/issues/1736
=> Add wait_on_channels_with_downgrade to SDK

.github/workflows/ci.yaml, examples/abitest/module_0/rust/Cargo.toml, examples/abitest/module_0/rust/src/lib.rs, oak_loader/Cargo.toml, oak_loader/src/main.rs, oak_loader/src/options.rs, oak_runtime/Cargo.toml, oak_runtime/src/introspect.rs, oak_runtime/src/introspection_events.rs, oak_runtime/src/lib.rs, oak_runtime/src/node/http/tests.rs, oak_runtime/src/node/logger.rs, oak_runtime/src/node/mod.rs, oak_runtime/src/permissions.rs, oak_runtime/src/proxy.rs, runner/src/internal.rs, runner/src/main.rs, sdk/rust/oak/src/logger/mod.rs
* `kebab-case` seems to be more conventional for feature names, so the feature names are updated
* Merges `kms` and `experimental` server variants in the runner
* Adds doc comments for server variants
* Adds a new step to `run_ci` and github CI for running the `hello_world` example with the base server and a permissions file.
=> Improve the use of features with server variants in the runner

.github/workflows/ci.yaml, scripts/git_check_diff
This change updates github CI actions to match Google Cloud Build.
Required for https://github.com/project-oak/oak/pull/1819 in order to disable GCB CI and completely move to github CI.
=> Update github CI

examples/injection/module/rust/Cargo.toml, examples/injection/module/rust/src/lib.rs, sdk/rust/oak/src/io/sender.rs
construction.
Tracking issue: #1854
=> Migrate injection example to use linear-handles feature.

examples/Cargo.lock, examples/proxy_attestation/client/rust/Cargo.toml, examples/proxy_attestation/client/rust/src/main.rs, examples/proxy_attestation/module/rust/src/lib.rs, experimental/Cargo.lock, experimental/Cargo.toml, experimental/attestation_common/Cargo.toml, experimental/attestation_common/src/lib.rs, experimental/attestation_common/src/tests.rs, experimental/proxy_attestation/Cargo.toml, experimental/proxy_attestation/src/certificate.rs, experimental/proxy_attestation/src/main.rs, oak_client/Cargo.lock, oak_client/Cargo.toml, oak_client/src/attestation.rs, oak_client/src/lib.rs, oak_loader/Cargo.lock
This commit adds a Proxy Attestation client with a custom TLS certificate verifier, that checks TEE quotes in X.509 TEE extensions.
Fixes https://github.com/project-oak/oak/issues/1861
=> Add Rust Proxy Attestation client

Dockerfile, examples/aggregator/README.md, examples/aggregator/client/android/cpp/client.cc, examples/aggregator/client/cpp/aggregator.cc, examples/aggregator/config.toml, examples/aggregator/oak_app_manifest.toml, examples/private_set_intersection/README.md, examples/private_set_intersection/oak_app_manifest.toml, examples/private_set_intersection/private_set_intersection_handler.sign, scripts/docker_build
This change:
- Prevents Docker from depending on the username
- Makes Wasm modules reproducibly buildable inside Docker on different machines (by making rust library paths have the same user)
Fixes https://github.com/project-oak/oak/issues/865
=> Fix Wasm module reproducibility

.github/workflows/ci.yaml, Dockerfile, runner/src/internal.rs, runner/src/main.rs
Use latest version of `cargo-deny` to avoid git fetch failure errors: 
```
2021-03-08 18:51:23 [ERROR] failed to fetch advisory database: git operation failed: reference 'refs/heads/master' not found; class=Reference (4); code=NotFound (-3)
```
Ref: https://github.com/EmbarkStudios/cargo-deny/pull/336
Also splits the `run-tests` step in github-ci to `run-cargo-test` and `run-bazel-test` to avoid the `No space left on device` problem.
=> Update cargo-deny version in Dockerfile

examples/Cargo.lock, examples/proxy_attestation/module/rust/Cargo.toml, examples/trusted_database/client/rust/Cargo.toml, examples/trusted_database/example.toml, experimental/Cargo.lock, experimental/split_grpc/client/Cargo.toml, runner/src/main.rs
construction.
When running things like `cargo check` and `cargo clippy` on a workspace instead of a separate crate, Cargo's behaviour is a bit weird, especially regarding crate features. All crates in the workspace will be compiled with the same feature flags, which can result in output different than if the commands were run for the crates individually, e.g.
- This PR add the `rt-multi-thread` feature to the `tokio` dependency of `experimental/split_grpc/client`. Omitting this result in an error when building the crate on its own, but that is hidden from CI because the `proxy` crate depends on `tokio` with the `full` feature enabled, which transitively enables the same feature for the entire workspace.
- With the …
=> Run checks per crate, not workspace.

docs/programming-oak.md
Adds programming guides about the use of HTTP client pseudo node.
=> Add client guides in the oak programming doc

.github/workflows/ci.yaml
Make `runner` print out commands (useful to retry a single step that is
failing).
=> Free up more space in GitHub actions runners

examples/aggregator/backend/src/main.rs, examples/aggregator/example.toml, examples/proxy_attestation/example.toml, experimental/proxy_attestation/src/main.rs, runner/src/main.rs
This change:
- Adds the ability to run multiple backend servers in Oak examples
- Makes running `applications` not mandatory (for examples that do not involve Oak modules)
=> Run multiple backends

runner/src/main.rs
This change allows `runner` to run examples that do not have `applications` specified.
=> Run examples with no applications

examples/proxy_attestation/example.toml, runner/src/main.rs
This change restores the ability to run examples with no clients.
Required for `reproducibility` builds.
=> Run examples with no clients

.github/workflows/ci.yaml, Dockerfile, runner/src/internal.rs, scripts/docker_run, scripts/runner
Modify the volume mount points so that they match the default values in
VScode, in order to gain additional shared caching.
Ref #1162
construction.
=> Enable sccache for Rust compilation 

.github/workflows/ci.yaml, runner/src/internal.rs, runner/src/main.rs
Update runner to remove generated files after running tests, to avoid the `No space left on device` error in CI builds.
=> Update runner to remove generated files after running tests

.github/workflows/ci.yaml
Move the Cargo crev verification step to be a separate job in the CI workflow so that it does not run before every runner step.
Fixes #1939 
construction.
=> Make Cargo crev a separate job

docs/programming-oak.md, examples/abitest/client/cpp/abitest.cc, examples/aggregator/README.md, examples/aggregator/client/cpp/aggregator.cc, examples/aggregator/scripts/run_client, examples/chat/client/cpp/chat.cc, examples/hello_world/client/cpp/hello_world.cc, examples/http_server/client/rust/src/main.rs, examples/http_server/example.toml, examples/injection/client/cpp/injection.cc, examples/private_set_intersection/client/cpp/private_set_intersection.cc, examples/tensorflow/client/cpp/tensorflow.cc, examples/translator/client/go/translator.go, examples/trusted_database/client/cpp/trusted_database.cc, oak/common/pkcs8.cc, oak_runtime/src/lib.rs, oak_runtime/src/node/wasm/mod.rs, runner/src/main.rs
- Specifies `path` in option names that indicate a path, as suggested in https://github.com/project-oak/oak/pull/1895#discussion_r589695057
- Fixes a few typos
=> Use more descriptive names for options specifying a path

oak_functions/loader/src/server.rs, oak_functions/loader/src/tests.rs
Make functions more async-friendly.
Make tests actually check responses.
Ensure benchmarks actually exercise the Wasm invocation. Note that now
the time is around 400ms, which seems more realistic than the previous
50ms, I suspect some (or all) of the Wasm execution was being optimized
away earlier.
Ref #1935
construction.
=> Encapsulate Wasm state for Oak Functions loader

oak_functions/loader/Cargo.toml, oak_functions/loader/src/main.rs, oak_functions/loader/src/server.rs, oak_functions/loader/src/tests.rs
Use a mock server in test to simulate serving such a file over HTTP.
Ref #1930
construction.
=> Download lookup data from URL instead of file

oak_functions/Dockerfile, oak_functions/examples/Cargo.lock, oak_functions/examples/hello_world/README.md, oak_functions/loader/Cargo.lock, oak_functions/loader/Cargo.toml, oak_functions/loader/src/main.rs, oak_functions/loader/testdata/.dockerignore, oak_functions/loader/testdata/Dockerfile, oak_functions/loader/testdata/config.toml, scripts/deploy_oak_functions_loader
Reduce the number of test requests when deploying.
Make curl fail if the server does not return an OK HTTP status.
Fix #1961
construction.
=> Use config file instead of command line flags

oak_functions/loader/src/tests.rs
This makes the code more explicit, and also prints out a nicely
formatted value on failure.
construction.
=> Use Duration time for benchmark

runner/src/main.rs
This change deletes the "Parsed manifest files" output from `runner`.
Fixes https://github.com/project-oak/oak/issues/1956
=> Delete 'Parsed manifest files'

.codecov.yml, .github/dependabot.yml, runner/src/main.rs
=> Enable dependabot for oak Functions loader

docs/oak_functions_abi.md, oak_functions/abi/src/lib.rs, oak_functions/examples/Cargo.lock, oak_functions/examples/hello_world/module/Cargo.toml, oak_functions/examples/hello_world/module/src/lib.rs, oak_functions/examples/hello_world/module/src/tests.rs, oak_functions/loader/Cargo.lock, oak_functions/loader/src/lib.rs, oak_functions/loader/src/lookup.rs, oak_functions/loader/src/main.rs, oak_functions/loader/src/server.rs, oak_functions/loader/src/tests.rs, oak_functions/proto/abi.proto, oak_functions/sdk/Cargo.lock, oak_functions/sdk/oak_functions/src/lib.rs, oak_functions/sdk/test_utils/Cargo.toml, oak_functions/sdk/test_utils/src/lib.rs
- move lookup functionality to its own mod
- pass LookupData instance to server
- add ABI method for looking up individual items
- add OakStatus value to indicate the absence of a lookup item
- add SDK wrapper
- refactor various Wasm memory-related functions
- move ABI documentation to the Readme file, and reference that from the
Rust code, instead of maintaining different slightly different versions
- modify hello world example to make use of the lookup functionality
Ref: #1930
construction.
=> ABI for lookups

.github/workflows/cancel.yml
This should save us a few GitHub actions instances when pushing to a PR
that has already some runs in progress.
construction.
=> Cancel pending workflow runs

.github/workflows/build_rust_docs.yaml, .github/workflows/reproducibility.yaml
This is required before we can change the default `GITHUB_TOKEN` permissions to read-only.
See #2003 and https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/
construction.
=> Add explicit write permissions to actions

.github/workflows/upload_coverage.yaml
This is to make sure that the codecov.io upload script only has read permissions, even if the default permissions for the repo allow writing.
See #2003 and https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/
construction.
=> Add explicit codecov permissions

docs/oak_functions_abi.md, oak_functions/examples/Cargo.lock, oak_functions/examples/hello_world/module/src/tests.rs, oak_functions/loader/Cargo.lock, oak_functions/loader/src/server.rs, oak_functions/loader/src/tests.rs, oak_functions/sdk/Cargo.lock, oak_functions/sdk/test_utils/Cargo.toml, oak_functions/sdk/test_utils/src/lib.rs
Synchronize tests and allocate ports randomly at runtime to ensure there
are no conflicts even if running in parallel, and properly terminate
and wait for background tasks.
construction.
=> Follow up fixes for #1991

examples/deny.toml, experimental/deny.toml, oak_client/deny.toml, oak_loader/deny.toml, oak_runtime/deny.toml, oak_runtime/src/node/http/server.rs, sdk/deny.toml
This change also removes code to defend against `RUSTSEC-2021-0020`, which is no longer applicable.
Fixes #1267
Fixes #1874
construction.
=> Stop ignoring RUSTSEC advisories

experimental/envoy_proxy/README.md, experimental/envoy_proxy/client/client.Dockerfile, experimental/envoy_proxy/client/client.yaml, experimental/envoy_proxy/client/client_localhost.yaml, experimental/envoy_proxy/scripts/build.sh, experimental/envoy_proxy/scripts/common.sh, experimental/envoy_proxy/scripts/delete.sh, experimental/envoy_proxy/scripts/deploy.sh, experimental/envoy_proxy/scripts/run_client.sh, experimental/envoy_proxy/scripts/run_server.sh, experimental/envoy_proxy/server/server.Dockerfile, experimental/envoy_proxy/server/server.yaml
This commit adds an Envoy Proxy experiment that shows how Envoy proxy can create a consistent connection to a Cloud Run backend by encapsulating TCP streams in HTTP/2 streams.
=> Add Envoy Proxy Experiment

oak_functions/abi/deny.toml, oak_functions/sdk/deny.toml, runner/src/main.rs
This changes the runner to run cargo-deny at the workspace level where the deny.toml files are defined to resolve warnings about unencountered licenses.
Fixes #2009 
construction.
=> Run cargo-deny at the workspace level

oak_functions/loader/src/server.rs
Merges `WasmInterface` into `WasmState`. 
Ref: https://github.com/project-oak/oak/pull/1991#discussion_r617479503
=> Remove Wasm instance in WasmState

oak_runtime/tests/integration_test.rs
To address CI flakiness (see #2008). `test_metrics_gives_the_correct_number_of_nodes` sometimes fails because the Wasm node has already exited when getting the metrics. This makes sure that it is around for a short while by looping 100 000 times in the exported main function.
The 100 000 iteration count is a guess, but it seems sufficient to remove the flakiness (at least locally based on running the test 50 times) without slowing down the test too much.
construction.
=> Add loop to oak_main in oak_runtime integration test

.github/workflows/reproducibility.yaml
This is to allow the workflow to add a comment to the current PR discussion.
See https://github.com/project-oak/oak/pull/2004#discussion_r623840132
construction.
=> Add `write` permission on issues to reproducibility index workflow

.github/workflows/reproducibility.yaml, examples/deny.toml, experimental/deny.toml, oak_loader/deny.toml, oak_runtime/deny.toml, sdk/deny.toml
See https://github.com/project-oak/oak/pull/2049#issuecomment-830242473
This change also resolves new cargo-deny errors related to new RUSTSEC advisories about unmaintained crates. These errors are currently blocking CI runs.
construction.
=> Give write permissions on pull requests rather than issues for Reproducibility Index workflow

runner/src/examples.rs
Currently `run-functions-examples` also runs `https_attestation` and `tls_attestation` which are not `Oak Functions` examples.
=> Fix condition for running functions examples

oak_functions/loader/fuzz/Cargo.lock
This could potentially solve the problem with fuzzing coverage. 
Ref https://github.com/google/oss-fuzz/issues/5767#issuecomment-841338549
=> Bump libfuzzer-sys version

oak_functions/examples/weather_lookup/client/client
Currently it is generating a file named `--write-out` every time it
runs.
construction.
=> Fix curl command line in client script

examples/Cargo.lock, examples/Cargo.toml, examples/grpc_attestation/client/Cargo.toml, examples/grpc_attestation/client/src/main.rs, examples/grpc_attestation/example.toml, experimental/Cargo.lock, experimental/Cargo.toml, experimental/attestation_common/Cargo.toml, experimental/attestation_common/src/crypto.rs, experimental/grpc_attestation/Cargo.toml, experimental/grpc_attestation/build.rs, experimental/grpc_attestation/proto/grpc_attestation.proto, experimental/grpc_attestation/src/attestation.rs, experimental/grpc_attestation/src/lib.rs, experimental/grpc_attestation/src/main.rs, experimental/grpc_attestation_client/rust/Cargo.toml, experimental/grpc_attestation_client/rust/src/lib.rs, oak_client/Cargo.lock, oak_loader/Cargo.lock
This change adds an experimental version of gRPC remote attestation scheme.
This attestation scheme uses:
- [`ring::agreement`](https://briansmith.org/rustdoc/ring/agreement/index.html) to exchange X25519 Diffie-Hellman keys
- [`ring::aead`](https://briansmith.org/rustdoc/ring/aead/index.html) to encrypt and authenticate messages with AES-GCM
=> Add remote attestation via gRPC

.github/workflows/ci.yaml, WORKSPACE, android.Dockerfile, experimental/attestation_common/src/crypto.rs, experimental/grpc_attestation/proto/BUILD, experimental/grpc_attestation/proto/grpc_attestation.proto, experimental/grpc_attestation/src/attestation.rs, experimental/grpc_attestation/src/main.rs, experimental/grpc_attestation_client/java/BUILD, experimental/grpc_attestation_client/java/com/google/oak/grpc_attestation_client/AeadEncryptor.java, experimental/grpc_attestation_client/java/com/google/oak/grpc_attestation_client/AttestationClient.java, experimental/grpc_attestation_client/java/com/google/oak/grpc_attestation_client/KeyNegotiator.java, experimental/grpc_attestation_client/java/com/google/oak/grpc_attestation_client/Main.java, experimental/grpc_attestation_client/rust/src/lib.rs, third_party/google/tink/Remove-android-from-java.patch
This commit:
- Adds a Java client for gRPC Attestation
- Updates Bazel `WORKSPACE`
- Adds a patch that fixes Tink Java library compilation
Fixes #2113
=> Add Java client for gRPC Attestation

experimental/grpc_attestation/build.rs, experimental/grpc_attestation/src/attestation.rs, experimental/grpc_attestation/src/lib.rs, experimental/grpc_attestation/src/main.rs, experimental/grpc_attestation_client/rust/src/lib.rs, oak_functions/client/java/BUILD, oak_functions/client/java/src/AttestationClient.java, remote_attestation/proto/BUILD, remote_attestation/proto/remote_attestation.proto
This change moves gRPC Attestation proto from `experimental/grpc_attestation/proto` to `remote_attestation`.
=> Move gRPC Attestation proto to remote_attestation

experimental/oak_functions_with_envoy/scripts/build.sh, oak_functions/examples/weather_lookup/README.md, scripts/deploy_oak_functions_loader
I could not run this script without docker, because of missing Rust crates, and GCP commands don't work when running inside docker.
This change list also removes (no longer applicable) mentions of #1943, which was merged a long time ago. But we still need to build the loader binary in the script.
=> Change deploy script for Oak Functions to run outside docker

oak_functions/client/android/BUILD, oak_functions/client/java/BUILD, remote_attestation/java/BUILD, scripts/build_example_android, scripts/build_examples_android
This change:
- Adds Android Oak Functions client to the CI
- Add separate Android targets to Oak Functions, which is necessary for using Tink internally
=> Add separate Android targets to Oak Functions

experimental/ni_coq/_CoqProject, experimental/ni_coq/vfiles/Lattice.v, experimental/ni_coq/vfiles/LowProjPS_Thms.v, experimental/ni_coq/vfiles/PossibilisticNI.v, experimental/ni_coq/vfiles/PossibilisticNI_PS.v, experimental/ni_coq/vfiles/PossibilisticNI_def.v, experimental/ni_coq/vfiles/RuntimeModel.v, experimental/ni_coq/vfiles/RuntimeModelPS.v, experimental/ni_coq/vfiles/UnwindPS.v
Completes all of Possibilistic non-interference for partially-secret
labels with the exception of one critical theorem, which relies on a
fact that is no longer true with partially secret labels. The erroneous
fact is commented out, and the critical theorem is left Admitted.
PNI should still be provable, but more work will be required to find a
workaround for that fact and complete the proof.
Also cleans up some unused lemmas.
=> Prove most of PNI with partially-secret labels

.cargo/config.toml, scripts/release_build_oak_functions, scripts/release_snapshot
Note that currently the hashes do not actually match those in the checked in index, but there seems to be some other non-determinism involved. Anyways, that should probably be sorted out separately in a future PR.
=> Add release scripts

examples/Cargo.lock, experimental/Cargo.lock, oak_client/Cargo.lock, oak_functions/abi/deny.toml, oak_functions/client/rust/Cargo.lock, oak_functions/examples/Cargo.lock, oak_functions/examples/deny.toml, oak_functions/load_test/Cargo.lock, oak_functions/loader/Cargo.lock, oak_functions/loader/deny.toml, oak_functions/loader/fuzz/Cargo.lock, oak_functions/loader/fuzz/deny.toml, oak_functions/lookup_data_generator/deny.toml, oak_functions/sdk/Cargo.lock, oak_functions/sdk/deny.toml, oak_loader/Cargo.lock, oak_runtime/Cargo.lock, oak_sign/deny.toml, remote_attestation/rust/Cargo.lock, runner/Cargo.lock, sdk/Cargo.lock
- Update tokio to the latest version to resolve a vulnerability that could lead to race conditions
- Ignore prost-types advisory (that could lead to an overflow causing a panic) until we update '/third_party/prost/'
construction.
=> Resolve cargo-deny advisory failures

.github/workflows/release_oak_functions.yaml
This follows the same steps that we would need to execute for an actual
release, and provides us a way to double check that the release process
is reproducible, even though we will rely on GCB for the actual
release.
construction.
=> Add release workflow to CI

oak_functions/examples/weather_lookup/Dockerfile
This change it to support buildling the weather lookup container from a specific version of the base Oak Functions container image using build-args.
construction.
=> Change container identifier to an ARG

examples/aggregator/README.md, examples/aggregator/gcp/deployment.yaml, oak_loader/src/options.rs, runner/src/examples.rs
[This `cfg_attr`](https://github.com/project-oak/oak/blob/facc62bff8ad7feed92ffd29c6a59e03838c5e1f/oak_loader/src/options.rs#L48-L51) in the Oak Loader, only applies to the name of the `permissions` flag. When compiling Oak Loader with `oak-unsafe` feature, a permissions parameter is still required: 
```
oak_loader [FLAGS] [OPTIONS] <permissions> --application <application> [--] [ARGS]
```
I tried to fix this by making the `permissions` field in the struct compile conditionally too (using `#[cfg(not(feature = "oak-unsafe"))]`), but it did not solve the problem. So, I changed the `permissions` to be an `Option<String>`.
=> Make `permissions` flag optional

oak_functions/client/android/com/google/oak/functions/android/client/MainActivity.java, oak_functions/client/java/src/com/google/oak/functions/client/AttestationClient.java, oak_functions/examples/weather_lookup/client/java/src/Main.java
=> Allow caller to specify channel for attestation in Java attestation client

.github/workflows/ci.yaml, .gitignore, .rustfmt.toml, oak_functions/abi/build.rs, oak_functions/examples/Cargo.lock, oak_functions/examples/fuzzable/module/build.rs, oak_functions/examples/fuzzable/module/src/tests.rs, oak_functions/examples/key_value_lookup/module/src/tests.rs, oak_functions/examples/metrics/config.toml, oak_functions/examples/mobilenet/config.toml, oak_functions/examples/mobilenet/module/Cargo.toml, oak_functions/examples/weather_lookup/module/src/tests.rs, oak_functions/loader/Cargo.lock, oak_functions/loader/Cargo.toml, oak_functions/loader/fuzz/Cargo.lock, oak_functions/loader/fuzz/build.rs, oak_functions/loader/src/lookup.rs, oak_functions/loader/src/main.rs, oak_functions/loader/src/tests.rs, oak_utils/src/lib.rs, remote_attestation/java/src/com/google/oak/remote_attestation/Message.java
Also allow empty lookup data source.
Fix build script to specify the correct paths for
`cargo:rerun-if-changed`. Previously the paths were invalid, which meant
that cargo thought that those files had been deleted and therefore was
always rerunning all the build scripts every time.
Fix #2253
Fix #2219
construction.
=> Allow fetching lookup data from files

examples/deny.toml, experimental/deny.toml, oak_loader/deny.toml, oak_runtime/deny.toml, sdk/deny.toml
Temporarily ignores [RUSTSEC-2021-0115](https://rustsec.org/advisories/RUSTSEC-2021-0115) until `tink-rust` is updated.
Ref https://github.com/project-oak/oak/issues/2303
=> Ignore RUSTSEC-2021-0115

oak_functions/examples/Cargo.lock, oak_functions/loader/Cargo.lock, oak_functions/loader/Cargo.toml, oak_functions/loader/fuzz/Cargo.lock, oak_functions/loader/src/server.rs, oak_functions/loader/src/tests.rs
=> Use wasmi in no_std mode

oak_functions/Cargo.lock, oak_functions/examples/key_value_lookup/module/src/lib.rs, oak_functions/examples/key_value_lookup/module/src/tests.rs, oak_functions/loader/Cargo.toml, oak_functions/loader/benches/lookup.rs, oak_functions/loader/src/main.rs
This change switches the Oak Functions loader benchmarks to use Criterion.
This change also moves the fixed-data lookup benchmark to the key_value_lookup example to support asserting that the bench takes less than the expected amount of time.
construction.
=> Use Criterion for benchmarking

.devcontainer.json, .github/workflows/build_rust_docs.yaml, .github/workflows/ci.yaml, .github/workflows/release_oak_functions.yaml, .github/workflows/reproducibility.yaml, .github/workflows/upload_coverage.yaml, Dockerfile, oak_functions/client/java/tests/com/google/oak/functions/client/ServerConfigurationVerifierTest.java, remote_attestation/java/tests/com/google/oak/remote_attestation/ClientHandshakerTest.java, remote_attestation/java/tests/com/google/oak/remote_attestation/KeyNegotiatorTest.java, remote_attestation/java/tests/com/google/oak/remote_attestation/MessageTest.java, scripts/common, scripts/docker_build, scripts/docker_pull, scripts/docker_push, scripts/docker_run, scripts/fix_docker_user_and_run
This ensures that each commit in the repository has a cryptographic
reference to the exact Docker image to use to build any artifacts.
Fixes #2374
=> Pin Docker image to specific hash

oak_functions/Cargo.lock, oak_functions/Cargo.toml, oak_functions/examples/abitest/backend/Cargo.toml, oak_functions/examples/abitest/backend/src/main.rs, oak_functions/examples/abitest/client/Cargo.toml, oak_functions/examples/abitest/client/src/main.rs, oak_functions/examples/abitest/common/Cargo.toml, oak_functions/examples/abitest/common/src/lib.rs, oak_functions/examples/abitest/config.toml, oak_functions/examples/abitest/example.toml, oak_functions/examples/abitest/module/Cargo.toml, oak_functions/examples/abitest/module/src/lib.rs, remote_attestation/rust/Cargo.lock
This commit adds an `abitest` example to Oak Functions.
Ref https://github.com/project-oak/oak/issues/1963
=> Add abitest example for oak_functions

.github/workflows/cifuzz.yml
Signed-off-by: David Korczynski <david@adalogics.com>
This adds CI integration with CIFuzz. CIFuzz will run the oak OSS-Fuzz fuzzers for 600 seconds for each PR. The benefit is that regressions and bugs has a chance of being captured early in the development process.
=> ci: Add cifuzz integration

oak_functions/abi/src/lib.rs
=> Add definitions of Wasm host functions based on channels

.github/workflows/ci.yaml
In test runs, it reduced the main command execution time of the
build-functions-server step from 7m to 1m.
=> Cache Rust target dir

examples/Cargo.lock, examples/Cargo.toml, experimental/tf_proxy/client/src/data.rs, experimental/tf_proxy/client/src/main.rs, experimental/tf_proxy/server/src/grpc.rs, oak_functions/loader/src/tests.rs, oak_functions/sdk/oak_functions/tests/integration_test.rs, oak_functions/sdk/oak_functions/tests/module/src/lib.rs, oak_sign/src/lib.rs, runner/Cargo.lock, runner/src/main.rs
Also fix all of the remaining ones.
I think this was accidentally disabled in 183407a71b30a670f645525fd698ba1d2306a5f1.
=> Re-enable clippy warnings

.github/workflows/ci.yaml
The previous one only works for PRs, but not for post-merge, since
`head_ref` is not set in that case.
=> Fix concurrency group

oak_functions/client/java/src/com/google/oak/functions/client/AttestationClient.java
This change fixes the following warning received after a gRPC channel is closed:
```
WARNING: Couldn't receive response: Status{code=UNAVAILABLE, description=Channel shutdownNow invoked, cause=null}
```
=> Fix gRPC UNAVAILABLE due to channel shutdownNow invoked

.github/workflows/ci.yaml, cloudbuild.yaml
See #2435 for context. This aligns the comments with what the code does, and also what we want it too.
=> Clarify CI comments on git diff step

oak_functions/examples/fuzzable/module/src/tests.rs, oak_functions/examples/key_value_lookup/module/src/tests.rs, oak_functions/examples/weather_lookup/module/src/tests.rs, oak_functions/loader/benches/lookup.rs, oak_functions/loader/fuzz/fuzz_targets/wasm_invoke.rs, oak_functions/loader/src/lookup.rs, oak_functions/loader/src/main.rs, oak_functions/loader/src/metrics.rs, oak_functions/loader/src/tests.rs, oak_functions/loader/src/tf.rs, oak_functions/sdk/oak_functions/tests/integration_test.rs
Unify creating a BoxedExentsionFactory with `new_boxed_extension_factory`
For LookupFactory:
* merge `new` and `create` to `new_boxed_extension_factory`
For PrivateMetricsFactory:
* refactor `create_metics_proxy_factory` and `new` to `new_boxed_extension_factory` by
* inlining `validate` and boxing in `new_boxed_extension_factory`
* checking `config` is some before creating the factory
For TensorFlowFactory:
* refactor `create_tensorflow_factory` and `new` to `new_boxed_extension_factory` by
* inlining boxing in `new_boxed_extension_factory`
* checking `config` is some and async reading the model before creating the factory
=> Unify creating a BoxedExentsionFactory

.github/workflows/reproducibility.yaml
This change was suggested in my debugging reproducibility thread: https://github.com/project-oak/oak/pull/2438#issuecomment-998160165. It also seems sensible, given that the unsafe flag is intended for experimental purposes
=> Build the base server variant for the reproducibility index

.github/workflows/ci.yaml, .runner_bash_completion, runner/src/internal.rs, runner/src/main.rs
Add seperate command `run_cargo_clippy`. Now we run clippy only on directly modified crates (as opposed to all affected crates).
=> Seperate steps in `run_cargo_tests`

oak_functions/Cargo.lock, oak_functions/loader/Cargo.toml
tract-tensorflow had another issue that we patched upstream via https://github.com/sonos/tract/pull/607
The unsafe variant of oak_functions now produces a binary of the same hash across machines, thereby solving the issue reported in b/209639154.
```
> git clean -d --force --force -x && ./scripts/docker_run ./scripts/runner build-functions-server --server-variant=unsafe && sha256sum ./oak_functions/loader/bin/oak_functions_loader
a296d50bdb301d8b7a2421c0d91fabb100bce4ec647becd93a31f4d23b8959e7  ./oak_functions/loader/bin/oak_functions_loader
```
=> Update tract-tensorflow to finalize reproducibility fix

runner/src/main.rs
We already run it on all our crates, and there is the risk that it will
start failing because of some dep we don't have control over.
=> Exclude deps from clippy

oak_functions/loader/src/server.rs, oak_functions/loader/src/tests.rs
Moved tests to `server.rs` so the functionality related to `Endpoint` can be private. We might need export `Endpoint` later, but we should do that on demand.
=> Refactor `Endpoint` functionality to be private

Cargo.lock, experimental/tf_proxy/client/Cargo.toml, experimental/tf_proxy/client/build.rs, experimental/tf_proxy/client/src/main.rs, experimental/tf_proxy/server/Cargo.toml, experimental/tf_proxy/server/build.rs, experimental/tf_proxy/server/src/grpc.rs, experimental/tf_proxy/server/src/main.rs
The Remote Attestation Proxy instance currently has an explicit dependency on the service/proto definitions of the backend (TensorFlow Serving). To make it more generic and reusable this change moves it to a model where it receives a generic gRPC encapsulation request and just passes the bytes through to the backend.
=> Use generic gRPC encapsulation rather than explicit protos in Remote Attestation Proxy

Cargo.lock, Cargo.toml, oak_functions/examples/echo/README.md, oak_functions/examples/echo/module/Cargo.toml, oak_functions/examples/echo/module/src/lib.rs, oak_functions/loader/src/lookup.rs, oak_functions/loader/src/metrics.rs, oak_functions/loader/src/server.rs, oak_functions/loader/src/tests.rs, oak_functions/loader/src/tf.rs, oak_functions/proto/abi.proto, oak_functions/sdk/test_utils/src/lib.rs
- Define trait for `Uwabi` extensions
- Change `Extensions` to be either a `Native` or `Uwabi` extension
- Define new Testing Extension which implements `Uwabi` extension
- Use Testing Extension instead of Lookup Extension for tests
=> Add UwabiExtension Trait and Testing extension

Dockerfile
Previously we just used a tag. Tags are mutable and don't describe the actual image. The image described by a tag could be swapped out on the registry. Using the digest means we use CaS and ask for the specific image we expect.
=> Fix docker parent image by its digest

oak_functions/abi/src/lib.rs, oak_functions/loader/src/server.rs, oak_functions/loader/src/tf.rs
OakStatus is returned by all current ABI functions (read/write_request, get_storage_item, tf, metrics, logging).
ChannelStatus by UWABI functions channel_read/write.
For operations on the Wasm memory, we now also return a `ChannelStatus`. These operations are used by both, UWABI and current ABI functions, but when the current ABI is replaced by UWABI, then we will remove OakStatus, so we decided to return a ChannelStatus.
=> Define relation between OakStatus and ChannelStatus

.github/workflows/provenance.yaml, scripts/build_provenance
Creates provenance files (oak_loader, oak_functions_loader) for each commit added to the main branch, as outlined in: https://docs.google.com/document/d/1jWloPhrr-IykJBXtWuDdirqn9MH_FCUShBr_w0F3j3Y/edit?usp=sharing&resourcekey=0-q20m0jqEhzMyYn-kAbq_wA
This initial implementation generates provenance files as a TOML file in the shape currently used by https://github.com/project-oak/transparent-release. This will be changed to a SLSA provenance file, once our SLSA [build type](https://github.com/project-oak/transparent-release/pull/3) is fully defined, and transparent-release has been updated to parse that.
=> Add GitHub action to generate provenance files

.github/workflows/provenance.yaml, scripts/build_provenance
This aligns the invocation of the provenance script with the provenance file, which stores build arguments as an array.
Previously the build_provenance script accepted exactly two arguments 1) exactly one build arg, 2) the output path.
Now it accepts 1) the output path, followed by one or multiple build args.
=> Accept an array of arguments when building the provenance

oak_functions/loader/src/server.rs
When we start tasks for UWABI extensions we need to move the UWABI extension to the task, so we don't want to hold them in the WasmState.
=> Remove UWABI extensions from WasmState

scripts/build_provenance
- updates the buildType key to match https://github.com/project-oak/transparent-release/pull/26
- simplifies the docker configuration to address https://github.com/project-oak/transparent-release/issues/25
Down the road we probably want to change to change how transparent-release/amber-provenances captures the the docker config used, see @rbehjati thoughts in https://github.com/project-oak/transparent-release/pull/26. We may also want to use the transparent release CLI itself to generate provenance statements once it supports doing so (see https://github.com/project-oak/transparent-release/blob/main/common/common.go#L250). 
For now this aligns how provenances are built with how they are verified by the transparent release CLI. Conceptually that means building the binaries with minimal env …
=> Align the generated provenances with the transparent release CLI

.github/workflows/provenance.yaml, docs/INSTALL-OSX.md, docs/development.md
* Removes the `build-server` step from the provenance generation
* Replaces `build-server` with `build-functions-server` in the docs
Ref #2543
=> Remove build-server from the provenance generation step

.github/workflows/ci.yaml
Remove steps for freeing up disk space, it does not seem necessary now
that the number of crates is much smaller.
=> Re-enable caching for all steps

Cargo.lock, oak_functions/loader/fuzz/Cargo.lock, remote_attestation/rust/Cargo.toml, remote_attestation/rust/src/lib.rs
This makes sense conceptually too, as the remote_attestation crate is not tied to a specific protocol, whereas tonic is. 
As an aside, I like how `remote_attestation` is already a seperate crate from `grpc_attestation`, makes the unary request migration a lot nicer. :)
=> Remove tonic dep from remote_attestation crate by natively including protos

Cargo.lock, grpc_attestation/Cargo.toml, oak_functions/loader/fuzz/Cargo.lock, remote_attestation/rust/Cargo.toml, remote_attestation/rust/build.rs, remote_attestation/rust/src/crypto.rs, remote_attestation/rust/src/handshaker.rs, remote_attestation/rust/src/lib.rs, remote_attestation/rust/src/message.rs, remote_attestation/rust/src/report.rs, remote_attestation/rust/src/tests/crypto.rs, remote_attestation/rust/src/tests/handshaker.rs, remote_attestation/rust/src/tests/message.rs
This PR reduces dependencies of the `remote_attestation` crate and makes it usable in `no_std` environments.
Reducing the dependencies should simplify future code audits. An important part of the change is to move away from the `bincode` crate to manual serialization of the handshake messages. The `bincode` crate requires `std`, and manual serialization will also provide more control over the structure of these handshake messages.
Fixes #2294
=> Make remote_attestation crate no_std compatible

remote_attestation/rust/src/message.rs
This wasn't obvious from reading the runtime code, which apart from this piece makes heavy use of protos to define RPC messages.
=> Document why EKEP messages use custom serialization logic

Cargo.lock, Cargo.toml, oak_functions/examples/fuzzable/module/Cargo.toml, oak_functions/examples/fuzzable/module/src/tests.rs, oak_functions/experimental/metrics/Cargo.toml, oak_functions/experimental/metrics/src/lib.rs, oak_functions/loader/Cargo.toml, oak_functions/loader/fuzz/Cargo.lock, oak_functions/loader/fuzz/Cargo.toml, oak_functions/loader/fuzz/fuzz_targets/wasm_invoke.rs, oak_functions/loader/src/lib.rs, oak_functions/loader/src/metrics.rs, oak_functions/loader/src/tf.rs
The `oak_functions_metrics` crate is not yet `no_std` compatible, but will be in future once #2579 and #2580 have been fixed.
=> Make Metrics a separate crate

docs/development.md
Without the logs flag the expected output mentioned in the docs is never shown.
=> Add missing flag to development docs

oak_functions/examples/fuzzable/module/src/tests.rs, oak_functions/examples/key_value_lookup/module/src/tests.rs, oak_functions/examples/weather_lookup/module/src/tests.rs, oak_functions/loader/src/grpc.rs, oak_functions/loader/src/lib.rs, oak_functions/loader/src/tests.rs
Implements the feature flag as a runtime flag as that's what we do atm for lookupdata, tensorflow etc. Worth mentioning alternatively we could make this a build time flag (ref our previous discussion in https://github.com/project-oak/oak/issues/2569). Doing so would introduce additional complexity however since we currently only have two binary variants. 
Opening this so we can decide whether we want a build time or runtime flag for this. Imo build time would be preferable in principle, but runtime is the pragmatic choice right now: It's our current model and changing it for this particular flag probs isn't worth it. This flag is transient and has limited security implications.
=> Add runtime flag to specify gRPC request model

.devcontainer.json, Dockerfile, scripts/common
Right now rebuilding the Oak docker image often fails when running `apt-get`; this PR attempts to alleviate that.
First, switch the base to debian/snapshot:buster-20220228. The original idea was that maybe our previous snapshot was too old, but that doesn't seem to be the case.
Second, add a rate-limit to `apt-get`. That seems to make things better.
=> Switch to a newer Buster snapshot and rate-limit apt-get

Cargo.lock, oak_functions/lookup_data_checker/Cargo.toml, oak_functions/lookup_data_checker/src/main.rs
This change removes UTF8 parsing from the lookup data checker, since the data may be in any format.
=> Update lookup data checker

.github/workflows/ci.yaml, .github/workflows/provenance.yaml, .github/workflows/reproducibility.yaml, .xtask_bash_completion, Cargo.lock, docs/INSTALL-OSX.md, docs/development.md, xtask/Cargo.toml, xtask/src/examples.rs, xtask/src/internal.rs, xtask/src/main.rs
- remove --server-variant flag from CI by always building all variants
- print manifest path in step to build rust binary flag
=> Build all variants of Functions Server by default

xtask/src/examples.rs, xtask/src/internal.rs, xtask/src/main.rs
The only actually useful one was limiting the rustfmt logs, but I think
we can assume that that variable is set correctly in the Dockerfile.
Fixes #2627
=> Remove env variables from xtask

oak_functions/loader/src/lib.rs, oak_functions/loader/src/server.rs, oak_functions/loader/src/testing.rs
This testing extension currently accepts messages to echo to the Wasm module, but we can extend `TestingMessages` to add functionality to test the Wasm module, e.g., the Wasm module could send a message make the Oak Functions runtime sleep.
NB: This is currently an `UwabiExtension`, but we want to refactor it to be a `OakApiNativeExtension`.
=> Move testing extension to seperate module

Cargo.lock, Cargo.toml, oak_functions/experimental/metrics/Cargo.toml, oak_functions/experimental/metrics/src/lib.rs, oak_functions/loader/Cargo.toml, oak_functions/loader/fuzz/Cargo.lock, oak_functions/loader/src/lib.rs, oak_functions/loader/src/metrics.rs, oak_functions/lookup/Cargo.toml, oak_functions/lookup/src/lib.rs, oak_functions/util/Cargo.toml, oak_functions/util/src/lib.rs, oak_functions/util/src/sync.rs
This is in preparation for the Oak Functions loader compatible with no_std
in the future.
Note that the current use of RwLock was replaced by a Mutex. This is because
the critical section is extremely short: just cloning or replacing an Arc. Such
short critical sections do not need the flexibility of reader-writer lock.
=> Use a custom implementation of Mutex instead of std (#2579)

.devcontainer.json, Cargo.lock, Dockerfile, deny.toml, oak_functions/examples/weather_lookup/example.toml, oak_functions/examples/weather_lookup/module/Cargo.toml, oak_functions/examples/weather_lookup/module/src/lib.rs, oak_functions/examples/weather_lookup/module/src/tests.rs, oak_functions/sdk/test_utils/src/lib.rs, scripts/common, xtask/src/examples.rs
Wizer runs an initialisation function on a Wasm module, takes a snapshot of the state and updates the module binary so that the state for new instances match the post-warmup state.
This is particularly useful for the weather lookup example. The S2 geometry library we use populates lookup tables during the first S2 cell lookup. This is expensive and we don't want to repeat it for every request. We use Wizer to create a version of the Wasm module where the startup state contains the initislised lookup tables:
```
$ cargo bench --manifest-path=oak_functions/examples/weather_lookup/module/Cargo.toml 
Finished bench [optimized] target(s) in 0.28s
Running unittests (target/release/deps/weather_lookup-19f777eae18e99bf)
running 3 tests
test tests::test_server ... ignored
Finished release …
```
=> Use Wizer to enable Wasm module warmup

.github/workflows/ci.yaml, .github/workflows/provenance.yaml, .github/workflows/reproducibility.yaml, .xtask_bash_completion, docs/INSTALL-OSX.md, docs/development.md, kokoro/presubmit.sh, oak_functions/examples/echo/example.toml, oak_functions/examples/key_value_lookup/example.toml, oak_functions/examples/metrics/example.toml, oak_functions/examples/mobilenet/example.toml, oak_functions/examples/weather_lookup/example.toml, scripts/deploy_oak_functions_loader, xtask/src/examples.rs, xtask/src/internal.rs, xtask/src/main.rs
To re-use the infrastructure for running an example with a client/server/backend, we refactor to extract Oak Functions-specific functionality.
=> Refactor running of examples

experimental/uefi/.cargo/config.toml, experimental/uefi/Cargo.lock, experimental/uefi/Cargo.toml, experimental/uefi/src/main.rs
The first serial port we have is used for the UEFI stdio, so let's add a second port that's under our control. Right now it just echos everything it receives back to the sender, and writes the bytes received into the log (which will be written to stdio, so the first serial port).
=> Add a second serial port to the system.

docs/development.md, experimental/oak_functions_with_envoy/scripts/build.sh, oak_functions/examples/metrics/README.md, oak_functions/examples/weather_lookup/README.md, oak_functions/examples/weather_lookup/client/java/README.md, scripts/run_tests_coverage
This command was renamed in #2612. Our docs and scritps feature older versions that don't work.
=> Fix invalid xtask command in docs & scripts

deny.toml
Temporarily ignore the advisory until an updated version of Wizer is available.
This vulnerability should not affect the runtime, as it does not use wasmtime directly. It is only used for the ahead-of-time warmup of the weather lookup example.
=> Fix cargo-deny error

Cargo.toml, remote_attestation/rust/src/crypto.rs
The default feature resolver leads to some unexpected behavior regarding features, which are set globally. This has masked errors, by unexpectedly enabling features we thought were not enabled. (See the chat discussion: http://chat/room/AAAAp6czer4/R-8PDylbqF8)
Ref: https://doc.rust-lang.org/cargo/reference/features.html#feature-resolver-version-2
=> Use new cargo feature resolver to avoid feature flags unexpectedly being set

Cargo.lock, oak_functions/loader/Cargo.toml, oak_functions/loader/src/grpc.rs
This adds an endpoint for future web clients to communicate with the runtime directly, by exposing a [grpc-web](https://github.com/grpc/grpc-web) endpoint. grpc-web is an adaption of the gRPC protocol that supports wire formats that web clients can use. 
We'll be using the binary format, see the OSS description here: https://github.com/grpc/grpc-web#wire-format-mode. Defacto this means that requests are sent as unary HTTP/1 requests, with the body consisting of binary encoded protobuf messages. 
Imo this is a nice approach to supporting OSS web clients in the linux-binary version of the runtime. The runtime itself will expose compatible endpoints, with no need to spin up a separate translation layer server. 
In prod deployments too secret to discuss in depth here we'd use a translation …
=> Expose remote attestation endpoint for webclients

.github/workflows/ci.yaml
=> Include cache version in github action

Cargo.lock, experimental/attestation_common/Cargo.toml, experimental/attestation_common/src/keying_material.rs, experimental/https_attestation/Cargo.toml, experimental/https_attestation/src/main.rs, experimental/https_attestation/src/server.rs, experimental/tls_attestation/Cargo.toml, experimental/tls_attestation/src/server.rs
Some code changes are required to bump the versions of `rustls` and `tokio-rustls` that was attempted by dependabot in #2675 and #2674.
=> Upgrade rustls and tokio-rustls

.devcontainer.json, Dockerfile, experimental/uefi/app/Cargo.lock, experimental/uefi/app/Cargo.toml, scripts/common, third_party/ring/.github/workflows/ci.yml, third_party/ring/Cargo.toml, third_party/ring/build.rs, third_party/ring/crypto/fipsmodule/rand/asm/rdrand-x86_64.pl, third_party/ring/mk/cargo.sh, third_party/ring/mk/install-build-tools.sh, third_party/ring/src/rand.rs
- Applies the UEFI compatibility patch for ring from https://github.com/briansmith/ring/pull/1406
- Adds needed build tooling to build ring for a UEFI target
- Includes it as a dep in the UEFI app
=> Build remote attestation for UEFI

scripts/docker_run, scripts/fix_docker_user_and_run
This only applies when running docker via our scripts, which are not (yet) invoked by the VSCode dev container. Supporting the dev container is likely best done by configuring it to use our docker scripts, added https://github.com/project-oak/oak/issues/2717 to track that.
=> Setup docker scripts to allow the image to use KVM

third_party/ring/src/rand.rs
**Please review carefully.** 
The original UEFI patch uses OpenSSL to get CPU feature bits, but it does not seem to be working, see the code comment for details. 
One way to patch it would be to use the rust core lib for this. (Another could be to try and debug the OpenSSL solution). 
I've no strong opinion on the best way to approach this, raising the PR to gather input. cc @conradgrobler
=> Patch how ring gets CPU feature bits when detecting RDRAND support

experimental/uefi/app/.cargo/config.toml
This config does not behave as intended, as (somewhat counterintuitively) cfg in the config does not have access to all the usual values, including features or in this case test. As result, the `[target.'cfg(test)']` runner is never actually used.
See the tracking cargo https://github.com/rust-lang/cargo/issues/8170.
Imo we probably also do not need
=> Remove invalid test runner variation in the UEFI app

.github/workflows/reproducibility.yaml
This allows storing artifacts in Ent, a general purpose Content Addressable Store, for future reference.
See https://github.com/project-oak/oak/runs/6023254832?check_suite_focus=true#step:9:5 for a sample output.
=> Upload binaries to Ent

Cargo.lock, experimental/uefi/app/Cargo.lock, experimental/uefi/app/Cargo.toml, experimental/uefi/app/src/main.rs, experimental/uefi/app/src/serial.rs, experimental/uefi/loader/Cargo.toml, experimental/uefi/loader/src/main.rs
In preparation for proper gRPC request/response flow this change adds some basic framing to the serial data channel: instead of just sending bytes back and forth, we use CBOR as a framing mechanism.
For now, we're still sending strings back and forth, though.
Also, while I was in there, I moved the serial-specific stuff in the UEFI app into its own file.
=> Add CBOR framing to the serial channel

Cargo.lock, oak_functions/examples/mobilenet/client/rust/src/main.rs, oak_functions/experimental/tf_inference/Cargo.toml
We depended on a pre-release commit that incorporated our reproducibility fix: https://github.com/sonos/tract/pull/601
This fix has been incorporated into the released version.
=> Update tract-tensorflow crate source

experimental/uefi/app/src/main.rs, experimental/uefi/client/src/main.rs, experimental/uefi/loader/src/main.rs, experimental/uefi/loader/src/server.rs, experimental/uefi/proto/echo.proto
Done in preparation for adding remote attestation handshake support, which takes place using messages serialized to binary using our remote attestation protocol.
=> UEFI example: Use binary messages

grpc_unary_attestation/src/server.rs, remote_attestation_sessions/src/lib.rs
Adresses @conradgrobler's comment on #2742 https://github.com/project-oak/oak/pull/2742#discussion_r856095803 to improve the clarity of naming. 
Done in a separate PR as it's technically refactoring of other code; will rebase #2742 after this is merged.
=> Refactoring: Improve naming of SessionsTracker method

.devcontainer.json, Dockerfile, scripts/common
The main reason for this is https://github.com/phil-opp/linked-list-allocator/issues/56; a newer nightly fixes the issue.
=> Bump rust version to nightly-2022-04-22

.github/workflows/ci.yaml, oak_functions/loader/src/server.rs
Also removes duplicate function `write_extension_result`.
Also adds function to read `u32` from Wasm memory.
Fixes #2755
=> Add test to write empty buffer to Wasm memory

Cargo.lock, grpc_unary_attestation/Cargo.toml, grpc_unary_attestation/src/client.rs, oak_functions/client/rust/src/lib.rs, oak_functions/loader/fuzz/Cargo.lock
Makes it so the remote attestation client expects to be invoked with binary payloads. This allows us to share it across runtimes.
=> Separate Oak Invocation Protos from remote attestation logic

experimental/uefi/app/runner, experimental/uefi/loader/src/qemu.rs
The previous model of Broadwell also supports other newer features like RDSEED, which we don't actually require need. This leads to issues on older hosts that don't support that feature.
The enforce flag is also added, to trigger an error if hosts don't required support CPU features.
=> Update QEMU CPU model to lowest Intel CPU that supports RDRAND.

.github/dependabot.yml
Currently I think dependabot gets confused because it tries to add its
own reviewer, even though CODEOWNERS already specifies the same
reviewer, and therefore we end up with two reviewers (one auto-assigned,
one left as team) in each PR (e.g. see
https://github.com/project-oak/oak/pull/2781)
I am not 100% sure this will work, but it's worth a try.
=> Remove explicit reviewers from dependabot

third_party/rust-hypervisor-firmware-subset/Cargo.toml, third_party/rust-hypervisor-firmware-subset/LICENSE, third_party/rust-hypervisor-firmware-subset/README.md, third_party/rust-hypervisor-firmware-subset/layout.ld, third_party/rust-hypervisor-firmware-subset/src/asm/mod.rs, third_party/rust-hypervisor-firmware-subset/src/asm/ram32.s, third_party/rust-hypervisor-firmware-subset/src/boot.rs, third_party/rust-hypervisor-firmware-subset/src/common.rs, third_party/rust-hypervisor-firmware-subset/src/gdt.rs, third_party/rust-hypervisor-firmware-subset/src/lib.rs, third_party/rust-hypervisor-firmware-subset/src/paging.rs, third_party/rust-hypervisor-firmware-subset/src/pvh.rs, third_party/rust-hypervisor-firmware-subset/target.json
This extracts the initial import of code out of https://github.com/project-oak/oak/pull/2766.
The code comes from https://github.com/cloud-hypervisor/rust-hypervisor-firmware as of commit e87f46211863ffdac8434293b3cad2372538149c.
Local modifications include the README file, adding `Cargo.toml` and `src/lib.rs` files. Everything else is a strict subset of the rust-hypervisor-firmware code.
=> Import a subset of rust-hypervisor-firmware code

xtask/src/internal.rs
Sometimes (especially for the no_std binaries) we need to specify the directory we have to run the command in (so that we would pick up the correct `.cargo/config.toml` file). If the runtime directory is specified, let's print that out as well in addition to the command itself.
=> When printing out the full command to run, also show the directory.

Cargo.lock, oak_functions/examples/mobilenet/client/rust/Cargo.toml, oak_functions/examples/mobilenet/client/rust/src/main.rs
If you look at, say, https://github.com/project-oak/oak/pull/2801 where Dependabot tries to update the version of `tract-tensorflow`, the tests fail because:
```
[14:56:07 ✓:1,✗:0,⠇:4] │││││││ ╔════════════════════════
[14:56:07 ✓:1,✗:0,⠇:4] │││││││ ║ ════╡ stderr ╞════
[14:56:07 ✓:1,✗:0,⠇:4] │││││││ ║     Finished release [optimized] target(s) in 0.25s
[14:56:07 ✓:1,✗:0,⠇:4] │││││││ ║      Running `target/x86_64-unknown-linux-gnu/release/mobilenet_client`
[14:56:07 ✓:1,✗:0,⠇:4] │││││││ ║ thread 'main' panicked at 'assertion failed: `(left == right)`
[14:56:07 ✓:1,✗:0,⠇:4] │││││││ ║   left: `"Best result: Some((0.1752324, 789))"`,
[14:56:07 ✓:1,✗:0,⠇:4] │││││││ ║  right: `"Best result: Some((0.17523259, 789))"`', oak_functions/examples/mobilenet/client/rust/src/main.rs:83:5
[14:56:07 …
```
=> Don't expect floats to be exactly the same

remote_attestation/rust/Cargo.toml, remote_attestation/rust/src/crypto/mod.rs, remote_attestation/rust/src/crypto/ring_crypto.rs
This change restructures the `remote_attestation` crate's crypto implemenation as a first step towards enabling option support for using the Rust Crypto crates instead of `ring` based on a feature.
=> Refactor `remote_attestation` crate crypto implementation

Cargo.lock, remote_attestation/rust/Cargo.toml, remote_attestation/rust/src/crypto/mod.rs, remote_attestation/rust/src/crypto/ring_crypto.rs, remote_attestation/rust/src/crypto/rust_crypto.rs, remote_attestation/rust/src/handshaker.rs, remote_attestation/rust/src/tests/crypto.rs
This allows us to choose which implementation of the crypto primitives to use for remote attestation.
Only the `ring` implementation is currently tested in CI, but I have manually tested the RustCrypto version. The next step after this PR it to use this RustCrypto implementation for the bare-metal binary. The client will still use the `ring` version, so we will also test interoperability between the two implementations.
=> Add RustCrypto implementation of remote attestation

kokoro/presubmit.sh
This was easier than expected, but not without its warts: namely, on Kokoro machines `/dev/kvm` was owned by `root:root`. However, that's nothing a quick `sudo chown` can't fix.
You can see the test logs if you go look at the Kokoro output -- unfortunately right now it requires corp credentials.
Steps for the future: (a) make the test run in Kokoro `prod`, not `qa` and (b) look into Resultstore so that we could make the build logs available without requiring Google corp credentials.
=> Run VM test under Kokoro

Cargo.lock, Cargo.toml, experimental/uefi/app/Cargo.lock, experimental/uefi/app/Cargo.toml, experimental/uefi/baremetal/Cargo.lock, experimental/uefi/baremetal/Cargo.toml, experimental/uefi/baremetal/src/main.rs, experimental/uefi/baremetal/src/serial.rs, experimental/uefi/runtime/Cargo.toml, remote_attestation/rust/Cargo.toml, remote_attestation_sessions/Cargo.toml, third_party/curve25519-dalek/Cargo.toml, third_party/rust-hypervisor-firmware-subset/layout.ld, third_party/rust-hypervisor-firmware-subset/src/asm/ram32.s, third_party/x25519-dalek/Cargo.toml, xtask/src/vm.rs
Enabling the tests required a few fixes:
- Patching `curve25519-dalek` and `x25519-dalek` to use a newer version of `rand_core` so that it could be built for `x86_64_unknown_none`
- `sha2` could not be built without SIMD support
- The baremetal binary had to enable SSE and AVX support on the CPU via control registers to allow execution of SIMD code
- Rust assumes that the stack is 16-byte aligned, but the bare metal boot code caused it to be misaligned by 8 bytes because of the way it jumps into the entry point for Rust code
- The serial communication code was sending bytes as if it were text-based rather than raw binary, so changed to `send_raw`
=> Enable bare-metal e2e test

Cargo.lock, experimental/uefi/app/Cargo.lock, experimental/uefi/app/Cargo.toml, experimental/uefi/app/src/serial.rs, experimental/uefi/baremetal/Cargo.lock, experimental/uefi/baremetal/Cargo.toml, experimental/uefi/baremetal/src/serial.rs, experimental/uefi/loader/Cargo.toml, experimental/uefi/loader/src/main.rs, experimental/uefi/runtime/Cargo.toml, experimental/uefi/runtime/src/framing.rs, experimental/uefi/runtime/src/lib.rs
This replaces our custom channel train with more standard `Read + Write` traits by refactoring the runtime, UEFI & bare metal implementation. Follows up to @tiziano88 suggestion in #2811: abstraction: https://github.com/project-oak/oak/pull/2811#discussion_r866690458. :) 
Traits from ciborium_io, since they are well maintained and fairly minimal. 
Other options were std (no_std env), acid_io (depends on libc), core-io (does not support our nightly), core2 (not well maintained).
=> Replace Channel with Read Write Traits

experimental/uefi/baremetal/.cargo/config.toml, experimental/uefi/baremetal/build.rs, experimental/uefi/baremetal/target.json
This is just shuffling around the deck chairs in preparation of having our own `layout.ld` script for the linker.
=> Create a separate target.json file for bare metal

Cargo.lock, experimental/uefi/loader/Cargo.toml, experimental/uefi/loader/src/main.rs, experimental/uefi/loader/src/qemu.rs, experimental/uefi/loader/src/vmm.rs
This is in preparation of introducing a second type of VMM: crosvm.
UEFI will still use qemu, but baremetal will use crosvm.
Right now some changes are a bit silly: for example, both the `Uefi` and `Bios` branches are pretty much equivalent; this is intentional, as this means once we enable crosvm it's just a simple change to the `Bios` branch.
=> Create a generic Vmm trait wrapper in loader

.devcontainer.json
The main goal was just to get syntax highlighting working, and those two plug-ins seem to be the most popular of their kind.
=> Add VSCode plug-ins for linker scripts and asm.

experimental/uefi/baremetal/src/main.rs, experimental/uefi/kernel/src/lib.rs, third_party/rust-hypervisor-firmware-subset/src/pvh.rs
As the name suggests, this makes `kernel::start_kernel` use a `&dyn boot::Info` argument, as we'll be using multiple boot protocols.
The fun bit was that after I made that change, the Rust optimizer dropped PVH code completely from the test build of the bootloader -- I guess it saw that we weren't really using anything from that crate. Unfortunately the collateral damage from that was the PVH boot note itself, which rendered test builds unloadable...
Thus, let's just print out that we're in tests to make sure everything is linked into the binary properly.
=> Change the kernel to be a bit more generic

Cargo.lock, experimental/virtio/Cargo.toml, experimental/virtio/src/vsock/mod.rs, experimental/virtio/src/vsock/packet.rs
Adds an implementation of a vsock packet based on the virtio 1.1 spec. The packet is backed by a buffer, and fields are read using an offset into the buffer.
=> Add virtio vsock packet implementation

experimental/uefi/loader/src/crosvm.rs, experimental/uefi/loader/src/main.rs, xtask/src/vm.rs
I spent quite some time trying to get the comms channel working over a file descriptor, but no data got through. Using stdio seems to work; while I'd still like to use the fd for this, the solution here works.
=> Add crosvm to the end-to-end tests

Cargo.lock, experimental/virtio/Cargo.toml, experimental/virtio/src/lib.rs, experimental/virtio/src/vsock/mod.rs, experimental/virtio/src/vsock/packet.rs, experimental/virtio/src/vsock/socket.rs
This is a basic socket implementation with some limitations to simplify the design for now:
- Only supports a single stream on a single port
- Can only be used once - disconnecting the stream consumes the virtio device, so the VM must be rebooted to get a new connection
- Copies data when reading packets
=> Add initial vsock socket implemenation

oak_idl/src/lib.rs, oak_idl_gen_services/src/lib.rs, oak_idl_tests/test_schema_services.rs.txt, oak_idl_tests/tests/test_schema.rs
The server should be able to indicate that a method invocation failed. The alteratives would be panicking (the tests do this at the moment) or silently failing by sending an empty / default value. Conceptually equivalent to a 500 status code in HTTP https://http.cat/500
=> Implement InternalError in IDL

Cargo.lock, oak_functions/loader/Cargo.toml, oak_functions/loader/fuzz/Cargo.lock, oak_functions/testing/Cargo.toml, xtask/Cargo.toml
`chrono` includes an old version of `time` by default, which is affected by  https://rustsec.org/advisories/RUSTSEC-2020-0071.
We don't seem to need the `oldtime` feature; therefore, let's disable it.
=> Fix `cargo deny` issue related to `chrono` and `time`

experimental/uefi/baremetal/Cargo.toml, experimental/uefi/baremetal/build.rs, experimental/uefi/baremetal/src/asm/mod.rs, experimental/uefi/baremetal/src/asm/multiboot.s, experimental/uefi/baremetal/src/main.rs, experimental/uefi/baremetal/src/multiboot.h, experimental/uefi/baremetal/src/multiboot.rs, third_party/grub/include/multiboot.h, third_party/rust-hypervisor-firmware-boot/Cargo.toml, third_party/rust-hypervisor-firmware-boot/layout.ld, third_party/rust-hypervisor-firmware-boot/src/asm/ram32.s, third_party/rust-hypervisor-firmware-boot/src/lib.rs
Highly experimental, but I've added multiboot1 support as that's what... a certain VMM nominally supports natively.
As it stands, it's untestable in our current framework as Qemu refuses to boot ELF64 binaries which have a multiboot header (as multiboot is nominally a 32-bit only protocol). You have to recompile qemu if you want to remove that check; if you do, the code seems to work. But I don't really want to build a patched qemu in our container.
However, as it stands, it _should_ be enough to test whether (claimed) multiboot1 support works or not in that other VMM, so I'm inclined to merge it even with the known large caveats.
I've left it as an optional feature, off by default, as otherwise qemu will try using multiboot (and fail because we're a 64-bit binary) before even trying to …
=> Add multiboot1 protocol support

experimental/virtio/src/queue/mod.rs, experimental/virtio/src/queue/tests.rs, experimental/virtio/src/queue/virtq.rs
Use wrapping values for virtqueue ring indices to ensure the queue keeps operating once the max value has been reached.
=> Wrap virtqueue indices

.devcontainer.json, Cargo.lock, experimental/uefi/baremetal-crosvm/Cargo.lock, experimental/uefi/baremetal-crosvm/Cargo.toml, experimental/uefi/channel/src/lib.rs, experimental/uefi/kernel/Cargo.toml, experimental/uefi/kernel/src/lib.rs, experimental/uefi/loader/Cargo.toml, experimental/uefi/loader/src/crosvm.rs, experimental/uefi/loader/src/main.rs, experimental/uefi/loader/src/qemu.rs, experimental/uefi/loader/src/vmm.rs, experimental/virtio/Cargo.toml, experimental/virtio/src/queue/virtq.rs, experimental/virtio/src/vsock/mod.rs, experimental/virtio/src/vsock/socket.rs, kokoro/presubmit.sh, scripts/docker_run, third_party/rust-hypervisor-firmware-virtio/src/device.rs, third_party/rust-hypervisor-firmware-virtio/src/pci.rs
This PR changes the crosvm-compatible bare-metal implementation to use a virtio vsock channel for host-to-guest communication.
The vsock channel can only be connected after the VM has booted when using crosvm. When using a serial port on QEMU for the comms the loader's comms channel for connecting to the serial port (a unix domain socket) must be created before the VM boots. To work around this, a wrapper struct for the VsockStream has been added so that it can be connected later, the first time we try to use it for actual comms. It is now also up to the VMM to create the comms channel, rather than passing it in as part of the VMM startup parameters.
=> Use virtio vsock socket as comms channel on crosvm
