project-oak/oak

oak_idl_gen_services/src/lib.rs, oak_idl_tests/test_schema_services.rs.txt, oak_idl_tests/tests/test_schema.rs
Needed to implement remote attestation handling
=> oak_idl: Allow service implementations to mutate themselves

Cargo.lock, experimental/uefi/baremetal-crosvm/Cargo.lock, experimental/uefi/baremetal/Cargo.lock, experimental/uefi/kernel/Cargo.toml, experimental/uefi/kernel/src/lib.rs, experimental/virtio/src/console/mod.rs, experimental/virtio/src/console/tests.rs, experimental/virtio/src/lib.rs, experimental/virtio/src/queue/mod.rs, experimental/virtio/src/test.rs, experimental/virtio/src/vsock/mod.rs, experimental/virtio/src/vsock/socket/mod.rs, experimental/virtio/src/vsock/socket/tests.rs, experimental/virtio/src/vsock/tests.rs
This PR also adds a test-specific VirtioTransport implementation to support testing of virtio devices without having to emulate a full PCI device,
=> Add tests for virtio devices

experimental/uefi/channel/src/lib.rs, experimental/uefi/loader/src/main.rs, experimental/uefi/loader/src/server.rs, experimental/uefi/runtime/src/framing.rs, oak_idl/src/lib.rs, oak_idl_gen_services/src/lib.rs, oak_idl_tests/test_schema_services.rs.txt, oak_idl_tests/tests/test_schema.rs
Tiziano proposed this earlier, and I agree it's probably a good idea. Crucially gRPC Status codes include a definition of a status code. This is nice, as it means we can use status codes as is in the framing implementation, doing away with what's a somewhat dodgy implementation rn. 
The downside is that technically an invocation could error with an Ok status, which wouldn't make sense. That's the same type / error signature as used by tonic though, so it's probably fine
=> Use gRPC status codes in the oak IDL

experimental/uefi/client/src/main.rs, experimental/virtio/src/queue/virtq.rs, experimental/virtio/src/vsock/mod.rs, experimental/virtio/src/vsock/packet.rs, experimental/virtio/src/vsock/socket/tests.rs, xtask/src/vm.rs
The vsock implementation failed after 16 buffers were used in the receive queue. This happened because of a mismatch in the believed number of available descriptors.
When configuring the vhost vsock device, CrosVM uses the maximum queue size rather than the negotiated size (https://chromium.googlesource.com/chromiumos/platform/crosvm/+/d4505a7f1c9e4aa502ff49367863aedeadbafb9d/devices/src/virtio/vhost/worker.rs#74).
For now the vsock device just uses the CrosVM maximum queue size of 256. This is not compatible with QEMU, which has a maximum size of 128, but we use the virtio console comms channel on QEMU, rather than vsock.
This PR also adds some tests to ensure we go past the maximum queue size to detect similar issues in future.
=> Fix queue size mismatch and add tests

experimental/oak_baremetal_app_qemu/Cargo.toml, experimental/oak_baremetal_kernel/Cargo.toml, experimental/oak_baremetal_kernel/src/lib.rs, experimental/oak_baremetal_kernel/src/serial.rs
This partially reverts commit ed55da95cc2ff4f1490fcbdb3392a233138278aa, as one of the VMMs we want to use does not support virtio right now.
I've made it an optional feature that is not on by default.
=> Restore serial comms channel + make it an optional feature.

experimental/virtio/src/vsock/socket/mod.rs, experimental/virtio/src/vsock/socket/tests.rs
The original choice of stream buffer length that we chose caused the comms to stall if we received a lot of data without sending any packets back, even though it indicated a very large capacity.
This updates value seems to avoid stalling without sending too many credit update packets.
=> Update credit calculation constants

experimental/oak_baremetal_channel/src/client.rs, experimental/oak_baremetal_channel/src/lib.rs, experimental/oak_baremetal_channel/src/server.rs, experimental/oak_baremetal_channel/src/tests.rs, experimental/oak_baremetal_loader/src/main.rs, experimental/oak_baremetal_runtime/src/framing.rs
This PR adds a `MessageId` in preparation for implementing message multiplexing in the future. For now messages are still sent in sequence.
=> Implement a MessageId in preparation for multiplexing

.devcontainer.json
At the moment the dev container requires the vsock devices to be present. These are only present if the required kernel modules are loaded, which seems to go missing after each reboot and needs to be reloaded before the dev container can be started.
After this change we will no longer be able to run the crosvm tests in the dev container terminal, but it will still be possible to run it using `scripts/docker_run`.
=> Remove vsock devices from dev container

experimental/oak_baremetal_kernel/src/memory.rs
`anyhow::Result` tries to allocate memory, but at the point we want to return an error we don't have a global memory allocator yet, so the allocation will fail.
It's not a safety issue as we'd panic if we return an error when initializing the allocator anyway, but right now when we try to return the error (no memory found) anyhow tries to allocate memory, which causes a panic with a different error message, swallowing the original.
Therefore, let's use `core::result::Result` here.
=> Use `core::result::Result` instead of `anyhow::Result` when initializing the memory allocator

Cargo.lock, experimental/oak_baremetal_app_crosvm/Cargo.lock, experimental/oak_baremetal_app_crosvm/src/bootparam.rs, experimental/oak_baremetal_app_crosvm/src/main.rs, experimental/oak_baremetal_app_qemu/Cargo.lock, experimental/oak_baremetal_app_qemu/src/hvm_start_info.rs, experimental/oak_baremetal_app_qemu/src/main.rs, experimental/oak_baremetal_app_qemu/src/multiboot.rs, experimental/oak_baremetal_kernel/Cargo.toml, experimental/oak_baremetal_kernel/src/args.rs, experimental/oak_baremetal_kernel/src/boot.rs, experimental/oak_baremetal_kernel/src/lib.rs
The idea is that in the future we may want to pass arguments to the kernel even before we establish our communication channel: for example, whether to use serial or vsock-virtio (or vsock-console) for said communication channel to begin with.
Part of this PR is also a request for ideas: I'm not happy about `args::args()` right now, but I couldn't figure out how to convince Rust that the memory is static so that a `&'static CStr` makes sense.
=> Add support for kernel boot arguments

experimental/oak_baremetal_app_crosvm/src/bootparam.rs, experimental/oak_baremetal_app_qemu/src/hvm_start_info.rs, experimental/oak_baremetal_app_qemu/src/multiboot.rs, experimental/oak_baremetal_kernel/src/boot.rs, experimental/oak_baremetal_kernel/src/lib.rs, experimental/oak_baremetal_kernel/src/memory.rs
As I found out in one of my other PRs, initializing the memory allocator can trash the contents of the boot metadata provided to us by the boot loader (as the metadata is stored _somewhere_ in valid memory, which may be overwritten at any point after we enable allocation).
Thus: let's make `memory::init_allocator()` take ownership of the reference, so that we know that it can't be used after we call the function.
=> Consume boot info when initializing memory

.github/workflows/reproducibility.yaml
Previously it was silently ignoring errors (and there was in fact an
issue with the server at some point that went unnoticed, which is now
resolved).
=> Make curl fail on server error

Cargo.lock, experimental/oak_baremetal_app_crosvm/Cargo.lock, experimental/oak_baremetal_app_qemu/Cargo.lock, experimental/oak_baremetal_client/src/main.rs, experimental/oak_baremetal_kernel/Cargo.toml, experimental/oak_baremetal_kernel/src/lib.rs, oak_remote_attestation_amd/Cargo.toml
…Previously it used the EmptyAttestationGenerator. Now it uses the PlaceholderAmdAttestationGenerator. This change will make it easier to share clients between the runtimes in the future
=> Update baremetal runtime to generate the same attestation as the linux runtime

Cargo.lock, experimental/oak_baremetal_app_crosvm/Cargo.lock, experimental/oak_baremetal_app_qemu/Cargo.lock, experimental/oak_baremetal_channel/Cargo.toml, experimental/oak_baremetal_channel/src/client.rs, experimental/oak_baremetal_channel/src/frame.rs, experimental/oak_baremetal_channel/src/lib.rs, experimental/oak_baremetal_channel/src/server.rs, experimental/oak_baremetal_channel/src/tests.rs, experimental/oak_baremetal_kernel/Cargo.toml, experimental/oak_baremetal_kernel/src/lib.rs, experimental/oak_baremetal_kernel/src/serial.rs, experimental/oak_baremetal_kernel/src/virtio.rs, experimental/oak_baremetal_loader/Cargo.toml, experimental/oak_baremetal_loader/src/main.rs, experimental/oak_baremetal_runtime/Cargo.toml, experimental/oak_baremetal_runtime/src/framing.rs, experimental/virtio/Cargo.toml, experimental/virtio/src/console/mod.rs, experimental/virtio/src/console/tests.rs, experimental/virtio/src/lib.rs, experimental/virtio/src/vsock/socket/mod.rs, experimental/virtio/src/vsock/socket/tests.rs
We weren't using anything but the `Read` and `Write` traits from `ciborium_io` anyway, so let's get rid of that dependency.
I've added compatible `Read` and `Write` traits to `oak_baremetal_channel`. That seemed to be the best location for them.
I had to implement completely identical but separate traits in the `virtio` crate as well, as I didn't want to make `virtio` depend on the channel crate.
Apart from that nuance it's pretty straightforward... although I do have to say that all the bajillion conditional compilation statements in the kernel are _really_ getting out of hand. As a side effect, you never know what exactly will be built if you specify some combination of feature flags (or none at all, or --all-features). That needs to be cleaned up, but that's a separate undertaking.
=> Get rid of ciborium_io dependency.

.devcontainer.json, Dockerfile, experimental/oak_baremetal_app_crosvm/layout.ld, experimental/oak_baremetal_app_crosvm/src/asm/boot.s, scripts/common
Crosvm has overhauled their ELF loading code, largely based on feedback from us. For example, now it loads segments to their specified physical address (instead of adding the constant `0x200000` internally) and starts executing from the correct entry point specified in the header (again, instead of having a hard-coded constant that just happened to work because the memory between that memory location and the real entry point was filled with `0x00` bytes).
Let's upgrade our crosvm and simplify our bootstrap code; equally importantly, this will also make it easier for the ELF kernel to be loaded with other VMMs.
(There were also some virtio-related changes. I feel like we should get something like dependabot to update our crosvm version every now and then automagically.)
=> Update crosvm and simplify crosvm bootstrap code

docs/remote-attestation.md
Making this PR as a follow up our discussion in the last on demand, where it seemed people were missing clarity around what the `AttestationReport` contains and when it is generated.
- It clarifies that (unlike what the docs previously stated) the Trusted Runtime does not request an Attestation Report for every handshake. Instead, the plan is to requests a report only once, and from there on out only uses a generated Signing key that was endorsed in the Attestation Report.
- Clarifies when the runtime is measured 
- It updates the diagram to use GitHub's native diagram renderer instead of the previous image. This means it's now readable on darkmode (😃) and by people using screen readers. Also makes it clear how to edit the diagram, and where the source of truth for the diagram is. You can …
=> Update Remote Attestation Docs

.github/dependabot.yml
By default kokoro checks are only triggered for PRs from users that belong to the same org as the repo. Other PRs can trigger kokoro if they include a certain label. Adds this label for all dependabot PRs.
Related to https://github.com/project-oak/oak/pull/3019, hopefully this can prevent similar build breaks
=> Ensure Kokoro runs against dependabot PRs

Cargo.lock, Cargo.toml, experimental/sev_guest/Cargo.toml, experimental/sev_guest/README.md, experimental/sev_guest/src/instructions.rs, experimental/sev_guest/src/lib.rs
This is the first of a series of PRs that will add Rust helper code to support running as a guest under AMD SEV-SNP. It provides impelementations of the new RMPADJUST, PVALIDATE and VMGEXIT instructions and related data structures.
=> Add initial SEV-SNP guest helper code

experimental/oak_baremetal_app_crosvm/src/main.rs, experimental/oak_baremetal_app_qemu/src/main.rs, xtask/src/main.rs
All of our bare-metal targets set panic strategy to `abort`, so `eh_personality` is not needed.
I think we added it back in the day to placate `xtask run-cargo-clippy`: as it runs `cargo clippy` in the root directory, it didn't pick up the `.cargo/config.toml` files properly.
Thus, let's fix xtask so that it runs `cargo clippy` in the directory of the crate, and drop the unnecessary `eh_personality` functions.
=> Clean-up: we don't actually need `eh_personality`.

experimental/oak_baremetal_app_crosvm/build.rs, experimental/oak_baremetal_app_crosvm/target.json, experimental/oak_baremetal_app_qemu/build.rs, experimental/oak_baremetal_app_qemu/target.json
For reference, this is the target spec from `x86_64-unknown-none`:
```
$ rustc -Z unstable-options --target=x86_64-unknown-none --print target-spec-json
{
"arch": "x86_64",
"code-model": "kernel",
"cpu": "x86-64",
"data-layout": "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128",
"disable-redzone": true,
"executables": true,
"features": "-mmx,-sse,-sse2,-sse3,-ssse3,-sse4.1,-sse4.2,-3dnow,-3dnowa,-avx,-avx2,+soft-float",
"is-builtin": true,
"linker": "rust-lld",
"linker-flavor": "ld.lld",
"llvm-target": "x86_64-unknown-none-elf",
"max-atomic-width": 64,
"panic-strategy": "abort",
"position-independent-executables": true,
"relro-level": "full",
"stack-probes": {
"kind": "call"
},
"static-position-independent-executables": true,
"target-pointer-width": "64"
}
```
Key …
=> Derive target.json from `x86_64-unknown-none`

experimental/oak_baremetal_loader/src/crosvm.rs
crosvm says the current way we pass flags to it is deprecated:
```
`--serial=num=1,hardware=serial,type=file,path=/proc/self/fd/9,console,earlycon` is deprecated, please use `--serial num=1,hardware=serial,type=file,path=/proc/self/fd/9,console,earlycon`
`--cid=3` is deprecated, please use `--cid 3`
`--params=channel=virtio_vsock` is deprecated, please use `--params channel=virtio_vsock`
```
Well, let's do that, then.
=> Change how we pass flags to crosvm

experimental/sev_guest/src/msr.rs
This PR adds unit tests for the conversion of the MSR protocol request objects to u64 values and u64 values to response objects.
See section 2.3.1 of [SEV-ES Guest-Hypervisor Communication Block Standardization](https://developer.amd.com/wp-content/resources/56421.pdf) for the specification.
=> Add GHCB MSR protocol unit tests

.github/dependabot.yml
The downside is that we will get far more dependabot PRs for now.
In the future this will get better:
- we expect one of the baremetal crates to go away (and thus one less `Cargo.lock` to maintain)
- hopefully Rust will figure out how to include baremetal crates in the main workspace soon.
=> Run dependabot against baremetal crates as well

README.md
Small tweak: GitHub recommends using the HTML picture element for this: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to :) 
Preview on the source branch: https://github.com/jul-sh/oak/tree/dark-mode-image
=> Use negative logo in dark mode to ensure readability

experimental/oak_baremetal_loader/src/lookup.rs, experimental/oak_baremetal_loader/src/main.rs, experimental/oak_baremetal_loader/src/server.rs, experimental/oak_baremetal_runtime/src/framing.rs, oak_idl/src/utils.rs, oak_idl_gen_services/src/lib.rs, oak_idl_tests/test_schema_services.rs.txt, oak_idl_tests/tests/test_schema.rs
Helps delineate it from Messages on the communication layer. The new name is `OwnedFlatbuffer`, as being an owned flatbuffer is in essence what this struct does. It's not that specific to our IDL logic. :)
=> Rename the oak IDL Message struct to something more descriptive

experimental/oak_baremetal_channel/Cargo.toml, experimental/oak_baremetal_channel/build.rs, experimental/oak_baremetal_channel/src/lib.rs, experimental/oak_baremetal_loader/Cargo.toml, experimental/oak_baremetal_loader/src/main.rs, experimental/oak_baremetal_loader/src/server.rs
Updates the untrusted loader to use an async IDL client. Instead of there being a central client that is being invoked over a bmrng channel by different parts of the runtime, there will now be multiple async clients that issue invocations over the bmrng channel.
This means that we'll get the code to differentiate various messages sent over the channel for free, provided by the oak IDL. This will come in handy when implementing periodic lookup-data refreshing.
In the future async clients will also allow us to more easily support non-sequential invocations.
=> Use Async IDL Client in the Untrusted Loader

experimental/oak_baremetal_app_crosvm/src/main.rs, experimental/oak_baremetal_app_qemu/src/main.rs
As of #3034 the binaries no longer have a test entrypoint, hence it seems these references can be removed :)
=> Remove remaining references to baremetal tests

experimental/oak_baremetal_kernel/src/interrupts.rs
After this change the kernel no longer double faults when encountering a breakpoint exception and instead continues afterwards. 
Tested this manually, and appears to work fine. This PR intentionally doesn't add an automated test since baremetal tests were removed in #3034, but would be happy to add a test back for this. 
Unfortunately this does not unlock debugging in crosvm. The runtime still crashes in crosvm when continuing from a breakpoint.
=> Kernel: Add simple breakpoint exception handler that logs

experimental/oak_baremetal_channel/src/lib.rs, experimental/oak_baremetal_loader/src/crosvm.rs, experimental/oak_baremetal_loader/src/main.rs, experimental/oak_baremetal_loader/src/qemu.rs, experimental/oak_baremetal_loader/src/vmm.rs
The ReadWrite trait is equivalent to the Channel trait. The ReadWrite can be removed by providing an implementation of our Read / Write traits from the std trait. 
Simplifies the code slightly, and will come in handy for the upcoming linux wrapper of the runtime, which also uses std Read / Write traits.
=> Remove duplicate trait

experimental/oak_baremetal_launcher/README.MD, experimental/oak_baremetal_launcher/src/instance.rs, experimental/oak_baremetal_launcher/src/instance_crosvm.rs, experimental/oak_baremetal_launcher/src/instance_qemu.rs, experimental/oak_baremetal_launcher/src/main.rs, xtask/src/vm.rs
Soon the launcher will launch not just VMs, hence this removes references to VMs and VMMs where they're not needed. In preparation for #3080.
=> Refactor launcher in preparation for supporting a runtime linux binary

xtask/src/launcher.rs, xtask/src/main.rs
Refactors this code to remove references to virtual machines in preparation for testing the linux binary variant of the baremetal-compatible runtime. (Ref: https://github.com/project-oak/oak/issues/3080)
=> Refactor xtask implementation of testing the baremetal-compatible runtime

.xtask_bash_completion, kokoro/presubmit.sh, xtask/src/internal.rs, xtask/src/launcher.rs, xtask/src/main.rs
Pulled out from #3106, after which these will no longer just be VM tests
=> Rename VM test logic in preparation for supporting running the runtime as a native binary

experimental/oak_baremetal_launcher/src/instance/crosvm.rs, experimental/oak_baremetal_launcher/src/instance/mod.rs, experimental/oak_baremetal_launcher/src/instance/native.rs, experimental/oak_baremetal_launcher/src/main.rs
Let's do some bikeshedding :)
Case in point, I don't like using underscores as kind of namespace delineators when we have a perfectly fine `/` that natively works as one.
Thus, here's my proposal: move `instance_*.rs` to `instance/*.rs`. I think this code is cleaner[*], but as it's a matter of taste I'm willing to entertain other opinions.
[*] -- having to include `crate::path_exists` is ugly, but then again, I'm surprised something like that doesn't exist in some other crate we could include.
=> Move instance implementations into a subdirectory.

java/BUILD, java/src/main/java/com/google/oak/client/Encryptor.java, java/src/main/java/com/google/oak/client/OakClient.java, java/src/main/java/com/google/oak/client/RpcClient.java, java/src/main/java/com/google/oak/util/Result.java, java/src/test/java/com/google/oak/client/OakClientTest.java, java/src/test/java/com/google/oak/util/ResultTest.java
Adds a `Result` type in Java, and updates the client code to use it. Currently, for the error type I am using `Exception`, but this can be replaced by other, more specific error types in the future.
Fixes #3063.
=> Add Rust-like Result type

deny.toml
Temporarily ignoring `RUSTSEC-2020-0159` until https://github.com/project-oak/oak/issues/3131 is fixed.
=> Ignore RUSTSEC-2020-0159

Cargo.lock, experimental/oak_functions_loader_linux_vsock/Cargo.toml, experimental/oak_functions_loader_linux_vsock/src/channel.rs, experimental/oak_functions_loader_linux_vsock/src/main.rs
This PR fixes:
- Vsock channel message sizes were read as BigEndian instead of NativeEndian
- Socket was set into the non-blocking mode by default causing the runtime to receive an error when reading an empty channel
=> Fix message size and socket blocks in Oak Functions Linux wrapper

Cargo.lock, experimental/oak_baremetal_app_crosvm/Cargo.lock, experimental/oak_baremetal_channel/src/server.rs, experimental/oak_baremetal_kernel/src/lib.rs, experimental/oak_baremetal_runtime/Cargo.toml, experimental/oak_baremetal_runtime/README.md, experimental/oak_baremetal_runtime/src/lib.rs, experimental/oak_functions_loader_linux_native/src/main.rs, experimental/oak_functions_loader_linux_vsock/src/main.rs
This makes the runtime crate a pure implementation of flatbuffer service [schema](https://github.com/project-oak/oak/blob/main/experimental/oak_baremetal_runtime/schema.fbs/#L3). It does so by moving all logic for translating between flatbuffer and the communication protocol into the `oak_baremetal_channel` crate.
I think this makes most logical sense, and will make it far easier to add integration tests covering the runtime behavior (issue ref: https://github.com/project-oak/oak/issues/3136)
=> Isolate runtime logic from communication channel logic

experimental/oak_baremetal_app_crosvm/layout.ld
For now, these do nothing, but will be used to denote locations in the memory where the SEV-SNP cpuid and secrets pages will be placed.
Although these are supposed to be page-sized (4K) I aligned the structures at 2M boundaries, as we've yet to figure out what page size do we want to use in the kernel (2M hugepages vs 4K pages), so that'll make it compatible with both at the cost of some wasted memory.
=> Add placeholder cpuid and secrets sections to the ELF kernel.

experimental/oak_baremetal_app_crosvm/layout.ld
None of the flags are actually respected right now, as the ELF loaders in the VMMs don't set up permissions (or page tables) for us.
But it's a first step toward setting up page tables with proper permissions.
=> Create separate sections in the ELF file for parts of the program that should have different permissions.

experimental/oak_baremetal_app_crosvm/layout.ld
Baby steps toward a higher-half kernel and setting up proper page tables with memory protection.
First, this will align all data structures at 2M boundaries, so that we can set up page tables more easily.
Second, this will add an explicit `KERNEL_MEM_START` to set the kernel offset. Right now we're in the lower half, so it's zero, but eventually this will be the upper half (more precisely, the last 2GB of virtual memory aka -2G).
Example of segments with `KERNEL_MEM_START = 0`:
```
Section Headers:
[Nr] Name              Type            Address          Off    Size   ES Flg Lk Inf Al
[ 0]                   NULL            0000000000000000 000000 000000 00      0   0  0
[ 1] .boot             PROGBITS        0000000000200000 001000 00000e 00  AX  0   0  1
[ 2] .text             PROGBITS …
```
=> Align all sections to 2M boundaries, and add an explicit load offset.

WORKSPACE, java/BUILD, java/src/main/java/com/google/oak/client/AeadEncryptor.java, java/src/main/java/com/google/oak/client/OakClient.java, java/src/main/java/com/google/oak/client/amd/AmdAttestationReport.java, java/src/main/java/com/google/oak/client/amd/AmdAttestedOakClient.java, java/src/main/java/com/google/oak/evidence/AttestationReport.java, java/src/main/java/com/google/oak/evidence/BasicEvidence.java, java/src/main/java/com/google/oak/evidence/EndorsementEvidence.java, java/src/main/java/com/google/oak/evidence/Evidence.java, java/src/main/java/com/google/oak/util/Result.java, java/src/test/java/com/google/oak/client/OakClientTest.java, java/src/test/java/com/google/oak/client/amd/AmdAttestedOakClientTest.java, java/src/test/java/com/google/oak/util/ResultTest.java
This PR:
- Adds placeholder implementation for `AmdAttestedOakClient`, and `AmdAttestationReport`.
- Moves classes related to `Evidence` into a separate package.
- Removes the abstract builder in `OakClient`, as a good implementation of it would require too many type parameters, and would not do much really.
Notable next steps:
- Implement Rekor logEntry verification and `verify` in `EndorsementEvidence`.
- Unifying the Rust and Java implementation. It is probably best to do this after updating the interactive remote attestation implementation. 
Ref #3066
=> Add Placeholder implementation for an AMD-attested Oak client

Cargo.lock, experimental/sev_guest/Cargo.toml, experimental/sev_guest/src/msr.rs
`anyhow` uses the heap, so it requires a global allocator. We don't have one in the SEV-SNP hello world kernel.
This does the laziest thing of replacing the error with a `&'static str`; it worked for all but one location where unfortunately we will now lose the error code.
We should really introduce proper error types for this, but for now, this will let us move forward.
=> Excise `anyhow` from the `sev_guest` crate.

experimental/oak_baremetal_app_crosvm/src/asm/boot.s
This change doesn't do much right now, as we're rewriting the page tables after we boot by setting up identity mapping for the lower 4 GB of memory.
Steps needed to load the kernel to the upper half:
=> Map the kernel to -2GB in virtual memory in the initial page tables.

third_party/rust-hypervisor-firmware-boot/src/paging.rs
Follow-up to #3158 -- we're rewriting page tables after the kernel starts, so we need to make sure we don't pull the rug from under our feet.
This code is temporary. In the not-too-distant-future I want to replace the whole `rust_hypervisor_firmware_boot::paging` code that just sets up identity mapping with more intelligent page table construction that pays attention to where the different ELF sections should go, and what permissions those regions should get (see #2983 and #2986). But for now, this hack allows us to progress on #2984.
Steps needed to load the kernel to the upper half:
=> Map last two gigabytes of virtual address space to physical 0x0

experimental/oak_baremetal_app_crosvm/layout.ld, experimental/oak_baremetal_kernel/src/lib.rs, experimental/oak_baremetal_kernel/src/memory.rs, third_party/rust-hypervisor-firmware-boot/src/paging.rs
This builds on #3158 and #3159 by actually setting the kernel virtual addresses to the kernel half of the address space.
Unfortunately Github doesn't have the concept of "this PR is dependent on those two", so this change contains changes from both of these. The core change here is the two-line change in `layout.ld`:
https://github.com/project-oak/oak/blob/fe8a7f0aecc3bf319ba7a3045155fb52a5d88783/experimental/oak_baremetal_app_crosvm/layout.ld#L40-41
Closes #2984.
Steps needed to load the kernel to the upper half:
=> Move the kernel to the upper half of VMA

.github/workflows/ci.yaml, .xtask_bash_completion, experimental/trusted_shuffler/Dockerfile, experimental/trusted_shuffler/backend/src/main.rs, experimental/trusted_shuffler/scripts/common, experimental/trusted_shuffler/scripts/deploy, experimental/trusted_shuffler/scripts/docker_build, experimental/trusted_shuffler/server/src/http.rs, xtask/src/examples.rs, xtask/src/internal.rs, xtask/src/main.rs
To allow for environment variables, which can be updated on Google Cloud, we don't use distroless docker any more. 
We also build the Rust binary with the builder Docker, so we don't rely on the host having Rust installed.
=> Update deploy script of Trusted Shuffler

experimental/oak_baremetal_app_crosvm/layout.ld
This PR will make the ELF file header (`FILEHDR`) and program headers (`PHDRS`) available for us during runtime.
The program headers will be useful in the future when constructing page tables for the kernel, as they tell us (a) which sections where loaded where in the physical memory, (b) what the virtual addresses should be, and (c) what privileges (write/execute) are needed for that section. This will allow us to map executable code with just execute bit set and data with just the write bit set, for example.
The section(s) containing `FILEHDR` and `PHDRS` have to be the first ones in the file. Previously we had the boot code at the 2M boundary, this will load the headers at the 2M mark, and punt the boot code up by 4K (one page size).
=> Load ELF headers into memory

.github/workflows/provenance.yaml
This PR adds a new job to the provenance workflow to generate a signed provenance using the generic SLSA generator. This is in an experimental state, since it is not possible to trigger the generator on pull-request events. I have added `workflow_dispatch` as a trigger for the provenance workflow. Once this is merged it is possible to experiment with provenance generation. 
If that is successful, I'll cleanup and complete the added step.
=> Experimental: Use SLSA generic workflow for generating provenances

.github/workflows/provenance.yaml
Follow up fix for #3166. The previous attempt failed with [error `expected at least one subject`](https://github.com/project-oak/oak/runs/8018867730?check_suite_focus=true#step:3:258).
=> Set subject in the output of the provenance workflow

experimental/oak_baremetal_app_crosvm/src/asm/boot.s, testing/sev_snp_hello_world_kernel/src/asm/boot.s
The BSS section contains static variables, and the C (and Rust's) memory model expects the memory there to be zero-initialized.
And it just happens by accident that the memory given to us by VMMs was always zero-initialized, meaning our code works. But we're well into undefined behaviour and it works by sheer luck only.
Once we tried enabling SNP, that property was no longer true (as zero doesn't necessarily decrypt to zero), and all kinds of interesting things started breaking as their internal invariants were horribly broken.
Thus: let's do what we should have always done, and manually reset the memory to zero. And x86 has a special magic instruction, `REP STOSB` to do just that, so we don't even need a loop.
=> Zero-initialize BSS properly

.github/workflows/ci.yaml, experimental/oak_baremetal_launcher/src/main.rs, experimental/oak_baremetal_launcher/src/server.rs, experimental/oak_baremetal_runtime/schema.fbs, experimental/oak_baremetal_runtime/src/lib.rs, experimental/oak_baremetal_runtime/src/remote_attestation.rs, grpc_unary_attestation/proto/BUILD, grpc_unary_attestation/proto/unary_server.proto, grpc_unary_attestation/src/server.rs, remote_attestation/rust/src/handshaker.rs, remote_attestation/rust/src/tests/handshaker.rs, remote_attestation_sessions/src/lib.rs
This change makes information about the attestation public key available to the client via a separate RPC method. This is the first step towards fixing #3096
=> Make remote attestation public key and attestation information available outside the handshake

docs/remote-attestation.md
We don't need to send a 3rd new string alongside the Client's Identity, because the challenge response only uses 2 strings (one from Client and one from Server).
=> Remove third new string from the remote attestation docs

Cargo.lock, Cargo.toml, experimental/oak_baremetal_app_crosvm/Cargo.lock, experimental/oak_baremetal_app_crosvm/Cargo.toml
Our PR to fix the issue upstream was merged and release, we can now remove the patch: https://github.com/bbqsrc/thiserror-core2/pull/3
Patch first added in: #2931
Tracking issue: #2920
=> Replace temp dependency patch with upstream fix

testing/sev_snp_hello_world_kernel/layout.ld, testing/sev_snp_hello_world_kernel/src/ghcb.rs, testing/sev_snp_hello_world_kernel/src/main.rs
This is the first in a series of PRs to enable serial port based logging on AMD SEV-ES and SEV-SNP using the GHCB IOIO protocol to drive the serial port.
This PR adds the GHCB data structure to the Hello World testing kernel, initialises it and shares it with the hypervisor (only SEV-ES version at the moment which requires marking the page as unencrypted).
Actually using this data structure and the protocol to write to the serial port will be done in a follow-up PR.
=> Add GHCB data structure to the Hello World testing kernel

stage0/.cargo/config.toml, stage0/README.md, stage0/layout.ld, stage0/src/main.rs
Things to note:
- This is a _massive_ pile of unsafe code.
- Linking Rust code in, especially in debug mode, required us to have a larger firmware image.
- There's a ton of clean-up to do in here, and missing features, but this is enough to get the machine to start executing from `0x200000`.
=> Set up data structures similar to crosvm and jump to kernel in our stage0 BIOS

testing/sev_snp_hello_world_kernel/src/main.rs, testing/sev_snp_hello_world_kernel/src/serial.rs
This is a follow-up to #3190. It allows the Hello World test kernel to use the GHCB serial port implementation when running on AMD SEV-ES.
Enabling support for AMD SEV-SNP will be done in a later PR.
=> Use GHCB serial port for logging when running on AMD SEV-ES

java/BUILD, java/src/main/java/com/google/oak/rekor/RekorLogEntry.java, java/src/test/java/com/google/oak/rekor/RekorLogEntryTest.java, oak_functions/client/java/BUILD
I am planning to endorsement verification logic to the top-level java. This PR is a pre-requisite restructuring step.
=> Move RekorLogEntry.java to top-level java folder

stage0/Cargo.lock, stage0/Cargo.toml, stage0/deny.toml, stage0/layout.ld, stage0/src/asm/boot.s, stage0/src/main.rs
This automatically detects whether we're running under SEV or not, and if memory encryption is required, sets the correct bit in the page tables.
To do that, we first need to enter unreal mode -- real mode with a 32-bit data segment -- so that we can access the memory near the 4G boundary, where the page tables live.
=> SEV enlightenment: set the encrypted bit if we're running under SEV-{,ES}.

deny.toml, experimental/oak_baremetal_app_crosvm/deny.toml, oak_functions/loader/fuzz/deny.toml, stage0/deny.toml, testing/oak_echo_bin/deny.toml, testing/sev_snp_hello_world_kernel/deny.toml
At the moment cargo-deny raises warnings if we use git source directly in Cargo.toml files without explicitly adding them to an allow list. I don't think we need these warnings and have been ignoring them anyway.
=> Remove cargo-deny git source warnings

stage0/layout.ld, stage0/src/asm/boot.s
Instead of entering 16-bit "unreal mode" (with a flat data segment), let's just enter 32-bit protected mode w/ said flat memory segment. As an additional bonus, by using a 32-bit code segment, `IP` values make sense in a debugger.
This means we're out of 16-bit mode in ~10 instructions. I think we could shave off a few more instructions (do we really need an IDT, for example?) but I think this is good enough to get from the 1970s to the 1980s in 10 instructions. (And then to the 2000s in ~30 instructions.)
=> Clean-up: enter protected mode and stay there.

.github/dependabot.yml, Cargo.lock, experimental/oak_baremetal_app_crosvm/Cargo.lock, experimental/oak_baremetal_kernel/src/memory.rs, testing/oak_echo_bin/Cargo.lock
The linked-list allocator has been updated past the buggy 0.10.0 version, so it should be fine to update throughout now.
=> Update linked-list allocator

experimental/oak_baremetal_runtime/tests/integration_test.rs, experimental/web_client/src/lib.rs, grpc_unary_attestation/src/client.rs, remote_attestation_sessions_client/src/lib.rs
Useful as soon (see #3191) we'll have an implementation of this trait using streaming gRPC. Renaming this now avoids confusion later on code related to unary gRPC.
=> Rename the former UnaryClient trait to clarify its role of abstracting networking

stage0/Cargo.lock, stage0/Cargo.toml, stage0/layout.ld, stage0/src/asm/boot.s, stage0/src/main.rs
We want the stage0 binary to be compatible with both machines that do support SEV, and machines that do not.
To determine whether memory encryption is enabled (and that we need to set the encrypted bit), we need to access the `SEV_STATUS` MSR.
Curveball 1: if we try to read the `SEV_STATUS` MSR on a machine that doesn't support it, we get killed with a `#GP` fault. Therefore, we need to determine via `CPUID` whether SEV is supported at all.
Curveball 2: if we're running under SEV-ES (and presumably SEV-SNP), calling `CPUID` triggers a `#VC` fault as you're supposed to use the GHCB protocol to get the CPUID values.
Thus: let's create a `#VC` handler that returns "yes, SEV is supported" (as if you're not under SEV-ES, how did you end up triggering that exception?), and then check the CPUID …
=> Call CPUID to figure out whether memory encryption is supported at all

.devcontainer.json, Dockerfile, docs/development.md, scripts/common, scripts/docker_build, scripts/docker_run
Required disabling buildkit support, which seems incompatible with
rootless for some reason (needs further investigation in https://github.com/project-oak/oak/issues/3225).
The next step (if no one complains) will be to remove the
`fix_docker_user_and_run` script, in another PR.
This should not affect CI, since CI usually already runs under root
anyways (Docker is not a security boundary, so it would be unlikely that
any CI would run the Docker daemon as root but the CI steps as a
different user).
Fix https://github.com/project-oak/oak/issues/2602
=> Use rootless docker

stage0/layout.ld
This is enough to get the stage0 code up and running under SEV-SNP; verified by adding a `loop {}` just after `rust64_start`.
Mind you, the VM crashes as soon as we call `GlobalDescriptorTable::new()` inside the stage0 code proper; presumably that's because we haven't validated the memory we're trying to access.
The locations for the secrets/cpuid/etc pages can't be in the BIOS blob itself. I poked around EDK2 source code, and it looks like they place those pages in the lower 1M of memory, and thankfully it looks like the addresses don't clash with anything we're using (our L1 page table is at `0xB000`), so we can use the same addresses as they do.
We do need to document the memory layout properly, though, to ensure that we won't accidentally introduce clashes in the future.
=> SEV-SNP enlightenment: add necessary data structures to stage0

scripts/common, scripts/docker_push
Also rename image to clarify that it is for development purposes (i.e. not for deployment of a running server)
Fix #3228
=> Use Google Cloud Artifact Registry

testing/sev_snp_hello_world_kernel/src/main.rs, testing/sev_snp_hello_world_kernel/src/serial.rs
Using the MSR protocol to request shutdown causes the VMM to exit with an error, so this uses a different mechanism for the shutdown.
=> Use the i8042 device for shutdown on SEV-ES/SNP

experimental/sev_guest/src/instructions.rs, stage0/src/main.rs
This is a bit hacky, but I got the hello world kernel to run under SEV-SNP with these changes.
For future:
- This blindly attempts to `PVALIDATE` all memory, no matter whether it's already marked or not. Either we need to be more clever (read the ELF header of the kernel and skip sections that should have been covered by the VMM), or add a sanity check that if the system says that it didn't change the value, then make sure it's indeed valid.
- Obviously cover all of the valid physical memory and not the arbitrary 32 MiB like I did here.
=> SEV-SNP enlightentment: `PVALIDATE` a chunk of memory.

Cargo.lock, Cargo.toml, linux_boot_params/Cargo.toml, linux_boot_params/README.md, linux_boot_params/src/lib.rs
We need the data structures in `stage0` to set up the boot environment, and later in the kernel(s) to read the zero page. Hence, it makes sense to have a separate crate for these that we can share between the different crates.
There's nothing Oak-specific in there, either. It's just the Linux data structures, Rustified a bit by hand.
=> Create a separate crate for Linux boot data structures.

stage0/layout.ld, stage0/src/main.rs
The main goal here was to move magic memory addresses to the linker script rather than have them in the Rust code.
This means that the linker can do some sanity checks: for example, if we have overlapping data structures, the linker would throw an error when linking the code. That wouldn't be the case if we're using raw memory addresses in The Rust code.
So, in a way, this code is safer than it was before: first, the linker guarantees that the memory won't overlap; second, `MaybeUninit::write` guarantees that the data structure there will be initialized properly. (It's a safe function!).
Unfortunately as we're dealing with `static mut`-s, the increased safety is not immediately visible as we need to wrap every access to those in an `unsafe` block anyway. But it' slightly less unsafe!
As …
=> Move hard-coded addresses to linker script in stage0.

scripts/xtask
This prevents the cargo cache from being overwritten when some other build command is run. Currently, if you run xtask and it runs some other command, sometimes it invalidates its own binary in the cargo cache, which means the next time it is invoked it will have to be rebuilt again, which takes a few tens of extra seconds each time. Now it is instant instead.
=> Always compile xtask with explicit target

stage0/Cargo.lock, stage0/Cargo.toml, stage0/layout.ld, stage0/src/main.rs
We were hoping to use magic ELF sections in the kernel itself to designate where the secrets and CPUID pages should go, but that won't work with the stage0 approach.
Instead of that, if stage0 detects we're running under SEV, let's add an extended setup_data arg to the zero page that points to the locations of those magic pages.
This is also how the location information is handed to the Linux kernel itself.
For now, we'll assume that the VMM has populated (the rest of) the zero page for us; in the hopefully not-too-distant future, the whole zero page will be created in stage0.
=> Populate locations of SEV secrets/cpuid pages in zero page.

experimental/sev_guest/src/ghcb.rs
We don't have to always reset the GHCB, because we set a bitmap which specifies the valid fields. Resetting an entire 4KiB data structure to 0 for every character we write to the serial port is very expensive and noticibly slows down logging.
Fixes #3231
=> Do not always reset the GHCB

testing/sev_snp_hello_world_kernel/Cargo.lock, testing/sev_snp_hello_world_kernel/Cargo.toml, testing/sev_snp_hello_world_kernel/layout.ld, testing/sev_snp_hello_world_kernel/src/main.rs
This is complementary to https://github.com/project-oak/oak/pull/3246.
We were always printing out those data structures, even when we weren't running under SEV-SNP; as the pages weren't populated, they contained garbage anyway.
Instead, let's print out nice status messages about whether we've detected any of {SEV,SEV-ES,SNP} as enabled and print out the cpuid/zero pages only under SEV-SNP.
=> Use the zero page to locate the cpuid/secrets structures in the hello world kernel

Cargo.lock, deny.toml
Tonic has not been updated, but a fixed version of axum-core is compatible with the current version of axum.
Fixes #3202
=> Update axum-core to resolve cargo-deny advisory

stage0/Cargo.lock, stage0/Cargo.toml, stage0/src/main.rs
Our hello world kernel had its entry point at `0x200000`, so we blindly jumped to that address. However, our real Restricted Kernel has its entry point at `0x201000`, as it first loads its own ELF file header to address `0x200000`.
Thus, let's check if we have a valid ELF header at that address. If yes, look up the entry point address from the header. If we don't find an ELF header at that address, assume it's code and just jump there.
Strictly speaking there is no standard that requires there to be either code or ELF header at 0x200000, it's just a convention we follow. I suspect we need to do something more clever here if we ever want to make the Linux kernel boot with our stage0.
Fixes #3199
=> Check if we have a ELF header at 0x200000 in stage0

Cargo.lock, experimental/oak_baremetal_app_crosvm/Cargo.lock, experimental/oak_baremetal_kernel/Cargo.toml, experimental/oak_baremetal_kernel/src/lib.rs, experimental/oak_baremetal_kernel/src/mm/bitmap_frame_allocator.rs, experimental/oak_baremetal_kernel/src/mm/mod.rs, testing/oak_echo_bin/Cargo.lock
This is the first step toward better tracking of the physical memory that we have available in the kernel.
What is implemented here is a frame allocator, limited to fixed frame sizes and memory range(s). While the algorithm is... unsophisticated, the key feature of the frame allocator is that it doesn't do dynamic memory allocation itself, as the frame allocator is initialized before the heap (in fact, the heap allocator will have to ask for memory to manage from the frame allocator).
Rough outline of what needs to be done:
=> Create a bitmap allocator for physical frames

experimental/oak_baremetal_app_crosvm/layout.ld, testing/oak_echo_bin/layout.ld, testing/sev_snp_hello_world_kernel/layout.ld
Our original plan was to determine what memory regions to use for the SEV-SNP secrets pages based on data in the ELF files (special magic sections), but as we're heading down the route of using stage0 that approach won't work.
The physical memory locations of the SEV-SNP secrets pages will be provided to the kernel during runtime in the `boot_info` structure.
Therefore, let's clean up the stray references to the sections that are neither used right now nor will never be.
=> Clean-up: remove references to special CPUID/secrets ELF sections.

experimental/oak_baremetal_kernel/src/lib.rs, experimental/oak_baremetal_kernel/src/memory.rs, experimental/oak_baremetal_kernel/src/mm/bitmap_frame_allocator.rs, experimental/oak_baremetal_kernel/src/mm/frame_allocator.rs, experimental/oak_baremetal_kernel/src/mm/mod.rs
Following up to #3168, this now makes use of the bitmap allocator.
First, we create a proper frame allocator for physical memory that is able to handle both 2M and 4K pages, as necessary.
Second, set up the frame allocator with the information from the E820 map, and use it to find the largest memory region for the heap, similar to what we do now.
This covers the basic functionality, but that's not all we need. It still relies on the magic linker variables to make sure we won't overwrite our other data structures; these reserved regions should be properly parsed from the ELF header (which we do load into memory).
And, we want the page allocator to use this frame allocator as well.
But we now do have an authoritative data structure to represent which memory regions are in use and which are …
=> Initialize frame allocator from E820 and use it for finding memory for the heap

.github/workflows/provenance.yaml, buildconfigs/oak_functions_loader_base.toml, oak_functions/examples/echo/config.toml, oak_functions/examples/echo/example.toml, oak_functions/examples/key_value_lookup/config.toml, oak_functions/examples/key_value_lookup/example.toml, oak_functions/examples/weather_lookup/config.toml, oak_functions/examples/weather_lookup/example.toml, remote_attestation/rust/src/handshaker.rs, xtask/src/examples.rs, xtask/src/internal.rs
Change logic in `xtask` to parse the config values (e.g. wasm module
location, constant size) from the example.toml file directly, since the
split launcher accepts them as separate flags instead of a single config
file.
The web client does not seem to work with the split launcher, so I
temporarily disabled it and created #3256 to follow up.
The Java client was also initially not working, but I tracked that down
to the server trying to parse the transcript signing key, but the Java
client only providing zeros for it at the moment. That work is already
tracked in #2918.
Fix #3241
=> Use Split launcher to run examples

Cargo.lock, experimental/sev_guest/Cargo.toml, experimental/sev_guest/src/ghcb.rs, experimental/sev_guest/src/io.rs, experimental/sev_guest/src/lib.rs, experimental/sev_guest/src/serial.rs, stage0/Cargo.lock, testing/sev_snp_hello_world_kernel/Cargo.lock, testing/sev_snp_hello_world_kernel/src/ghcb.rs
This implements an abstraction for IO ports so that our guest devices can be updated to use either direct IO access (when running without encryption or with SEV) or the GHCB IOIO protocol (when running with SEV-ES or SEV-SNP).
This PR also makes the GHCB-related code more generic so that is could be used with static references when there is no allocator, or with `Box` and `Arc` when an allocator is available.
=> Add traits for IO port access

.devcontainer.json, Dockerfile, scripts/common
`binutils` comes with various utilities to manage binaries, such as `objcopy` which can be used to turn ELF files into headerless binary blobs.
We need `objcopy` for `stage0`: namely, `cargo build` gives us an ELF file, but `qemu` and other VMMs expect the BIOS image to be a headerless blob.
Instead of doing `cargo build` + manually invoking objcopy on the target file, using `cargo-binutils` we can do it in one step:
```
cargo objcopy -- -O binary stage0.bin
```
=> Add `cargo-binutils` to our development image.

oak_restricted_kernel/src/lib.rs, oak_restricted_kernel/src/mm/mod.rs, oak_restricted_kernel/src/mm/page_tables.rs
Previously we just blindly mapped all of the lowest 2GiB of physical memory to the last 2 GiB of virtual memory, and marked everything as executable and writeable.
This is bad for multiple reasons. First, you don't need access to all of the memory; second, sections containing code should _not_ be writable by default and sections containing data should _not_ be executable by default.
As a reminder, this is the memory map of the kernel right now:
```
Program Headers:
Type           Offset   VirtAddr           PhysAddr           FileSiz  MemSiz   Flg Align
[...]
LOAD           0x002000 0xffffffff80400000 0x0000000000400000 0x268eeb 0x268eeb R E 0x1000
LOAD           0x26b000 0xffffffff80800000 0x0000000000800000 0x04a460 0x04a460 R   0x1000
LOAD           0x2b6000 0xffffffff80a00000 …
```
=> Create kernel page map entries based on ELF program headers

experimental/oak_baremetal_app_crosvm/Cargo.lock, oak_restricted_kernel/src/lib.rs, oak_restricted_kernel/src/memory.rs, oak_restricted_kernel/src/mm/mod.rs, oak_restricted_kernel/src/mm/page_tables.rs, oak_tensorflow_bin/Cargo.lock, testing/oak_echo_bin/Cargo.lock
For now, we've always assumed that there's an identity mapping; that is, you can freely convert between physical and virtual addresses by just using the raw pointer value.
This is the first step in moving away from that assumption: as the heap initialization deals in virtual memory, make that use (virtual) `Page`-s rather than (physical) `Frame`-s.
=> Change heap allocator to take (virtual) pages, not (physical) frames.

Cargo.lock, experimental/oak_baremetal_app_crosvm/Cargo.lock, experimental/oak_baremetal_app_crosvm/deny.toml, experimental/oak_baremetal_simple_io/Cargo.toml, experimental/oak_baremetal_simple_io/src/lib.rs, oak_restricted_kernel/Cargo.toml, oak_restricted_kernel/src/simpleio.rs, oak_tensorflow_bin/Cargo.lock, oak_tensorflow_bin/deny.toml, testing/oak_echo_bin/Cargo.lock, testing/oak_echo_bin/deny.toml
Similar to the serial port update in #3270, this change uses the IO abstraction to make the Simple IO device compatible with either direct port-based IO (when running without encryption or with SEV) and the GHCB IOIO protocol (when running with SEV-ES and SNP).
=> Refactor the SimpleIO device to be GHCB-compatible

Cargo.lock, experimental/oak_baremetal_app_crosvm/Cargo.lock, experimental/virtio/Cargo.toml, experimental/virtio/src/console/mod.rs, experimental/virtio/src/console/tests.rs, experimental/virtio/src/queue/mod.rs, experimental/virtio/src/queue/tests.rs, experimental/virtio/src/queue/virtq.rs, experimental/virtio/src/test.rs, experimental/virtio/src/vsock/mod.rs, experimental/virtio/src/vsock/tests.rs, oak_tensorflow_bin/Cargo.lock, testing/oak_echo_bin/Cargo.lock, third_party/rust-hypervisor-firmware-virtio/src/device.rs, third_party/rust-hypervisor-firmware-virtio/src/pci.rs, third_party/rust-hypervisor-firmware-virtio/src/virtio.rs
Right now the code assumes identity mapping (that is, `VirtAddr == PhysAddr`) and passes around naked `u64`-s everywhere.
We want to break the assumption that virtual addresses are identity mapped to physical addresses, and as the first step we should distinguish what `u64` is exactly what.
In short: if you use `as_ptr()` or anything like that, you get a `VirtAddr`. And any communication to the VMM needs to use `PhysAddr`s.
For now, the translation still assumes identity translation (we do `PhysAddr::new(VirtAddr.as_u64())`), but this makes the conversion between virtual and physical addresses explicit, and gives us a point where we need to apply a transformation function in the future.
=> Distinguish between `VirtAddr` and `PhysAddr` in the virtio crate.

experimental/virtio/src/console/mod.rs, experimental/virtio/src/test.rs, experimental/virtio/src/vsock/mod.rs, third_party/rust-hypervisor-firmware-virtio/src/device.rs, third_party/rust-hypervisor-firmware-virtio/src/lib.rs, third_party/rust-hypervisor-firmware-virtio/src/mem.rs, third_party/rust-hypervisor-firmware-virtio/src/pci.rs, third_party/rust-hypervisor-firmware-virtio/src/virtio.rs
As with many other crates, the assumption that virtual addresses are the same as physical was baked deep into the virtio crate.
This PR cleans up the code by using `PhysAddr` and `VirtAddr` where appriopriate (instead of naked `u64`-s), and exposes a translator function to the API users in case we're not running under identity-mapped memory.
For now, the assumption (of running under identity mapping) is still true, so in the `virtio` crate we just pass in a dummy translator. But this gives us a hook to use later when we move away from identity mapping.
=> Expose a memory translator function in rust-hypervisor-firmware-virtio.

experimental/virtio/src/console/mod.rs, experimental/virtio/src/console/tests.rs, experimental/virtio/src/lib.rs, experimental/virtio/src/queue/mod.rs, experimental/virtio/src/queue/tests.rs, experimental/virtio/src/test.rs, experimental/virtio/src/vsock/mod.rs, experimental/virtio/src/vsock/socket/tests.rs, experimental/virtio/src/vsock/tests.rs, oak_restricted_kernel/src/virtio.rs
This PR builds on #3302 and is similar in purpose to #3306: move the memory mapping functions to the kernel.
As in that PR, for now we continue to assume identity mapping. But at least after this the kernel is in control, and we can switch it out in one single place.
=> Expose virtio memory translation functions to the kernel

experimental/oak_baremetal_simple_io/src/lib.rs, oak_restricted_kernel/src/simpleio.rs
The main goal here was to expose the memory translation function to the users of the crate; for now, we still assume identity mapping in the kernel.
However, as I was in there, `cargo clippy` deemed a function with 9 arguments as too much, so I refactored how the buffer I/O port descriptors are handled into a separate struct. I think it looks cleaner this way, so can't say I disagree with `cargo clippy` in the end...
=> Expose the memory translation function in simple_io crate.

third_party/rust-hypervisor-firmware-virtio/src/device.rs, third_party/rust-hypervisor-firmware-virtio/src/lib.rs, third_party/rust-hypervisor-firmware-virtio/src/pci.rs, third_party/rust-hypervisor-firmware-virtio/src/virtio.rs
This addresses a comment in #3307 where Conrad noted that we're using the names in an inconsistent way in different crates.
=> Rename `Translator` to `InverseTranslator` for consistency

Cargo.lock, experimental/sev_guest/Cargo.toml, experimental/sev_guest/src/io.rs, oak_functions_freestanding_bin/Cargo.lock, oak_simple_io/src/lib.rs, oak_tensorflow_freestanding_bin/Cargo.lock, sev_serial/src/lib.rs, stage0/Cargo.lock, testing/oak_echo_bin/Cargo.lock, testing/sev_snp_hello_world_kernel/Cargo.lock
This change adds wrapper enums around the IO port implementations (raw and GHCB-based) and the related IO port factories. This will be used in follow-up PRs to simplify the drivers that depend on these port implementations.
=> Add wrappers for IO ports and related factories

oak_restricted_kernel/src/descriptors.rs, oak_restricted_kernel/src/lib.rs
After we removed the identity-mapped memory, our interrupt handlers broke.
This was bit of a mystery, but boils down to the fact that when an interrupt happens the processor will try to switch segments to the one described in the IDT. However, we weren't setting up a proper new GDT in the kernel but rather relying on the one set up by the bootloader for us, which meant the GDT was somewhere in low memory that was no longer mapped.
All of our existing code worked just fine, because we don't switch between segments during normal execution. However, once an interrupt happened, the CPU triple-faulted as it couldn't find the GDT.
This PR sets up a new GDT, managed by our kernel. I've also used this opportunity to set up user code/data segments and a proper task state segment as well, although …
=> Populate GDT in Restricted Kernel

oak_restricted_kernel/src/simpleio.rs, oak_simple_io/src/lib.rs, sev_serial/src/lib.rs, testing/sev_snp_hello_world_kernel/src/serial.rs
The wrapper enums for IO ports and their related factories mean that we can now have simpler drivers that depend on these.
=> Simplify drivers using the new port wrapper enum

Cargo.lock, oak_functions/examples/key_value_lookup/module/Cargo.toml, oak_functions/examples/key_value_lookup/module/src/tests.rs, oak_functions/examples/weather_lookup/module/Cargo.toml, oak_functions/examples/weather_lookup/module/src/tests.rs, oak_functions/loader/Cargo.toml, oak_functions/loader/src/tests.rs, oak_functions/sdk/oak_functions/Cargo.toml, oak_functions/sdk/oak_functions/tests/integration_test.rs, oak_functions/sdk/test_utils/Cargo.toml, oak_functions/sdk/test_utils/src/lib.rs, oak_functions/wasm/src/lib.rs, oak_functions/wasm/src/tests.rs, oak_functions_launcher/src/main.rs, oak_functions_linux_fd_bin/src/main.rs
The overall goal is to stop depending on the unified Oak Functions
loader library, so that it may be deleted.
Also remove some of the tests that rely on constant processing time,
since that's not supported in the split binary yet (https://github.com/project-oak/oak/issues/3079).
Incidentally, I made the integration tests more aligned with actually
testing meaningful integrations, and I am starting to think that they
can replace running the examples at some point in the future (so we
drive the examples from proper Rust tests, instead of doing that from xtask).
Ref https://github.com/project-oak/oak/issues/3081
=> Use split Oak Functions server for tests

oak_restricted_kernel/src/descriptors.rs
This should have been a part of #3315 but I missed it it there.
We're not really using the TSS structure (yet), so there were/are no ill effects from the fact that we didn't load the TSS properly.
=> Load the TSS structure with the other segment descriptors.

oak_restricted_kernel/src/interrupts.rs, oak_restricted_kernel/src/lib.rs
This is similar to #3323 where we introduced a similar handler in the hello world kernel, but a bit more clever.
As we can't change register values when using the `x86-interrupt` calling convention, the naked interrupt handler checks if we're dealing with a `rdmsr`. If yes, it emulates `rdmsr` by setting RAX and RDX to zero, skipping the `rdmsr`, and continuing execution.
If, however, the `#GP` as triggered by something else than `rdmsr`, we make sure to _not_ overwrite RAX and pass the control on to the interrupt handler written in Rust, so that it could do whatever it pleases.
All of this is necessary so that we could read the SEV_STATUS MSR on machines that may not support SEV, such as Github Actions or Kokoro, without crashing.
=> Create a `#GP` handler that emulates `rdmsr` in Restricted Kernel.

trusted_shuffler/server/src/http.rs, trusted_shuffler/trusted_shuffler/src/lib.rs, trusted_shuffler/trusted_shuffler/src/tests.rs
Fixes #3282 . I opted for keeping the type information because it was (a) easier, and (b) we can re-visit that when we think of serialization for the whole Request/Response, i.e., also the headers.
=> Unify data and body in Requests/Responses

WORKSPACE, third_party/tflite-micro/remove-debug-logging.patch
This PR adds a patch to TFLM that removes the use of `fprintf`.
Ref https://github.com/project-oak/oak/issues/3297
=> Remove fprintf from TFLM debug logging

Cargo.lock, oak_functions_freestanding_bin/Cargo.lock, oak_functions_freestanding_bin/Cargo.toml, oak_restricted_kernel/Cargo.toml, oak_restricted_kernel/src/logging.rs, oak_tensorflow_freestanding_bin/Cargo.lock, testing/oak_echo_bin/Cargo.lock
Switch to using the SEV-ES and SNP compatible serial port implementation for logging. For now we just use the direct port IO implementation. Once the HGCB is set up correctly we can start using when running on SEV-ES or SNP.
=> Use sev-compatible serial port for logging

experimental/sev_guest/src/interrupts.rs, oak_restricted_kernel/src/interrupts.rs
For now we just want to log if the VMM communication exception happens. Actually handling this when CPUID is called and returning a valid response will be done later once we are able to read the location of the CPUID page from the boot parameter in the kernel.
=> Add initial #VC exception handler

Cargo.lock, oak_functions_freestanding_bin/Cargo.lock, oak_restricted_kernel/Cargo.toml, oak_restricted_kernel/src/lib.rs, oak_restricted_kernel/src/mm/encrypted_mapper.rs, oak_restricted_kernel/src/mm/mod.rs, oak_restricted_kernel/src/mm/page_tables.rs, oak_restricted_kernel/src/simpleio.rs, oak_restricted_kernel/src/virtio.rs, oak_tensorflow_freestanding_bin/Cargo.lock, testing/oak_echo_bin/Cargo.lock
Building page maps is complex enough, and this PR does its best to delegate things to the `x86_64` crate but I still needed to re-implement several bits of it.
The mapper created here still doesn't know how to add or remove the `ENCRYPTED` bit for now; that'll be addressed separately.
I also tried really hard to hoist the encryption status into the type system, but let's just say it got real unwieldy real quick.
The key here is that we want to lie to the mapper from `x86_64` crate: first, we create a `FrameAllocator` that asks the real frame allocator for a frame and sets the encrypted bit in there, if necessary. That encryption-aware FrameAllocator is passed to the `x86_64` OffsetMapper, which is completely oblivious to the fact that something weird is going on with the physical frames. …
=> SEV enligthenment: implement encryption-aware page mapper

oak_restricted_kernel/src/mm/bitmap_frame_allocator.rs, oak_restricted_kernel/src/mm/frame_allocator.rs, oak_restricted_kernel/src/mm/mod.rs
Ranges are hard.
We're using a mix of inclusive ranges ([start...end], both ends included in range) and exclusive ranges ([start..limit), where the limit is not inside the range).
It's a mess and we should consolidate on one particular range style, and I think it makes sense to use exclusive ranges -- while we still need to do range arithmetic here and there, there's less of it when using exclusive ranges.
I've left the tests largely untouched on purpose: there's some clean-up to do there as well, but for now, I wanted the tests to pass with no (or at least minimal) changes.
=> Switch from inclusive ranges to exclusive ranges.

oak_restricted_kernel/src/lib.rs, oak_restricted_kernel/src/simpleio.rs, oak_simple_io/src/lib.rs
We need a custom allocator to ensure that the vectors are allocated in the memory area reserved for guest-host communication; we can't just rely on the system allocator in the future.
Unfortunately this means we now have to track lifetimes throughout the crate to placate the borrow checker. I'm still not _entirely_ convinced it's worth it, but at least in this crate it wasn't much hassle.
=> Plumb an explicit allocator through oak_simple_io crate.

oak_restricted_kernel/src/lib.rs, oak_restricted_kernel/src/memory.rs, oak_restricted_kernel/src/mm/encrypted_mapper.rs, oak_restricted_kernel/src/mm/mod.rs, oak_restricted_kernel/src/mm/page_tables.rs
This adds a facility to change page table flags (by default, all memory is marked as `ENCRYPTED`) and then uses it to set up a 2M page for use with guest-host communication.
I've also shuffled some data structures around in the hope of keeping `encrypted_mapper` private.
The allocator is not used for anything (yet) -- that'll be in follow-up PRs. This PR just lays out the infrastructure.
=> SEV enlightenment: create an allocator for unencrypted memory

experimental/virtio/src/console/mod.rs, experimental/virtio/src/console/tests.rs, experimental/virtio/src/lib.rs, experimental/virtio/src/queue/mod.rs, experimental/virtio/src/queue/tests.rs, experimental/virtio/src/vsock/mod.rs, experimental/virtio/src/vsock/socket/mod.rs, experimental/virtio/src/vsock/socket/tests.rs, experimental/virtio/src/vsock/tests.rs, oak_restricted_kernel/src/lib.rs, oak_restricted_kernel/src/virtio.rs
We need a custom allocator to ensure that the vectors are allocated in the memory area reserved for guest-host communication; we can't just rely on the system allocator in the future.
Unfortunately this means we now have to track lifetimes throughout the crate to placate the borrow checker. I'm still not entirely convinced it's worth it, but at least in this crate it wasn't much hassle.
This PR mirrors #3360 for the simple_io crate.
=> Plumb an explicit allocator through the virtio crate.

oak_restricted_kernel/Cargo.toml, oak_restricted_kernel/src/lib.rs, oak_restricted_kernel/src/mm/bitmap_frame_allocator.rs, oak_restricted_kernel/src/mm/frame_allocator.rs
We allocate 4 MB (two contiguous pages) for guest-host communication, set up a separate heap allocator managing that space, and then finally connect the dots by passing that allocator to the comms channels, instead of using the global allocator.
Note that the guest-host heap is still "global", hence we store it in a `static`.
=> Use separate heap for guest-host communication memory.

oak_restricted_kernel/src/interface.rs
This is to allow C code to shut down the VM via interop with the kernel.
=> Add exported function for exiting the VM

.github/actions/reproducibility_index/action.yml, .github/workflows/provenance.yaml
- Fixes the currently failing workflow job. 
- Fixes the set-output issue in GitHub workflow
- Adds a workflow step for publishing the output of uploading DSSE to Ent as a comment on the PR.
=> Fix provenance workflow

Cargo.lock, Cargo.toml, oak_protobuf_idl_build/Cargo.toml, oak_protobuf_idl_build/src/lib.rs, oak_protobuf_idl_tests/Cargo.toml, oak_protobuf_idl_tests/build.rs, oak_protobuf_idl_tests/oak.protobuf_idl.tests.rs.txt, oak_protobuf_idl_tests/test_schema.proto, oak_protobuf_idl_tests/tests/generate.rs, oak_protobuf_idl_tests/tests/test_schema.rs
Currently as a stand-alone crate, but in the future it may replace (and be renamed into) `oak_idl`.
Currently not used anywhere, just in its own tests.
The structure of the code generator is identical to the existing one from
https://github.com/project-oak/oak/blob/e75740a22c5c3db3d25031cd8b660b50aa60eda2/oak_idl_gen_services/src/lib.rs , which I copy-pasted and modified in order to be driven from prost instead of flatc.
The easiest way of reviewing this PR is probably to look at the generated file, which is also checked in for convenience and to catch regression or changes in the generator.
Ref #3385
=> Implement IDL based on protobuf

cc/tflite_micro/tflite_micro.cc, cc/tflite_micro/tflite_micro.h, oak_tensorflow_service/src/lib.rs, oak_tensorflow_service/src/tflite.rs
This PR makes TFLite initialization function return an output buffer length, so that this buffer could be allocated in Rust before calling TFLite inference.
=> Return output buffer length from TFLite initialization

experimental/sev_guest/src/ghcb.rs, experimental/sev_guest/src/lib.rs, oak_restricted_kernel/src/mm/mod.rs, oak_simple_io/src/lib.rs, testing/sev_snp_hello_world_kernel/src/ghcb.rs, third_party/rust-hypervisor-firmware-virtio/src/lib.rs
So far we have assumed an identity mapping between virtual and physical addresses of the GHCB. That works for the "hello world" test kernel, but will not work for the restricted kernel which is relocated to high memory.
=> Stop assuming identity mapping for GHCB

oak_functions_client/build.rs, oak_functions_launcher/build.rs, oak_utils/src/lib.rs
Currently we pass the entire workspace as the root path for protos compiled by tonic, but this causes tonic itself to emit change tracking logic that covers the entire directory (recursively).
Instead, limit the include path to the proto directory only.
Also, do not emit additional change tracking in our own code, since tonic already does that.
Fix #3392
=> Fix logic for tracking changes to protobuf

.xtask_bash_completion, docs/development.md, xtask/src/internal.rs, xtask/src/main.rs
#3271 has moved fuzz targets to a top-level `fuzz` crate. As a result the `crate-name` option passed to the `run-cargo-fuzz` command is no longer needed. This PR removes it.
=> Cleanup the run-cargo-fuzz command

.github/workflows/provenance.yaml, buildconfigs/oak_functions_freestanding_bin.toml, docs/release.md, scripts/build_binary
Fixes #3339 and fixes #3333.
- Removes the steps for uploading the provenances to the provenance branch from the "Build Provenance" workflow.
- Renames the "generate_provenance" script to "build_binary".
- Updates the `docs/release.md` with updated instructions for fetching provenance from `Ent`.
=> Cleanup the provenance generation and update the readme

experimental/sev_guest/src/ghcb.rs, oak_functions_freestanding_bin/Cargo.lock, oak_restricted_kernel/Cargo.toml, oak_restricted_kernel/src/ghcb.rs, oak_restricted_kernel/src/lib.rs, oak_restricted_kernel/src/mm/mod.rs, oak_restricted_kernel/src/mm/page_tables.rs, oak_tensorflow_freestanding_bin/Cargo.lock, testing/oak_echo_bin/Cargo.lock
This PR only adds the code to initialise the GHCB in the Restricted Kernel and share it with the hypervisor. The code for actually using the GHCB will be added in a follow-up PR.
=> Initialize the GHCB in the restricted kernel

Cargo.lock, oak_functions_freestanding_bin/Cargo.lock, oak_restricted_kernel/Cargo.toml, oak_restricted_kernel/src/ghcb.rs, oak_restricted_kernel/src/lib.rs, oak_restricted_kernel/src/logging.rs, oak_restricted_kernel/src/simpleio.rs, oak_tensorflow_freestanding_bin/Cargo.lock, testing/oak_echo_bin/Cargo.lock, testing/oak_echo_raw_bin/Cargo.lock
We can now use the GHCB for serial port logging and the simple IO device to support running under SEV-ES and SEV-SNP.
The virtio drivers are not yet compatible as they require additional work to support the MMIO GHCB protocol. That will be added in future.
=> Use the GHCB for drivers in the Restricted Kernel

oak_restricted_kernel/src/ghcb.rs, oak_restricted_kernel/src/mm/encrypted_mapper.rs
The GHCB sharing code duplicated code around address translation and page table management that was already written elsewhere in the restricted kernel. This PR removes the duplication and simplifies the implementation.
=> Clean up GHCB sharing code

experimental/sev_guest/src/msr.rs, oak_restricted_kernel/src/ghcb.rs, oak_restricted_kernel/src/lib.rs
When running on AMD SEV-SNP we need to also mark the shared heap that is used for guest-host communication as shared in the reverse-map table (RMP).
=> Mark guest-host heap as shared in the RMP

experimental/sev_guest/src/msr.rs, oak_restricted_kernel/src/interrupts.rs
This PR implements initial CPUID support in the VM Communications Exception handler using the MSR protocol. The MSR protocol does not support CPUID sub-leafs, but hopefully this is enough support for now to boot with SEV-ES activated.
=> Implement CPUID support for the VC exception handler

experimental/sev_guest/src/cpuid.rs, experimental/sev_guest/src/ghcb.rs, oak_restricted_kernel/src/ghcb.rs
The GHCB protocol provides a richer and more efficient mechanism for calling CPUID under AMD SEV-ES than the MSR protocol, including support for sub-leafs.
With AMD SEV-SNP the CPUID page can be used to get the information, but with SEV-ES there is no CPUID page.
=> Add support for CPUID to the GHCB protocol

stage0/layout.ld, stage0/src/asm/boot.s
This implements the fake `RDMSR` handler we have in Restricted Kernel, in 32-bit bootstrap code in stage0.
We need to know whether SEV is enabled so that we'd know whether we have to toggle the encrypted bit in the page tables. Previously, we first called `CPUID` to figure out whether SEV is supported at all, before calling `RDMSR` to figure out whether SEV is enabled.
However... as we're not particularly thorough here (we don't check whether the CPUID page is supported at all, for example) it looks like some Intel CPUs gave us garbage in return which we interpreted as SEV support being there, which then caused stage0 to crash with a `#GP` when trying to read the MSR.
However, we can just shortcut the whole process and trap the `#GP` that happens when we try to read the MSR and it doesn't …
=> Don't use `CPUID` to detect whether SEV is enabled in stage0

oak_functions_freestanding_bin/.cargo/config.toml
Given that our `#VC` handler is still buggy, any calls to `CPUID` fail right now. Case in point, the Rust getrandom crate will try to use `CPUID` to figure out if it can use `RDRAND`, which means we can't run under SEV-ES right now.
However... we can just force-enable the `RDRAND` instruction in the build target, optimizing away the `CPUID` check in getrandom. With this change we can run under SEV-ES!
=> SEV-ES: enable `RDRAND` in Oak Functions build

experimental/sev_guest/src/interrupts.rs, oak_restricted_kernel/src/interrupts.rs
I forgot to advance the instruction pointer past the CPUID instruction in the #VC exception handler, which meant that it kept on executing it after returning from the handler. This fixes the problem.
=> Advance RIP in CPUID VC handler

experimental/sev_guest/src/guest.rs, experimental/sev_guest/src/lib.rs, experimental/sev_guest/src/msr.rs
This is the first step towards implementing support for making SNP Guest Requests (such as requesting a remote attestation report) over the GHCB protocol.
This PR adds the structs and enums needed to create and interact with the messages used as requests and response in the protocol.
=> Add SNP Guest Request Message-related structs

stage0/src/main.rs, stage0/src/sev.rs
We need to run `pvalidate` on all physical memory before we use it; it's usually done in the bootloader, hence we put it in stage0.
For now, we ignore any errors that may occur. For some pages, we expect the validation status change to fail (everything populated by the hypervisor); in the future, we should double-check that the errors happen only where we expect them to, and crash if they occur anywhere else.
=> SEV-SNP: `pvalidate` all physical memory in stage0

stage0/.cargo/config.toml, stage0/Cargo.toml, stage0/build.rs, stage0/layout.ld
There are three major things in here:
* Enabling `opt-level = "z"` reduces the code by ~50K
* enabling LTO (which prunes a lot of dead code) reduces code size ~10x (!!!) -- from 70K to 7K.
This means we can fit the debug build into 256K instead of 512K, and in theory the release build would fit into 48K (!!!).
There are other things we can do to trim the size down further; for example, we could move the stack to low memory and we have 12K worth of page table structures in the BIOS data area. We could construct them during runtime in low memory with far less code than that -- but, to be blunt, I'm amazed at how much just enabling LTO for release builds saved us.
My main goal was to shave it down enough so that the release build could fit into 128K, and that goal is met, so I've left the …
=> Reduce the size of stage0 binary

oak_functions_freestanding_bin/Cargo.toml
For some yet unknown reason, the binary only works on SNP with this option or, or with some other random changes to the code. This is not a perfect solution, and will likely break again in the future, but at least it unblocks syncing previous changes to google3.
=> Enable LTO on Oak Functions binary

docs/oak_functions_abi.md, oak_functions/README.md, oak_functions/proto/abi.proto, oak_functions/wasm/src/tests.rs, oak_functions_abi/src/lib.rs
The TF Infrerence and Differentially Private metrics code has been removed, but there were still a few references to it in the code base.
=> Remove unused tf_inference and metrics references

oak_functions_freestanding_bin/Cargo.toml
@tiziano88 added this in #3435 as it seemed to help with weird errors we were seeing while running under SEV-SNP; however, it looks like @conradgrobler fixed the real underlying problem in #3441.
Thus, let's disable LTO, again. This is not to say we shouldn't enable LTO or LTO is bad; in fact, we probably should enable it, and will likely do so in the future. For now, I want to reduce the number of baseline changes until we're certain we caught the bug.
=> Turn off LTO on `oak_functions_freestanding_bin`

Cargo.lock, oak_functions_freestanding_bin/Cargo.lock, oak_functions_utils/Cargo.toml, oak_functions_utils/src/sync.rs
This PR provides an implementation of a synchronised OnceCell. We want this so that we can move away from using `lazy_static!` and have better control over the initialisation of static variables throughout.
See #3403 for more information.
The `oak_functions_utils` crate also contains a spinlock implementation, but this OnceCell implementation uses the spinlock from the `spinning_top` crate. We rely on the `spinning_top` crate for some other dependencies (such as the linked-list allocator), and having two equivalent but different spinlock implementations is not needed. I will remove our spinlock implementation and rename the crate in a follow-up PR.
=> Implement a synchronized no_std OnceCell

stage0/layout.ld, stage0/src/asm/boot.s, stage0/src/sev.rs
Thus far we've relied on three levels of page tables (PML4, PDPT, PD) leaving the leaf covering [0, 2MiB) in the PD to be a 2M hugepage.
However, we want to designate one 4K page in there as the GHCB for early logging under SEV-SNP, which requires us to change flags for just that 4K page, and not the whole 2M page.
Therefore, let's break the 2M page into 512 4K pages, and introduce a fourth-level page table (PT) for that memory area.
Instead of copy-pasting something in the linker script 512 times, I've written a small loop in assembly to set up the page table.
As we can't rely on hard-coded entries, setting the encrypted bit is both simpler and more complicated: I thought it'd be easiest just to blanket set the encrypted bit in all 512 entries of all four page tables, even if the entries …
=> Add a 4K page table for the lowest 2M of memory in stage0

Cargo.lock, oak_core/src/sync.rs, oak_functions_freestanding_bin/Cargo.lock, oak_restricted_kernel/Cargo.toml, oak_restricted_kernel/src/lib.rs, oak_restricted_kernel/src/snp.rs, oak_tensorflow_freestanding_bin/Cargo.lock, testing/oak_echo_bin/Cargo.lock, testing/oak_echo_raw_bin/Cargo.lock
When SEV-SNP is enabled the Stage 0 firmware provides the addresses of the SNP-specific pages (CPUID and secrets pages) as part of the boot parameters.
This PR reads the locations of the pages from the boot paramters and initialises static instances. Using the information from these pages will be done in follow-up PRs.
=> Initialize the SNP CPUID and secrets pages

stage0/layout.ld, stage0/src/main.rs, stage0/src/sev.rs
We need a GHCB page to use the IOIO protocol under SEV-ES/SNP for two reasons:
- We want to do some early logging, which means we need to access the serial port.
- We need to set up the E820 tables, for which we need to use the QEMU `fw_cfg` interface, which again implies using IO ports.
Both of these will be tackled separately in future PRs; this just sets up a GHCB page for us to use in the future.
In particular, we'd like the comms to be initialized as early as possible. Earlier than the point we run `PVALIDATE` on physical memory; partly because we need to query `fw_cfg` to figure out what the physical memory is at all. Thus, we ask the GHCB location to be pre-validated in the SEV metadata blob.
=> Set up an early GHCB page in stage0.

third_party/tflite-micro/tensorflow/lite/core/api/error_reporter.h, third_party/tflite-micro/tensorflow/lite/core/api/error_reporter_macro.h, third_party/tflite-micro/tensorflow/lite/core/api/flatbuffer_conversions.cc, third_party/tflite-micro/tensorflow/lite/core/api/op_resolver.cc, third_party/tflite-micro/tensorflow/lite/kernels/internal/common.h, third_party/tflite-micro/tensorflow/lite/kernels/internal/reduce_common.h, third_party/tflite-micro/tensorflow/lite/kernels/internal/reference/strided_slice.h, third_party/tflite-micro/tensorflow/lite/micro/all_ops_resolver.cc, third_party/tflite-micro/tensorflow/lite/micro/kernels/cast.cc, third_party/tflite-micro/tensorflow/lite/micro/kernels/reduce.cc, third_party/tflite-micro/tensorflow/lite/micro/kernels/reduce.h, third_party/tflite-micro/tensorflow/lite/micro/kernels/reduce_common.cc, third_party/tflite-micro/tensorflow/lite/micro/kernels/softmax_common.cc, third_party/tflite-micro/tensorflow/lite/micro/micro_mutable_op_resolver.h
REDUCE_ANY OP is still pending for review at TFLM github ([PR](https://github.com/tensorflow/tflite-micro/pull/1538)).
TFLM reviewers don't have time reviewing it until next week.
To support demo which requires the op, update Oak TFLM source tree first.
The OP has passed [tests](https://github.com/tensorflow/tflite-micro/blob/977c3f19786026912cd9df95f9f52b01e1c509a0/tensorflow/lite/micro/kernels/reduce_test.cc#L449-L481) that are ported from tensorflow lite.
=> Update TFLM to support REDUCE_ANY OP

cc/tflite_micro/include/tflite_micro.h, cc/tflite_micro/tflite_micro.cc, testing/tflite_micro/hello_world/main.cc
Generic model runner is extended to support multiple input/output tensors that demo model requires.
Demo model has: 1 input tensor and 3 output tensors.
input tensor[0]: int * 10
output tensor[0]: float * 3
output tensor[1]: float * 105
output tensor[2]: float * 4522
As we only accept one single input buffer and one single output buffer,
input buffer will be split properly into input tensors per tensor size and
output tensors will be consolidated and cancatenated to output buffer in order.
Next step: I'll create a testing freestanding binary for demo model to validate flowing data through all layers w/o crashes.
I'll be off for rest of the week but could still check and work intermittently.
=> Support multi tensors in generic model runner

Cargo.lock, Cargo.toml, oak_remote_attestation_noninteractive/Cargo.toml, oak_remote_attestation_noninteractive/build.rs, oak_remote_attestation_noninteractive/src/client.rs, oak_remote_attestation_noninteractive/src/lib.rs
For noninteractive remote attestation.
Will be used in the future in Oak Functions and Oak Tensorflow support the noninteractive protocol.
Ref #3442
=> Implement Rust remote attestation client

oak_core/Cargo.toml, oak_core/src/lib.rs, stage0/Cargo.lock, stage0/Cargo.toml, stage0/build.rs, stage0/layout.ld, stage0/src/logging.rs, stage0/src/main.rs, stage0/src/sev.rs
This sets up a PortFactory that we can use to get access to the raw I/O ports in the system, which we will need for communicating via the serial port and in the future to use the QEMU fw_cfg API.
As the first step, this PR exercises the PortFactory functionality to enable basic logging in stage0.
However, unfortunately formatting is really expensive for the stack. I blew the 16K stack with hilarious results as usual; bumping it to 32K gives it enough headroom. Unfortunately this means the BIOS image won't fit in 64K any longer, and I had to bump the size to 128K.
In the future we should move the stack to the low 1M of memory as well, as it doesn't really need to be in the BIOS image area.
=> Add PortFactory and a serial log to stage0

oak_restricted_kernel/src/lib.rs
This is needed to support the remote attestation requests.
We must be able to create pages in the shared heap for the remote attestation requests and also be able to translate the virtual addresses to physical addresses when notifying the hypervisor of their location.
This PR also uses the synchronised OnceCell for the guest-host heap to avoid the spread of unsafe blocks everywhere it is used.
Using these as part of a remote attestation request will be done in a future PR.
=> Make the guest-host heap and mapper public

Cargo.lock, experimental/sev_guest/src/ghcb.rs, experimental/sev_guest/src/io.rs, linux_boot_params/Cargo.toml, linux_boot_params/src/lib.rs, oak_functions_freestanding_bin/Cargo.lock, oak_restricted_kernel/src/mm/mod.rs, oak_tensorflow_freestanding_bin/Cargo.lock, stage0/Cargo.lock, stage0/Cargo.toml, stage0/src/fw_cfg.rs, stage0/src/main.rs, stage0/src/sev.rs, stage0/src/zero_page.rs, testing/oak_echo_bin/Cargo.lock, testing/oak_echo_raw_bin/Cargo.lock, testing/sev_snp_hello_world_kernel/Cargo.lock
For now, neither of the VMMs we use exposes the QEMU `fw_cfg` device, but longer term we do want to switch to using it (which will mean that we'll got from crosvm back to QEMU).
Thus, the only thing this PR really does is just debug log the E820 entries. We likely need to do some post-processing here as well, because (a) the entries are not sorted and (b) I believe SeaBIOS does something extra in its code, like marking ACPI memory ranges as reserved, which we should duplicate as well.
As an example, here's the output when I run stage0 with `qemu` and give it 32 MB of memory:
```
stage0 INFO: starting...
stage0 DEBUG: early E820 entry: start 0x00000000feffc000, len 16384, type RESERVED
stage0 DEBUG: early E820 entry: start 0x0000000000000000, len 33554432, type RAM
```
and here's what it …
=> Use the QEMU fw_cfg device to read the memory layout in stage0.

stage0/src/zero_page.rs
Looking over the SeaBIOS code we might just get lucky by not having to mark any other additional memory ranges as reserved (what SeaBIOS does is that it marks the memory ranges it itself uses as RESERVED, but we don't need stage0 to stick around after we've jumped to the kernel.)
However, all BIOSes I've seen thus far sort the E820 map before handing it over to the kernel. So let's do the same.
Ideally, we'd have a proper interval map implementation in there that'd let us detect overlaps etc, but this will do for now.
=> Sort E820 entries by address in stage0.

experimental/offline_attestation/README.md, experimental/offline_attestation/client/src/main.rs, experimental/offline_attestation/server/src/main.rs, experimental/offline_attestation/shared/src/lib.rs
The public key provided by the client was not covered by any cryptographic authentication, which meant that someone in the middle could replace it with a different pulbic key and intercept the response.
This change binds the public key to the encrypted payload as context info, which means that the payload cannot be decrypted if the public key is modified.
=> Fix public key malleability in offline attestation

java/src/main/java/com/google/oak/functions/client/AttestationClientNoninteractive.java, java/src/main/java/com/google/oak/functions/client/BUILD, java/src/main/java/com/google/oak/functions/weather_lookup_client/BUILD, java/src/main/java/com/google/oak/functions/weather_lookup_client/Main.java
Now it does not depend on the gRPC method definition, only on an abstraction over it that works with any streaming method with the appropriate request and response types.
Ref #3442
=> Generalize Java attestation client

scripts/docker_run
We don't need docker-in-docker any more, and it is causing issues with Kokoro.
=> Remove Docker socket mount

oak_functions_freestanding/proto/oak_functions.proto, oak_functions_freestanding/src/lib.rs, oak_functions_freestanding/tests/integration_test.rs, oak_functions_freestanding_bin/src/main.rs, oak_functions_launcher/README.md, oak_functions_launcher/src/instance/crosvm.rs, oak_functions_launcher/src/instance/mod.rs, oak_functions_launcher/src/instance/native.rs, oak_functions_launcher/src/main.rs, oak_functions_launcher/src/server.rs, oak_functions_linux_fd_bin/src/main.rs, oak_functions_linux_vsock_bin/src/main.rs, oak_functions_test_utils/src/lib.rs, oak_tensorflow_freestanding_bin/src/main.rs, oak_tensorflow_service/proto/oak_tensorflow.proto, oak_tensorflow_service/src/lib.rs, testing/oak_echo_bin/src/main.rs, testing/oak_echo_service/build.rs, testing/oak_echo_service/proto/oak_echo.proto, testing/oak_echo_service/src/lib.rs, testing/oak_echo_service/tests/integration_test.rs, xtask/src/examples.rs, xtask/src/launcher.rs
In particular enclave, service, server and corresponding definitions.
Also request and response messages.
=> Use consistent naming

Cargo.lock, cc/tflite_micro/tflite_micro.cc, oak_tensorflow_freestanding_bin/Cargo.lock, oak_tensorflow_service/Cargo.toml, oak_tensorflow_service/build.rs, third_party/tflite-micro/tensorflow/lite/micro/micro_log.cc
This PR makes `oak_tensorflow_service` rebuild the `tflite_micro` if third-party dependencies have been updated
=> Rebuild Oak TensorFlow if third-party has been updated

.github/actions/reproducibility_index/action.yml, .github/workflows/provenance.yaml, .github/workflows/reusable_provenance.yaml, scripts/build_reproducibility_index
Ref #3428.
Prerequisite for #3473.
Refactors the provenances workflow, moving most of the steps to a reusable workflow, to make parameterization with a matrix easier.
Some steps only run on push... this might still fail after merge.
=> Refactor the provenance workflow to make parameterization easier

oak_sev_guest/src/lib.rs, oak_sev_guest/src/vmsa.rs
The VM State Save Area (VMSA) is needed for two future features:
- Calculating the expected measurement in an SEV-SNP attestation report: the intial VMSA for each vCPU is included in the measurement
- Creating and booting new vCPUs
=> Add implementation of SEV-ES State Save Area

Cargo.lock, Cargo.toml, snp_measurement/Cargo.toml, snp_measurement/src/main.rs, snp_measurement/src/page.rs, snp_measurement/src/stage0.rs
This is the first step towards calculating the expected measurement in the attestation report from the Stage 0 firmware image and the enclave binary.
See #3486 for more details.
=> Add initial attestation measurement calculation

Cargo.lock, oak_sev_guest/src/vmsa.rs, snp_measurement/Cargo.toml, snp_measurement/src/main.rs, snp_measurement/src/page.rs, snp_measurement/src/vmsa.rs
The initial state of the VM state save area for the boot vCPU must be included in the attestation measurement calculation.
See #3486 for more details.
=> Include VMSA page in the attestation measurement

stage0/Cargo.lock, stage0/Cargo.toml, stage0/layout.ld, stage0/src/acpi.rs, stage0/src/fw_cfg.rs, stage0/src/main.rs
This is a fairly straightforward and, at times, naive implementation of the ACPI table builder. I spent some time trying to do it "properly" by implementing my own dedicated heap allocator, but it was too much of a hassle.
In the future, to clean this up, we should use the standard allocator from `alloc` and the bog-standard Rust `Box` etc data types, even if this means we need to instantiate a global heap allocator to placate the Rust runtime.
All of the `fw_cfg` related code should also be moved to a separate crate, so that we can do proper testing.
=> stage0: create ACPI tables based on instructions from fw_cfg

snp_measurement/src/main.rs, snp_measurement/src/page.rs, snp_measurement/src/stage0.rs
The metadata of the SEV-SNP-related pages (secret, CPUID and unmeasured pages) must also be included in the attestation measurement.
The addresses and types of these pages are included in the the Stage 0 firmware image as metadata tables in the same way as is done in [OVMF](https://github.com/tianocore/edk2/tree/master/OvmfPkg), so we parse these values from the firmware image to be able to include them in the calculation.
See #3486 for more details.
=> Include SEV-SNP pages in attestation measurement

Cargo.lock, oak_functions_freestanding_bin/Cargo.lock, oak_restricted_kernel/Cargo.toml, oak_restricted_kernel/src/acpi.rs, oak_restricted_kernel/src/lib.rs, oak_tensorflow_freestanding_bin/Cargo.lock, testing/oak_echo_bin/Cargo.lock, testing/oak_echo_raw_bin/Cargo.lock
We don't do anything useful with these tables (yet), but at least we can (mostly) parse them!
For some reason some fields in the ACPI tables are not marked as public in the `aml` crate; in particular, we can't peek into `IoPortDescriptor` or `AddressSpaceDescriptor` structs. I'll need to find out what's going on there, if this is on principle, ongoing work or just an oversight.
Some examples:
- running on crosvm:
```
INFO: ACPI device: \_SB_.PC00 PNP0A08 PCI Express bus
INFO:   Address space: AddressSpaceDescriptor { resource_type: BusNumberRange, is_maximum_address_fixed: true, is_minimum_address_fixed: true, decode_type: Additive, granularity: 0, address_range: (0, 63), translation_offset: 0, length: 64 }
INFO:   IO port: IOPortDescriptor { decodes_full_address: true, memory_range: …
```
=> Parse ACPI tables, if present, in Restricted Kernel

snp_measurement/src/vmsa.rs
This is to match the expected state when running with AMD SEV-SNP in production.
=> Update the initial VMSA state for measurements

oak_restricted_kernel/src/interrupts.rs
This is related to the panic @ipetr0v got: unfortunately, when we get a double fault, there is no way to know which exception actually happened.
This PR adds a bunch of placeholder interrupt handlers that hopefully log _which_ exception occurred.
=> Add a bunch of placeholder interrupt handlers

.github/workflows/ci.yaml, .github/workflows/cifuzz.yml, fuzz/Cargo.lock, fuzz/Cargo.toml, fuzz/fuzz_targets/failing.rs
- Adds a temporary failing fuzz target, to generate data.
- Tweaks fuzz-related CI steps to avoid CI failures.
=> Add a failing fuzz target

fuzz/Cargo.lock, fuzz/Cargo.toml, fuzz/fuzz_targets/failing.rs
Follow up on #3502 which was merged without rebasing after #3504 was merged.
=> Remove the dependency to oak_remote_attestation to avoid cargo-deny errors

.github/workflows/reusable_provenance.yaml
This should fix the issue with incorrect (repeated) provenance digests reported for #3509.
=> Fix path for accessing outputs in the provenance workflow

oak_restricted_kernel/src/acpi.rs, oak_restricted_kernel/src/lib.rs
We'll soon need to search the ACPI device tree for the virtio device: this sets up the infrastructure so that we can do that.
=> Refactor ACPI code to include a simple `AcpiDevice` wrapper

stage0/.cargo/config.toml
There was a race between the following commits:
- dd3be6ab3e9c47844869ff5807aca0ee1d8c360a
- c7207686ecda0c6474714a34ea1d8c4c2e2766c8
Which introduced a bug that causes Kokoro to fail.
=> Build std for stage0

micro_rpc_build/src/lib.rs, micro_rpc_tests/out/micro_rpc.tests.rs.txt, micro_rpc_tests/tests/test_schema.rs, oak_functions_freestanding/tests/integration_test.rs, oak_functions_freestanding_bin/src/main.rs, oak_functions_linux_fd_bin/src/main.rs, oak_functions_linux_vsock_bin/src/main.rs, oak_tensorflow_freestanding_bin/src/main.rs, testing/oak_echo_bin/src/main.rs, testing/oak_echo_service/tests/integration_test.rs
The previous method was added to the list of methods on the trait, but that risks conflicting with a real method with the same name.
=> Move server creation method

Cargo.lock, micro_rpc_build/src/lib.rs, micro_rpc_tests/Cargo.toml, micro_rpc_tests/out/micro_rpc.tests.rs.txt, micro_rpc_tests/proto/test_schema.proto, micro_rpc_tests/tests/test_schema.rs
Previously the generator was producing incorrect code because the `()` type was not correctly delimited.
=> Support well known Empty type in micro RPC

.github/dependabot.yml
Now that we don't have auto assignment enabled any more on the repo.
=> Assign team to dependabot updates

linux_boot_params/src/lib.rs, stage0/src/cmos.rs, stage0/src/fw_cfg.rs, stage0/src/main.rs, stage0/src/zero_page.rs
Sometimes the E820 table is not available in the `fw_cfg` interface, and we have to resort to more arcane methods of determining what memory is available to us.
This code is largely inspired by what SeaBIOS is doing under QEMU in the exact same scenario.
=> Use CMOS to populate E820 table if one is not available from QEMU

stage0/layout.ld
As we're no longer relying on the VMM to provide us with a zero page, we need to ensure that the memory location is validated when we run under SEV-SNP before we write to it.
However, we're in a bit of a chicken and egg scenario here: we need the zero page to know where the physical memory is in order to validate all of the memory, and we need the memory for the zero page to be valid before we write to it.
Thus, add the zero page location to the SEV metadata as an unmeasured page, which means the VMM will do the state change for us before we boot.
=> Mark the location where we'll write the zero page as unmeasured

snp_measurement/src/main.rs
The firmware will not always be shadowed to support legacy boot, so this change makes it configurable via the command-line.
=> Make legacy boot firmware shadow optional

oak_restricted_kernel/src/acpi.rs
We don't fully support the ACPI tables that we get internally yet, but... we also don't need them (yet) to function properly.
Thus, let's stub out the calls and log that "something is happening", even if the tables that we do get are broken because of that.
We only need ACPI tables to locate the virtio-console device that we use with QEMU and Kokoro. Thus, the fact that ACPI parsing is broken (for now) when we run it internally with simple-sev-io, is not a problem.
=> ACPI: log accesses to ports and PCI, but return 0 instead of crashing

linux_boot_params/src/lib.rs, stage0/Cargo.lock, stage0/Cargo.toml, stage0/layout.ld, stage0/src/main.rs
Thus far, we've had a lot of tricky code to ensure that the boot data structures end up at well-known addresses (where the addresses were mostly derived from crosvm).
Truth is, it doesn't really matter where in memory those data structures are and we were just making things much more difficult for us.
By using a simple bump allocator -- as we're never going to deallocate anything anyway -- we can make the code much more simpler, more understandable, and safe.
=> Use an allocator for boot data structures in stage0

stage0/src/acpi.rs, stage0/src/fw_cfg.rs, stage0/src/main.rs
Some low-level changes for the future Linux kernel compatibility:
- set the ACPI RSDP location in the zero page structures. The Linux kernel won't search EBDA for RSDP, it expects the value in the zero page to point to the correct location.
- if there's a kernel command line available in fw_cfg, load that into memory and pass it to the kernel as well.
=> Set ACPI RSDP location and kernel command line in zero_page

stage0/layout.ld, stage0/src/main.rs
We don't actually care where _exactly_ in the memory the CPUID/secrets pages land, thus we don't really need the special sections for them.
However, we _do_ need to know where they land statically (as the locations need to be in the GUIDed tables), so we can't allocate them dynamically as in #3557.
Even with that restriction in mind I think this way of doing things is still a bit cleaner.
=> Remove special sections for SEV pages

sev_serial/Cargo.toml, stage0/Cargo.lock, stage0/Cargo.toml, testing/sev_snp_hello_world_kernel/Cargo.lock
First, it causes debug builds to fail.
Second, it relies on SSE/AVX which is not enabled in stage0.
Third, we don't use it and don't need it in stage0.
Fourth, it unnecessarily bloats the size of the stage0 binary.
=> Don't include crypto stuff in stage0

stage0/layout.ld, stage0/src/main.rs, stage0/src/sev.rs
This is the last data structure which has a magic location pre-allocated in the linker script: the GHCB, or guest-host communcation block, that's used under SEV-ES and SEV-SNP to communicate with the hypervisor.
While I do think this code is _a bit_ cleaner than previously, it's still a mess and not particularly Rust-y. This is the minimum I was able to do without starting heavy refactoring of our existing GHCB APIs, so better take the easy win here and come back later for more clean-ups.
=> Remove the fixed location for GHCB in stage0

stage0/src/sev.rs
One of the most important things we have to do in stage0 when running under SEV-SNP is to run `PVALIDATE` on all of the physical memory to ensure it's marked as guest-private.
Right now we just blindly iterate over all the memory using 4 KiB pages. However, this means that if the host side was using 2 MiB pages, the host needs to create a 4 KiB page table on the host side as well -- incurring a significant overhead, especially if we give a large amount of memory to the guest (consider 8 GiB of memory: using 2 MiB pages, it takes 8 page tables, or 32 KiB, to cover the whole range; with 4 KiB pages, it takes 4096 page tables, or 16 MiB).
Thus, let's first try `PVALIDATE` using 2 MiB pages in hopes that it aligns with what the host is using. If we get `FailSizeMismatch`, which means that the …
=> Try validating memory with 2 MiB pages

stage0/layout.ld, stage0/src/main.rs
For context, `.bss` is the section in the compiled binary where zero-initialized static variables are placed. The memory gets zeroed out in `boot.s` , just before we jump to Rust. (For static variables that _have_ an initial value, they end up in `.data`.)
Shuffling these around has the following benefits:
- Moving BSS to low memory means that the BIOS image can be smaller.
- Increased compatibility as we won't try to write to BIOS memory region (as that sometimes is indeed read-only)
- Moving the `BOOT_ALLOC` to the BSS allows us to simplify the code and get rid of one `unsafe` block.
=> Move BSS to low memory and put the allocator in there

Cargo.lock, oak_functions_enclave/Cargo.lock, oak_functions_enclave/Cargo.toml, oak_functions_enclave/src/main.rs, oak_restricted_kernel/Cargo.toml, oak_restricted_kernel/src/lib.rs, oak_tensorflow_enclave/Cargo.lock, oak_tensorflow_enclave/Cargo.toml, oak_tensorflow_enclave/src/main.rs, testing/oak_echo_enclave/Cargo.lock, testing/oak_echo_enclave/Cargo.toml, testing/oak_echo_enclave/src/main.rs, testing/oak_echo_raw_enclave/Cargo.lock, testing/oak_echo_raw_enclave/Cargo.toml, testing/oak_echo_raw_enclave/src/main.rs
The actual implementation if the channel (virtio-vsock, virtio-console, serial, simpleio) is now hidden in the kernel. The payload code should just use the newly-introduced syscall interface to communicate with the kernel.
Thus, we can move the actual channel instantiation to the payload crates and out of the kernel. I think we might be able to do some more clean-up here (like replacing the Box<dyn Channel> with a generic argument and getting rid of the box altogether), but that can wait for a future PR.
=> Instantiate a channel in the payload, not the kernel

oak_restricted_kernel/src/lib.rs
The frame allocator needs to be in a separate static as we'll need out-of-band access from the `mmap()` system call in the future.
Also, it makes sense to have one global static for the physical memory allocator: after all, memory in the machine is inherently a global resource, therefore it makes sense to have a global object to track what's been allocated as well.
=> Move the frame allocator into a separate global static

oak_restricted_kernel/src/syscall/channel.rs, oak_restricted_kernel/src/syscall/fd.rs, oak_restricted_kernel/src/syscall/mod.rs, oak_restricted_kernel/src/syscall/stdio.rs, oak_restricted_kernel_interface/src/syscalls.rs
Here we shuffle the code around a little bit (extracting the generic file descriptor code to a separate file), make it possible to have multiple file descriptors and register a handler for FD 2 (stdout) that just dumps data to the serial port.
The goal is that anything our future user space code writes to stdout (logging) would end up with the kernel logs.
Longer-term, as we've discussed previously, we probably want to treat the logs coming from user space differently than the kernel logs as they can potentially contain data we shouldn't leak. But for now, let's just proxy everything.
=> Allow for multiple file descriptors in read/write/sync

oak_restricted_kernel/src/acpi.rs, oak_restricted_kernel/src/attestation.rs, oak_restricted_kernel/src/lib.rs, oak_restricted_kernel/src/memory.rs, oak_restricted_kernel/src/simpleio.rs, oak_restricted_kernel/src/virtio.rs, oak_restricted_kernel/src/virtio_console.rs
Right now we pretty much dump all of the physical memory into the kernel heap and call it a day.
Obviously this won't do in the future: we expect the vast majority of memory to be used by the user space, not the kernel.
Here we create a wrapper around some existing heap allocator (so that we could replace the `linked_list_allocator` with something more clever in the future) that uses at minimum 2 MiB of memory (one page), and asks for more physical memory only if necessary.
The address chosen for the heap -- `0xFFFF_C900_0000_0000` -- is arbitrarly chosen to be the same as the Linux vmalloc area (as I understand it, Linux kmalloc() will return memory from the directly mapped region, and vmalloc() will return memory from the vmalloc area, setting up page tables as necessary -- thus, it …
=> Allocate only the necessary memory to the kernel heap

oak_restricted_kernel/src/syscall/mod.rs, oak_restricted_kernel/src/syscall/process.rs, oak_restricted_kernel_api/src/syscall.rs, oak_restricted_kernel_interface/src/syscalls.rs
We need a way how the user space code can notify the kernel of a potentially abnormal termination: for example, when the code panics in an unrecoverable way.
As we'll eventually move into the process management business anyway, the most obvious way how to do it would be via an `exit` syscall that lets you report a termination status to the kernel.
However, as we _don't_ have proper process management yet, we don't expect the user code ever to call this unless something has gone horribly wrong -- therefore, we can just cause a kernel panic if the user code terminates.
=> Add an `exit` syscall to cause a crash.

deny.toml
I tried looking at the dependency mess, but at this point I'd rather stick pins under my fingernails than deal with that mess.
The root cause of some ancient deps seems to be `ed25519_dalek`, which hasn't been updated in years.
=> Ignore security advisories due to ancient libraries

deny.toml
Let's try this again and hope the checks actually run this time around.
=> Ignore twoway deprecation notice

oak_restricted_kernel/src/syscall/mmap.rs, oak_restricted_kernel_api/src/syscall.rs, oak_tensorflow_service/src/tflite.rs
Instead of passing around raw pointers like it's the 70s and we only have C to work with, let's use slices and proper address types.
=> Change the Rust interfaces of `mmap` to be a bit more Rust-y.

oak_restricted_kernel/src/mm/encrypted_mapper.rs, oak_restricted_kernel/src/syscall/mmap.rs, oak_restricted_kernel_interface/src/syscalls.rs
The main use case for this will be setting up the user space, where we will want mappings to land on certain fixed addresses and not just the next available one.
=> Add support for `MAP_FIXED` to `mmap` syscall

.devcontainer.json, Cargo.lock, Dockerfile, deny.toml, docs/development.md, oak_functions/examples/weather_lookup/example.toml, oak_functions/examples/weather_lookup/module/Cargo.toml, oak_functions/examples/weather_lookup/module/src/lib.rs, oak_functions/examples/weather_lookup/module/src/tests.rs, scripts/common, xtask/src/examples.rs
Wizer depends on an old version of wasmtime, which has some vulnerabilities.
Fixes #3604
=> Remove Wasm warmup with Wizer

oak_restricted_kernel/src/lib.rs, oak_restricted_kernel/src/memory.rs, oak_restricted_kernel/src/mm/mod.rs, oak_restricted_kernel/src/mm/virtual_address_allocator.rs
Instead of allocating all of `[0xFFFF_C900_0000_0000...0xFFFF_E900_0000_0000)` for the kernel heap, let's use this range of virtual memory for other long-lived data structures that need a place in the virtual memory, as well. After all, we don't really expect the kernel heap to ever grow particularly large.
The motivating example is that we're going to need a separate stack for syscalls. We could just allocate a frame, and use the directly-mapped region for the stack; however, this runs the risk that if we ever blow the stack, we start writing to memory that's not ours.
With this allocator, the algorithm can be: ask for two pages of virtual memory and one frame of physical memory; leave the first page unmapped as a guard page, and map the second page to the physical frame; use that …
=> Create an allocator for a pool of virtual memory

oak_restricted_kernel/src/mm/mod.rs, oak_restricted_kernel/src/syscall/mod.rs
This does go into a fairly obscure corner of x86-64 architecture, namely the `GS` segment and `SWAPGS`.
For detailed information read the architecture manuals, but the gist is that the GS is the only reference to memory one can switch without any side effects -- namely, with the `swapgs` instruction.
Thus, in order to switch from the userspace stack to the kernel stack, we make the kernel GS point to a static data structure (`GsData`) that points to where the kernel stack is, and when a syscall is invoked we save the old `RSP` value in there and replace it with the kernel one. After the syscall we do the inverse: first restore the user `RSP`, and then swap the `GS` values again to go back to whatever it was in the user space.
Yes, it means that you shouldn't call `SYSCALL` from within a …
=> Create a separate kernel stack for syscalls

oak_restricted_kernel/src/descriptors.rs, oak_restricted_kernel/src/interrupts.rs, oak_restricted_kernel/src/lib.rs
This should be the last bit that's needed before we can try entering Ring 3 properly.
We allocate two stacks here:
a) one that is used when an interrupt triggers change from Ring 3 to Ring 0 (referenced by `tss.privilege_stack_table`)
b) one that is used if things go horribly wrong and we get a double fault (referenced by `tss.interrupt_stack_table` and `opts.set_stack_index`)
The idea behind giving the double fault handler its own stack is that if we do ever get a double fault, things must have gone spectacularly bad and we can't trust any other stack to be in a reasonable state. It's a best practice followed by many kernels.
While in there, I also simplified the code drastically by getting rid of a bunch of OnceCells and replacing them with bog-standard Spinlocks.
=> Create a separate stack for interrupts and double faults.

kokoro/presubmit.sh
a) we don't need vsock right now;
b) the launcher is built as a part of `run-launcher-test` anyway, so there's no need to build it separately.
=> Clean up the Kokoro presubmit a bit.

buildconfigs/oak_echo_enclave.toml, buildconfigs/oak_echo_raw_enclave.toml, buildconfigs/oak_tensorflow_enclave.toml, oak_enclave_runtime_support/src/libm.rs, oak_tensorflow_enclave/.cargo/config.toml, oak_tensorflow_enclave/Cargo.lock, oak_tensorflow_enclave/Cargo.toml, oak_tensorflow_enclave/build.rs, oak_tensorflow_enclave/src/main.rs, testing/oak_echo_enclave/.cargo/config.toml, testing/oak_echo_enclave/Cargo.lock, testing/oak_echo_enclave/Cargo.toml, testing/oak_echo_enclave/build.rs, testing/oak_echo_enclave/src/main.rs, testing/oak_echo_raw_enclave/.cargo/config.toml, testing/oak_echo_raw_enclave/Cargo.lock, testing/oak_echo_raw_enclave/Cargo.toml, testing/oak_echo_raw_enclave/build.rs, testing/oak_echo_raw_enclave/src/main.rs
Now that we have Ring 3 and have applications as separate binaries, it's time to bring everyone else along for the ride as well.
I still need to fix Google-internal systems to work with these, though, so unfortunately for a short while you won't be able to just copy them into Google and run them on SEV-SNP.
=> Change all other enclave binaries to be standalone as well.

stage0/Cargo.lock, stage0/Cargo.toml, stage0/src/fw_cfg.rs, stage0/src/initramfs.rs
This allows us to load the initial RAM disk via DMA rather than 1 byte at a time.
Fixes #3631
=> Add DMA support to the QEMU FW_CFG device

oak_restricted_kernel_api/src/syscall.rs
For whatever reason, when we execute this on Github Actions (which presumably are linux), we'll still be able to read even though there's nobody writing to the socket.
=> Remove the flaky `test_erroneous_read` test.

oak_enclave_shim/src/main.rs, oak_functions_launcher/src/instance/virtualized.rs, oak_functions_launcher/src/main.rs, oak_restricted_kernel/layout.ld, oak_restricted_kernel/src/lib.rs, oak_restricted_kernel/src/payload.rs, xtask/src/launcher.rs
As we've discussed before, we want to load the application (e.g. Oak Functions itself) separately from the rest of the kernel. In order to achieve this, we hijack the communication channel before we hand it to user code, and transmit the ELF file to the kernel using a really trivial chunked protocol.
(We need the chunks, as sending 20 MB file into the enclave in 4K chunks takes <5 seconds, whereas just dumping the whole 20MB file into the channel at one takes several minutes).
I will admit that this is a bit hacky. In the future, we want to be able to talk to multiple processes inside the VM, so we'll need some kind of multiplexing over the channel. The multiplexing will be useful for other things as well, as we do want to have some kind of "control channel" in the future: say, to get …
=> Load the application binary separately

stage0/src/fw_cfg.rs, stage0/src/initramfs.rs, stage0/src/main.rs
Checks whether the suggested initial RAM disk address is suitable, and if not tries to find a more suitable one.
Fixes #3628
=> Ensure the initial RAM disk address is suitable

oak_functions_launcher/src/instance/virtualized.rs, oak_restricted_kernel/src/payload.rs
Little-endian is the native byte order for x86-64, and this is also the one used by our regular communication protocol.
I don't know why I blanked out and used big-endian format here at all; this should always have been little-endian.
=> Write bytes in LE order, not BE order when loading the application.

oak_hello_world_linux_init/README.md
It turns out that we don't need to use the loader device when passing an uncompressed ELF binary as the kernel to QEMU. It already lays it out into the guest memory.
I also reordered the parameters a bit an suppressed most of the kernel logging by passing `quiet` in the kernel command line.
=> Update example command for booting Linux on QEMU

stage0/src/fw_cfg.rs, stage0/src/main.rs, stage0/src/sev.rs
The memory-encryption part is currently untested as we cannot run Linux workloads with initial RAM disks on AMD SEV-SNP yet using the stage 0 firmware.
Fixes #3636
=> Enlighten fw_cfg to support AMD SEV-SNP

oak_enclave_runtime_support/src/heap.rs, oak_restricted_kernel/src/payload.rs, oak_tensorflow_service/src/tflite.rs
This fixes a couple of things I ran into while getting things up and running on our internal VMM:
- When increasing the application heap size I didn't take the number of pages into account correctly when moving the cursor forward.
- Just to be on the safe side, if we're asked to load data to an address that's not aligned with 2 MiB pages and need to align the address down, take the extra padding we need to have into account when allocating memory.
- Keep interrupts disabled when we jump to Ring 3, as we don't handle them properly yet. Case in point, I think we need to disable the PIC (external interrupt controller) that QEMU microvm doesn't expose, but I think our internal VMM has.
- For Tensorflow, make sure that the heap can grow a reasonable bit before we hit the chunk of memory we …
=> Some minor fixes to mmap and interrupt handling

stage0/src/sev.rs
After changing the page state in the RMP to guest-private we need to PVALIDATE it again to make it usable. The current pages we are unsharing don't really matter, since they fall in a range that will not be used by the kernel, but in future this function might be used on pages that will be reused.
=> PVALIDATE page when unsharing

oak_functions/lookup/src/lib.rs, oak_functions_client/src/main.rs
The large test key we sent in was not really 2MiB, but only 2050 bytes.
Logging such a large key is very slow, so I also updated the debug logging code for the key to match the way the value is logged: only log the first 512 bytes.
=> Really send a 2MiB test message

Cargo.lock, oak_functions_launcher/Cargo.toml, oak_functions_launcher/src/instance/native.rs, oak_functions_launcher/src/instance/virtualized.rs, oak_functions_launcher/src/lib.rs, oak_functions_launcher/src/main.rs, oak_functions_launcher/src/server.rs, oak_functions_launcher/tests/integration_test.rs, oak_functions_test_utils/src/lib.rs
- Refactor to allow integration tests
- Add integration test with single lookup.
- Add integration test with lookup in 2 GiB of lookup data.
Fixes #3660.
=> Add test with >2 GiB of Lookup Data

.devcontainer.json, Dockerfile, WORKSPACE, scripts/common, third_party/newlib/BUILD, third_party/newlib/newlib-4.3.0/config.sub
This is not a full port to Oak Restricted Kernel by any means, but it's enough to get newlib to compile for `x86_64-unknown-oak`.
What's missing beyond the fact that it compiles: essentially everything. There's no crt0, there's no syscall wrappers. This is a broken implementation, but the keyword here is that _it compiles_. Next step would be to write a small test enclave application and patch the holes in the libc as we find them.
As we also don't have a cross-compiler for our target, I've done some environment shenanigans to compile things with the regular Linux compiler. It should work, as we're following the same ABI when it comes to function calls and both are targeting x86_64. The "correct" way would be to set up cross-compilers, but that'd be a significant effort in itself that's …
=> Build newlib with bazel

scripts/common
I rebuilt the Docker image but managed to miss this file.
=> Updat `scripts/common` that was left out from #3673

Cargo.lock, oak_remote_attestation_noninteractive/Cargo.toml, oak_remote_attestation_noninteractive/proto/v1/messages.proto, oak_remote_attestation_noninteractive/proto/v1/service_streaming.proto, oak_remote_attestation_noninteractive/tests/integration_test.rs
Fixes #3656
@project-oak/core Putting this out early for discussion. 
1. What do you think about the naming?
2. Any important points that could be included in the documentation at this stage?
3. Is there any other piece of information that should be included in `PublicKeyInfo`?
=> Extend the PublicKeyInfo proto definition with additional evidence info

cc/oak_echo_raw_enclave_app/BUILD, cc/oak_echo_raw_enclave_app/main.cc, third_party/newlib/BUILD, third_party/newlib/newlib-4.3.0/libgloss/Makefile.am, third_party/newlib/newlib-4.3.0/libgloss/Makefile.in, third_party/newlib/newlib-4.3.0/libgloss/configure, third_party/newlib/newlib-4.3.0/libgloss/configure.ac, third_party/newlib/newlib-4.3.0/libgloss/oak/Makefile.inc, third_party/newlib/newlib-4.3.0/libgloss/oak/crt0.S, third_party/newlib/newlib-4.3.0/libgloss/oak/syscalls.c, third_party/newlib/newlib-4.3.0/newlib/configure.host, third_party/newlib/newlib-4.3.0/newlib/libc/include/sys/config.h, third_party/newlib/newlib-4.3.0/newlib/newlib.hin
Here we add a really trivial `oak_echo_raw` clone, and modify Newlib enough to be able to issue necessary syscalls.
Note that at this stage although it claims to be C++, it's more like C in a funny hat and a fake mustache: we don't really use the C++ standard library but rather rely on the libc primitives (`fprintf`, `read`, `write`).
=> Create a C(++)-based oak_echo_raw binary

Cargo.lock, Cargo.toml, oak_client/Cargo.toml, oak_client/build.rs, oak_client/src/lib.rs, oak_client/src/transport.rs, oak_client/src/verifier.rs
This PR adds a template for the Rust client, which will be built upon as part of the https://github.com/project-oak/oak/issues/3643
=> Add oak_client Rust template

Cargo.lock, Cargo.toml, oak_restricted_kernel/src/virtio_console.rs, oak_restricted_kernel_bin/Cargo.lock, oak_restricted_kernel_bin/Cargo.toml
This updates the virtio-drivers crate to the latest released version, which contains a number of fixes.
I had to create a patch PR (https://github.com/rcore-os/virtio-drivers/pull/62) to make the virtio-console work for us as a comms channel. Once the PR is merged and a new version release we can stop overriding the dependency (see #3706).
=> Update virtio-drivers crate

scripts/git_check_diff
Currently the output of the git diff step is not very explicative, and does not actually show the diff.
=> Clarify git diffs in error message

stage0/src/fw_cfg.rs
The first fence was not needed, since neither the compiler nor the CPU will reorder instructions that have side effect (like writing to IO ports).
The second fence was not strong enough. It has not caused any issues so far, but I believe the stronger fence is more correct.
=> Fix memory fences in fw_cfg DMA

.config/nextest.toml, .devcontainer.json, Dockerfile, scripts/common
Can be used optionally, to get a more nicely formatted output, and xunit-compatible test outputs (which will be useful for Kokoro integration later on).
Ref #2537
=> Install nextest

BUILD, WORKSPACE, cc/oak_echo_raw_enclave_app/BUILD, cc/oak_echo_raw_enclave_app/main.cc, toolchain/BUILD, toolchain/cc_toolchain_config.bzl
It should be noted that I really have no idea what I'm doing here...
What I hope I achieved is:
- using the Bazel `platforms` mechanism, introduce a new OS constraint for Oak
- create a toolchain, compatible with the aforementioned OS constraint, that compiles things with clang.
The downside is that if you just invoke `blaze build :all`, it won't compile the app. You have to explicitly say `blaze build :oak_echo_raw_enclave_app --platforms=//:oak`.
There's a ton of things to figure out how to do better here, but it seems to work.
=> Introduce a bazel OS entry and toolchain for Oak

Cargo.lock, flake.nix, kokoro/presubmit.sh, oak_functions_launcher/tests/integration_test.rs, quirk_echo_launcher/Cargo.toml, quirk_echo_launcher/src/lib.rs, quirk_echo_launcher/src/main.rs, quirk_echo_launcher/tests/integration_test.rs, xtask/src/launcher.rs, xtask/src/testing.rs
Running them via xtask is quite inconvenient, so now there is a regular Rust test, that can be customized with extra logic in the future.
Ref #2591
=> Make Quirk tests actual Rust tests

Cargo.lock, oak_functions_launcher/src/lib.rs, oak_functions_launcher/src/lookup.rs, oak_functions_launcher/src/main.rs, oak_functions_launcher/tests/integration_test.rs, oak_functions_test_utils/Cargo.toml, oak_functions_test_utils/src/lib.rs
Refactoring launcher to make it possible to test `update_lookup_data`. 
Major changes:
- make `max_chunk_size` configurable,
- make it possible to not periodically update the lookup data
- extract functionality to create test lookup data entries of a certain size
=> Refactor launcher for testing

oak_restricted_kernel/src/payload.rs
If you don't, weird things happen, like SSE instructions generating general protection faults or stack pointer arithmetic going awry and generating page faults at mysterious locations.
=> Ensure the stack is 16-byte aligned when starting the application.

third_party/newlib/newlib-4.3.0/libgloss/oak/crt0.S, third_party/newlib/newlib-4.3.0/libgloss/oak/syscalls.c
First step in merging my GCC experiments.
Unfortunately the `syscalls.c` change is rather messy, as VS Code decided it'd be a good idea to reformat the file. The key changes are the addition of `_open_r` and `getentropy`.
=> Call `_init` during C initialization + stub out more syscalls

.gitignore, toolchain/binutils-2.40-oak.patch, toolchain/build.sh
This builds the basic tools for any cross compiler, like the assembler and linker.
The newly-introduced `x86_64-unknown-oak` platform is only 64-bit, available only on `x86_64`, and uses the ELF executable format.
Ref #3759
=> Step 1 in building a cross-compiling toolchain: binutils.

.devcontainer.json, Dockerfile, scripts/common, toolchain/build.sh, toolchain/gcc-12.2.0-oak.patch
Unfortunately I also had to add two libraries to `Dockerfile` as they are needed to build GCC itself.
Although after this PR we have a compiler, it *won't* be able to produce executables yet as we're missing libc (and libgloss). Those come from newlib, which is the next step.
Ref #3759
Fixes #3762
=> Step 2: build GCC as a cross compiler for Oak

toolchain/build.sh, toolchain/newlib-4.3.0-oak.patch
The diff contains some automake/autoconf junk because newlib is _really_ particular about which version of those tools you use to generate those files, and we don't have an old enough version in our Docker image.
Ref #3759
Fixes #3765
=> Step 3: build newlib (the C library) as part of the toolchain

toolchain/build.sh
Last step in setting up the basic toolchain.
Unfortunately Github doesn't do DIFFBASE, so this also includes changes required for #3766 (newlib). Focus on just the libstdc++ bits here.
Depends on #3766
Ref #3759 
Fixes #3771
=> Build libstdc++ as part of the cross compiling toolchain

kokoro/presubmit.sh
Add the usual stanza to make bash scripts sensible. Before this change, a failure in any of the steps was silently ignored by bash.
Also combine tests for multiple packages in a single step.
Ref #3756
=> Fix Kokoro tests

Cargo.lock, oak_restricted_kernel/Cargo.toml, oak_restricted_kernel/src/lib.rs, oak_restricted_kernel/src/payload.rs, oak_restricted_kernel_bin/Cargo.lock
This is in preparation for the future: first, we want to keep the hash of the executable around for attestation purposes; second, I want to make the kernel panic more clever and see if we can use the debug data in the binary to resolve some symbols, if at all possible, to provide more information.
The key trick here is that in order to not parse the ELF file multiple times, we need a self-referential struct. Which, as we know, is hard to achieve with Rust move semantics. Thankfully, I think the (cleverly named) `ouroboros` crate provides us a safe way out here.
=> Create a separate wrapper for an application in Restricted Kernel.

oak_launcher_utils/src/launcher/virtualized.rs
Fixes #3786 .
Now, the tests seem not to be failing with out-of-memory any more, so I didn't change anything in the tests. However, if we run out of memory again, we can increase the memory now.
=> Add optional flag `memory_size` in parameters of virtualized VM

.bazelrc, WORKSPACE, cc/oak_echo_raw_enclave_app/BUILD, cc/oak_echo_raw_enclave_app/main.cc, toolchain/BUILD, toolchain/cc_toolchain_config.bzl, toolchain/wrappers/wrapper, toolchain/wrappers/x86_64-unknown-oak-ar, toolchain/wrappers/x86_64-unknown-oak-cpp, toolchain/wrappers/x86_64-unknown-oak-gcc, toolchain/wrappers/x86_64-unknown-oak-gcov, toolchain/wrappers/x86_64-unknown-oak-ld, toolchain/wrappers/x86_64-unknown-oak-nm, toolchain/wrappers/x86_64-unknown-oak-objdump, toolchain/wrappers/x86_64-unknown-oak-strip, toolchain/x86_64-unknown-oak.BUILD
I'm yet again in territory that I don't know particularly well...
This is largely cargo culted from https://ltekieli.com/cross-compiling-with-bazel/ as a base.
How to use:
```
bazel build //cc/oak_echo_raw_enclave_app --platforms=//:oak
```
...and you should get a binary palatable for Restricted Kernel.
=> Set up Bazel rules to use the precompiled toolchain

toolchain/newlib/crt0.S
Yet again stack alignment issues...
For whatever reason if:
(a) I remove the `rsp - 8` in Restricted Kernel and replace it with this alignment, the Rust applications break.
(b) if I don't force this 16-byte alignment, C++ applications break.
Things that are aligned to 16 bytes should _by definition_ be also aligned to 8 bytes, so we've got something broken with our alignments here. But this should be the minimum change to get things to work properly.
And now we get to recompile the toolchain!
=> Ensure 16-byte stack alignment in `_start`.

oak_echo_linux_init/README.md, oak_hello_world_linux_init/README.md, stage0/.cargo/config.toml, stage0/Cargo.lock, stage0/Cargo.toml, stage0/src/fw_cfg.rs, stage0/src/initramfs.rs, stage0/src/kernel.rs, stage0/src/main.rs
This change adds support for Loading an ELF kernel from stage0 using the QEMU fw_cfg device, parsing it, and laying it out in memory.
QEMU assumes that an ELF kernel passed using the `-kernel` command-line argument will use the PVH boot protocol and lays it out into the guest memory. This causes a problem when booting with SEV enabled, since the kernel data in guest memory does not get encrypted. To work around it we pass the raw kernel ELF file manually via the fw_cfg device.
QEMU does not accept the `-append` or `-initrd` arguments if `-kernel` is not specified, so we also pass those in manually via the fw_cfg device.
Parsing an ELF kernel required adding a global allocator, since paring ELF program headers return a vector.
I also had to enable LTO to make sure stage0 still fits within …
=> Add support for loading and parsing an ELF kernel

Cargo.lock, oak_enclave_runtime_support/Cargo.toml, oak_enclave_runtime_support/src/heap.rs, oak_functions_enclave_app/Cargo.lock, oak_tensorflow_enclave_app/Cargo.lock, quirk_echo_enclave_app/Cargo.lock, testing/oak_echo_enclave_app/Cargo.lock, testing/oak_echo_raw_enclave_app/Cargo.lock
The malloc algorithm provided by `rlsf` is much more efficient than the one provided by `linked_list_allocator`.
How much more efficient? With a certain pathological data set it took 11 hours (!) to parse the protobuf containing the data. With `rlsf`, it took 11 seconds. Yes, seconds.
=> Replace `linked_list_allocator` with `rlsf` in the enclave binaries

oak_crypto/proto/crypto.proto
This PR adds `HpkeRequest` and `HpkeResponse` proto messages.
This PR is a split from https://github.com/project-oak/oak/pull/3790
Ref https://github.com/project-oak/oak/issues/3767
=> Add HPKE proto messages to oak_crypto

Cargo.lock, Cargo.toml, oak_client/Cargo.toml, oak_client/build.rs, oak_client/src/lib.rs, oak_client/src/transport.rs, oak_functions/load_test/src/main.rs, oak_functions_client/Cargo.toml, oak_functions_client/src/lib.rs, oak_functions_client/src/main.rs, oak_functions_launcher/Cargo.toml, oak_functions_launcher/build.rs, oak_functions_launcher/src/lib.rs, oak_functions_launcher/src/server.rs, oak_functions_launcher/tests/integration_test.rs, oak_functions_test_utils/Cargo.toml, oak_functions_test_utils/src/lib.rs
This PR adds `oak_client` dependency to `oak_functions_client` and removes the oak_remote_attestation_noninteractive` crate dependency from `oak_functions_launcher`.
This PR is a split from https://github.com/project-oak/oak/pull/3790
Ref https://github.com/project-oak/oak/issues/3643
=> Use oak_client crate for Oak Functions

oak_functions/README.md
I removed the part about "Read-Only Storage" and the link to "Policies" as I cannot find them in the repo.
=> Fix broken links in oak_functions README

kokoro/presubmit.sh, oak_channel/src/frame.rs, oak_channel/src/lib.rs, oak_channel/src/message.rs, oak_channel/src/tests.rs
Instead of passing around vectors, this changes some APIs to take in references to slices instead.
After all that, we can now instantiate one vector for the whole frame and read directly into that, instead of allocating many smaller vectors that need to be copied into `encoded_message`.
Unfortunately we still need some special treatment (which may involve a copy) for the first frame, as at that point we don't yet know how much space we need for the whole message.
=> Get rid of one data copy in `oak_channel`

Cargo.lock, oak_functions_enclave_app/Cargo.lock, oak_remote_attestation_noninteractive/proto/v1/messages.proto, oak_remote_attestation_noninteractive/tests/integration_test.rs
Some renaming and refactoring based on a chat with @ipetr0v to make the terminology more consistent with RATS.
=> Use AttestationEvidence for evidence coming from the enclave

stage0/src/fw_cfg.rs, stage0/src/initramfs.rs, stage0/src/kernel.rs, stage0/src/main.rs, stage0/src/sev.rs
When testing the latest Stage0 image on AMD SEV-SNP we found some issues. To fix these:
- Don't PVALIDATE pages when unsharing pages
- Also, we don't need to change the encryption bit for the pages when unsharing, as we set it for the entire first 2MiB huge page when we switch back to using a huge page
- Loading the ACPI tables using fw_cfg DMA is not currently supported, so we only use DMA for the kernel image and initial RAM disk when booting Linux
=> Fix Stage0 SEV-SNP errors

oak_minirootfs_linux_init/README.md, oak_minirootfs_linux_init/init
Note that instead of packaging the init binary as rust binary, we have simply created a shell script with the appropriate initialization commands.
=> Example to boot a shell with Alpine's minirootfs and stage0 firmware.

Cargo.lock, deny.toml, oak_functions_enclave_app/Cargo.lock, oak_functions_launcher/tests/integration_test.rs, oak_restricted_kernel_bin/deny.toml, oak_tensorflow_enclave_app/deny.toml, quirk_echo_enclave_app/deny.toml, testing/oak_echo_enclave_app/deny.toml, testing/oak_echo_raw_enclave_app/deny.toml, testing/sev_snp_hello_world_kernel/deny.toml
This change updates the `spin` crate to a version that has not been yanked.
It also resolves the warning and starts treating unsound advisories as errors rather than warnings.
Side note: I also increase the time the oak functions launcher integration tests waited for the server to start up, as the Kokoro tests were very flaky due to the server not always starting up in time.
=> Fix cargo deny error and warnings

oak_restricted_kernel/src/ghcb.rs, oak_sev_guest/src/ghcb.rs, stage0/src/sev.rs
This change addresses some flakiness when running stage0 and the Oak Restricted Kernel with SEV-ES or SEV-SNP enabled.
There seems to be an occasional timing issue around the GHCB when marking it as unencrypted, with the GHCB becoming corrupted. To make sure it stays consistent we reset it to all zeros every time after the page has been marked as not encrypted and the TLB has been flushed.
This change also makes sure that stage0 and the restricted kernel follows the same order of steps when sharing the GHCB with the hypervisor (mark it unencrypted, flush TLB, mark it as shared in the RMP, register the location with the hypervisor) for consitency.
Lastly I also decided to add stronger memory fences around the VMGEXIT call as an extra assurance.
=> Reset GHCB after marking memory as unencrypted

WORKSPACE, cc/crypto/BUILD, cc/crypto/encryptor.cc, cc/crypto/encryptor.h, cc/crypto/hpke.cc, cc/crypto/hpke.h, java/src/main/java/com/google/oak/crypto/BUILD, java/src/main/java/com/google/oak/crypto/ClientEncryptor.java, java/src/test/java/com/google/oak/crypto/BUILD, java/src/test/java/com/google/oak/crypto/ClientEncryptorTest.java
This PR adds interfaces for C++ crypto library and Java `SenderEncryptor`.
Interfaces a made to resemble the Rust implementation: https://github.com/project-oak/oak/pull/3842
Ref https://github.com/project-oak/oak/issues/3644
=> Add C++ crypto template

stage0/src/asm/boot.s
I made this change when chasing down an unrelated bug and turns out it wasn't the root cause, but this little change might be worth submitting anyway.
This will change stage0 to leave the first 4K of memory unmapped so that if we ever accidentally dereference a null pointer, we'd get a page fault and crash instead of the read accidentally working.
=> Don't map [`0x0000`...`0x1000`) in stage0

Cargo.lock, Cargo.toml, oak_docker_linux_init/Cargo.toml, oak_docker_linux_init/README.md, oak_docker_linux_init/docker_to_initramfs.sh, oak_docker_linux_init/src/init.rs, oak_docker_linux_init/src/main.rs
The idea is to convert the docker image into a initramfs image and use it when booting the kernel. The docker_to_initramfs.sh in this PR has all the details of how this is accomplished.
=> Demonstrate running a docker container from oak's stage0 firmware.

.github/workflows/reusable_provenance.yaml
Follow up fix after ##3669
The name of the downloaded provenance has an extra `.sigstore` suffix on triggers other than `pull_request`. The suffix was missing, resulting in empty provenance digest in the post-merge comments published on the PR. 
Note that the fix cannot be verified until this PR is merged!
Also it looks like my fancy trick to control running the provenance CI steps with the `provenance:force-run` label does not quite work. I'll look into it later.
=> Fix provenance file name in upload_provenance

stage0/layout.ld, stage0/src/asm/boot.s
We used to assume that the C-bit was always bit 51 as that was true for the machines we were testing on, but it's not _always_ true. For example, Rome CPUs have that at bit 47.
This PR sets up enough machinery (VC handler, etc) to properly identify the C-bit position by inspecting CPUID.
=> Determine the C-bit position dynamically in stage0

oak_restricted_kernel/src/logging.rs, oak_restricted_kernel/src/syscall/mmap.rs
a) prefix logs from the kernel with a explicit "kernel" to distinguish them from logs from the application, as both of them use a similar format and go into the same channel
b) add a bunch of logging into `mmap()` to get more information about allocation failures in particular
We will likely want to remove the debug calls at some point, but `mmap()` should not be called too often so I don't expect there to be too much noise from those statement.
=> Add some debug logging into the `mmap()` syscall in Restricted Kernel

.devcontainer.json, Dockerfile, scripts/common
`cargo vet` looks like a rather promising tool to ensure that our dependencies have been audited by a trusted entity.
This brings `cargo-vet` into our Docker image so that we can start experimenting with it on the dependencies of `stage0`.
=> Include `cargo-vet` in our Docker image.

oak_restricted_kernel/src/interrupts.rs, oak_sev_guest/README.md, oak_sev_guest/src/cpuid.rs, oak_sev_guest/src/ghcb.rs, oak_sev_guest/src/msr.rs, sev_serial/src/lib.rs
See section 4.1.3 in https://www.amd.com/system/files/TechDocs/56421-guest-hypervisor-communication-block-standardization.pdf for more information.
I also noticed that the URL of the GHCB spec changed, so I changed it throughout the codebase as well.
=> Add GHCB support for reading and writing MSRs

oak_sev_guest/src/ghcb.rs, stage0/src/main.rs, stage0/src/sev.rs
Accessing the MTRRDefType MSR cuases a VC exception on SEV-ES and SEV-SNP, so we should access it via the GHCB protocol to avoid the need for a VC handler in stage 0.
There were also a couple of bugs in the GHCB implementation:
- When writing to an MSR the sw_exit_info_1 field must be set to 1
- The order of RBX, RCX and RDX in the GHCB was incorrect
=> Use the GHCB protocol for the MTRRDefType MSR if SEV-ES or SEV-SNP is active

Cargo.lock, oak_functions_launcher/Cargo.toml, oak_functions_launcher/src/server.rs
This PR updates the Oak Launcher to use gRPC bidirectional streaming.
Previously it was just returning a single response and closing the stream.
=> Use gRPC bidirectional streaming in Oak Launcher

stage0/src/sev.rs
At the moment we are logging a lot of warnings and errors when pvalidating the guest memory in Stage0 on AMD SEV-SNP. These logs are not useful, and causes a lot of noise.
Based on the AMD documentation for the PVALIDATE instruction in [AMD64 Architecture Programmer’s Manual Volume 3](https://www.amd.com/system/files/TechDocs/24594.pdf): if the instruction reports success, but also that the validation status was not changed, it is either because the page was already validated (e.g. by the secure processor before boot) or SEV-SNP is not enabled (e.g. if this is called on the host). Either way, there is no need to log it.
For any real errors we will panic and log the error messages as part of that, so there is no need to log them additionally.
=> Stop logging when page validation is not updated

docs/release.md
Ref #3862 
This change updates the docs/release.md file, reflecting the changes in provenance generation and format now that we are using the container-based workflow.
Note that since the new workflow generates a Sigstore Bundle instead of a DSSE document, some of the instructions for fetching the provenance from Rekor no longer apply.
=> Update the release doc

oak_docker_linux_init/docker_to_initramfs.sh, oak_docker_linux_init/src/main.rs
Earlier, we were using spaces to separate the elements of a Docker CMD/ENTRYPOINT. However, this caused a single argument to be split into multiple arguments at the time of execution in certain cases:
```
"Cmd": [                                                                                       
"bash",                                                                                    
"-c",                                                                                      
"source /etc/bash.bashrc && jupyter notebook --notebook-dir=/tf --ip 0.0.0.0 --no-browser --allow-root"
],
```
This PR changes the separator to `\n`.
=> Use newline to separate args of docker command to prevent lossy representation.

stage0/src/asm/boot.s, stage0/src/asm/mod.rs, stage0/src/main.rs, stage0/src/paging.rs
This PR simplifies the Stage 0 assembly code related to page tables:
- Move the page tables to BSS
- Move the code to zeo-out BSS earlier so we don't have to separately zero out the page tables
- Only map 2MiB huge pages in assembly and create the 4KiB pages in Rust code
- Only update the actual page table entries we created with the encrypted bit rather than looping through all the page table entries
=> Simplify Stage0 page table assembly code

stage0/src/acpi.rs
We just build ACPI tables in stage0, so we don't care whether we're dealing with ACPI 1.0 or 2.0.
=> Be more lenient about ACPI RSDP size in stage0

oak_docker_linux_init/README.md, oak_docker_linux_init/docker_to_rootfs.sh, oak_docker_linux_init/prepare_docker_launcher_initramfs.sh, oak_docker_linux_init/src/main.rs
This PR has a a bunch of changes:
1. A `prepare_docker_launcher_initramfs.sh` script combines the following to create the initramfs:
- Alpine's minirootfs
- Necessary drivers from an Alpine Linux distribution.
- Filesystem extracted from the given docker image.
Note that if the docker image is not provided, the script creates an initramfs that provides a working shell.
1. Generalize the `docker_to_initramfs.sh` script to generate a chroot directory or initramfs images
1. A hack to set up PATH environment variables to some common locations.
Note that this PR is meant to demonstrate the steps that are needed to launch a docker container with networking support. To achieve the task, we pull drivers and kernel from the [Alpine Linux](www.alpinelinux.org) distribution. We also use Alpine's …
=> A bash script that prepares minirootfs + docker image as initramfs.

stage0/layout.ld, stage0/src/asm/boot.s
This moves the target location DATA segment into low memory, while still storing the content in the ROM image. The bootstrap assembly then copies it from the ROM image into the expected memory location in low memory.
=> Move the stage0 data segment to low memory

stage0/src/asm/boot.s, stage0/src/main.rs, stage0/src/sev.rs
After refactoring the page table management in Stage 0 the GHCB was being created and shared before the page tables were fully initialised.
The bootstrap assembly was also modifying memory in the first megabyte before PVALIDATE was called on this memory.
This PR fixes both issues so that stage0 again works on AMD SEV-ES and SEV-SNP.
=> Fix the stage0 GHCB

Cargo.lock, Cargo.toml, oak_tdx_guest/Cargo.toml, oak_tdx_guest/README.md, oak_tdx_guest/src/lib.rs, oak_tdx_guest/src/tdcall.rs
Adds a new helper crate to support TDX enlightenment. Also adds support for the first two TDCALL leaves that we will use:
- Getting information about the encrypted VM (TD)
- Getting information about a recent virtualisation exception (#VE)
Support for the TDG.VP.VMCALL leaf and its sub-functions will be added in a follow-up PR.
Support for other leaves will only be added later when needed.
For more information see https://www.intel.com/content/dam/develop/external/us/en/documents/intel-tdx-guest-hypervisor-communication-interface.pdf
=> Add initial TDX enlightenment helpers

oak_restricted_kernel/src/lib.rs, oak_restricted_kernel/src/memory.rs, oak_restricted_kernel/src/mm/bitmap_frame_allocator.rs, oak_restricted_kernel/src/mm/encrypted_mapper.rs, oak_restricted_kernel/src/mm/frame_allocator.rs, oak_restricted_kernel/src/mm/mod.rs, oak_restricted_kernel/src/mm/page_tables.rs, oak_restricted_kernel/src/syscall/mmap.rs
Although we have a global FRAME_ALLOCATOR static variable, at times we still carried a reference to it around. We don't really need to, and that simplifies the code. Physical memory is a global resource anyway, and it doesn't make much sense to have multiple frame allocators around.
Another insight is that when we create a `FrameAllocator` all of the memory will be marked as invalid (and you won't be able to acquire any physical memory until `mm::init()` is called). Thus, we can simplify things even further and just have it in a `Spinlock` without bothering with a `OnceCell` as nothing bad can happen if you call `FrameAllocator::allocate_frame` _before_ any memory there is marked as available.
=> Simplify how we track physical memory

oak_restricted_kernel/src/lib.rs
Turns out 128 GiB is not enough for everybody.
This does increase the bitmap size significantly (it'll be 2* 32KiB), and at some point we may want to implement a cleverer algorithm to track physical memory. But 64K is still tiny in the grand scheme of things.
=> Increase the amount of physical memory we can track to 512 GiB.

Cargo.lock, oak_tdx_guest/Cargo.toml, oak_tdx_guest/src/lib.rs, oak_tdx_guest/src/tdcall.rs, oak_tdx_guest/src/vmcall.rs
This PR adds Intel TDX support for:
- Sharing and unsharing guest-physical memory frames
- Reading from and writing to IO ports
- Reading from and writing to model-specific registers
=> Add support for initial TDX VMCALL sub-functions

oak_restricted_kernel/src/lib.rs, oak_restricted_kernel/src/mm/encrypted_mapper.rs, oak_restricted_kernel/src/mm/mod.rs, oak_restricted_kernel/src/mm/page_tables.rs
The idea is that in the future every process would have it's very own `RootPageTable`, and as part of context switches we load the appropriate PML4 inside the `RootPageTable` into `cr3`.
For now, `RootPageTable` does almost nothing; it just wraps `EncryptedPageTable` and delegates all operations to that. But it will gain more features in the future.
=> Create a `RootPageTable` struct to encapsulate all page operations

oak_docker_linux_init/Dockerfile, oak_docker_linux_init/README.md, oak_docker_linux_init/mk_base_initramfs.sh, oak_docker_linux_init/prepare_docker_launcher_initramfs.sh
This PR contains the following changes:
- Adds a Dockerfile to build a docker image of an Alpine distribution, which can be used to extract the kernel and necessary drivers for our Docker experiments. This approach makes it easier to pick and choose drivers as we can configure the Alpine Docker image as opposed to downloading tars/isos from different locations.
- Picks up the drivers needed to support block devices and ext4 fs.
=> Use a Docker approach to extract kernel/drivers from Alpine Distribution

oak_docker_linux_init/mk_base_initramfs.sh
This is necessary for running some tensorflow models.
=> Add IPv6 Drivers to the initramfs for Oak Docker

.cargo/config.toml, scripts/build_gh_pages, xtask/src/launcher.rs
Running `cargo bench --package` twice, takes for the second iteration:
- before this change: 54s
- after this change: 6s
Fix #3941
=> Specify default target

stage0/supply-chain/audits.toml, stage0/supply-chain/config.toml, stage0/supply-chain/imports.lock, xtask/src/main.rs
If you want to double-check the source you can do it here: https://sourcegraph.com/crates/alloc-traits@v0.1.1
Some unsafe code in there as it deals with allocators (which is inherently unsafe), but it's well-contained and easy to reason about.
I've also included a change to `xtask` that makes it not run Prettier on the `cargo vet` TOML files, as `cargo vet` insists on its own format that clashes with Prettier's opinions.
Fixes #3946
=> Vet `alloc-traits` as `does-not-implement-crypto` and `safe-to-deploy`

oak_restricted_kernel/src/mm/bitmap_frame_allocator.rs, oak_restricted_kernel/src/mm/frame_allocator.rs, oak_restricted_kernel/src/syscall/mmap.rs
Hopefully this gives a little bit more information into what's the current state when a call to `mmap` can't allocate the application more memory.
Ideally we'd give more information, e.g. how much of the physical memory has been allocated to the kernel and how much to the application, but currently we don't keep track of the users of the memory regions, just whether they are allocated or not.
=> Print out some debug information when `mmap` can't allocate memory

stage0/supply-chain/audits.toml
Based on https://sourcegraph.com/crates/doc-comment@v0.3.3
Fixes #3952
=> Vet `doc-comment` 0.3.3 as `does-not-implement-crypto`

stage0/Cargo.lock, stage0/supply-chain/imports.lock
Newer versions of the `quote` and `proc-macro2` crates have already been vetted, so this update removes the need for vetting.
Fixes #3958
Fixes #3957
=> Update `quote` and `proc-macro2` for Stage0

stage0/supply-chain/audits.toml
Based on https://sourcegraph.com/crates/synstructure@v0.12.6
Fixes #3969
=> Vet `synstructure` 0.12.6 as `does-not-implement-crypto`

stage0/supply-chain/audits.toml, stage0/supply-chain/imports.lock
These crates have already been vetted as "safe-to-deploy". This confirms that none of these crates implement any crypto.
Code for the crates:
- autocfg 1.1.0: https://sourcegraph.com/crates/autocfg@v1.1.0
- rustversion 1.0.9: https://sourcegraph.com/crates/rustversion@v1.0.9/
- unicode-xid 0.2.4: https://sourcegraph.com/crates/unicode-xid@v0.2.4
Fixes #3971
Fixes #3959
Fixes #3947
=> Vet `autocfg`, `rustversion` and `unicode-xid`

stage0/supply-chain/audits.toml
https://sourcegraph.com/crates/zerocopy-derive@v0.3.1
Fixes #3975
=> Vet `zerocopy-derive` as `safe-to-deploy`, `does-not-implement-crypto`

Cargo.lock, oak_tdx_guest/Cargo.toml, oak_tdx_guest/src/tdcall.rs
Stage0 must accept all pending private pages on TDX, similar to how private pages are validated on AMD SEV-SNP.
=> Add support for accepting memory pages on TDX

stage0_bin/supply-chain/audits.toml
Probably one of the most risky crates we have, so I'd appreciate at least a cursory look at the crate source do double-check my conclusion.
There's a ton of `unsafe` code in there, but that's to be expected -- however, I think all potentially dangerous methods are properly marked as `unsafe`; therefore, if the caller is calling them with untrusted inputs it's up to them to guarantee that we don't load, say, a troll Youtube video as the interrupt descriptor table.
Source: https://sourcegraph.com/crates/x86_64@v0.14.10
Fixes #3973
=> Vet `x86_64`

Cargo.lock, enclave_apps/Cargo.lock, enclave_apps/Cargo.toml, enclave_apps/oak_echo_enclave_app/Cargo.toml, enclave_apps/oak_echo_enclave_app/src/main.rs, enclave_apps/oak_functions_enclave_app/Cargo.toml, enclave_apps/oak_functions_enclave_app/src/main.rs, enclave_apps/oak_iree_enclave_app/Cargo.toml, enclave_apps/oak_iree_enclave_app/src/main.rs, enclave_apps/oak_tensorflow_enclave_app/Cargo.toml, enclave_apps/oak_tensorflow_enclave_app/src/main.rs, enclave_apps/quirk_echo_enclave_app/Cargo.toml, enclave_apps/quirk_echo_enclave_app/src/main.rs, oak_channel/Cargo.toml, oak_channel/src/client.rs, oak_channel/src/frame.rs, oak_channel/src/lib.rs, oak_channel/src/server.rs, oak_channel/src/tests.rs, oak_core/src/samplestore.rs, oak_core/src/timer.rs, oak_functions_linux_fd_bin/Cargo.toml, oak_functions_linux_fd_bin/src/main.rs, oak_launcher_utils/src/channel.rs, oak_restricted_kernel_bin/Cargo.lock
First steps toward exposing some details about what's going on inside the enclave...
This should start measuring how long it takes for the enclave to service a RPC, all the way from reading the request to writing the response back.
There are multiple caveats here:
- as calling the `read` syscall can block, I start measuring time after we've read the padding for the start frame. (I can't start the timer _before_ reading the padding, otherwise we'd potentially count the idle time it took for the loader to write anything to the channel as time it took to read the frame.)
- right now we do nothing with the gathered stats as we don't have a mechanism for exporting them
- this doesn't distinguish between the different types of RPCs; from my cursory read that will require extensive modifications …
=> Start keeping statistics about how long a RPC invocation took

stage0_bin/supply-chain/audits.toml
Closes #3954.
Please carefully read audit notes before approving. 
While this crate imo qualifies for `does-not-implement-crypto`, I feel a bit hesitant about attaching the implied label `crypto-safe`. A label that could plausibly be considered to imply that the random number generators exposed by this crate are sufficiently trustworthy for implementing arbitrary crypto algorithms. An endorsement that I would not be prepared to make.
Imo fine but consider when reviewing.
=> vet getrandom 0.2.9

Cargo.lock, stage0/Cargo.toml, stage0/src/alloc.rs, stage0/src/kernel.rs, stage0/src/lib.rs, stage0_bin/.cargo/config.toml, stage0_bin/Cargo.lock, stage0_bin/supply-chain/audits.toml, stage0_bin/supply-chain/config.toml
This PR does three things:
First, get rid of a`vec!` in `kernel.rs`. After we do that, we no longer need to pull in anything from the `alloc` crate.
Second, replace the `Bump` allocator from `static-alloc` with a simplified home-grown version. This means there's less crates to vet, at the expense of introducing some `unsafe` code straight to stage0 (as we're dealing with raw pointers here, but there's only two small blocks of unsafe code).
Third, rescind the vet for `alloc-traits`, as that was only used by `static-alloc`, which is no longer used.
Fixes #3964
=> Replace `static-alloc` with a home-grown bump allocator

.devcontainer.json
thanks @mariaschett for recommending this one. Unlike our previous extension for getting links to files on github, this one directly allows you to copy perma links to code snippets also
=> devcontainer: use better extension for getting github links for code snippets

.devcontainer.json, Dockerfile, kokoro/presubmit.sh, oak_docker_linux_init/Dockerfile, oak_docker_linux_init/README.md, oak_docker_linux_init/prepare_docker_launcher_initramfs.sh, scripts/common, scripts/docker_run
Make it possible to successfully run the commands in the README without modifications.
Additionally, to enable running the commands without having to manually get the proper dependencies, the commands in the README should work within the Oak development docker container. Make this possible by adding dependencies to the Oak development docker
image and providing the docker container with access to necessary files on the host machine.
Tested by running the commands in the README both from within a docker container started from VSCode, from within a docker container started via the scripts/docker_sh, and from outside Docker with dependencies downloaded manually.
=> Fix commands to run docker container from stage0

oak_functions/wasm/src/lib.rs
Create a handy proc macro to stub multiple functions easily.
Follow up from 75bbbcf1418489dfe4c05392c150a496ff62dcbb
=> Stub more WASI functions

micro_rpc/build.rs, oak_crypto/build.rs, oak_remote_attestation/build.rs
When run, each build script's working directory is set to the source directory of the build script's package
(https://doc.rust-lang.org/cargo/reference/build-scripts.html#inputs-to-the-build-script), so these paths can all be made relative.
Using relative paths makes it much easier to use these crates from another workspace since it's no longer necessary to set WORKSPACE_ROOT to the right path within the Cargo home.
Tested by running `cargo build`.
=> Remove several unnecessary uses of WORKSPACE_ROOT.

Cargo.lock, Cargo.toml, oak_containers_stage1/Cargo.toml, oak_containers_stage1/build.rs, oak_containers_stage1/proto/stage1.proto, oak_containers_stage1/src/image.rs, oak_containers_stage1/src/main.rs, oak_containers_stage1/src/server.rs
As discussed, we first want to have a small initrd image (this binary compiles down to ~3 MB stripped, probably even smaller if we enable LTO) that loads a full-size filesystem image over a more high-bandwidth channel.
This PR creates the first version of that program; it's somewhat of a request for comments as there is no way to test it yet. But it exposes a gRPC service that can be used to upload a TAR archive, which is then unpacked to a ramdrive and stage1 executes the `/sbin/init` program from that ramdrive.
(Feel free to bikeshed about the name as well; I picked stage1 as it's (a) after stage0 and (b) much like stage0 once we've executed the next step the life of this stage is done, it will not stick around.)
=> Create an initial version of stage1 (loader in initrd)

oak_containers/proto/launcher.proto
As discussed the launcher will be the server, and stage1/orchestrator will fetch their images from them (pull, not push).
This adds the first version of the service proto (as it's needed for my stage1 experiments).
=> Define the service interface between launcher and (stage1/orhcestrator)

Cargo.lock, oak_containers_launcher/Cargo.toml, oak_containers_launcher/src/main.rs, oak_containers_launcher/src/qemu.rs
Largely untested in real life (but we can spawn QEMU), but after this PR we should have all the pieces there to start trying plugging all of them together.
The code is mostly based on the Oak Functions launcher code; shortcuts were taken, but we can always refactor in the future.
Ref #4023
=> Spawn a QEMU instance in the Oak Containers launcher

cc/crypto/hpke/recipient_context.cc, cc/crypto/hpke/recipient_context.h, cc/crypto/hpke/sender_context.cc, cc/crypto/hpke/sender_context.h, cc/crypto/hpke/sender_context_test.cc, java/src/main/java/com/google/oak/crypto/hpke/KeyPair.java, java/src/test/java/com/google/oak/crypto/EncryptorTest.java
This PR adds an empty implementation for key pair generation in C++ and Java.
Ref https://github.com/project-oak/oak/issues/4026 https://github.com/project-oak/oak/issues/3642
=> Add key pair generation template

.github/workflows/reusable_provenance.yaml
Add a sha256sum check after downloading the ent binary.
The check prevents an RCE within the workflow if the ent server is compromised.
Potential attack:
1. A malicious actor overrides the ent binary on the server with a malicious one.
2. The malicious ent binary uses the `pull-reuqest: write` permission to push malicious code to the main branch.
3. The malicious code pushed to the main branch triggers the workflows, thus being injected into the next application version.
4. The malicious version also generates a legitimate provenance document.
Moreover, the attacker can create a new workflow with ALL write permissions, resulting in a complete compromise of the repository and its secrets, and the ability to remove the code and actions from the git history -- making the attack even more …
=> fix: verify ent sha256sum

cc/crypto/BUILD, cc/crypto/client_encryptor.cc, cc/crypto/client_encryptor.h, cc/crypto/common.h, cc/crypto/server_encryptor.cc, cc/crypto/server_encryptor.h
This PR splits `cc/crypto/encryptor.h` into `cc/crypto/client_encryptor.h` and `cc/crypto/server_encryptor.h`
Ref https://github.com/project-oak/oak/issues/4026
=> Split C++ encryptor file

oak_containers_system_image/Dockerfile, oak_containers_system_image/build.sh
Last piece of the puzzle for now: a script to build a tarball suitable for use as the system image in Oak Docker.
=> Add a script to build a base system image based on Clear Linux

cc/crypto/client_encryptor.cc, cc/crypto/client_encryptor.h
This PR adds an implementation for the Client Encryptor as part of C++ Hybrid Encryption implementation.
Ref https://github.com/project-oak/oak/issues/4026
=> Add C++ Client Encryptor implementation

WORKSPACE
This PR updates:
- Java gRPC to v1.56.0 (2023-06-21)
- External Java rules to v5.2 (2023-04-13)
=> Update Java gRPC

oak_containers_system_image/Dockerfile
The docker runtime is seriously overkill for us. However it's fasted way to unblock running containers, which imo makes it the right fit for now.
=> Install docker container runtime in oak container system image

oak_containers/proto/interfaces.proto, oak_containers_launcher_server/build.rs, oak_containers_orchestrator_client/build.rs, oak_containers_stage1/build.rs
At the moment it only includes a method to load application config, we'll add encryption/decryption methods later. 
I defined it in the same file as the launcher service, since the `GetApplicationConfigResponse` is shared. Imo that seems simpler than using multiple files and importing messages, but open to different opinions.
=> Add initial orchestrator service definition

.github/workflows/provenance.yaml
Fixes #4061
This seems to work. I've added and removed the label. 
If the label is there, the provenance workflow is run. Otherwise it is not.
Can you think of anything else I should test?
=> Run only if post merge

cc/crypto/BUILD, cc/crypto/hpke/recipient_context.h, cc/crypto/server_encryptor.cc, cc/crypto/server_encryptor.h, java/src/main/java/com/google/oak/crypto/ServerEncryptor.java
This PR adds an implementation for the Server Encryptor as part of C++ Hybrid Encryption implementation.
Ref https://github.com/project-oak/oak/issues/4026
=> Add C++ Server Encryptor implementation

oak_containers_launcher/src/qemu.rs, oak_containers_stage1/Cargo.toml, oak_containers_stage1/Makefile, oak_containers_stage1/src/main.rs
Most of the weird startup issues I saw when we were unpacking the system image onto a `ramfs` filesystem stemmed from the fact that `systemd` recognized it as a transient filesystem, and thus refused to do some operations on it.
Thus, instead of creating a `ramfs` root, let's create a real ext4 filesystem on a fixed-size ramdrive and unpack the system image onto that; `systemd` seems to be far more happer with that arrangement.
This unfortunately does mean we get another knob to tweak, namely the ramdrive size. Ramfs could just arbitrarily grow, ramdrives are of a fixed size. On the other hand, this also means we won't accidentally fill memory with garbage when writing files to the filesystem (but rather eventually we will get drive full errors if, say, logs back up), so it's more of a …
=> Use a fixed-size ramdrive instead of ramfs for the system root

oak_containers_system_image/Dockerfile, oak_containers_system_image/journald.conf
The key change here is that `journald` will now output system logs to the console. We may want to build a more clever way how to extract logs in the future, but for now, that'll do.
I've also included a couple more tweaks:
- don't copy the orchestrator unit file to `/lib/systemd` but rather to `/etc/systemd`, which is supposed to be the place for the system-specific overrides
- conversely, don't directly change the default target link, but rather use `systemctl target` to create a default override under `/etc/systemd`
- and finally, delete some packages we don't need in the system image (for example, we will never run an OS updater in there) -- this shaves ~200 MB off the image size.
=> Configure logging in system image + minor cleanups and tweaks

cc/crypto/hpke/recipient_context.cc, cc/crypto/hpke/recipient_context.h, cc/crypto/hpke/recipient_context_test.cc
Generate public-private key pair using BoringSSL library
Ref #4026
=> Implement Recipient C++ Key Generator

justfile
This simplifies the buildconfig files, and makes it possible to build the binaries more easily even without the transparent release builder.
=> Use `just` for enclave app and other binaries

java/src/main/java/com/google/oak/crypto/hpke/Context.java, java/src/main/java/com/google/oak/crypto/hpke/Hpke.java, java/src/main/java/com/google/oak/crypto/hpke/KeyPair.java
This PR removes system.exit() calls when calling JNI loadLibrary as it is untestable.
This PR is part of the the Java implementation for (https://github.com/project-oak/oak/issues/3642).
=> Remove system.exit() calls when calling JNI loadLibrary

cc/crypto/BUILD, cc/crypto/client_encryptor.cc, cc/crypto/common.h, cc/crypto/encryptor_test.cc, cc/crypto/hpke/recipient_context.cc, cc/crypto/hpke/recipient_context.h, cc/crypto/server_encryptor.cc, cc/crypto/server_encryptor.h
This contains some basic testing for the communication between client and server encryptors.
The most common error seen in the communication should be related to mismatched keys (i.e. the client uses the wrong public key). All other errors are likely bugs related to the internal context classes.
Ref #4026
=> C++ Encryption Testing using X25519

java/src/main/java/com/google/oak/remote_attestation/AmdAttestationVerifier.java
Use empty reference value in the AMD verifier to prevent internal checks from failing.
Attestation verification will be implemented in https://github.com/project-oak/oak/issues/3641
=> Use empty reference value in the verifier

java/src/main/java/com/google/oak/client/weather_lookup_client/BUILD, java/src/main/java/com/google/oak/crypto/BUILD, java/src/main/java/com/google/oak/crypto/hpke/BUILD, java/src/test/java/com/google/oak/client/BUILD, java/src/test/java/com/google/oak/crypto/BUILD
This PR moves the  libhpke.so binary to bazel deps.
This PR is part of the the Java implementation for (https://github.com/project-oak/oak/issues/3642).
=> Move JNI .so binary to bazel deps.

flake.nix, justfile, kokoro/presubmit.sh, oak_containers_stage1/Makefile
I've changed Kokoro to use the default shell, as sooner or later we'll also want to build the kernel and everything else related to containers in Kokoro as well.
=> Build `stage1.cpio` on Kokoro

Cargo.lock, oak_containers_orchestrator/Cargo.toml, oak_containers_orchestrator/src/container_runtime.rs, oak_containers_orchestrator/src/logging.rs, oak_containers_orchestrator/src/main.rs
Implements a simple chroot based container runtime. I welcome opinions on the choice of the runtime. 
On the pro side: small!
- small and easy to reason about 
- small and probably integratable into a statically linked linux distro
On the con side: executes an [OCI filesystem bundle](https://github.com/opencontainers/runtime-spec/blob/main/bundle.md) in a likely non-standard/unexpected way
- newest version of the OCI filesystem bundle it supports all req attributes of is v0.2.0 (v old). Newer versions afaik cannot be supported with chroot, since chroot fixes the workdir to root
- does not implement any of the optional settings of the OCI filesystem bundle config file, most certainly leading to unexpected things happening by default.
- in essence this means containers must likely be …
=> Implement simple chroot container runtime

justfile, kokoro/oak_containers_presubmit.sh, kokoro/presubmit.sh
I'll have to follow this PR up with an internal change to actually call `oak-container-presubmit.sh` from Kokoro.
=> Move stage1 to a separate Kokoro presubmit

stage0/src/fw_cfg.rs
Rather than always trying to use DMA access on the fw_cfg device (and falling back to byte-by-byte reading on failure) we can query the device to check whether DMA is enabled.
=> Query fw_cfg device to check if DMA is enabled

oak_containers/proto/interfaces.proto, oak_containers_launcher_server/build.rs, oak_containers_launcher_server/src/lib.rs, oak_containers_orchestrator/src/main.rs, oak_containers_orchestrator_client/build.rs, oak_containers_orchestrator_client/src/lib.rs, oak_containers_stage1/build.rs, oak_containers_stage1/src/client.rs
This PR makes the Orchestrator send an empty Attestation Evidence to the Containers Launcher.
=> Send empty Attestation Evidence to the Containers Launcher

.github/workflows/provenance.yaml
The #4125 was obviously the completely wrong way of disabling the provenance workflow for `oak_tensorflow_enclave_app`.
=> Remove oak_tensorflow_enclave_app.toml from provenance workflow

oak_containers_system_image/Dockerfile
This reduces the system image size from 1.1G to 400M -- or, once we compress it, from 300M to 95M.
And we can likely prune more stuff that's in there right now.
=> Replace Clear Linux with Debian in the Oak Containers system image

java/src/main/java/com/google/oak/crypto/hpke/BUILD
This PR moves the Java deps for the libhpke-jni.so file from deps to runtime_deps in the BUILD file.
This PR is part of the the Java implementation for (https://github.com/project-oak/oak/issues/3642).
=> Move jni.so import to runtime_deps.

oak_containers_system_image/build.sh, oak_containers_system_image/oak-orchestrator.service
If the orchestrator dies, then it doesn't make much sense to keep the system around. We can configure systemd to restart the service, but I'm worried that might mask other errors that might happen.
Having the system shut down when the orchestrator dies lets us handle the (unexpected) error on a higher level. We can always retry by restarting the whole VM, if we want to -- with the benefit of starting from a clean slate.
(I've also sneaked in a change to force `xz` to always overwrite the system image file.)
=> If the orchestrator dies, take the rest of the system down with it

oak_containers_hello_world_container/config.json, oak_containers_orchestrator/src/container_runtime.rs
…
This will be important when running internally built docker images that reference relative paths. Supporting the [cwd](https://github.com/opencontainers/runtime-spec/blob/v1.0.2/config.md#process) key in the OCI filesystem bundle config also means we can support the significantly newer version of 1.0.2 (vs 0.2.0 previously)
=> Permit containers to set the working directory of the trusted application

Cargo.lock, oak_containers_hello_world_trusted_app/Cargo.toml, oak_containers_hello_world_trusted_app/build.rs, oak_containers_hello_world_trusted_app/proto/interface.proto, oak_containers_hello_world_trusted_app/src/app_service.rs, oak_containers_hello_world_trusted_app/src/main.rs, oak_containers_hello_world_untrusted_app/Cargo.toml, oak_containers_hello_world_untrusted_app/build.rs, oak_containers_hello_world_untrusted_app/src/app_client.rs, oak_containers_hello_world_untrusted_app/src/main.rs
This inverts the prior hello world example in which the trusted app implemented a gRPC client that invoked a gRPC service exposed by the untrusted app.
Now the trusted app exposes the service and the untrusted app invokes it, which is closer to a real world example of Oak Containers.
=> Oak Containers Hello World: Expose service in Trusted App

oak_containers_system_image/10-enp0s1.network, oak_containers_system_image/Dockerfile
Follow-up to #4154 -- the system now automagically renames `eth0` to `enp0s1`, so the configuration file needs a different name as well.
After this the network in the container is properly configured:
```
root@10:~# networkctl -a
IDX LINK   TYPE     OPERATIONAL SETUP     
1 lo     loopback carrier     unmanaged
2 enp0s1 ether    routable    configured
3 sit0   sit      off         unmanaged
3 links listed.
root@10:~# networkctl status enp0s1
● 2: enp0s1                                                                    
Link File: /usr/lib/systemd/network/99-default.link
Network File: /etc/systemd/network/10-enp0s1.network
State: routable (configured)
Online state: online                                         
Type: ether
Path: pci-0000:00:01.0
Driver: virtio_net
Vendor: Red Hat, Inc. …
```
=> Rename `eth0` configuration file to `enp0s1`

oak_containers_system_image/Dockerfile, oak_containers_system_image/oak-orchestrator.service
As I understand we currently don't use Docker, and even if we switch to a richer container manager in the future, it'd be something more lightweight than Docker. Hence, let's get rid of Docker in our system image.
Result: the (compressed) system image is now 31 MB in size. I'd call that a successful slimming down operation, as we started from a gigabyte.
=> Get rid of Docker in the system image

oak_containers_system_image/Dockerfile
Normally the root account has a disabled password, which means you can't log in a root. In most cases it won't matter as you won't be interactively log into the VM anyway.
However, to aid debugging, it sometimes makes sense to log in to poke around. #4151 adds a flag to expose the console via telnet; this change will make it possible to log in as `root` by forcing a password change when you try to do so.
Ref #4160
=> Force password change when trying to log in as root

cc/crypto/client_encryptor.cc, cc/crypto/encryptor_test.cc, cc/crypto/server_encryptor.cc
This PR temporarily disables C++ encryption to allow a breaking change.
Ref https://github.com/project-oak/oak/issues/4146
=> Temporarily disable C++ encryption

oak_containers_launcher/src/qemu.rs
Just to keep things in sync with your findings and ensure that the whole system keeps working with that turned off.
=> Set `rombar=0` on the virtio-net device

stage0_bin/supply-chain/audits.toml, stage0_bin/supply-chain/config.toml, stage0_bin/supply-chain/imports.lock
Reveiwed from https://sourcegraph.com/crates/zerocopy@v0.6.1
Fixes #3974
=> Vet zerocopy 0.6.1 as "safe-to-deploy"

.gitignore, oak_ml_transparency/mnist/Dockerfile, oak_ml_transparency/mnist/README.md, oak_ml_transparency/mnist/build.py, oak_ml_transparency/mnist/eval.py
This is the first step for an ML transparency demo.
Remaining work:
- Add CI steps to make sure the code here continues to work
- The eval script currently only prints out the accuracy, but it should be wrapped into a claim, and be signed and stored. A trusted runner will be responsible for doing this. The runner will be added in future PRs. As part of this we should also clarify the API for calling the evaluation script.
=> Add MNIST example for ML Transparency

cc/client/grpc_client_cli.cc, cc/transport/BUILD, cc/transport/grpc_streaming_transport.cc, cc/transport/grpc_streaming_transport.h, cc/transport/transport.h, oak_functions_launcher/tests/integration_test.rs
This PR makes Oak Functions integration test to run C++ gRPC client CLI.
Fixes https://github.com/project-oak/oak/issues/4069
=> Add C++ gRPC client to the Oak Functions integration test

.github/workflows/mnist_eval.yaml, buildconfigs/oak_ml_transparency_eval.toml, oak_ml_transparency/mnist/Dockerfile, oak_ml_transparency/mnist/README.md, oak_ml_transparency/mnist/build.py, oak_ml_transparency/mnist/eval.py
This PR:
- Updates the build.py and eval.py scripts for MNIST, and stores the result of the evaluation in an output file. 
- Enables CI for MNIST eval, and generates SLSA3 provenances for the result of the evaluation, on pull-request and workflow-dispatch (manual) events.
To be able to use the SLSA builder, I had to push the Docker image available in a registry. 
Roughly, I did the following steps (inspired by `scripts/docker_push`)
1. Build the image: `docker build -t europe-west2-docker.pkg.dev/oak-ci/mnist-eval/mnist-eval:latest .`
2. Push the image: `docker push europe-west2-docker.pkg.dev/oak-ci/mnist-eval/mnist-eval:latest`
3. Make the `mnist-eval` repository on artifact registry public. This is needed for GitHub Actions to be able to access the image.
=> Store MNIST evaluation result to file and enable CI

oak_containers_hello_world_container/Dockerfile
We don't need all of clear linux
=> Use a smaller linux distro for the oak containers example

stage0/src/zero_page.rs
We should always have done this, but I guess the DSDT under QEMU was small enough that we never stepped on this particular rake before. (As long as the DSDT is less than 1 page in size, or 4K, Linux was happy with it.)
=> Mark the EBDA as the ACPI memory region in the E820 map

linux_boot_params/src/lib.rs, oak_restricted_kernel/src/snp.rs, stage0/src/fw_cfg.rs, stage0/src/initramfs.rs, stage0/src/kernel.rs, stage0/src/lib.rs, stage0/src/zero_page.rs, testing/sev_snp_hello_world_kernel/src/main.rs
Stage 0 can now boot either an uncompressed 64-bit ELF kernel, or a 64-bit compressed Linux kernel using the bzImage format.
To boot using an ELF kernel, use the custom file paths in QEMU, e.g:
```
qemu-system-x86_64 -cpu host -enable-kvm -machine "microvm,acpi=on" -m 1G \
-nographic -nodefaults -no-reboot -serial stdio -bios "bin/stage0.bin" \
-fw_cfg "name=opt/stage0/elf_kernel,file=bin/vmlinux" \
-fw_cfg "name=opt/stage0/initramfs,file=bin/initramfs" \
-fw_cfg "name=opt/stage0/cmdline,string=console=ttyS0 quiet"
```
To boot using a bzImage kernel, use the normal QEMU direct-booting paramters, e.g.
```
qemu-system-x86_64 -cpu host -enable-kvm -machine "microvm,acpi=on" -m 1G \
-nographic -nodefaults -no-reboot -serial stdio -bios "bin/stage0.bin" \
-append "console=ttyS0 quiet" -kernel …
```
=> Add support for booting a bzImage Linux Kernel

stage0/src/zero_page.rs
When booting bzImage kernels older than v5.5 the setup header that is included in the kernel image is shorter. The mismatch in the sizes caused a crash.
We still want a crash if we get more data than expected, as that would indicate that we are dealing with a newer kernel version that we don't yet support.
=> Support booting older Linux kernels with Stage 0

stage0/src/zero_page.rs, stage0_bin/src/asm/boot.s
The Linux kernel assumes that the BIOS will not call pvalidate on the video ROM area just below the 1MiB boundary. We don't use any memory between 640KiB and 1MiB in stage 0, so we can avoid pvalidating it by:
- Only pvalidating memory up to 640KiB in the boot assembly
- Marking memory bewteen 640KiB and 1MiB as reserved in the E820 table so that our later code won't see it as valid memory that needs to be validated
=> Avoid pvalidating memory between 640Kib and 1MiB

kokoro/build_binaries_oak_containers.sh
Instead of the raw ELF `vmlinux` file, we will use the normal `bzImage`. Hence, include that in the list of files that are copied to Placer; removal of vmlinux from there will be in a follow-up PR once we no longer need it for tests.
=> Include `bzImage` with the Oak Containers generated binaries

.github/workflows/mnist_eval.yaml, java/src/main/java/com/google/oak/transport/BUILD, java/src/main/java/com/google/oak/transport/GrpcStreamingTransport.java, java/src/main/java/com/google/oak/transport/QueueingStreamObserver.java
Applies a condition similar to the one in provenance generation to disable building mnist-eval on pull-requests by default.
=> Disable building mnist-eval on pull-requests

stage0/src/sev.rs
DMA access in the fw_cfg device failed on SEV-SNP due to an RMP write violation. This was a side effect of calling pvalidate again on these pages after sharing them. It seems like the pages got into an unexpected state in the RMP due to this.
It is not clear why the GHCB was not affected by the same issue, but I have 2 guesses:
- It is written to by the VMM before we call pvalidate
- We register it as the GHCB in a separate call
Either way, if we avoid pvalidating the pages after sharing them it works fine.
=> Don't pvalidate memory twice

Cargo.lock, enclave_apps/Cargo.lock, linux_boot_params/Cargo.toml, oak_channel/Cargo.toml, oak_channel/src/frame.rs, oak_restricted_kernel/Cargo.toml, oak_restricted_kernel/src/mm/mod.rs, oak_restricted_kernel_bin/Cargo.lock, oak_restricted_kernel_interface/Cargo.toml, oak_restricted_kernel_interface/src/syscalls.rs, oak_sev_guest/Cargo.toml, oak_sev_guest/src/ghcb.rs, oak_sev_guest/src/instructions.rs, oak_sev_guest/src/msr.rs, oak_tdx_guest/Cargo.toml, oak_tdx_guest/src/vmcall.rs, oak_virtio/Cargo.toml, oak_virtio/src/queue/virtq.rs, oak_virtio/src/vsock/packet.rs, stage0/Cargo.toml, stage0_bin/Cargo.lock, testing/sev_snp_hello_world_kernel/Cargo.lock
The implementation of the `bitflags` crate changed between v1 and v2:
- `Copy`, `Clone`, `Debug`  and `PartialEq` are no longer derived by default
- The `bits` field is no longer accessible
- `FromBytes` cannot be derived on the default implementation
Fixes #4223
=> Update the bitflags crate

stage0_bin/supply-chain/audits.toml
Reviewed diff between `bitflags` v2.4.0 and v1.3.2 for "safe-to-deploy" and "does-not-implement-crypto"
Reviewed from https://sourcegraph.com/crates/bitflags/-/compare/v1.3.2...v2.4.0?visible=53
=> Vet `bitflags` v2.4.0

oak_client/src/lib.rs, oak_containers_hello_world_trusted_app/src/lib.rs, oak_containers_launcher/src/lib.rs, oak_functions_launcher/src/lib.rs, oak_remote_attestation/proto/v1/messages.proto, oak_remote_attestation_verification/src/rekor.rs, oak_remote_attestation_verification/src/tests.rs, oak_remote_attestation_verification/src/verifier.rs
Includes Rekor public key in the BinaryAttestation message. 
Rationale: Rekor may in future start using rolling keys. To be able to successfully verify the signature in a Rekor log entry, the client will need the public key at the time of the creation of the log entry. 
The client still needs to acquire to actual or the parent public key out of band, to be able to trust the key. 
The same applies to the endorser's public key. The log entry contains the public key with which the uploaded artifact was signed. The client still needs the actual or the parent public key to be able to verify the public key in the Rekor log entry.
The PR also splits the verification logic into two steps:
- Verify the signatures in the log entry, using the public keys coming from the server (either in the log …
=> Include rekor public key in BinaryAttestation message

stage0_bin/supply-chain/audits.toml
Reviewed `strum` v0.24.1 and `strum_macros` v0.24.3 as "safe-to-deploy" and "does-not-implement-crypto".
Reviewed from
- https://sourcegraph.com/crates/strum@v0.24.1
- https://sourcegraph.com/crates/strum_macros@v0.24.3
=> Vet `strum` v0.24.1 and `strum_macros` v0.24.3

stage0/src/acpi.rs, stage0/src/lib.rs
Second step in finding out how many CPUs we have on the machine: once we have the RSDP, find the reference to MADT (Multiple APIC Description Table) from that.
This is really starting to strain what's sensible in Rust, unfortunately. The XSDT has a dynamic length which is a pain to work with.
I hope that I've handled all the unsafety as safely as reasonably possible.
Ref #4235
=> Parse the XSDT and extract the location of MADT in stage0

oak_containers_launcher/src/lib.rs
Tokio's `timeout` provide a simpler mechanism for waiting on a future with a timeout rather than using a combination of `sleep` and `select`.
=> Use a tokio timeout instead of sleeping

stage0/src/acpi.rs, stage0/src/lib.rs, stage0/src/smp.rs
As the AP bootstrap code will be quite complicated, I think it warrants a file of its own.
For now if we fail to enumerate the APs I just log an error. This means that stage0 will still work even if you don't have ACPI tables available (or they are broken).
Also, while I'm in there, fix the X2APIC structure type identifier -- its 9; 16 was the length...
Ref #4235
=> Move the fledgling AP bootstrap code into a separate file.

stage0/Cargo.toml, stage0/src/kernel.rs, stage0/src/lib.rs, stage0/src/zero_page.rs
This change also switches the measurement to using SHA2-256 instead of SHA2-384 for now.
Ref #4074
=> Measure the kernel command line, setup data, and initial RAM disk

deny.toml
RUSTSEC-2023-0052 affects the `webpki` crate, which we indirectly depend on via `tonic`. It could lead to a denial of service is malicious TLS certificates are supplied. This does not directly affect us, since we don't use TLS certificates.
A fix has not been released, so created #4251 to update it once a fix is released.
=> Ignore RUSTSEC-2023-0052 for now

oak_sev_guest/src/guest.rs
These structs can be used with the guest message protocol to request derived keys from the secure processor on AMD SEV-SNP.
=> Add key derivation request and response structs

Cargo.lock, oak_restricted_kernel/Cargo.toml, oak_restricted_kernel/src/lib.rs, oak_restricted_kernel/src/payload.rs, oak_restricted_kernel/src/snp_guest.rs, oak_restricted_kernel/src/syscall/key.rs, oak_restricted_kernel/src/syscall/mod.rs, oak_restricted_kernel_bin/Cargo.lock, oak_restricted_kernel_interface/src/lib.rs
This change is currently untested.
It asks the secure processor (on AMD SEV-SNP) to derive a key from the intial launch measurement. It then uses and HKDF to derive a key based on this key and the application digest. The resulting application-specific key is available to enclave applications by reading on file descriptor 0x21.
=> Make derived key available via a file descriptor

oak_sev_guest/src/guest.rs
The incorrect message type caused key derivation to fail on AMD SEV-SNP.
=> Fix key response message type

justfile, kokoro/build_binaries_rust.sh
The simple-io version of the restricted kernel is not currently included in the list of generated binaries.
=> Add the simple-io version of the restricted kernel

Cargo.lock, enclave_apps/Cargo.lock, oak_channel/Cargo.toml, oak_channel/src/server.rs, oak_functions/examples/key_value_lookup/module/src/tests.rs, oak_functions_launcher/src/lib.rs, oak_functions_launcher/src/main.rs, oak_functions_service/Cargo.toml, oak_functions_service/proto/oak_functions.proto, oak_functions_service/src/instance.rs, oak_functions_service/src/lib.rs, oak_functions_service/src/wasm/mod.rs, oak_functions_service/tests/integration_test.rs, oak_iree_service/Cargo.toml, oak_iree_service/src/lib.rs, oak_remote_attestation/Cargo.toml, oak_remote_attestation/src/handler.rs, oak_restricted_kernel_bin/Cargo.lock, xtask/src/launcher.rs
Refactor the core logic of Oak Functions into a separate `OakFunctionsInstance` object. This object is still in the same crate as `OakFunctionsService` for now, but does not have any logic related to remote attestation nor encryption at all. Instead, that logic now only exists in the `OakFunctionsService` wrapper.
I changed the `InitializationState` from an enum to an `Option` so that it behaves like a proper functor (being able to use map and other methods on it).
`AttestationHandler` is changed to take an `FnOnce` and is expected to be constructed on the fly around a single invocation of an individual method, therefore it does not need to own the entire object being invoked, but can borrow a specific method when needed (and could be applied to several methods if necessary). The way …
=> Refactor Oak Functions to separate encryption

Cargo.lock, oak_containers_orchestrator/Cargo.toml, oak_containers_orchestrator/src/container_runtime.rs, oak_containers_orchestrator/src/ipc_server.rs, oak_containers_orchestrator/src/main.rs, oak_containers_system_image/oak-orchestrator.service
If the main process in the container exits we no longer need the orchestrator gRPC service to remain active.
This change also modifies the systemd service definition so that the VM shuts down if the orchestrator exits.
=> Shut down orchestrator if the container exits

.github/workflows/build_toolchain.yaml, .github/workflows/provenance.yaml, .github/workflows/reusable_provenance.yaml
This allows uploading the mapping from name to the resulting digest for the binary and the provenance directly in ent.
This required adding the functionality in ent to sign a mapping with a secret key, which is now provided as an additional secret to the repo.
Also add more sensible options to shell commands in GitHub actions.
Note that this commit changes the format of the digest to a base58 encoded multihash (see https://github.com/multiformats/multihash ). This allows for more flexibility in supporting different digests going forward, and also disambiguates existing hash functions; e.g. currently we use `sha256` but we really mean `sha2-256` -- as opposed to `sha3-256`, for instance; multihash makes this unambiguous and represented in binary form.
This means we may have to change the …
=> Create ent tag for provenance generation

Cargo.lock, stage0/Cargo.toml, stage0/src/allocator.rs, stage0/src/lib.rs, stage0_bin/.cargo/config.toml, stage0_bin/Cargo.lock
We need an allocator for short-term allocations in Stage 0 to support generationr of CBOR/COSE certificates. We have so far avoided using memory in the range between 1MiB and 2MiB, so I am using this as the location for the heap.f
I also renamed the `alloc` module to avoid conflicts with the alloc crate and `Allocator` to clarify the intended use.
=> Add short-term allocator to Stage 0

stage0/src/lib.rs, stage0/src/smp.rs, stage0_bin/layout.ld, stage0_bin/src/asm/ap_boot.s, stage0_bin/src/asm/boot.s, stage0_bin/src/asm/mod.rs
Although QEMU was fine with the AP bootstrap code being up high in the BIOS area, the docs do actually say (and some VMMs expect) the AP bootstrap code to be within the first megabyte.
To simplify things, I've set it up so that the AP bootstrap code (`.ap_text`) and any data it references (`.ap_bss`) land within the first 64K of memory, meaning that we don't have to deal with segments.
We also change the SEV-ES reset block to point to `ap_start` (but mind you that we can't bootstrap APs under SEV-ES yet as MMIO is not properly set up).
Ref #4235
=> Create a special sections for the 16-bit AP boot code and data

oak_sev_guest/src/ghcb.rs, oak_sev_guest/src/lib.rs
I've opted against being too clever with types here, as we only need to read u32-s in stage0 and thus don't need to mark read as unsafe as we're only dealing with them.
Otherwise, I've left in the `ghcb.reset()` for now.
Ref #4235
=> Add support for the MMIO Access protocol to oak_sev_guest

stage0/src/apic.rs, stage0/src/sev.rs
Instead of using `read_volatile` and `write_volatile` directly, unfortunately under SEV-ES we need to use the GHCB MMIO protocol.
To simplify the code I've also exposed the global GHCB static to the world. I think we should refactor all the code to use that instead of dragging the port factories through every piece of code, but that will be a future clean-up.
And, I think the APIC code itself now could use some clean-ups as well. But that's also for the future.
As of this PR stage0 should be able to wake up all the processors under all confidentiality modes, even if it doesn't park them correctly yet nor passes on the jump table.
Ref #4235
=> Use the GHCB MMIO protocol to talk to APIC under SEV-{ES,SNP}

oak_sev_guest/src/ap_jump_table.rs, oak_sev_guest/src/ghcb.rs, oak_sev_guest/src/lib.rs, oak_sev_guest/src/msr.rs
I've also added support for the AP Reset Hold MSR protocol, although we will likely not use this code as the hope is to keep the AP-s in 16-bit mode and thus we can't use Rust.
Ref #4235
=> Add AP Jump Table and related operations to `oak_sev_guest`

oak_sev_guest/src/secrets.rs, stage0/src/lib.rs, stage0/src/smp.rs, stage0_bin/layout.ld, stage0_bin/src/asm/ap_boot.s
This is enough to hand over APs to Linux under SEV-ES:
```
stage0 INFO: starting...
stage0 INFO: Expected number of APs: 1, started number of APs: 1
stage0 INFO: jumping to kernel at 0x0000000000200200
Linux version 6.1.33 (root@kokoro-gcp-ubuntu-docker-prod-423502096) (gcc (GCC) 12.3.0, GNU ld (GNU Binutils) 2.40) #1 SMP Wed Aug  9 15:45:05 UTC 2023
Memory Encryption Features active: AMD SEV SEV-ES
smp: Bringing up secondary CPUs ...
x86: Booting SMP configuration:
.... node  #0, CPUs:      #1
smp: Brought up 1 node, 2 CPUs
smpboot: Max logical packages: 1
smpboot: Total of 2 processors activated (9799.99 BogoMIPS)
```
After fixing the validation issue SEV-SNP starts up as well:
```
Memory Encryption Features active: AMD SEV SEV-ES SEV-SNP
smp: Bringing up secondary CPUs ...
x86: Booting …
```
=> Set up a jump table and the 16-bit code to park APs under SEV-ES/SNP

oak_containers_launcher/src/qemu.rs
We've done a lot of work to enable multiple cores in Oak Containers; let's run the tests with multiple CPUs as well.
Ref #4235
=> Run QEMU tests with 2 CPUs (and add a flag to add more)

stage0/src/apic.rs, stage0/src/lib.rs, stage0/src/msr.rs, stage0/src/sev.rs
Lots of stuff moving around, but conceptually just a big copy-paste in hopes of improving readability.
Accessing MSRs requires a different approach under SEV-ES/SNP. We had at least two independent implementations of that in stage0 (one for the APIC stuff, and one for MTRRs) -- this consolidates all of it into one common base struct, mirroring the `Msr` in `x86_64` crate, and moves all the MSR implementations themselves into one common file.
=> Consolidate all MSRs and operations on them into one file

enclave_apps/README.md, enclave_apps/oak_functions_enclave_app/README.md
This also fixes a broken link in the Oak Function Enclave App readme.
=> Add readme for enclave apps

stage0_bin/supply-chain/config.toml
We've added a bunch of crates as dependencies to stage0, so we should require `crypto-safe` from them as well. Unfortunately cargo-vet only requires `safe-to-deploy` by default, and there is no way to set a global default (unless that issue has been fixed recently).
Second, exempt `elf` as we're planning to get rid of it and thus there's no point in us spending time on auditing it.
Closes #3953
=> Update stage0 vetting config

.github/workflows/provenance.yaml, buildconfigs/oak_functions_insecure_enclave_app.toml, enclave_apps/oak_functions_enclave_app/Cargo.toml, enclave_apps/oak_functions_enclave_app/src/main.rs, justfile, kokoro/build_binaries_rust.sh, oak_functions_service/Cargo.toml, oak_functions_service/src/logger.rs
We should not be logging sensitive information in release builds of Oak Functions.
This change also restricts direct logging (e.g. in the oak_channel crate) to only log warnings and errors in release mode.
=> Update Oak Functions logger to only log in debug

stage0/src/cmos.rs, stage0/src/fw_cfg.rs, stage0/src/lib.rs, stage0/src/logging.rs, stage0/src/pic.rs, stage0/src/sev.rs, stage0/src/smp.rs, stage0/src/zero_page.rs
We have the GHCB as a static anyway, so there's no point in expliclity dragging it along in all the code that uses I/O ports.
This pattern is also used for MSRs (which also may need access to the GHCB), so it both simplifies the code and makes it more uniform.
=> Move IoPortFactory creation down to where we need it

stage0/src/acpi.rs, stage0/src/fw_cfg.rs
As we now have an allocator we can support an arbitrary number of commands.
Unfortunately we still have to rely on `unsafe`, but interestingly it now does the opposite cast of what it did previously.
=> Read ACPI romfile commands into a vector

stage0/src/lib.rs, stage0/src/sev.rs
Instead of managing sharing in the `Shared` struct, I thought it'd be better to introduce an allocator wrapper that will always return shared memory. This guarantees that (a) even if the data structure is not page-aligned, it will be the sole tenant on a page, and (b) if the data structure is bigger than a page, all of the pages it lands on will be properly marked as shared.
=> Store shared data structures in a Box instead of leaking memory.

oak_containers_launcher/src/qemu.rs, oak_containers_system_image/Dockerfile, oak_containers_system_image/root-passwd.service, oak_containers_system_image/serial-getty@.override.conf
Both the Linux kernel and systemd already treat the `debug` kernel flag as special, so I thought it'd be a good criteria for our debugging aides as well.
By default, this (a) doesn't reset the root password and (b) disables the `getty` services, which means you will neither get a login prompt on the serial nor if you did could you log on with `root`.
However, if you _do_ specify `debug`, then we both reset the root password and enable `getty`, which means you can log on over the serial console.
And, in the Oak Containers launcher, I've tied the debug condition to whether the serial is exposed over telnet or not as a debugging aide.
Ref #4160
=> Disable serial logins if Oak Containers is not started with `debug`

enclave_apps/Cargo.lock, justfile
The name interpolation format in the justfile was incorrect, meaning that the name of the enclave app wasn't used.
=> Fix justfile name interpolation

enclave_apps/Cargo.lock, oak_restricted_kernel_wrapper/.cargo/config.toml, oak_restricted_kernel_wrapper/src/asm/boot.s, oak_restricted_kernel_wrapper/src/elf.rs, oak_restricted_kernel_wrapper/src/main.rs, xtask/src/main.rs
This change resolves part of #4319 by making the wrapper binary position-independent.
=> Make the Restricted Kernel Wrapper relocatable

stage0/src/sev.rs
We have two functions, `share_page` and `unshare_page` to handle the sharedness of a page under SEV-{,ES,SNP}. Unfortunately the two are not perfectly symmetric: `share_page` removes the encrypted bit and if required (under SEV-SNP) changes the RMP state, whereas `unshare_page` unconditionally changed the RMP state.
After I introduced the "shared pages allocator" in #4318 sometimes we ended up calling `unshare_page` when just SEV was enabled, which obviously doesn't work.
This should fix the issue by making `unshare_page` a no-op when you're not calling it under SEV-SNP, meaning that if it is safe to call `share_page`, it's also safe to call `unshare_page`.
There are further questions in here about whether `unshare_page` should restore the encrypted bit to make it fully symmetric with …
=> Call `change_snp_page_state` only when really running under SEV-SNP

flake.nix, oak_containers_hello_world_container/build_container_bundle, scripts/export_container_bundle
Closes #4331. 
We currently use our own [script](https://github.com/project-oak/oak/blob/main/scripts/export_container_bundle) to save a docker containers as an OCI runtime bundles. 
Imo that approach a little bit brittle and hard to maintain, since our script has to manually ensure that all relevant properties from the docker container (eg entrypoint/CMD, uid, gid etc) are preserved. 
Thankfully we can replace it with existing prod grade tools. 
Specifically that's 
1) use docker to export a spec compliant OCI Image instead of just the filesystem
2) use OCI's [umoci](https://github.com/opencontainers/umoci) to convert that OCI Image to an OCI Runtime Bundle
=> Use existing tools to generate OCI Runtime Bundles

cc/client/client_test.cc, cc/crypto/BUILD, cc/crypto/encryption_key_provider.cc, cc/crypto/encryption_key_provider.h, cc/crypto/encryptor_test.cc, cc/crypto/server_encryptor.cc, cc/crypto/server_encryptor.h
This PR adds 2 new abstractions to the C++ crypto code:
- `EncryptionKeyProvider` that contains a key pair and generates contexts
- `RecipientContextGenerator` that is an interface for generating contexts. The main purpose for this interface is to allow generating contexts in the Oak Containers Orchestrator and abstracting it with the interface implementation
It also makes it more similar to our Rust crypto implementation.
=> Add encryption key provider to C++ crypto

enclave_apps/oak_functions_enclave_app/Cargo.toml
Because the `deny_sensitive_logging` feature is on by default on the `oak_functions_service` crate sensitive logging was disabled, even in the "insecure" version of the app.
=> Enable sensitive logging in insecure Oak Functions

cc/crypto/hpke/BUILD, cc/crypto/hpke/recipient_context.cc, cc/crypto/hpke/recipient_context.h, cc/crypto/hpke/recipient_context_test.cc
This PR adds deserialization for `RecipientContext` in C++.
Nore: Currently we have to serialize sequence numbers as well, since if we not include them, deserialization will restart them.
This change is required to allow generating crypto contexts in Oak Containers Orchestrator or Restricted Kernel and sending it to the C++ enclave application.
Ref https://github.com/project-oak/oak/issues/3841
=> Deserialize crypto context in C++

Cargo.lock, Cargo.toml, flake.nix, oak_containers/proto/interfaces.proto, oak_containers_launcher/src/qemu.rs, oak_containers_launcher/src/server.rs, oak_containers_orchestrator_client/Cargo.toml, oak_containers_orchestrator_client/src/lib.rs, oak_containers_syslogd/Cargo.toml, oak_containers_syslogd/README.md, oak_containers_syslogd/build.rs, oak_containers_syslogd/src/log_relay.rs, oak_containers_syslogd/src/main.rs, oak_containers_syslogd/src/systemd_journal.rs, oak_containers_system_image/Dockerfile, oak_containers_system_image/build.sh, oak_containers_system_image/journald.conf, oak_containers_system_image/oak-syslogd.service
As we've discussed, we don't really want to log over the (relatively slow) serial console for anything but truly critical situations where we can't rely on any other channel being available.
To that end, this PR creates a simple journal reader that will send logs to the launcher via gRPC.
In particular:
* The log entries themselves are just key-value pairs of strings. This follows what systemd (and syslog) do.
* I've built the log forwarder (or extractor, or whatever you want to call it) as a separate binary. The main reason for it is that I'm using the native systemd journal API, and that requires you to dynamically link against `libsystemd`. As the orchestrator itself is statically linked and uses musl, we can't rely on `libsystemd` there.
* On that note, nix is leaking. I had to use …
=> Forward non-critical log messages to the launcher via the gRPC interface

oak_launcher_utils/Cargo.toml, quirk_echo_launcher/Cargo.toml
The hope is that perhaps Dependabot can now start updating some of these dependencies.
=> Remove some pinned crate versions from `Cargo.toml` files

.github/workflows/ci.yaml, java/README.md, java/src/main/java/com/google/oak/transparency/BUILD, java/src/main/java/com/google/oak/transparency/EndorsementVerifier.java, java/src/main/java/com/google/oak/transparency/Failure.java, java/src/main/java/com/google/oak/transparency/LogEntryVerifier.java, java/src/main/java/com/google/oak/transparency/RekorLogEntry.java, java/src/main/java/com/google/oak/transparency/RekorSignatureBundle.java, java/src/main/java/com/google/oak/transparency/SignatureVerifier.java, java/src/test/java/com/google/oak/transparency/BUILD, java/src/test/java/com/google/oak/transparency/EndorsementVerifierTest.java, java/src/test/java/com/google/oak/transparency/LogEntryVerifierTest.java, java/src/test/java/com/google/oak/transparency/RekorLogEntryTest.java
- Split and renamed EndorsementVerifier class and added main() functions so they can be called from the command line
- Use `Optional<Failure>`  rather than `Result<Boolean, Exception>`
- Improved error handling during creation
- Fix a build breakage on copybara import
- Fix breakage in xtask Free disk space check
- Don't parse RekorLogEntry more than once
- Shortening in general
- Actual signature verification still not implemented
=> Refactor java endorsement verification.

java/src/main/java/com/google/oak/transparency/LogEntryVerifier.java, java/src/main/java/com/google/oak/transparency/SignatureVerifier.java
This is required so the reason why verification failed appears in the internal test log.
=> Use logging rather than System.err.

oak_crypto/proto/v1/BUILD, oak_remote_attestation/proto/v1/BUILD, oak_remote_attestation/proto/v1/dice.proto, oak_remote_attestation/proto/v1/service_unary.proto, oak_remote_attestation_verification/proto/v1/BUILD
This went undetected, even the copybara import did not flag this.
- Seems like the protoc compiler is happy, or the protos were not used yet
- TAP only considers *_binary and *_test targets (therefore we should have more tests, however trivial, just as the present build_test)
=> Add bazel build test for protocol buffers. Fix build.

flake.nix, oak_containers_orchestrator/Cargo.toml, oak_containers_orchestrator/src/container_runtime.rs, oak_containers_system_image/Dockerfile, scripts/export_container_bundle
Well, I say "properly", but this PR comes with a list of caveats a mile long, for example the `jq` hacks in the `export_container_bundle` that we need to fix properly.
However, it works, and has the added benefit of creating a proper systemd unit and cgroup for the container!
```
● 10.0.2.15
State: running
Units: 175 loaded (incl. loaded aliases)
Jobs: 0 queued
Failed: 0 units
Since: Wed 2023-10-11 17:44:44 UTC; 37s ago
systemd: 252.17-1~deb12u1
CGroup: /
├─init.scope
│ └─1 /init
└─system.slice
├─dbus.service
│ └─177 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
├─oak-orchestrator.service
│ ├─195 /bin/oak_containers_orchestrator
│ └─213 /bin/systemd-run --service-type=forking --property=PIDFile=/run/oakc.pid --wait --collect …
```
=> Run the container properly using `runc` instead of just forking

Cargo.lock, oak_containers_orchestrator/Cargo.toml, oak_containers_orchestrator/src/container_runtime.rs, oak_containers_orchestrator/src/lib.rs, oak_containers_orchestrator/src/main.rs, oak_containers_system_image/files/etc/systemd/system/oak-orchestrator.service, scripts/export_container_bundle
First steps in hardening the system.
systemd offers this neat feature, [`ProtectSystem=strict`](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#ProtectSystem=), which makes the whole file system hierarchy read-only, meaning the orchestrator can't write random files.
However, we do need to write _some_ things to the filesystem: namely, the container image itself and the IPC socket. To achieve that, [`RuntimeDirectory`](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#RuntimeDirectory=) to the rescue: it creates a directory under `/run` for us to use.
This PR plumbs a lot of that infrastructure through the orchestrator itself. The trusted application should see no change; this is one step in one day dropping the root privileges for both the container and …
=> Isolate orchestrator from system and use systemd `RuntimeDirectory`

oak_containers_system_image/build.sh, oak_containers_system_image/files/etc/hosts
We build the sysimage from the Docker container, which assumes `/etc/hosts` will be bind-mounted from the host. But we're not using it as a container, we're using it as a proper host image.
The "correct" solution here would be _not_ to use Docker at all, as there may be other surprises lurking in there, but rather use something like `debootstrap` to create the system image as that tool is designed for installing Debian properly. However, switching to debootstrap is not an easy task, especially if you want to do it in a rootless environment.
Hence, for now, let's add a hack.
=> Add `/etc/hosts` to sysimage by hand.

oak_containers_system_image/build.sh
I broke the permissions in #4367 partly intentionally (I fixed the permissions and expected git to track them) and partly inadvertently (git doesn't.)
Building the system image worked for me until I started jumping around branches, at which point the permissions broke and `/etc/` ended up world-unreadable, with surprisingly little consequences -- apart from the network not coming up as expected.
=> Fix file permissions in the generated system image

oak_containers_orchestrator/src/container_runtime.rs, oak_containers_orchestrator/src/main.rs, oak_containers_system_image/files/etc/systemd/system/oak-orchestrator.service
Preliminary steps toward setting `ProtectSystem=strict` on for `runc` as well: much like in the orchestrator unit file, use the systemd magic to generate a directory under `/var/run` for `runc` to store things in.
As a side effect, we no longer need to store the PID file in the (dynamically allocated) orchestrator runtime directory, which means we can remove code related to that.
=> Segregate `runc` into its own runtime directory

Cargo.lock, oak_containers_orchestrator/Cargo.toml, oak_containers_orchestrator/src/container_runtime.rs, oak_containers_orchestrator/src/ipc_server.rs, oak_containers_orchestrator/src/lib.rs, oak_containers_orchestrator/src/main.rs, oak_containers_system_image/files/etc/sysusers.d/oak.conf, scripts/export_container_bundle
This will create a new user, `oakc`, for the container and overrides all UID mappings to point to the newly created user.
It's a bit less than perfect as I had to remove `--systemd-cgroup` from runc which means the cgroups are not properly propagated to the systemd level, but there's some complexity around `dbus` I need to read up about and I wasn't able to get it to work right now.
However, for our current use, it's mostly cosmetic anyway.
=> Run the container rootless under a nonprivileged user

Cargo.lock, oak_containers_launcher/Cargo.toml, oak_containers_launcher/src/server.rs, oak_containers_orchestrator_client/Cargo.toml, oak_containers_syslogd/Cargo.toml, oak_containers_syslogd/src/log_relay.rs
We use the opentelemetry APIs for metrics already, but it has other facilities, like logging (and tracing -- but that will need more thought).
This PR migrates the Github bits from the method in the Launcher interface to opentelemetry APIs.
The end goal is to provide a more standardised interface to the enclave: opentelemetry comes with client libraries (and integrations!) in several languages, hopefully lowering the barrier to adoption.
=> Opentelemetrification, vol 2: use the opentelemetry log APIs.

Cargo.lock, oak_dice/Cargo.toml, oak_dice/src/cert.rs, oak_dice/src/lib.rs, stage0/Cargo.toml, stage0/src/dice_attestation.rs, stage0_bin/Cargo.lock, stage0_bin/build.rs
Many parts of the existing Stage 0 DICE certificate generation code can be reused for other boot stages. This change refactors the code so that the reusable parts can be moved to a shared crate (oak_dice).
=> Extract reusable components from Stage0 DICE code

oak_containers_orchestrator/src/container_runtime.rs, scripts/export_container_bundle
This is a bit less than ideal -- the correct answer here would be to route the console over a unix socket -- but has the benefit of being simple and it works.
=> Enable a pty for runc so that trusted application stdout isn't dropped

linux_boot_params/src/lib.rs, oak_dice/src/evidence.rs, oak_restricted_kernel_bin/Cargo.lock, stage0/Cargo.toml, stage0/src/dice_attestation.rs, stage0/src/lib.rs, stage0/src/zero_page.rs, stage0_bin/build.rs
This PR is a step towards propagating the DICE data from Stage 0 to the next stage. The following features will be added in follow-up PRs:
- Marking the memory range of the Stage0 DICE data as a special reserved region in the E820 table so the the next stage can find the data
- Actually generating a real attestation report when running on AMD SEV-SNP
- Adding support for sealing key derivation
=> Generate the DICE data struct in Stage 0

oak_restricted_kernel/src/syscall/dice_data.rs
addresses https://github.com/project-oak/oak/pull/4377#discussion_r1361345702
I'm unsure if this is the right way.
Pro: I think zeroing out the private key is a good idea, and I think it should be done automatically once its been read.
Con: The stateful behavior of this descriptor is different from all other ones. They're stateless and always read from 0
=> zero out DiceData after reading it and keep state

Cargo.lock, oak_containers/proto/interfaces.proto, oak_containers_launcher/src/server.rs, oak_containers_orchestrator_client/Cargo.toml, oak_containers_orchestrator_client/src/lib.rs
We've moved to the opentelemetry APIs, so this is now unused.
=> Remove the `Launcher::Log` RPC

oak_restricted_kernel/src/interrupts.rs
Just extra information for debugging, as we will crash anyway.
=> Print our `MXCSR` error flags when encountering `#XF` exception

oak_restricted_kernel/src/syscall/dice_data.rs, oak_restricted_kernel/src/syscall/fd.rs, oak_restricted_kernel/src/syscall/key.rs, oak_restricted_kernel/src/syscall/mod.rs, oak_restricted_kernel/src/syscall/tests.rs
~Review once https://github.com/project-oak/oak/pull/4384 is merged.~
Now all FDs keep an inner state that tracks how much they've been read. Subsequent reads return the subequent bytes. If the FD has been read to end, no bytes are copied on subsequent reads.
If we want to permit mulitple reads in the future, we should add a seek method to permit the app manipulate the state of the FD.
=> Make all FD reads behave consistently & idiomatically

oak_restricted_kernel/src/avx.rs
The Oak Restricted Kernel does not provide custom floating-point exception handlers to resolve problems that might occur, so we mask the exceptions so that we fall back on the default behaviour so that we don't shut down the entire VM due to a loss of precision or underflow when an application does floating point arithmetic.
=> Set initial FPU state and mask SIMD FP exceptions

cc/client/BUILD, cc/client/client.cc, cc/client/client_test.cc, cc/crypto/client_encryptor.cc, cc/crypto/client_encryptor.h, cc/crypto/server_encryptor.cc, cc/crypto/server_encryptor.h, cc/transport/BUILD, cc/transport/grpc_streaming_transport.cc, cc/transport/grpc_streaming_transport.h, cc/transport/transport.h
This PR makes the C++ crypto library use explicit `oak_crypto` messages.
=> Use explicit crypto protos in C++ crypto library

Cargo.lock
The dependency tree has some duplicated crates. For example, tonic v0.8.3 and v0.9.2 co-exists. We can do some clean ups to keep the dependency tree tidy and reduce the size of TCB.
The proposed change
- Removed tonic v0.8.3 (11k sloc)
- Removed tracing-futures v0.2.5 (1k sloc)
- Upgraded tonic-web v0.5.0 -> v0.9.2, tower-http v0.3.5 -> v0.4.4
- Removed digest v0.9.0 and v0.10.6, added digest v0.10.7
- Upgraded hpke v0.10.0 to v0.11.0
- Removed rand_core v0.5.1
- Added fiat-crypto v0.2.1 platforms v3.1.2 rustc_version v0.4.0
- Updated subtle v2.4.1 to v2.5.0 universal-hash v0.5.0 to v0.5.1
- Updated x25519-dalek v2.0.0-pre.1 to v2.0.0
- Updated hermit-abi v0.3.1 (yanked) to v0.3.3
=> Dependency clean ups

Cargo.lock, oak_functions_containers_app/Cargo.toml, oak_functions_containers_app/build.rs, oak_functions_containers_app/src/lib.rs, oak_functions_containers_app/src/main.rs, oak_functions_service/src/wasm/mod.rs
This is to be the first step in a longer process, but it compiles!
There are _many_ issues here:
- the `OakFunctionsServce` is wrapped in a mutex, which precludes any kind of concurrency we may want to exploit
- `oak_functions_service` has logic and `micro_rpc`-specifics mixed together, so either (a) use of `micro_rpc` needs to be excised from there and banished to the Restricted Kernel-specific crate, (b) gRPC needs to be an optional dependency of `oak_functions_service`, or (c) the crate needs to be split into two (three?) crates: one with core functionality, one with `micro_rpc` specifics, and one with gRPC specifics.
- obviously the attestation, it does nothing!
- tests
Ref #4409
=> Hook `oak_functions_servce` into `oak_functions_containers_app`

Cargo.lock, oak_functions_service/Cargo.toml, oak_functions_service/src/instance.rs, oak_functions_service/src/lib.rs
This might actually be everything that's needed to make `OakFunctionServce` thread-safe.
The `LookupDataManager` uses locking internally to guarantee safety (and thus doesn't require `&mut self), and `WasmHandler` just clones a lot of stuff and as long as `wasm_api_factory` is thread-safe, it should be golden there as well.
The only potential race condition is when `initialize` is called concurrently; to avoid that, I've used `oak_core::sync::OnceCell` to ensure that the initialization is guaranteed to happen once.
Ref #4409
=> Remove unnecessary `&mut`-s and use `OnceCell` in `oak_functions_service`

oak_containers_stage1/src/main.rs, oak_dice/src/evidence.rs, stage0/src/dice_attestation.rs, stage0/src/kernel.rs, stage0/src/lib.rs, stage0/src/zero_page.rs
To make sure we can find the DICE data from Stage 0 in the next boot stage this change adds two features:
- The address of the DICE data is appended as a kernel command-line argument
- The restricted kernel can read this parameter directly
- The Linux kernel will ignore this parameter, and pass it as a command-line parameter to the init process (Stage1 in Oak Containers)
- A magic number at the start of the `Stage0DiceData` struct so that the next stage can check that the address points to an expected data structure
=> Send Stage 0 DICE Data address to the next stage

oak_functions_service/src/instance.rs, oak_functions_service/src/lib.rs
We have a `Vec` that is used only once, but we pass it as a slice and create of the copy of the contents. It'll be more efficient to just move the vector itself around.
=> Elide an unnecessary copy in `OakFunctionsInstance`

micro_rpc/build.rs, micro_rpc_build/src/lib.rs, micro_rpc_tests/build.rs, oak_crypto/build.rs, oak_functions_launcher/build.rs, oak_functions_sdk/build.rs, oak_functions_service/build.rs, oak_functions_service/src/lib.rs, oak_iree_service/build.rs, oak_remote_attestation/build.rs, oak_tensorflow_service/build.rs, quirk_echo_launcher/build.rs, quirk_echo_service/build.rs, testing/oak_echo_service/build.rs
This will make it possible to call methods from a Tonic handler, as `&self` is all we get there and we want to get rid of the `Mutex` there.
Ref #4409
=> Support generating interfaces with non-mutable references with microrpc

oak_functions_containers_app/src/lib.rs
This should mean that we're now able to serve multiple incoming invocations in parallel!
Ref #4409
=> Get rid of the `Mutex` around `OakFunctionsService`

Cargo.lock, oak_client/Cargo.toml, oak_client/src/lib.rs, oak_client/src/transport.rs
This PR makes the Rust client library use explicit `oak_crypto` messages.
=> Use explicit crypto protos in Rust client library

Cargo.lock, oak_functions_containers_app/Cargo.toml, oak_functions_containers_app/build.rs, oak_functions_containers_app/src/lib.rs, oak_functions_containers_app/src/main.rs, oak_functions_containers_app/tests/integration_test.rs
This is a really basic test that fires up the gRPC server and tries to initialize Oak Functions. Nothing too complicated.
Ref #4409
=> Add a integration test to `oak_functions_containers_app`

Cargo.lock, oak_client/src/lib.rs, oak_client/src/transport.rs, oak_functions_containers_app/build.rs, oak_functions_containers_launcher/Cargo.toml, oak_functions_containers_launcher/build.rs, oak_functions_containers_launcher/src/lib.rs, oak_functions_launcher/Cargo.toml, oak_functions_launcher/benches/integration_benches.rs, oak_functions_launcher/build.rs, oak_functions_launcher/src/lib.rs, oak_functions_launcher/src/server.rs, oak_functions_service/build.rs, oak_functions_service/proto/oak_functions.proto, oak_functions_service/src/lib.rs, oak_functions_service/tests/integration_test.rs, oak_remote_attestation/build.rs, oak_remote_attestation/proto/v1/messages.proto, oak_remote_attestation/src/lib.rs
This PR adds explicit `oak_crypto` messages to `oak_functions.proto` and `messages.proto` but doesn't remove the old serialized fields yet.
=> Add explicit crypto proto messages to Oak services

oak_containers_launcher/src/qemu.rs, oak_containers_syslogd/src/main.rs, oak_functions_containers_launcher/src/lib.rs
If there's ever a fault, right now the `oak_functions_containers_launcher` can hang, with the only symptom that something is going wrong being that the code in the enclave will complain that it can't send logs to the launcher.
This is because of the following sequence of events:
1. Something fails, like `untrusted.app_initialize_enclave()?` in the launcher
2. Because of the `?`, the control flow wants to return, which means in turn it starts cleaning up the stack, which means dropping the `untrusted_app` itself
3. In the `untrusted_app`, it starts dropping the launcher
4. In the launcher, the gRPC server is successfully shut down (and dropped), but dropping `qemu` fails as it's still running.
Net result: the launcher gRPC server is down, so nothing in the enclave can talk to the launcher, …
=> Improve shutdown behaviour in oak_functions_containers_launcher

oak_containers/proto/interfaces.proto, oak_containers_orchestrator/src/control_plane.rs, oak_containers_orchestrator/src/key_provisioning.rs, oak_containers_orchestrator/src/lib.rs
This PR adds a Key Provisioning service definition for communication from the Hostlib to the Orchestrator.
=> Add Orchestrator Key Provisioning service definition

Cargo.lock, oak_functions_containers_launcher/Cargo.toml, oak_functions_containers_launcher/src/lib.rs, oak_functions_containers_launcher/src/main.rs, oak_functions_containers_launcher/src/server.rs
Yet again it mostly clones what's in `oak_functions_launcher`, but now there should be enough infrastructure there that I can start looking at porting over the tests.
And after that, there will need to be a lot of cleaning up.
Ref #4409
=> Run a RPC server in oak_functions_containers_launcher

oak_functions_containers_launcher/src/server.rs, oak_functions_launcher/benches/integration_benches.rs, oak_functions_launcher/src/server.rs, oak_functions_service/src/lib.rs, oak_functions_service/tests/integration_test.rs, oak_remote_attestation/src/handler.rs
This PR adds explicit `oak_crypto` messages to Oak Rust enclaves.
=> Add explicit crypto proto messages to Oak Enclaves

cc/transport/grpc_streaming_transport.cc, java/src/main/java/com/google/oak/server/EncryptedStreamObserver.java, java/src/main/java/com/google/oak/transport/GrpcStreamingTransport.java, java/src/test/java/com/google/oak/transport/GrpcStreamingTransportTest.java, oak_client/src/transport.rs
This PR adds explicit `oak_crypto` messages to Oak Rust, C++ and Java clients.
=> Add explicit crypto proto messages to Oak Clients

Cargo.lock, kokoro/run_tests.sh, oak_functions_containers_launcher/Cargo.toml, oak_functions_containers_launcher/src/main.rs, oak_functions_containers_launcher/tests/integration_test.rs, xtask/Cargo.toml, xtask/src/containers.rs, xtask/src/lib.rs
We now run the basic end-to-end tests that we do with plain Oak Functions with Oak Functions on Oak Containers as well.
As always, this could use a ton of cleaning up, but... the tests are there, and more importantly, they pass!
Ref #4409
=> Port basic integration tests to Oak Functions Containers launcher

oak_functions_service/src/instance.rs, oak_functions_service/src/lookup.rs
1. We start with the proto, iterate over field values in there, turn the result into a `HashMap` (via `collect()`)... only to then iterate over the same `HashMap` to merge data into the main hashmap inside `LookupDataManager`. This optimizes away the extra `HashMap` by just passing iterators around.
2. Get rid of the `unwrap()` in the `to_data()` function that can cause a crash, and instead return a proper RPC error if something is wrong.
=> Micro-optimization: elide one copy of data when loading lookup data

oak_functions_service/src/lookup.rs, oak_functions_service/src/wasm/api.rs
1) I think the message we printed when loading lookup data is wrong: we set `next_data_len` to be the size of the new lookup data, then proceed to update `data` , and _after that_ look up the size and say it's the old size. I don't think it is what it says it is.
2) in the wasm api when we log the lookup key and value, we truncate them to 512 bytes. Doing it via slices is simpler and elides a copy (because of `.collect()`).
(Note: I'm not seeking out these minor things on purpose, but rather I'm trying to understand how all of it fits together and while I'm in that file anyway I might as well fix some minor issues I see.)
=> Minor fix and optimization to wasm API

Cargo.lock, oak_restricted_kernel_bin/Cargo.lock
The version of `self_cell` that we have been using has been yanked, so updating it to resolve a new `cargo-deny` failure.
=> Update `self_cell` to resolve `cargo-deny` error

stage0_bin/.cargo/config.toml
Fixes #4460
It turns out the problem was with random number generation (generating a new dice key). If the `rdrand` compiler feature is not enabled it looks like the code does a CPUID call to check whether RDRAND is supported. Since we don't have a #VC handler in Stage 0 this crashes on SEV-ES and SEV-SNP.
=> Fix Stage 0 crashes on SEV-ES and SNP

Cargo.lock, oak_containers_hello_world_trusted_app/Cargo.toml, oak_containers_hello_world_trusted_app/src/app_service.rs, oak_containers_hello_world_trusted_app/src/orchestrator_client.rs, oak_crypto/src/encryptor.rs, oak_crypto/src/tests.rs, oak_functions_containers_app/Cargo.toml, oak_functions_containers_app/src/orchestrator_client.rs, oak_remote_attestation/src/handler.rs
This PR adds:
- `AsyncEncryptionHandler` to be used in Oak Containers in conjunction with the Orchestrator client
- Logic for requesting the session key from the Orchestrator to Oak Functions Containers
Though we will still need to add this to Oak Functions Service. And because of how Rust works, we cannot have the same version that works for both sync and async. So we might need to reimplement Oak Functions Service in an async fashion.
=> Add Orchestrator encryption key generation in Oak Functions

Cargo.lock, oak_client/Cargo.toml, oak_client/src/lib.rs, oak_client/src/transport.rs, oak_containers/proto/interfaces.proto, oak_containers_hello_world_untrusted_app/src/main.rs, oak_containers_hello_world_untrusted_app/tests/integration_test.rs, oak_containers_launcher/src/lib.rs, oak_containers_launcher/src/server.rs, oak_containers_orchestrator_client/src/lib.rs, oak_functions_containers_launcher/src/server.rs, oak_functions_launcher/Cargo.toml, oak_functions_launcher/src/lib.rs, oak_functions_launcher/src/server.rs, oak_remote_attestation/proto/v1/BUILD, oak_remote_attestation/proto/v1/messages.proto, oak_restricted_kernel_bin/Cargo.lock
Add `dice_evidence` to the `AttestationBundle` and deprecates `AttestationEvidence`.
This is an intermediate step to allow us to swith from `AttestationEvidence` to DICE `Evidence`. `AttestationEvidence` will be removed once nothing depends on it anymore.
=> Deprecate AttestationEvidence, add DICE Evidence

proto/attestation/endorsement.proto
The transparent release endorsement message needs to include the signature for the endorsement of the underlying binary
=> Add endorsement signature to the transparent release endorsement.

oak_crypto/src/encryptor.rs, oak_functions_containers_app/src/lib.rs, oak_functions_containers_app/src/main.rs, oak_functions_containers_app/tests/integration_test.rs, oak_functions_containers_launcher/src/main.rs, oak_remote_attestation/src/handler.rs
This _should_ allow the sync code the rely on async code. Emphasis on _should_, we'll see what the tests think of this.
I've left the existing `encryption_key_provider` as-is for now; it's only used in the `initialize` call. Per Conrad, the attestation report (and public key) we return there should be unused; I'll see about ripping that out (and returning an empty proto) in a follow-up PR.
=> Bridge the gap between sync and async universes in `OrchestratorClient`

oak_functions_containers_app/src/lib.rs, oak_functions_containers_app/src/main.rs, oak_functions_containers_app/tests/integration_test.rs
We no longer rely on information in the `InvokeResponse`, drop all the code (including the attestation report generator) that managed that.
Plus, drop an `Arc` around the instance that's not needed + rename `orchestrator_client` to something more readable.
=> Remove attestation and public key code + minor clean-ups

java/src/main/java/com/google/oak/verification/MainVerifier.java, java/src/test/java/com/google/oak/verification/MainVerifierTest.java, proto/attestation/endorsement.proto, proto/attestation/reference_value.proto
InitLayerEndorsements doesn't reflect well which components the endorsements refer to, and the binary field is too generic. Renaming to more descriptive names
=> Rename InitLayerEndorsements and the binary field

oak_functions_containers_app/src/lib.rs, oak_functions_containers_app/src/main.rs, oak_functions_containers_app/src/orchestrator_client.rs, oak_remote_attestation/src/handler.rs
Mostly just more efficient use of `anyhow` (instead of formatting bazillions of strings), but also one meaningful change:
The `EncryptionHandler::invoke` had an `expect()` in it, which means that if someone sends an RPC with no public key, the server will promptly crash.
The server should _never_ panic on invalid user input, otherwise this provides a way how to DoS the server. This replaces the `expect` with proper error propagation, which should fail the RPC (but keep the server alive for other requests).
=> Clean up some of the error handling code in Oak Functions

oak_sev_guest/src/instructions.rs, stage0/src/lib.rs, stage0/src/sev.rs
This is a better fix for the unsharing issues I mentioned in #4503.
When sharing and unsharing pages we didn't run pvalidate on them again. This meant that the pages ended up in a non-validated state and the Linux kernel crashed when trying to reuse these pages. We perviously got away with it because the other pages we shared were in a range that the Linux kernel did not try to reuse.
=> Revalidate pages after un-sharing

oak_crypto/proto/v1/crypto.proto, oak_crypto/src/encryptor.rs, oak_crypto/src/hpke/mod.rs, oak_crypto/src/tests.rs
This PR makes Rust Crypto send nonces in Proto messages.
This PR is part of a non-breaking change aimed to implement random nonces for Hybrid Encryption.
For now we send deterministic nonces, but once we make sure that code uses nonces from the proto instead of computing them, we can swap nonces for random ones.
=> Send nonces in Rust Crypto

Cargo.lock, enclave_apps/oak_functions_enclave_app/src/main.rs, oak_dice/src/cert.rs, oak_functions_containers_app/build.rs, oak_functions_containers_launcher/Cargo.toml, oak_functions_containers_launcher/build.rs, oak_functions_containers_launcher/src/lib.rs, oak_functions_launcher/benches/integration_benches.rs, oak_functions_launcher/src/main.rs, oak_functions_service/src/lib.rs, oak_functions_service/tests/integration_test.rs, oak_restricted_kernel_api/src/dice.rs, proto/oak_functions/service/oak_functions.proto
This change adds supports for using DICE evidence in the Restricted Kernel version of Oak Functions.
It also deprecates the `PublicKeyInfo` message, which is still needed untill we have a DICE verification library, but will be removed when clients no longer rely on direclty fetching the public key.
=> Use DICE evidence in Oak Functions

cc/crypto/client_encryptor.cc, cc/crypto/encryptor_test.cc, cc/crypto/hpke/jni/com_google_oak_crypto_hpke_RecipientContext.h, cc/crypto/hpke/jni/com_google_oak_crypto_hpke_SenderContext.h, cc/crypto/hpke/jni/context_jni.cc, cc/crypto/hpke/jni/jni_helper.cc, cc/crypto/hpke/recipient_context.cc, cc/crypto/hpke/recipient_context.h, cc/crypto/hpke/recipient_context_test.cc, cc/crypto/hpke/sender_context.cc, cc/crypto/hpke/sender_context.h, cc/crypto/hpke/sender_context_test.cc, cc/crypto/server_encryptor.cc, java/src/main/java/com/google/oak/crypto/ClientEncryptor.java, java/src/main/java/com/google/oak/crypto/ServerEncryptor.java, java/src/main/java/com/google/oak/crypto/hpke/RecipientContext.java, java/src/main/java/com/google/oak/crypto/hpke/SenderContext.java, java/src/test/java/com/google/oak/crypto/EncryptorTest.java
This PR makes C++ and Java Crypto send nonces in Proto messages.
This PR is part of a non-breaking change aimed to implement random nonces for Hybrid Encryption.
For now we send deterministic nonces, but once we make sure that code uses nonces from the proto instead of computing them, we can swap nonces for random ones.
=> Send nonces in C++ and Java Crypto

Cargo.lock, micro_rpc_build/src/lib.rs, oak_functions_sdk/tests/integration_test.rs, oak_functions_service/Cargo.toml, oak_functions_service/build.rs, oak_functions_service/src/instance.rs, oak_functions_service/src/lookup.rs, oak_functions_service/tests/integration_test.rs
`Bytes` is a data structure that is cheap to copy, as it effectively is an `Arc` to a buffer in memory, and thus you don't actually need to clone the data.
This is, again, in quest of efficiency: experimentation suggests up to 15% increase in performance.
=> Use `bytes::Bytes` instead of `Vec<u8>` in lookup data map

.github/workflows/reusable_provenance.yaml
* Bug fix: Change artifact suffix from .sigstore to .builder.slsa
* Bug fix: Don't put crucial commands inside an echo since failure will not trigger the `errexit` (if set). See https://github.com/project-oak/oak/actions/runs/7064214967/job/19231936581, where the step before the failing step contains the actual failure
* Better quoting
* Shorten long comment lines to 80 cols
Not 100% clear if this fixes the failure behind the link, but it is a promising attempt.
=> Fix provenance generation.

enclave_apps/Cargo.lock, oak_functions_containers_app/src/lib.rs, oak_functions_service/src/instance.rs, oak_functions_service/src/lib.rs, oak_functions_service/src/lookup.rs, proto/oak_functions/service/oak_functions.proto
Evidence suggests that reserving space in the map before streaming in the entries can shave ~10% off the runtime, presumably because the `HashMap` doesn't have to keep re-allocating more space as entries are added to it.
It's totally optional to call it though; the system will work just fine if you don't pre-allocate space.
=> Add a method to pre-reserve space for the lookup data entries

oak_containers_orchestrator/src/logging.rs
As it stands, the orchestrator is duly sending _all_ of its log entries to syslog. That is fine.
Unfortunately tonic likes to be really verbose on the trace level; we don't need all of that.
Case in point, you often see journald complaining about the verbosity of the orchestrator:
```
Suppressed 529629 messages from oak-orchestrator.service
```
I'm not sure we want ~half a million log entries every time we do a couple of RPCs.
=> Log less in the orchestrator

oak_containers_launcher/src/lib.rs, oak_containers_launcher/src/qemu.rs, oak_containers_orchestrator/src/main.rs
This PR creates port forwarding from host to the VM in order to access the Orchestrator Key Provisioning service.
=> Forward host to Orchestrator port

oak_ml_transparency/runner/Cargo.lock
This is currently failing because of yanked crates
See https://github.com/project-oak/oak/actions/runs/7113465489/job/19365472089#step:5:2897
Ref #4534
=> Update deps for oak_ml_transparency

Cargo.lock, oak_functions_containers_app/Cargo.toml, oak_functions_containers_app/src/lib.rs
Tracing: it's like logging, but more clever.
This modification doesn't do much right now as we don't log anything (for now), but it adds a `Span` that can hold extra context; for example, which RPC service and method is being invoked.
It'll allow for log messages to contain more context in the future, e.g.:
```
2023-12-05T21:25:00.173017Z  INFO request{rpc.method="StreamLookupData" rpc.service="oak.functions.OakFunctions" rpc.system="grpc" server.address="[::1]" server.port=48951}: oak_functions_service::lookup: Start replacing lookup data by next lookup data
2023-12-05T21:25:00.173356Z  INFO request{rpc.method="StreamLookupData" rpc.service="oak.functions.OakFunctions" rpc.system="grpc" server.address="[::1]" server.port=48951}: oak_functions_service::lookup: Finished replacing lookup …
```
=> Create `tracing::Span` for each incoming RPC

enclave_apps/Cargo.lock, scripts/common, scripts/git_check_diff
The fix is to add the repo to the list of safe folders.
Also reorder bash common options to start with `xtrace` so they all logged
correctly.
Ref #4538
=> Fix git diff check

Cargo.lock, enclave_apps/Cargo.lock, enclave_apps/oak_functions_enclave_app/src/main.rs, oak_crypto/Cargo.toml, oak_crypto/proto/v1/crypto.proto, oak_crypto/src/signer.rs, oak_restricted_kernel_bin/Cargo.lock, oak_restricted_kernel_sdk/src/dice.rs, oak_restricted_kernel_sdk/src/lib.rs
Previously we would expose the signign key directly, now it's behind a struct whose only public method is a sign.
Tracking http://b/314749025 and http://b/312897453.
The implementation is slightly different from what is outlined in the bugs. Specifically the bug propsed implementing a create method directly Signer struct, which would call directly into the kernel to fetch the key.
This isn't feasible dice data can only be read from the restricted kernel once and only read at once. Hence a create method is used for the overarching DiceWrapper struct.
If we want to maintain the orginally proposed interface, we could store the dice data seperately in memory for the application, and read ot from there whenever a new struct is created. A perhaps more ergonimic but also more complex and magical …
=> Impl signing crypto oracle in the restricted kernel sdk

oak_attestation_verification/src/verifier.rs, oak_attestation_verification/tests/verifier_tests.rs, proto/attestation/endorsement.proto
- Extend endorsements and reference values so that they are in a 1:1 correspondence w.r.t. subfields
=> Explode verification of transparent release endorsements to cover all cases.

Cargo.lock, enclave_apps/Cargo.lock, enclave_apps/Cargo.toml, enclave_apps/oak_functions_enclave_app/Cargo.toml, enclave_apps/oak_functions_enclave_app/src/main.rs, oak_crypto/Cargo.toml, oak_crypto/src/encryptor.rs, oak_restricted_kernel_bin/Cargo.lock, oak_restricted_kernel_sdk/Cargo.toml, oak_restricted_kernel_sdk/src/dice.rs, oak_restricted_kernel_sdk/src/lib.rs
The SDK should be agnostic about which underlying attesation method is used. Hence dice related structs are removed. oak functions still depends on them, so the relevant code has been moved to continue supporting it. In the future it should be refactored to use the SDK.
=> Stop exposing dice related structs in the SDK

Cargo.lock, enclave_apps/Cargo.lock, enclave_apps/key_xor_test_app/src/main.rs, enclave_apps/oak_echo_enclave_app/Cargo.toml, enclave_apps/oak_echo_enclave_app/src/main.rs, enclave_apps/oak_echo_raw_enclave_app/Cargo.toml, enclave_apps/oak_echo_raw_enclave_app/src/main.rs, enclave_apps/oak_functions_enclave_app/src/main.rs, oak_enclave_runtime_support/Cargo.toml, oak_enclave_runtime_support/src/heap.rs, oak_restricted_kernel_interface/Cargo.toml, oak_restricted_kernel_interface/src/lib.rs, oak_restricted_kernel_interface/src/raw_syscall.rs, oak_restricted_kernel_interface/src/syscall.rs, oak_restricted_kernel_sdk/Cargo.toml, oak_restricted_kernel_sdk/src/channel.rs, oak_restricted_kernel_sdk/src/dice.rs, oak_restricted_kernel_sdk/src/lib.rs, oak_restricted_kernel_sdk/src/logging.rs
This isn't part of the SDK as outlined in the design doc, so let's move it to a different crate.
=> Move logic for syscalls out of the restricted kernel sdk

enclave_apps/oak_functions_enclave_app/src/main.rs, oak_functions_containers_app/Cargo.toml, oak_functions_containers_app/src/lib.rs, oak_functions_sdk/tests/integration_test.rs, oak_functions_service/Cargo.toml, oak_functions_service/src/instance.rs, oak_functions_service/src/lib.rs, oak_functions_service/src/wasm/mod.rs, oak_functions_service/src/wasm/tests.rs, oak_functions_service/tests/integration_test.rs
The main goal for these metrics is to help us find out where the time is going: for example, if we know (from the outside) that a RPC took 5 seconds, was the time spent executing wasm code or lost somewhere else?
I added two metrics: one for the initialization work (linking the module etc), and one for the actual invocation of `main`.
These statistics are collected unconditionally for every request. Privacy-wise, I argue that this is fine, because (a) we expect the wasm code to be called to we're not leaking any information based on the fact that we're calling wasm, and (b) in an ideal case the externally-observable RPC latency will be the wasm invocation time + some constant-ish overhead for the sandbox setup, so we're not leaking any new information there either.
Now, I would really …
=> Add histograms to track wasm sandbox setup and invocation times

oak_containers_orchestrator/src/metrics.rs
Include basic networking stats in the system metrics we export.
Right now all of these system metrics are collected inside the orchestrator; I'm thinking all of this metrics collection should really be broken out into a separate binary, much like the syslog proxy is in a separate binary.
=> Export basic network metrics (bytes/packets/errors sent/received)

oak_functions_containers_app/Cargo.toml, oak_functions_containers_app/src/lib.rs
What we've observed is that when we increase load to Oak Functions, at some point we'll start getting 100% RPC error rates with the RPCs timing out.
Remember that the number of threads in tokio is the same as the number of cores on the machine, so you will not be able to serve more requests in parallel than the number of worker threads. I assume there's a queue where the requests start building up, waiting for a worker thread to be available to execute.
My current theory is that we're hitting that limit: we have some requests that take a long time to execute, and thus are hogging all the worker threads. More RPCs are piling in into the queue, only to stay in the queue long enough to time out, which means we start serving timeout errors.
The hope is that after we've got enough parallel …
=> Add load shedding to Oak Functions

oak_functions_containers_app/src/lib.rs, oak_remote_attestation/src/handler.rs
On its own, this PR doesn't do much interesting, but it will allow us to call `await` in the request handler callback.
=> Change `AsyncEncryptionHandler` callback to be async

Cargo.lock, enclave_apps/Cargo.lock, oak_ml_transparency/runner/Cargo.lock, oak_restricted_kernel_bin/Cargo.lock, oak_restricted_kernel_wrapper/Cargo.lock, stage0_bin/Cargo.lock, testing/sev_snp_hello_world_kernel/Cargo.lock
Versions 0.6.5 and 0.7.12 have been yanked due to found vulnerabilities. Also updated other dependencies needed for resolver.
Fixes #4569
=> Update zerocopy dependency

Cargo.lock, Cargo.toml, stage0/Cargo.toml, stage0/src/dice_attestation.rs, stage0/src/lib.rs, stage0_bin/Cargo.lock, stage0_dice/Cargo.toml, stage0_dice/src/lib.rs
This is done to make it available for testing the oak SDK, which requires attestation evidence to initialize
=> Break out stage0 attestation generation logic

oak_crypto/src/encryptor.rs, oak_crypto/src/hpke/mod.rs, oak_crypto/src/tests.rs
This PR makes `oak_crypto` use crypto nonces provided by the incoming message. This is one of the steps for implementing random nonces and sending them inside encrypted messages.
=> Use crypto nonces from proto messages in Rust

oak_attestation_verification/src/rekor.rs
Avoids reallocating, and to_vec() is safer.
=> Use to_vec() instead of to_string()

stage0/src/acpi.rs
Numeric overflow is common in checksum calculation. We should use wrapping_sub to avoid overflow check by rust runtime. Without this patch panics are observed when stage0 is built with debug mode.
=> stage0: use wrapping_sub for AddChecksum

cc/crypto/client_encryptor.cc, cc/crypto/hpke/jni/com_google_oak_crypto_hpke_RecipientContext.h, cc/crypto/hpke/jni/com_google_oak_crypto_hpke_SenderContext.h, cc/crypto/hpke/jni/context_jni.cc, cc/crypto/hpke/recipient_context.cc, cc/crypto/hpke/recipient_context.h, cc/crypto/hpke/recipient_context_test.cc, cc/crypto/hpke/sender_context.cc, cc/crypto/hpke/sender_context.h, cc/crypto/hpke/sender_context_test.cc, cc/crypto/server_encryptor.cc, java/src/main/java/com/google/oak/crypto/ClientEncryptor.java, java/src/main/java/com/google/oak/crypto/ServerEncryptor.java, java/src/main/java/com/google/oak/crypto/hpke/RecipientContext.java, java/src/main/java/com/google/oak/crypto/hpke/SenderContext.java
This PR makes C++ and Java crypto code to use nonces provided by Proto messages.
=> Use crypto nonces from proto messages in C++ and Java

Cargo.lock, java/src/main/java/com/google/oak/verification/RekorLogEntry.java, oak_containers_launcher/build.rs, oak_containers_launcher/src/lib.rs, oak_containers_launcher/src/server.rs, oak_containers_orchestrator/Cargo.toml, oak_containers_orchestrator/src/crypto.rs, oak_containers_orchestrator/src/logging.rs, oak_containers_orchestrator/src/main.rs, oak_crypto/src/encryptor.rs
This PR adds the Orchestrator logic for requesting the Hostlib with:
- Key Provisioning role request (whether it's a Leader or a Dependant)
- Requesting group keys for a Dependant role
=> Add Key Provisioning logic for requesting group keys from Hostlib

micro_rpc_workspace_test/build.rs, oak_client/build.rs, oak_containers_hello_world_trusted_app/build.rs, oak_containers_hello_world_untrusted_app/build.rs, oak_containers_launcher/build.rs, oak_containers_orchestrator/build.rs, oak_containers_stage1/build.rs, oak_containers_syslogd/build.rs, oak_functions_containers_app/build.rs, oak_functions_containers_launcher/build.rs, oak_functions_launcher/build.rs, oak_grpc_utils/src/lib.rs
Use same name, type and semantics as prost and tonic.
Simplify the change tracking logic.
Fix #4587
=> Reorder arguments for proto compilation

oak_client/build.rs, oak_containers_hello_world_trusted_app/build.rs, oak_containers_hello_world_untrusted_app/build.rs, oak_containers_launcher/build.rs, oak_containers_orchestrator/build.rs, oak_containers_stage1/build.rs, oak_containers_syslogd/build.rs, oak_functions_containers_app/build.rs, oak_functions_containers_launcher/build.rs, oak_functions_launcher/build.rs, oak_functions_sdk/build.rs, oak_functions_service/build.rs, oak_grpc_utils/src/lib.rs, oak_remote_attestation/build.rs
This makes `cargo build` idempotent again, which should noticeably reduce build and test time.
Ref #4608
=> Use correct paths for proto compilation

oak_crypto/src/encryptor.rs, oak_restricted_kernel_sdk/src/dice.rs
Moves alias trait from the sdk crate to the crypto crate.
It means that all structs that implement the new trait implicitly satisfy any existing functions/structs that requires an implementation of the old trait. 
Improvement over #4604.
=> Improve trait aliasing impl for restricted kernel SDK

Cargo.lock, Cargo.toml, oak_containers_hello_world_trusted_app/Cargo.toml, oak_containers_hello_world_trusted_app/src/app_service.rs, oak_containers_hello_world_trusted_app/src/main.rs, oak_containers_hello_world_trusted_app/src/orchestrator_client.rs, oak_containers_sdk/Cargo.toml, oak_containers_sdk/README.md, oak_containers_sdk/build.rs, oak_containers_sdk/src/crypto.rs, oak_containers_sdk/src/lib.rs, oak_functions_containers_app/Cargo.toml, oak_functions_containers_app/src/lib.rs, oak_functions_containers_app/src/main.rs, oak_functions_containers_app/src/orchestrator_client.rs, oak_functions_containers_app/tests/integration_test.rs
This PR adds a `oak_containers_sdk` crate for implementing enclave applications.
It also adds an SDK implementation for encryption: the new gRPC client connects to the Orchestrator Crypto service.
Ref https://github.com/project-oak/oak/issues/4490
=> Add Oak Containers SDK for encryption

oak_functions_containers_app/src/lib.rs
a) OpenTelemetry strictly speaking disallows `/` in metrics names, so let's not use that.
b) Running experiments locally on my workstation suggested that milliseconds were too much: initializing the wasm sandbox and invoking the code took only a few hundred microseconds, which meant they always got put into the "0 ms" bucket.
=> Rename a metric and change wasm timing metrics to micros

cc/transport/BUILD, cc/transport/grpc_streaming_transport_test.cc
And use "" style imports for grpc and test deps, for consistency.
=> Make grpc_streaming_test use a compatiable time for deadline

.cargo/config.toml, Cargo.lock, oak_functions_containers_app/src/lib.rs, oak_functions_containers_app/src/main.rs, oak_functions_containers_app/tests/integration_test.rs
This will be somewhat contentious as while Tokio has a facility to expose some runtime metrics, they're gated behind `tokio_unstable` -- and even worse, it's not a simple feature you can just throw into `Cargo.toml`, you need a compiler flag for it.
However, enabling this should give us a bit more visibility into what the runtime is doing: namely, how many threads are there, and how many tasks we have queued in the system.
There are other metrics that can be exposed -- see https://docs.rs/tokio/latest/tokio/runtime/struct.RuntimeMetrics.html -- but we can add them later if these work and prove useful.
=> Attempt to export some Tokio-related metrics from Oak Functions

Cargo.lock, stage0/Cargo.toml, stage0/src/sev.rs, stage0_bin/Cargo.lock
The VM Platform Communication Key (VMPCK) for VM Protection Level (VMPL) 0 is used to request an attestation report and a sealing key that form the basis of the DICE attestation chain. We don't want later boot stages to be able to request updated attestation reports or sealing keys for VMPL0, as that would allow them to generate counterfeit DICE chains.
To stop that from happening we wipe VMPCK0 as soon as we have successfully read it and initialised the Guest Message Encryptor.
=> Wipe VMPCK0 after reading it

stage0/src/sev.rs, stage0_bin/README.md
Stage 0 fails to boot the Linux kernel on AMD SEV-SNP is CONFIG_DMI is enabled in the kernel. This seems to be because the Linux kernel scans the range 0xF0000 to 0xFFFFF looking for the SMBIOS entry point table, even though this range is marked as reserved. If we don't PVALIDATE this memory page, the scan causes an unhandled #VC during early boot.
=> PVALIDATE the SMBIOS entry point table range

stage0/src/sev.rs, stage0/src/zero_page.rs, stage0_bin/README.md
The change in #4640 caused the Linux kernel to fail earlier AMD SEV-SNP, even if DMI is not enabled. So, instead of PVALIDATing this range, let's try to mark the memory range as "disabled" so that the Linux kernel will not touch it at all.
=> Mark the SMBIOS entry point table region as disabled

cc/crypto/hpke/recipient_context.cc, cc/crypto/hpke/recipient_context.h, cc/crypto/hpke/recipient_context_test.cc, oak_containers_orchestrator/src/crypto.rs, oak_containers_sdk/src/crypto.rs, oak_crypto/proto/v1/crypto.proto, oak_crypto/src/hpke/mod.rs, proto/containers/orchestrator_crypto.proto
This PR removes predetermined nonces from the serialized proto for the `RecipientContext`, because we are currently using randomly generated nonces.
=> Remove nonces from the serialized RecipientContext

oak_containers/proto/interfaces.proto, oak_containers_launcher/src/lib.rs, oak_containers_launcher/src/server.rs, oak_functions_containers_launcher/src/main.rs, oak_functions_containers_launcher/src/server.rs, oak_functions_launcher/src/main.rs, oak_functions_launcher/src/server.rs, proto/session/BUILD, proto/session/messages.proto
This PR makes Hostlibs accept and send DICE evidence and endorsements as part of the `AttestationBundle`
Ref https://github.com/project-oak/oak/issues/4627
=> Send DICE evidence and endorsements in Hostlibs

oak_containers_sdk/build.rs
The change detection logic was not working correctly because of the proto paths, and this crate (and its dependants) were constantly rebuilt instead of being cached.
=> Stop rebuilding Oak Containers SDK

oak_functions_service/src/lib.rs, oak_functions_service/src/wasm/mod.rs, oak_functions_service/src/wasm/tests.rs
Only create a single linker, and reuse that to create all subsequent instances.
Add benchmarks to measure it.
Before:
```
test wasm::tests::bench_invoke ... bench:     246,826 ns/iter (+/- 49,215)
```
After:
```
test wasm::tests::bench_invoke ... bench:      45,246 ns/iter (+/- 1,894)
```
Ref #3757
=> Reduce latency of Wasm invocations

oak_functions/examples/key_value_lookup/module/src/tests.rs, oak_functions_containers_launcher/src/lib.rs, oak_functions_launcher/src/lib.rs
We should find a better solution, but this at least lets us get past #4677
=> Increase timeout for oak functions tests

Cargo.lock, micro_rpc_workspace_test/Cargo.lock
This PR updates the h2 crate with fix for vulnerability: https://rustsec.org/advisories/RUSTSEC-2024-0003
=> Update h2 crate to v0.3.24

micro_rpc_build/src/lib.rs, oak_functions_service/build.rs
This mirrors the similar feature in the `oak_grpc_utils` crate.
Fixes #4679
=> Add micro_rpc_build support for external paths.

oak_crypto/proto/v1/crypto.proto, proto/crypto/BUILD, proto/crypto/crypto.proto
This PR copies Crypto proto files into the `proto` directory. We need this step to first update internal dependencies to use the new proto directory.
Ref https://github.com/project-oak/oak/issues/4392
=> Copy crypto protos into the global proto directory

oak_functions_containers_app/src/lib.rs
Turns out `service` is a reserved attribute name and this is one of the reasons my metrics weren't properly ingested by monitoring.
=> Rename some attributes when we export RPC metrics

Cargo.lock, justfile, oak_attestation_verification/Cargo.toml, oak_attestation_verification/src/claims.rs, oak_attestation_verification/src/endorsement.rs, oak_attestation_verification/src/rekor.rs, oak_attestation_verification/src/util.rs, oak_attestation_verification/src/verifier.rs, oak_ml_transparency/runner/Cargo.lock, oak_ml_transparency/runner/Cargo.toml
The crate itself already set no_std, but it relied on a lot of std-only features in its dependencies, such as anyhow::Context and serde json serialization.
Since all canonical serde json serialization libraries require std, it's necessary to manually serialize one structure. But since the structure doesn't have optional fields, nesting, or complex types, the serialization logic is straightforward.
Fixes #4682
=> Remove oak_attestation_verification dependency on std.

oak_attestation_verification/Cargo.toml, oak_attestation_verification/src/claims.rs, oak_attestation_verification/src/rekor.rs, oak_ml_transparency/runner/Cargo.toml
The new name was requested in
https://github.com/project-oak/oak/pull/4685#discussion_r1459674232.
=> Rename oak_attestation_verification "serialize" feature to "std".

oak_attestation_verification/build.rs
`WORKSPACE_ROOT` makes a crate incompatible with use from another repository because there's no way for it to be set relative to the root of the oak repository. `cargo:rerun-if-change` supports relative paths, however, which solve this problem.
=> Remove WORKSPACE_ROOT from oak_attestation_verification.

oak_containers_hello_world_untrusted_app/tests/integration_test.rs, oak_containers_launcher/src/lib.rs, oak_containers_launcher/src/qemu.rs
* Hide the default constructor functions behind a feature flag, since they use WORKSPACE_ROOT.
* Expose the Qemu params struct
* Make the Args fields public
=> Modifications to oak_containers_launcher for external use

justfile
Cargo check does not detect all failures. Running cargo build without extra flags exposes failures.
=> no_std test: use cargo build (with flags) instead of cargo check

Cargo.lock, oak_functions_containers_app/Cargo.toml, oak_functions_containers_app/src/lib.rs, oak_functions_containers_app/tests/integration_test.rs
This is entirely optional; the expectation is that with this we can trade off higher CPU usage (as we need to do compression) for increased network bandwidth (as we need to transmit fewer bytes).
Obviously this needs to be enabled on the client side as well. I've also not enabled compression for responses to be on the safe side for now.
=> Accept compressed RPCs in Oak Functions trusted app

.cargo/config.toml, enclave_apps/.cargo/config.toml
The default target CPU is `x86-64`, which is fairly conservative; this will change the default target to `x86-64-v3`, which is roughly the feature set of Nehalem (which in itself is 10 years old by now).
It would obviously be even better to compile for the particular CPU you're going to run on, but we can't reliably predict which CPU we're going to run the binary on, so we'll have to choose something generic.
What features does v3 enable?
```
+target_feature="avx"
+target_feature="avx2"
+target_feature="bmi1"
+target_feature="bmi2"
+target_feature="cmpxchg16b"
+target_feature="f16c"
+target_feature="fma"
+target_feature="lzcnt"
+target_feature="movbe"
+target_feature="popcnt"
+target_feature="sse3"
+target_feature="sse4.1"
+target_feature="sse4.2"
+target_feature="ssse3" …
```
=> Change the default CPU target to `x86-64-v3`

Cargo.lock, stage0/Cargo.toml, stage0/src/efi.rs, stage0/src/lib.rs, stage0/src/zero_page.rs, stage0_bin/Cargo.lock
This might not be enough to convince Linux that it should read the EFI tables, but I think this should be the first attempt (and let's see whether it's palatable or it throws errors at us).
If this doesn't work, then the next step would be to set `zero_page.efi_info.efi_loader_signature` to `EL64` which should make Linux think it's booting under EFI -- but this may have other adverse effects as we're not setting anything up in the table itself.
I have my doubts whether this approach is feasible at all, therefore I've gated the whole thing behind a feature.
=> Create a fake EFI System Table in stage0.

justfile, oak_restricted_kernel_wrapper/Cargo.toml, oak_restricted_kernel_wrapper/build.rs
One can now specify which kernel binary should be wrapped using feature flags.
=> Make oak_restricted_kernel_wrapper configurable

Cargo.lock, oak_functions_containers_app/Cargo.toml, oak_functions_containers_app/src/main.rs
This drastically improves multi-core scaling.
For example, previously quadrupling the number of cores had little to no effect on QPS; however, with jemalloc, quadrupling the number of cores triples the QPS we can handle.
Going beyond that is not great (for example, going from 4 to 16 cores only gave perhaps 20% more QPS), but that's a different bottleneck to chase down.
=> Use jemalloc instead of the default musl allocator in Oak Functions

oak_crypto/src/hpke/aead.rs
Right now we take in a slice, turn it into a vector (which entails an allocation + copy), and then call `encrypt_in_place` which explicitly states in the documentation that the ciphertext will be larger than the original, therefore the `Vec` will be reallocated (and possibly copied) at least once more.
I don't think we need to bother with any of that. Just use `encrypt` and `decrypt`, which return Vec-s directly.
=> Don't bother with in-place encryption in oak_crypto

Cargo.lock, enclave_apps/Cargo.lock, enclave_apps/Cargo.toml, enclave_apps/oak_echo_enclave_app/Cargo.toml, enclave_apps/oak_echo_enclave_app/src/main.rs, enclave_apps/oak_functions_enclave_app/Cargo.toml, enclave_apps/oak_functions_enclave_app/src/main.rs, oak_restricted_kernel_sdk/Cargo.toml, oak_restricted_kernel_sdk/src/lib.rs
oak_core datastructures are used in interfaces exposed by the SDK
=> Re-export oak_core as utils in SDK

oak_attestation/src/handler.rs, oak_containers_orchestrator/src/crypto.rs, oak_crypto/src/encryptor.rs, oak_crypto/src/hpke/mod.rs, oak_crypto/src/tests.rs
As far as I can see these `mut`-s are not necessary as the code doesn't actually try to mutate anything and is stateless.
However, I believe there were some API design questions that might mandate the `mut`-s, so I'll defer to you whether this is just cruft that can be cleaned up or something we want to retain.
=> Remove some seemingly unnecessary `mut`-s in the crypto code

Cargo.lock, oak_containers_orchestrator/Cargo.toml, oak_containers_orchestrator/src/main.rs, oak_containers_system_image/build.sh
Switching to jemalloc _drastically_ improved multithread performance of Oak Functions itself. As the orchestrator can also use multiple threads, let's use jemalloc there was well.
Clearly the default musl allocator is not that good in concurrent situations. I'm not expecting miracles here, but hey, every little helps.
And while I'm in here build the orchestrator with `release-lto` as well. This is likely to have even more miniscule effect, but might as well do it while I'm in here.
=> Use jemalloc in the `oak_containers_orchestrator` as well

oak_client/src/transport.rs, oak_functions_containers_launcher/src/server.rs, oak_functions_launcher/src/server.rs, proto/session/messages.proto, proto/session/service_streaming.proto, proto/session/service_unary.proto
This PR adds a new `GetEndorsedEvidence` RPC call and a corresponding `EndorsedEvidence` message. Also updates the Rust client code to use the new RPC.
Ref https://github.com/project-oak/oak/issues/4417
=> Add GetEndorsedEvidence RPC

Cargo.toml, oak_enclave_runtime_support/Cargo.toml, oak_enclave_runtime_support/README.md, oak_enclave_runtime_support/src/heap.rs, oak_enclave_runtime_support/src/lib.rs, oak_functions_enclave_service/Cargo.toml, oak_restricted_kernel_sdk/Cargo.toml, oak_restricted_kernel_sdk/src/lib.rs, oak_restricted_kernel_sdk/src/logging.rs, oak_restricted_kernel_sdk_proc_macro/src/lib.rs
It's inconvenient to inadvertently declare a global alloc when importing the sdk for crate for unit tests. Hence this makes sure it only happens for enclave binaries.
=> SDK: Only define global alloc in code output by entrypoint macro

oak_containers_kernel/Makefile, oak_containers_kernel/patches/virtio-dma.patch
As we're dealing with VMMs that only support old virtio standards, this is unfortunately required (for now).
This is inspired by the patch proposed in https://lore.kernel.org/all/20211027232828.2043569-1-erdemaktas@google.com/T/ except that a lot of things have changed in the intervening years, and I've taken the lazy option of just returning false instead of making sure we're in confidential mode.
Not meant for upstreaming or consumption outside our project, really. Hopefully we can modernize said VMM a bit in the future and drop this patch altogether.
=> Patch the Oak Container kernels to enable DMA with virtio <1.0

linux_boot_params/src/lib.rs, oak_containers_stage1/src/dice.rs, oak_restricted_kernel/src/lib.rs, stage0/src/lib.rs
We previously added this type for the linux stage1 implementation, however it cannot read the E820 table, so at this point the custom type is just a historical artifact.
=> Remove non standard dice data type from E820 table

oak_attestation/src/handler.rs, oak_containers_hello_world_trusted_app/src/app_service.rs, oak_containers_orchestrator/src/crypto.rs, oak_crypto/src/encryptor.rs, oak_crypto/src/tests.rs
What started up as an endeavour to get rid of the `mut`-s in `AsyncServerEncryptor` ended up with an unified `ServerEncryptor`, with just a slightly different `create` method -- until hopefully one day we can unify all of it.
And, remove some hard dependencies on `Arc`-s while I'm in there. If we're not keeping a reference around, then there is no need for things to be wrapped in a smart pointer.
Ref #4311
=> Merge `AsyncServerEncryptor` into `ServerEncryptor` (mostly)

oak_channel/src/lib.rs, oak_crypto/src/encryptor.rs, oak_restricted_kernel_sdk/src/channel.rs, oak_restricted_kernel_sdk/src/dice.rs, oak_restricted_kernel_sdk/src/lib.rs, oak_restricted_kernel_sdk/src/logging.rs, oak_restricted_kernel_sdk_proc_macro/src/lib.rs
This should help other teams find their way around more easily
=> Add more doc comments to restricted kernel

java/src/test/java/com/google/oak/transport/BUILD, java/src/test/java/com/google/oak/transport/GrpcStreamingTransportTest.java
This PR adds a `GET_ENDORSED_EVIDENCE_REQUEST` case to Java tests.
Ref https://github.com/project-oak/oak/issues/4417
=> Add missing request wrapper case in Java tests

oak_restricted_kernel/Cargo.toml, oak_restricted_kernel/src/lib.rs, oak_restricted_kernel/src/mm/mod.rs, oak_restricted_kernel/src/syscall/dice_data.rs, oak_restricted_kernel/src/syscall/mod.rs
At this point we imo need conditional compilation, because we want the kernel to behave quite differently based on whether it is loading an applicatino over the channel vs from the initrd.
In the first case we want to create a new dice layer. In the second case we want to just expose the stage0 dice data to the orchestrator
=> Add initrd feature flag to kernel, and expose stage0 dice data if it's set

enclave_apps/Cargo.lock, oak_functions_service/src/lookup.rs
There is no need to grab an exclusive lock when we're constructing new LookupData instances, as we only ever read.
My naive native lookup application went from 1.8k QPS to 7.2k QPS with just this one change.
This won't help Wasm code as much, as Wasm called `create_lookup_data()` once during sandbox creation; however, this will likely mean we can create more sandboxes in parallel as they don't have to synchronize here and we'll likely gain some marginal QPS for the simple use case.
=> Change a `Spinlock` to `RwSpinlock`

justfile, oak_restricted_kernel_wrapper/Cargo.toml, oak_restricted_kernel_wrapper/build.rs
We'll need more versions given that the kernel now has compile time flags. It gets messy with that many features, this is easier.
=> kernel wrapper: pass kernel file name via env

oak_launcher_utils/src/launcher.rs
Looks nicer now, no more trailing /n
=> Remove newline character appended to all VM logs

Cargo.lock, Cargo.toml, oak_functions/examples/key_value_lookup/module/Cargo.toml, oak_functions/examples/key_value_lookup_multi/module/Cargo.toml, oak_functions/examples/key_value_lookup_multi/module/src/lib.rs, oak_functions_sdk/src/lib.rs, oak_functions_service/benches/wasm_benchmark.rs, oak_functions_service/src/wasm/api.rs, proto/oak_functions/benchmark.proto, proto/oak_functions/sdk/oak_functions_wasm.proto
Adds a new microRPC method for multiple lookups. In the future the two may be easily unified, but at the moment I didn't want to risk breaking existing functionality.
Add a new Wasm module to perform multiple lookups. The difference from the existing one is that it deals with protos as input / output instead of just the raw value to look up, and also a parameter to determine how to do the lookups (to help with benchmarking).
Remove randomness in benchmark (it was not actually doing anything useful in the way it was written)
=> Allow batching lookup data from Wasm

oak_restricted_kernel/src/lib.rs, oak_restricted_kernel/src/syscall/dice_data.rs, oak_restricted_kernel/src/syscall/mod.rs
In v0 the orchestrator will use this mechanism to write dice data back to the kernel after it measures the application. Following this, it launches the application and exists.
Then, the application will load the dice data from the kernel as usual. 
This means we should be able to ship the orchestrator as a non breaking change, before context switching is implemented.
=> Permit dice data to be written back to the kernel

enclave_apps/Cargo.lock, enclave_apps/oak_functions_enclave_app/Cargo.toml, enclave_apps/oak_functions_enclave_app/src/main.rs, oak_functions_containers_app/src/lib.rs, oak_functions_enclave_service/src/lib.rs, oak_functions_enclave_service/tests/integration_test.rs, oak_functions_sdk/tests/integration_test.rs, oak_functions_service/benches/wasm_benchmark.rs, oak_functions_service/src/instance.rs, oak_functions_service/src/lib.rs, oak_functions_service/src/wasm/mod.rs, oak_functions_service/src/wasm/tests.rs
There is some clean-up to be done here, but the basic gist of it is that we now have a trait, `Handler`, for handling user invocations.
For now, we obviously only have the Wasm handler. But this is the hook that a native implementation could use.
=> Create an API for Oak Functions handlers

Cargo.lock, enclave_apps/Cargo.lock, oak_functions_containers_app/src/lib.rs, oak_functions_service/Cargo.toml, oak_functions_service/benches/wasm_benchmark.rs, oak_functions_service/src/wasm/wasmtime.rs
Make this the default for Oak Containers, but keep Wasmi for Oak Restricted Kernel.
Ref #4779
=> Add support for Wasmtime in Oak Functions

Cargo.lock, enclave_apps/Cargo.lock, micro_rpc_workspace_test/Cargo.lock, oak_attestation/src/attester.rs, oak_attestation/src/handler.rs, oak_containers_orchestrator/src/crypto.rs, oak_containers_orchestrator/src/ipc_server.rs, oak_containers_orchestrator/src/key_provisioning.rs, oak_containers_orchestrator/src/main.rs, oak_containers_sdk/src/crypto.rs, oak_crypto/Cargo.toml, oak_crypto/src/encryption_key.rs, oak_crypto/src/encryptor.rs, oak_crypto/src/hpke/mod.rs, oak_crypto/src/lib.rs, oak_crypto/src/tests.rs, oak_functions_containers_app/src/lib.rs, oak_functions_containers_app/tests/integration_test.rs, oak_functions_enclave_service/src/lib.rs, oak_restricted_kernel_bin/Cargo.lock, oak_restricted_kernel_dice/src/lib.rs, oak_restricted_kernel_sdk/src/instance_attestation.rs, oak_restricted_kernel_sdk/src/lib.rs, oak_restricted_kernel_sdk/src/mock_attestation.rs
This PR:
- Merges `oak_crypto::encryptor::EncryptionKeyProvider` and `oak_crypto::hpke::KeyPair` into `oak_crypto::encryption_key::EncryptionKey`
- Implements serialization/deserialization
- Implements encryping the private key for Key Provisioning.
- Removes public keys from `EncryptionKey` struct (it's only used to be put into the evidence)
Ref https://github.com/project-oak/oak/issues/4513
=> Merge Rust EncryptionKeyProvider and KeyPair

Cargo.lock, oak_functions_containers_app/Cargo.toml, oak_functions_containers_app/src/lib.rs, oak_functions_containers_app/src/main.rs, oak_functions_containers_app/src/native_handler.rs, oak_functions_containers_app/tests/integration_test.rs
I thought about creating a separate `oak_functions_containers_app` crate, but there's a ton more going on here -- like all the instrumentation to report metrics back to the launcher -- so decided that it's probably best, for now, to just tack the native handler onto the existing app.
Right now it does nothing; just echoes back the request.
In the future we probably do want some crate features in here to say whether to include wasm and/or native handlers.
=> Add a fairly rudimentary `NativeHandler` to oak_functions_containers_app

oak_functions_service/src/lookup.rs, oak_functions_service/src/wasm/api.rs
This is to help with the native logic implementation.
Wasm code executes in its own sandbox and we copy the lookup data in there, creating a copy; however, if the logic is run in native mode, we _don't_ want to create a copy for each lookup but rather just pass on the pointer into the hashmap straight to the native code.
(Otherwise, we'd need to keep track of values we've cloned for each request ourselves so that we'd know what copies to deallocate once we've handled the request.)
=> Don't always immediately clone the lookup table entry

Cargo.lock, oak_functions_containers_app/Cargo.toml, oak_functions_containers_app/src/lib.rs, oak_functions_containers_app/src/main.rs, oak_functions_containers_app/src/native_handler.rs
This is entirely untested as I don't have a `.so` file to play around with; constructing a test for this should be the next priority.
But: this will accept a bunch of bytes (that we'll need to append to the DICE log in the future), and attempts to load it dynamically as a shared object expecting it to adhere to the contract we've been discussion about seprately.
=> Flesh out the `NativeHandler` to actually invoke native code

Cargo.lock, cc/native_sdk/BUILD, cc/native_sdk/key_value_lookup.cc, oak_functions_containers_app/Cargo.toml, oak_functions_containers_app/tests/native_test.rs
This uses a `cc_binary` instead of `cc_library` as that's recommended by [bazel](https://bazel.build/reference/be/c-cpp#cc_binary):
> The .so files produced by cc_library rules are not linked against the libraries that they depend on. If you're trying to  create a shared library for use outside of the main repository, e.g. for manual use with dlopen() or LD_PRELOAD, it may be better to use a cc_binary rule with the linkshared=True attribute. See cc_binary.linkshared.
That being said, the test, as-is, doesn't work. For whatever reason, it can't find `libstdc++` in my environment:
```
$ ldd bazel-bin/cc/native_sdk/libkey_value_lookup.so
linux-vdso.so.1 (0x00007ffd51514000)
libm.so.6 => /nix/store/p3jshbwxiwifm1py0yq544fmdyy98j8a-glibc-2.38-27/lib/libm.so.6 (0x00007f1c7c10a000) …
```
=> Attempt to create a trivial native key-value lookup test

enclave_apps/Cargo.lock, enclave_apps/oak_orchestrator/Cargo.toml, enclave_apps/oak_orchestrator/src/main.rs, oak_restricted_kernel/src/mm/encrypted_mapper.rs, oak_restricted_kernel/src/mm/page_tables.rs, oak_restricted_kernel/src/syscall/mod.rs, oak_restricted_kernel/src/syscall/switch_process.rs, oak_restricted_kernel_interface/src/syscall.rs, oak_restricted_kernel_interface/src/syscalls.rs
Successfully executes the loaded application. 
Note: the memory of the orchestrator is leaked in this version and not cleared. Secrets are cleared manually by the orchestrator beforehand.
=> Execute app loaded by orchestrator

justfile, oak_functions_launcher/benches/integration_benches.rs, oak_functions_launcher/tests/integration_test.rs, oak_launcher_utils/src/launcher.rs, oak_restricted_kernel/Cargo.toml, oak_restricted_kernel_bin/Cargo.toml, oak_restricted_kernel_launcher/README.md, xtask/src/examples.rs, xtask/src/launcher.rs
We'll need to keep the `initrd` feature flag around until the internal launcher is updated to load the orchestrator also.
=> Update restricted kernel oak functions to load via orchestrator

cc/native_sdk/BUILD, cc/native_sdk/native_sdk.h, cc/native_sdk/symbols.map.ld
This ensures that the `.so` only has two global symbols that it exports: `oak_main` and `register_globals`, both following the C calling convention. These are the only symbols that we expect external code to call.
Without this change we have 811 exported symbols:
```
$ nm bazel-bin/cc/native_sdk/libkey_value_lookup.so | grep " T " | wc -l
811
```
After that, it's down to the two we'd expect:
```
$ nm bazel-bin/cc/native_sdk/libkey_value_lookup.so | grep " T "
0000000000009f1f T oak_main
000000000000a9e6 T register_callbacks
```
=> Reduce the number of exported symbols from the native lookup library

Cargo.lock, oak_attestation_verification/Cargo.toml, oak_attestation_verification/tests/verifier_tests.rs, oak_restricted_kernel_dice/src/lib.rs
This field is currently not populated by the restricted kernel, as there is no application config. However, the verification library expects it. 
Depending on preference, this field should either be populated with an empty value (this PR) or removed https://github.com/project-oak/oak/pull/4807. 
Those PRs are mutually exclusive. But one should be merged, for restricted kernel evidence to be parsed in the verification library.
=> Generate empty attestation config

oak_restricted_kernel/src/lib.rs, oak_restricted_kernel/src/mm/mod.rs, oak_restricted_kernel/src/syscall/switch_process.rs
This means all entries will point to a valid, pre-existing L3 page table. This allows us in the future swap between L4 page tables for different applications, since they will all point to the same memory / L3 tables in kernel space.
Means we no longer have to iteratate over kernel space entries when switching applications. Will be useful for concurrent apps.
=> Populate all kernel space entries of L4 page table

micro_rpc_tests/build.rs, oak_restricted_kernel_bin/build.rs, oak_restricted_kernel_wrapper/build.rs, stage0_bin/build.rs
This is mostly only an issue when switching between docker and non-docker builds.
=> Fix build scripts to track WORKSPACE_ROOT

Cargo.lock, oak_functions_containers_app/Cargo.toml, oak_functions_containers_app/src/main.rs, oak_functions_service/src/lib.rs, proto/oak_functions/application_config.proto
More infrastructure for the eventual native modules.
Previously I added a command-line flag to distinguish between native and wasm modules. However, we already have a facility to provide application configuration to the enclave apps (which should properly be put in the attestation chain as well), so it's far better to use that instead of trying to invent a new way how to pass command line flags to the app.
=> Create application config proto for Oak Functions

Cargo.lock, snp_measurement/Cargo.toml, snp_measurement/src/main.rs, snp_measurement/src/page.rs, snp_measurement/src/stage0.rs, snp_measurement/src/vmsa.rs
The SNP measurement prediction tool is outdated, since we no-longer preload the kernel into memory before boot. We also have more unmeasured pages configured and need to support additional vCPUs at startup.
With these updates the tool once again predicts that correct measurement in the AMD SEV-SNP attestation report.
Exmaple hex representation of an attestation report running with 2 vCPUs on AMD SEV-SNP:
```
02000000000000000000030000000000000000000000000000000000000000000000000000000000
0000000000000000000000000100000003000000000014d101000000000000000000000000000000
271f735e9368e74f04c92b3bdab5b468ae1405b2b8ad89c11cf8335378142fba0000000000000000
0000000000000000000000000000000000000000000000005f150e289cc75c525939c89ed242131b
7be08be075a7e658efe39542ca0c12005766e90b133da18d1a1d517253f691a8 …
```
=> Update the SNP predicted measurement tool

Cargo.lock, Cargo.toml, oak_debug_service/Cargo.toml, oak_debug_service/build.rs, oak_debug_service/src/lib.rs, oak_functions_containers_app/Cargo.toml, oak_functions_containers_app/src/lib.rs, proto/oak_debug/service/oak_debug.proto, third_party/google/profile.proto
What we're lacking now, especially during development, is visibility into what our app is doing inside the enclave.
This RPC server currently adds a facility to request a CPU profile (a lot of open source projects call this `profilez`, as the Google style of z-pages is well known by now).
There are other things I want to expose via this interface, like some way how to get a jemalloc heap profile in the future.
There's also the question of how much private information could leak via this interface and whether we want to disable it when running production, but that's something for a different day.
=> Start a skeleton of a runtime debug interface

cc/attestation/verification/BUILD, cc/attestation/verification/attestation_verifier.h, cc/attestation/verification/insecure_attestation_verifier.cc, cc/attestation/verification/insecure_attestation_verifier.h
Add a C++ `AttestationVerifier` that uses DICE protos.
This PR has been split from https://github.com/project-oak/oak/pull/4787 to avoid breaking changes.
Ref https://github.com/project-oak/oak/issues/3641
Ref https://github.com/project-oak/oak/issues/4627
=> Add C++ attestation verifier

cc/utils/cose/BUILD, cc/utils/cose/cose.cc, cc/utils/cose/cose.h, cc/utils/cose/cose_test.cc, cc/utils/cose/cwt.cc, cc/utils/cose/cwt.h, cc/utils/cose/cwt_test.cc
This PR adds functions to generate COSE_Sign1, COSE_Key and CWT certificates for testing purposes.
These functions are currently not fully implemented and only provide serializing an HPKE public key.
Ref https://github.com/project-oak/oak/issues/3641
Ref https://github.com/project-oak/oak/issues/4627
=> Add generating CWT for tests

java/src/main/java/com/google/oak/client/OakClient.java, java/src/main/java/com/google/oak/transport/EvidenceProvider.java, java/src/main/java/com/google/oak/transport/GrpcStreamingTransport.java, java/src/test/java/com/google/oak/client/OakClientTest.java, java/src/test/java/com/google/oak/transport/GrpcStreamingTransportTest.java
This PR makes Java transport and client use `GetEndorsedEvidence` method instead of the deprecated `GetPublicKey`
Ref https://github.com/project-oak/oak/issues/3641
Ref https://github.com/project-oak/oak/issues/4627
=> Use GetEndorsedEvidence method in Java transport

oak_attestation_verification/tests/verifier_tests.rs, oak_dice/src/cert.rs
Reopens #4821, tracks b/326283532
The keys being used are all provided by the p256 library, which uses the secp256r1 curve rather than the secp256k1 curve that cose::iana::Algorithm::ES256K maps to. Instead, we should be using cose::iana::Algorithm::ES256, which maps to the secp256r1 curve (see https://www.rfc-editor.org/rfc/rfc9053.html#section-2.1).
This update breaks tests that run against static testdata generated with the old algorithm. To create new testdata on AMD SEV SNP machines, this change must be merged first. Hence tests are temporarily skipped. They will be re-enabled in a follow up PR.
=> Specify 'ES256' instead of 'ES256K' in COSE keys generated by cert.rs

oak_attestation_verification/tests/verifier_tests.rs, oak_dice/src/cert.rs
This reverts commit eaabab4e6328b821f5bfd1a56e4369731afcbfe2 or #4829. We need commit with the aforementioned change to build new testdata. We now have one, so we can revert that PR since it also disabled the relevant tests.
=> Revert "Specify 'ES256' instead of 'ES256K' in COSE keys generated by cert.rs (#4829)"

Cargo.lock, Cargo.toml, oak_kernel_measurement/Cargo.toml, oak_kernel_measurement/README.md, oak_kernel_measurement/src/main.rs, stage0/src/zero_page.rs
When we start a new VM we pass the kernel in a bzImage format, but the VMM splits it into 2 parts before passing it to the Stage 0 firmware. So the measurements by stage 0 are of these two derived parts.
This tool applies the same changes to that we can predict what both measurements would be for a specific bzImage kernel.
Example local run:
Stage 0 logs when running Oak Containers Hello World:
```
stage0 DEBUG: Kernel image digest: sha2-256:3786bf59635b0ce0c5e2bd18f0cef28cc243ddeb13195531c509b8f9e0f1d538
stage0 DEBUG: Kernel setup data digest: sha2-256:b42f3c704ec17c87c17560ed9c23a44a44507e19065f81e16c3379e67417fd34
```
Running the prediction tool against the same Linux kernel:
```
Kernel Image Measurement: sha2-256:3786bf59635b0ce0c5e2bd18f0cef28cc243ddeb13195531c509b8f9e0f1d538
Kernel …
```
=> Add tool to predict kernel boot measurements

cc/attestation/verification/BUILD, cc/attestation/verification/insecure_attestation_verifier.cc, cc/attestation/verification/insecure_attestation_verifier.h, cc/attestation/verification/utils.cc, cc/attestation/verification/utils.h
This PR adds `ExtractEncryptionPublicKey` and `ExtractSigningPublicKey` as low-level attestation functions that could be used in integration tests
=> Move CWT public key extraction to utils

oak_functions_service/src/lookup_htbl.rs
Use larger data chunk sizes when we reserve large numbers of hash table entries.
This is primarily a cache optimization.  LookupHtbl.data_chunks is currently a vector of 2MiB data chunks.  At 1TiB, there will be > 500,000 entries in the data_chunks array, busting out of cache, causing an additional cache miss during hash table lookups.  This PR ensures that the data_chunks vector always fits in cache, without wasting much memory.  With 1B entries reserved in the hash table, we'll see 2GiB data chunks.
=> Large chunks

oak_attestation_integration_tests/README.md
Overlooked your comment on my previous PR, but I agree such a comment would be helpful. :)
=> Add comment calrifying why attestation/verification integration tests are extracted

Cargo.lock, enclave_apps/Cargo.lock, oak_functions_service/Cargo.toml, oak_functions_service/src/lib.rs, oak_functions_service/src/lookup_htbl.rs
This makes it harder to extract a user's location via cache-timing, but not impossible.
The new hash function distributes keys very evenly in tests.  In contrast, the ahash crate produces poor hashes, resulting in more hash collisions.   I've submitted [Issue #210](https://github.com/tkaitchuck/aHash/issues/210) upstream to ahash about this.
The average number of collisions in a 2B entry swiss table with 50% load factor was 3.50 for ahash.  For the custom hasher, it is 2.54, which is identical to what we see using true random numbers as hash values.  The custom hash function is also about 20% faster than ahash on my laptop.
=> Added randomness to lookup_htbl.

cc/attestation/verification/insecure_attestation_verifier.cc
Remove parsing signing key in the `InsecureAttestationVerifier` because not all internal tests are currently generating this key
=> Remove signing key from InsecureAttestationVerifier

oak_functions_service/src/lookup_htbl.rs
Switch back to the 2-round version of hash_u64.
I kept finding weaknesses in the 1-round version.  Most recently, I found that keys ending in several 0's led to many hash collisions.  I enhanced the test to check for this, and also ran the 2-round version through dieharder tests.  A couple fail, but the important ones like birthday pass, which is good enough.  The new function is:
```rust
fn hash_u64(v: u64, hash_secret: u64) -> u64 {
let v1 = u64::wrapping_mul((v + hash_secret) ^ (v >> 32), 0x9d46_0858_ea81_ac79);
let v2 = u64::wrapping_add(v1 ^ v, v1 >> 32);
let v3 = u64::wrapping_mul((v2 + hash_secret) ^ (v2 >> 32), 0xe177_d33d_28e7_10c9);
u64::wrapping_add(v3 ^ v, v3 >> 32)
}
```
=> Enhanced hash_u64 as 2-rounds.

oak_attestation_verification/src/verifier.rs, oak_attestation_verification/tests/verifier_tests.rs
Two goals achieved here:
(1) Make the verification fail on non-empty firmware version. We don't have a spec for that reference value yet. It would be good to address this in one go for all of AttestationReportValues.
(2) Make the verification fail for non-skip stage0 reference value. This adds code that could already work with the derived endorsements but fails now since we don't have the derived endorsements for stage0. 
See b/327069120
=> Fail on non-empty reference values

oak_containers_kernel/patches/virtio-dma.patch
The content of the patch was outdated after updating the Linux kernel to version 6.7.6
=> Update Linux kernel patch for v6.7.6

oak_attestation_verification/src/verifier.rs, proto/attestation/verification.proto
I was going through this code in preparation for using it using it in the OC3 talk demo, and found it a bit unwieldy to read. 
This is a small refactor that improves clarity and readability by making it more seqential reducing the number of variables in the outermost scope, and reducing mutation / redeclaration of variables.
=> Improve dice chain verification logic clarity

oak_functions_service/src/lookup_htbl.rs
The reduce function before this change did not uniformly select a hash table location, slightly increasing the number of collisions when inserting a billion entries into the table.  As the number of keys approaches 2^32, the situation becomes worse.  The problem is that a reduce function that takes only the lower 32 bits of the hash cannot evenly distribute to more than 2^32 buckets.
Since the updated hash function already relies on Intel/AMD/ARM u64 * u64->u128 instruction, there seems to be no harm in using that instruction in reduce, allowing it to take u64 hashes instead of u32.  
The reduce function is used rather than the standard masking operation on the hash to derive a table index because we did not want to waste the space required to round the table size up to the next power of …
=> Improve distribution of reduce function.

oak_attestation/src/handler.rs, oak_functions_containers_app/src/lib.rs, oak_functions_containers_app/src/main.rs, oak_functions_containers_app/tests/integration_test.rs
As pointed out in #4862 the signature of `serve` was getting rather unwieldy.
By boxing more things we can push most of the ugliness into the signature of `serve` itself, and clean up points of use so that there's only one generic (that matters) which you have to specify.
=> Remove some generics from `serve` by using dynamic dispatch

Cargo.lock, oak_containers_orchestrator/src/launcher_client.rs, oak_debug_service/Cargo.toml, oak_debug_service/src/lib.rs
The stars have aligned, some third-party crates have been updated, and we can now have a singular version of `prost` in our workspace.
=> Update prost/tonic/etc stack

oak_functions_containers_app/src/main.rs, proto/oak_functions/application_config.proto
This doesn't do much right now, but will give us a configuration setting that can be used to switch Oak Functions on Oak Containers to a different communication channel, if needed.
For now, nobody sets the application config proto anyway, so we default to the existing behaviour of listening for connections on TCP port 8080.
Ref b/289334144
=> Add communication channel parameters to the Oak Functions app config

oak_containers_launcher/src/lib.rs, oak_containers_launcher/src/server.rs, oak_functions_containers_launcher/build.rs, oak_functions_containers_launcher/src/lib.rs, oak_functions_containers_launcher/src/main.rs
We're not using that to read a file anywhere, and I want to construct a bespoke `ApplicationConfig` in the `oak_functions_containers_launcher`.
If any launcher indeed wants to read the config from a file in the future, they can do it on their own.
=> Change `application_config` from a path to a `Vec<u8>`

Cargo.lock, oak_containers_launcher/Cargo.toml, oak_containers_launcher/src/lib.rs, oak_containers_launcher/src/qemu.rs, oak_functions_containers_launcher/Cargo.toml, oak_functions_containers_launcher/src/lib.rs, oak_functions_containers_launcher/src/main.rs, oak_functions_containers_launcher/tests/integration_test.rs, xtask/src/containers.rs
This plumbs virtio-vsock through the launcher, and even runs the lookup test twice: once with a network connection, and once with a virtio-vsock connection to ensure both work.
Ref b/289334144
=> Add support for virtio-vsock to Oak Functions on Oak Containers

proto/attestation/reference_value.proto
Update the CB reference value proto.
- In CB there is cmd_line for system layer so that is additional.
- In application layer, CB does not have any configuration.
- Added the kernel layer for CB.
=> Update the CB reference value proto

.github/workflows/provenance.yaml, buildconfigs/oak_restricted_kernel_simple_io_init_rd_wrapper.toml, justfile, kokoro/build_binaries_rust.sh, oak_restricted_kernel_bin/Cargo.toml
the new oak_restricted_kernel_simple_io_init_rd_wrapper will exist alongside oak_restricted_kernel_simple_io_wrapper for a while. then internal dependencies will be updated, and the the former will be removed.
this approach is significantly simpler than #4828. For #4828 we would need to attempt to synchronize its merging with the updates to the internal launcher and the transparent release imports of the binary. It'd be too flaky.
=> Add new version of the restricted kernel simple_io and initrd

Cargo.lock, oak_channel/src/basic_framed.rs, oak_launcher_utils/Cargo.toml, oak_launcher_utils/src/launcher.rs, oak_restricted_kernel/src/lib.rs, oak_restricted_kernel_orchestrator/Cargo.toml, oak_restricted_kernel_orchestrator/src/lib.rs
(guarded behind a feature, as we'll need to update the internal launcher as well)
=> Make restricted kernel orchestrator return evidence to host

enclave_apps/Cargo.lock, oak_launcher_utils/Cargo.toml, oak_restricted_kernel_orchestrator/Cargo.toml
Upon reflection after merging #4907, we can already enable it. We can update the internal launcher at the same time as we migrate it to using the orchestrator.
=> Enable orchestrator evidence export

.cargo/config.toml, Cargo.toml, oak_debug_service/Cargo.toml
Using frame pointers will enable `pprof` to properly unwind the stack and give us a meaningful profile.
This will use up one register and extra data on the stack, but guesstimates on the Internet suggest that the performance impact is ~1%, which I think is acceptable as we get much better profiling data as a return.
Frame pointers have a long and complicated story on x86; they were disabled by everybody on x86 as that architecture was starved for registers and having one more available gave a noticeable impact in performance. In comparison, x86-64 has way more registers, and various Linux distributions have been starting re-enabling frame pointers in the recent past.
=> Force-enable frame pointers and use them for profiling.

Cargo.lock, enclave_apps/Cargo.lock, oak_functions_containers_app/tests/native_test.rs, oak_functions_sdk/tests/integration_test.rs, oak_functions_service/Cargo.toml, oak_functions_service/benches/wasm_benchmark.rs, oak_functions_service/src/instance.rs, oak_functions_service/src/lookup.rs, oak_functions_service/src/lookup_htbl.rs
This is not really about performance, given that `Bytes` is effectively an `Arc` under the hood. In fact, I expect this to be performance neutral.
However, this will give us more flexibility in the future, for example, when experimenting with custom serialization formats.
=> Use slices instead of `Bytes` in hashtable lookup data update code

Cargo.lock, oak_functions_service/Cargo.toml, oak_functions_service/src/lookup.rs
Now that we can get profiling information, it looks like the spinlocks we currently use for compatibility with `no_std` were one source of inefficiency.
Replacing them with `parking_lot` significanly reduced mutex overhead, on par with `std::sync::Mutex`. However, `parking_top` is API-compatible with `spinning_top`, unlike `std::sync::Mutex`, so using them will require less changes to our code.
=> Replace `spinning_top` with `parking_lot` when `std` is available

stage0_bin/layout.ld
The latest version of LLVM uses new sections when compiling with `-C code-model=large` (`.ltext`, `.ldata`, `.lrodata` and `.lbss`). This causes problems when building the Stage 0 binaries: the sections aren't referenced in the linker script so they get placed in locations that violate some of the requirements of the firmware layout. See https://lld.llvm.org/ELF/large_sections.html and b/330173039 for more context.
This version is used by Rust nightly from version 1.78 onwards, so would block us from updating the Rust compiler without support for these.
=> Add support for large sections to the Stage 0 linker script

oak_attestation_verification/src/verifier.rs, proto/attestation/verification.proto
This exposes more of the extracted evidence via the `AttestationResults` proto, rather than just the encryption and signing public keys. Since the `ExtractedEvidence` message  contains those same public keys again, the existing public key fields are marked deprecated, to be removed in a follow-up commit.
=> Add `ExtractedEvidence` to the `AttestationResults` proto.

stage0_bin/src/asm/boot.s
We want to make sure that the instruction pointer in a #VC exception really pointed to a CPUID instruction since it is the only #VC exception type we support.
Ref b/330197837
=> Check CPUID instruction in Stage0 #VC handler

proto/micro_rpc/BUILD, proto/micro_rpc/options.proto
This will allow other external/third party client repository protos to build
service protos that have added this option.
This option will eventually replace the comment-based approach for method_id
management.
b/326866415
=> Add the micro_proc options proto with method_id definition

oak_crypto/src/noise_handshake/client.rs, oak_crypto/src/noise_handshake/mod.rs, oak_crypto/src/noise_handshake/tests.rs
This PR simply moves private module `test_client` to a public module `client`.  It also fixes a minor goober where there were multiple definitions for P256_X962_LEN (the other being P256_X962_LENGTH).
=> Turn module test_client into client, so it is available for general use.

oak_attestation_verification/src/verifier.rs, oak_dice/src/cert.rs, proto/attestation/reference_value.proto, proto/attestation/verification.proto, stage0/src/lib.rs, stage0_dice/src/lib.rs
This is the first step towards validating the kernel command-line using a regular expression. Once this is imported and we are able to generate new DICE evidence with the raw kernel command-line we can update the verification code and protos.
=> Use the raw kernel command-line in DICE

flake.nix
I think this was the actual root cause of b/329124627, but we'll see for sure after the commit is merged.
=> Add linux kernel to bzImage provenance shell

oak_attestation_verification/src/verifier.rs, proto/attestation/verification.proto
Stage0 destroys the VM communication key for VM protection level 0 (VMPCK0) to avoid forged attestation reports. We must ensure that the attstation report was generated from VMPL as part of attestation verification for this to work.
Ref b/328163347
=> Ensure attestation report was generated from VMPL0

stage0_dice/src/lib.rs
The command-line is not a hash, so it should not be nested like other digests.
Ref https://github.com/project-oak/oak/pull/4936#issuecomment-2014595255
=> Update CWT representation of the command-line

stage0/src/zero_page.rs, stage0_bin/README.md
The memory between 640KiB and 1MiB should not be reported as physical memory in the E820 table, since the Linux kernel assumes this is a hardware BIOS-related memory range.
=> Do not report physical memory between 640KiB and 1MiB

oak_dice/src/cert.rs, stage0/src/lib.rs, stage0_dice/src/lib.rs
Repurposing the same ID for the kernel command-line that was used for the digest is a breaking change since some code still expected the ID to be associated with a digest.
So, for now add back the old ID as a digest and create a new ID for the raw kernel command-line. Once all the code has been migrated we can remove the old ID.
=> Temporarily add back the kernel cmdline digest

oak_dice/src/evidence.rs
Now that we are adding the entire kernel command-line to the root layer certificate it can grow beyond the 1024 bytes we allocated in the Stage0 structure. For now assume that the kernel command-line will be 1024 bytes, so a total of 1536 should be ok for the certificate.
=> Increase the size of the certificate in Stage0 DICE data

micro_rpc_tests/build.rs, micro_rpc_tests/proto/test_schema.proto, proto/oak_functions/BUILD, proto/oak_functions/sdk/oak_functions_wasm.proto, proto/oak_functions/service/oak_functions.proto, proto/oak_functions/testing.proto, testing/oak_echo_service/proto/oak_echo.proto
Eventually we should be able to switch to using these option values and
getting rid of the comments completely.
=> Add micro_rpc method_id option to service protos.

enclave_apps/oak_orchestrator/src/main.rs, oak_restricted_kernel_sdk/src/utils.rs
Now orchestrator logs will be prefixed, just as stage0 and kernel logs are.
=> Differentiate orchestrator logs

stage0_bin/build.rs
This is to ensure there aren't any issues stemming from the BIOS area not being aligned to a 2 MiB boundary (and the EDK2 blob is 2M in size as well.)
Unfortunately I need to actually commit this change as because of various permissions and imports I can't run a locally-built stage0 binary.
I may revert this PR in the future.
Ref b/330345538
=> Temporarly change stage0 release size to 2 MiB

oak_dice/src/evidence.rs
This reverts commit c86964406aade767a449afd51eb10f99a0c84cb4, as it introduced a breaking change that broke imports.
~~To be merged once all checks running on http://cl/619545627 have passed.~~ They've passed
=> Revert "Increase the size of the certificate in Stage0 DICE data (#4946)"

oak_attestation/src/dice.rs, oak_containers_orchestrator/src/main.rs, proto/attestation/evidence.proto, proto/containers/hostlib_key_provisioning.proto
This PR adds the ability to sign group keys in the attestation evidence as part of Key Provisioning.
=> Sign group keys as part of Key Provisioning

cc/transport/BUILD, cc/transport/grpc_streaming_transport.cc, cc/transport/grpc_unary_transport.h, cc/transport/grpc_unary_transport_test.cc, cc/transport/util.cc, cc/transport/util.h, proto/session/BUILD
Implementing unary transport class template for future Oak clients that use the unary interface.
This class allows for clients to supply any gRPC service name, but assumes the service has an `Invoke` and `GetEndorsedEvidence` gRPC methods with the same gRPC method signature as in https://github.com/project-oak/oak/blob/main/proto/session/service_unary.proto
=> Unary gRPC transport template class

oak_restricted_kernel/src/interrupts.rs
We want to make sure that the instruction pointer in a #VC exception really pointed to a CPUID instruction since it is the only #VC exception type we support.
This is the equivalent of #4921 but for the restricted kernel.
Thanks to @benschlueter for highlighting the issue and suggesting a fix.
=> Ensure CPUID triggered the #VC exception

oak_sev_guest/src/ghcb.rs, oak_sev_guest/src/instructions.rs, stage0/src/sev.rs
This seems to do the trick and we can now `PVALIDATE` 2 MiB frames.
This PR contains two related changes:
1. Try to use 2 MiB pages more aggressively when validating memory. Previously we only tried to use 2 MiB pages if the E820 entry perfectly aligned with 2M boundaries; now, I try to use the minimal amount of 4K pages.
2. Do an explicit Page State Change operation before attempting to validate memory.
We didn't do PSCs before as they seemed to be unnecessary. However, for whatever reason this meant that we were never able to PVALIDATE using 2M pages. However, if we first issue an explicit PSC using a 2M frame, the PVALIDATE succeeds.
This should drastically cut down the number of PVALIDATE operations we do, at the cost of doing some VMGEXITs. An obvious optimization for the future will …
=> Do a page state change operation before invoking `PVALIDATE`

buildconfigs/oak_restricted_kernel_simple_io_init_rd_wrapper.toml, justfile, oak_kernel_measurement/src/main.rs
Previously the provenance created by the SLSA builder was just for the bzImage. Not the artifact that would be measured in the attestation. With this PR the provenance subjects should include binaries measured in the attestation.
Change-Id: I16e3234d0d65e3790319294c416c378cd7611681
http://b/332723461
=> Directly issue kernel provenance for attestation measurements

.github/workflows/reusable_provenance.yaml
current workflow breaks: https://github.com/project-oak/oak/actions/runs/8544823048/job/23412049549, while slsa's wildcard workflow succeeds: https://github.com/slsa-framework/example-package/blob/e51524d7e65531856d3028bff6b1ac846ea85913/.github/configs-docker/app-config.toml . Maybe it's that we use an older version. Worth trying if updating fixes it.
There's some other issues to resolve from https://github.com/project-oak/oak/pull/4976 we'll get to them if and once this works
Change-Id: I82cc4a7194980d71318b12e0eeb8f35d6d1f2711
=> Update slsa builder version to see if it fixes the broken workflow

oak_attestation_verification/src/verifier.rs, oak_proto_rust/BUILD, oak_proto_rust/build.rs, proto/attestation/BUILD, proto/attestation/expected_value.proto
This doesn't change anything about the functionality of the verification
code. It moves us in the direction of being able to returned the
computed expected values to the client so that they can be provided
again to avoid re-computation.
b/324837692
=> Split verify_measurement_digest into get_expected/compare steps

oak_attestation_verification/src/verifier.rs, proto/attestation/expected_value.proto
Since the verify_* calls here are only used in one place, I moved the implementation to be inline in the calling verification function. Since soon, those functions will be split as well.
Another step for b/324837692
=> Split verify calls with only measurement_digest into get/compare calls. 

stage0/src/sev.rs, stage0/src/zero_page.rs, stage0_bin/README.md
Linux commit 0f4a1e80989a ("x86/sev: Skip ROM range scans and validation for SEV-SNP guests") removes Linux's attempt to PVALIDATE the legacy ROM regions, including the legacy SMBIOS range [0xf0000, 0x100000). However, legacy code may still attempt to scan this range when using non-EFI firmware such as Stage0.
To avoid a crash during guest boot, PVALIDATE the range in Stage0.
To avoid legacy code reading garbage from this region, initialize the PVALIDATEd memory to 0.
=> PVALIDATE and initialize the legacy SMBIOS range

oak_attestation_verification/src/verifier.rs, stage0/src/lib.rs
As a temporary workaround for #4981, limit the kernel command line included in the Stage0 DICE measurements to 256 chars.
=> Temporarily limit kernel command line length in Stage0 measurements

oak_attestation_verification/src/verifier.rs, proto/attestation/expected_value.proto
This change is similar to the verify_measurement_digest split, but the
retrieval of reference values is a bit different, since they come from
the endorsement subject as serialized KernelAttachment data, and the
endorsement subject itself must be verified.
Subsequent verifications can use the cached image and setup_data value,
so the subject endorsement remains totally encapsulated in the
get_verified_kernel_attachment helper function; the expected values from
the endorsement itself does not need to be returned to the client.
Another step for b/324837692
=> Split the verify_kernel_measurement_data into get_expected/compare

kokoro/build_binaries_oak_containers.sh, oak_functions_containers_app/Cargo.toml, oak_functions_containers_container/Dockerfile.insecure, oak_functions_containers_container/build_container_bundle
This is similar to what we have with the Restricted Kernel version, except a little bit more complicated as we need a whole second container.
(I considered bundling both binaries into one container, but decided against it as we want the choice be explicit.)
Ref b/331866772
=> Build the insecure flavour of Oak Functions container
